### ISSUE TITLE
Offer for external applications support

### ISSUE THREAD

**Issue by Michahel** [goldendict/goldendict#1003]
Press F3 and select the Programs tab. Here you can add external applications. 
If Html type is specified then GoldenDict accepts information in the UTF-8 encoding then the BOM marker isn't consulted. In Windows, the cscript.exe command-line utility issues the information in the utf-16le encoding. In connection with this there are certain difficulties because of the fact that GoldenDict ignores the BOM. There is a very strong desire that the GoldenDict consults BOM and in that way correctly determined the Unicode encoding.

**Comment by Michahel** [comment]
If this is necessary, then I can attach the WSH script so that you can play and better understand the problem.

**Comment by Abs62** [comment]
Try [goldendict-1.5.0-RC2-302-g9892fdc](http://www.mediafire.com/file/6s8m5xbx6adk985/goldendict-1.5.0-RC2-302-g9892fdc%28EXE_only%29.7z).

**Comment by Michahel** [comment]
I can not download. It is possible that the site is blocked by the provider.

**Comment by Abs62** [comment]
Try from [here](http://rgho.st/6QFWpqfW8).

**Comment by Michahel** [comment]
Can you change the default? It is necessary that the text without the BOM should be treated as utf-16le. The fact is that for inserting a BOM to UTF-8 text there is an option, and for utf-16le it is not possible to insert a BOM.

**Comment by Abs62** [comment]
It will break interaction with other programs. Can you show your script example?

**Comment by Michahel** [comment]
[dict1.12.1.zip](https://github.com/goldendict/goldendict/files/1977989/dict1.12.1.zip)
Decompress this file into the directory where your GoldenDict is located. For example into "C:\Program Files\GoldenDict\dict1.12.1"
Command for run:
`C:\WINDOWS\system32\cscript //Nologo //U dict1.12.1\dict.js /h:dict.bibleonline.ru /p:2628 /s:lev "%GDWORD%"`

**Comment by Michahel** [comment]
Now works perfectly for me. Thanks.
