### ISSUE TITLE
About Popup Window Size

### ISSUE THREAD

**Issue by LynnHo** [goldendict/goldendict#1010]
Is it possible to modify the popup window size? The current size is a little small for big screen.

**Comment by Abs62** [comment]
Just pin window (by button in upper right corner), resize it as any other window and unpin it.

**Comment by LynnHo** [comment]
@Abs62 It works! Thanks a lot!

**Comment by Stephen2252Ro** [comment]
This method can solve the window problem temporary. Is it possible to make the window size permanently.
