### ISSUE TITLE
The DICT servers: improperly text highlighting in green

### ISSUE THREAD

**Issue by Michahel** [goldendict/goldendict#1016]
**Operation system:** Windows XP Home Edition, Service Pack 3
**The version number of the GoldenDict:** 1.5.0-RC2-302-g9892fdc

**How to reproduce the problem**

Setup utility for access to DICT server from GoldenDict through console DICT-client. For that run the self-extracting archive [dict1.12.1.exe](https://1drv.ms/u/s!ApR0ksy-ixJUnVf72995QSqy2Crl).
After you click on the archive it will automatically extract the files, start the process of detecting GoldenDict on your computer, and after detection — it automatically adds three files (dict.js, dict.exe, cygwin1.dll), which are contained in the archive, to the sub-directory dict1.12.1 in the same directory as the GoldenDict is located.
Start up GoldenDict. 
In the menu, under "Edit > Dictionaries > Sources (F3)" in the "Programs" tab click on the add button and create a new recording. Indicate the Type of program — Html. In the "Program name" field write "JScript dictionary". Type in the "Command Line" field:

`cscript //Nologo //U dict1.12.1\dict.js /h:dict.bible.ru /p:2628 /s:word /d:ell-rus_strong "%GDWORD%"`

Choose the "DICT Servers" tab. Click on the Add button for creating a new DICT server setting. Give the name "DICT-BIBLE". Type this in the "Address" field:  dict://dict.bible.ru, in the "Base" field: ell-rus_strong, in the "Strategies" field: lev. Check the "Enabled" option and click OK.  
In the menu go to "Help > Configuration Folder". Open the article-style.css file in the text editor Notebook and make the following changes:
```
.dictd_phonetic:before, .dictd_phonetic:after
{
  content: "";
}
.dictd_phonetic
{
  font-style: normal;
}
```

Then click on Ctrl+s for saving the installation and exit Notebook.
In the search line type the letter "a" and wait a little until the definitions from the recently created dictionaries are displayed.
[See screen capture](https://downloader.disk.yandex.ru/disk/949347e7b01dd022e65f123188042b87d8effbd10e52eb237c1ca1658bccf764/5afc1ca9/pJJK1FSRDOT43o5Vkb8CrQdmcWW18koZ2ykfFyaz0cstXFzSCpnyDFoCaaXJ15mR0tqmpb4QvHBbU9UOvorQTQ%3D%3D?uid=0&filename=2018-05-16_11-21-09.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=77498&hid=28b2057d96fccb1c3560ada30a381d61&media_type=image&tknv=v2&etag=cb67eb4b0422fcb715e9e328124cbf54)

**The core of the problem:** if the line contains the unmatched Formatting code "\\", then the text is hightlighted in green till the end of the line. In the remaining lines the highlighted text is absent in spite of the fact that the are present in their closed code. 
In the dictionary "JScript dictionary" (on the screen capture below) the definition is displayed correctly. The creation of this dictionary is carried out especially with the goal to visually demonstrate the core of the problem. The problem with the unmatched formatting code is solved in the line 113 in the dict.js file.
Will it be difficult to solve the problem anologically in GoldenDict as well?

**Comment by Abs62** [comment]
Try last version (from [here](http://www.mediafire.com/file/j73lha78io1k067/goldendict-1.5.0-RC2-310-gccb5eb1%28EXE+only%29.7z) or [here](http://rgho.st/download/7JJQkHYCf/92144e96d174d1eae0383026df7b6e09d0bc89e2/goldendict-1.5.0-RC2-310-gccb5eb1(EXE%20only).7z)).

**Comment by Michahel** [comment]
The problem is fixed.
