### ISSUE TITLE
ffmpegaudio.cc:54: warning: 'void av_register_all()' is deprecated

### ISSUE THREAD

**Issue by Eosphorus** [goldendict/goldendict#1020]
ffmpegaudio.cc:54: warning: 'void av_register_all()' is deprecated [-Wdeprecated-declarations]

In file included from ..\goldendict-master\ffmpegaudio.cc:20:0:

avcodec-gd-58.dll
avformat-gd-58.dll
avutil-gd-56.dll
libavcodec-gd.dll.a
libavformat-gd.dll.a
libavutil-gd.dll.a
& headers

from ffmpeg-4.0

**Comment by vedgy** [comment]
GCC warnings are tracked in #978. This one is number 9.

**Comment by Eosphorus** [comment]
I see. Missed it. Will follow it there.
