### ISSUE TITLE
Pronunciation volume control

### ISSUE THREAD

**Issue by vstepaniuk** [goldendict/goldendict#1023]
Is there a way to control the pronunciation volume (using internal or external player), independently from the OS?

**Comment by vstepaniuk** [comment]
Is it possible to add a slider, or at least a number field in the Preferences dialog? Thank you

**Comment by vedgy** [comment]
This feature can't be implemented in general for all possible external players.

Can't you adjust per-application settings in a system configuration tool? For example, *pavucontrol* GUI tool allows doing this in a GNU/Linux system with PulseAudio.

**Comment by vstepaniuk** [comment]
I have found even a better, native way - in Ubuntu **Sound settings** window there is a tab **Applications**, which does just that - controls the volume of every application (currently producing sound) SEPARATELY. So all you need is to play some long enough word (or, preferably, sentence) in GoldenDict (cause the slider will disappear once the playback is finished), and to adjust the **libao [goldendict]** volume level, and it will be remembered for all future playbacks. Thanks for suggestion!! ))

Still, is there a GoldenDict native way of controlling the volume at least of internal player? Say, a command-line option, or a config file variable? Thank you.

**Comment by vedgy** [comment]
No volume control is currently implemented for any player in goldendict.

**Comment by vstepaniuk** [comment]
All clear, thank you!

**Comment by timur-enikeev** [comment]
I want to implement this function (for QtMultimedia backend). But I need agreement (and maybe some assistance) from a main developer because it is not so easy, I should change many parts of the program and maybe broke internal API.
