### ISSUE TITLE
Dictionary group names - random ampersands.

### ISSUE THREAD

**Issue by e-pc** [goldendict/goldendict#1031]
In archlinux goldendict randomly adds ampersand signs into dictionary names.

Goldendict version: Based on Qt 5.11.1 (GCC 7.3.1 20180406, 64 bit).
![screenshot_20180625_073423](https://user-images.githubusercontent.com/22566545/41832554-d7b4b672-784c-11e8-80be-731c0b3e3cb9.png)

**Comment by Abs62** [comment]
Look issue #847.

**Comment by e-pc** [comment]
> Look issue #847.
Thanks, that helped.
