### ISSUE TITLE
Translated from the clipboard, missing tail punctuation mark.

### ISSUE THREAD

**Issue by barrer** [goldendict/goldendict#1035]
Function: "Use the following hotkey to translate a word from clipboard"  
This problem can also occur when you paste text with a shortcut (`Ctrl+V` or `Command+V`).

Example: `First, clone this repository, e.g.:`

However, what is obtained is: `First, clone this repository, e.g`

Punctuation mark is very useful when calling external programs for sentence translation. Is the correct handling only removing spaces instead of punctuation mark?

External word, sentence translation program URL:  
https://github.com/barrer/translate-online

**Comment by Abs62** [comment]
GD is dictionary, not translator. It is not designed to translate sentences or whole text.
