### ISSUE TITLE
looks up long weird number after PC startup

### ISSUE THREAD

**Issue by Bercio** [goldendict/goldendict#1041]
On kubuntu 18.4, goldendict version 1.5.0-RC2+git. If i set goldendict to initialize at startup (through the system options, not through goldendict preferences because it doesn't allow me to) it always tries to look up a long weird number, this time it's 101d0230227190000153133135500000011590012_1531331473_782430. It also automatically opens the File menu, when showing me the results of the lookup.

**All this only happens if the option "closes to system tray" or "start to system tray" or both are set.**

![image](https://user-images.githubusercontent.com/3931668/42590876-4a5c68fa-8545-11e8-8c59-51b1f877c8a1.png)

Also may be worth noting, the command assigned to goldendict autostart is "goldendict", which makes me think kubuntu is launching it from the command line [?], which would explain the File menu being opened, 'cause that happens also when I launch goldendict from the command line.

![image](https://user-images.githubusercontent.com/3931668/42592012-a907e3e0-8548-11e8-97b6-0962feb25eb6.png)

**Comment by Bercio** [comment]
Correction, the number is not always the same, only similar. I've rebooted the pc a few minutes after opening the issue and the number shown this time is 101d0230227190000153133220700000011600009_1531332232_276675

**Comment by Abs62** [comment]
GD just transtate word placed into it command line. Try build GD from git sources, the sessions handling was adjusted there.

**Comment by Bercio** [comment]
Building from sources fixed it, thanks

**Comment by Konfekt** [comment]
This can be fixed on KDE by adding`goldendict` to the line starting with `excludeApps`  in the file `~/.config/ksmserverrc`; for example
```
excludeApps=goldendict
```
