### ISSUE TITLE
goldendict does not preserve zoom level after restarting

### ISSUE THREAD

**Issue by zhou13** [goldendict/goldendict#1043]
1. open goldendict
2. press `ctrl+=` several times
3. close goldendict and reopen it
4. the zoom level is not preserved.

This feature can be useful because on hidpi screen the default font size is too small compared to the menu:

![image](https://user-images.githubusercontent.com/576382/42808612-89a0fe0a-8968-11e8-8e51-d6ce982787f7.png)

**Comment by Abs62** [comment]
Can't reproduce on last version.

**Comment by zhou13** [comment]
Update to the git version and the problem is fixed.  Thanks!
