### ISSUE TITLE
Is this an error in the time of installation

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [goldendict/goldendict#1050]
I am using ubuntu 18,10.
My question is, is this a error message?
`jigao@jigao-CW35S:~$ cd goldendict && qmake && make
Project MESSAGE: Install Prefix is: /usr/local
/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name resources resources.qrc -o build/qrc_resources.cpp
g++ -c -m64 -pipe -rdynamic -O2 -Wall -W -D_REENTRANT -DMAKE_FFMPEG_PLAYER -DHAVE_X11 -DPROGRAM_DATA_DIR=\"/usr/local/share/goldendict/\" -DPROGRAM_VERSION=\"1.5.0-RC2+git\" -DMAKE_EXTRA_TIFF_HANDLER -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_SVG_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtSvg -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I/usr/include/qt4/QtHelp -I. -Iqtsingleapplication/src -I/usr/include/hunspell -I/usr/include/x86_64-linux-gnu -Ibuild -Ibuild -o build/qrc_resources.o build/qrc_resources.cpp
g++ -m64 -rdynamic -Wl,-O1 -o goldendict build/folding.o build/main.o build/dictionary.o build/config.o build/sources.o build/mainwindow.o build/utf8.o build/file.o build/bgl_babylon.o build/bgl.o build/initializing.o build/article_netmgr.o build/dictzip.o build/btreeidx.o build/stardict.o build/chunkedstorage.o build/xdxf2html.o build/iconv.o build/lsa.o build/htmlescape.o build/dsl.o build/dsl_details.o build/filetype.o build/fsencoding.o build/groups.o build/groups_widgets.o build/instances.o build/article_maker.o build/scanpopup.o build/articleview.o build/audioplayerfactory.o build/multimediaaudioplayer.o build/externalaudioplayer.o build/externalviewer.o build/wordfinder.o build/groupcombobox.o build/keyboardstate.o build/mouseover.o build/preferences.o build/mutex.o build/mediawiki.o build/sounddir.o build/hunspell.o build/dictdfiles.o build/audiolink.o build/wstring.o build/wstring_qt.o build/processwrapper.o build/hotkeywrapper.o build/hotkeyedit.o build/langcoder.o build/editdictionaries.o build/loaddictionaries.o build/transliteration.o build/romaji.o build/belarusiantranslit.o build/russiantranslit.o build/german.o build/website.o build/orderandprops.o build/language.o build/dictionarybar.o build/broken_xrecord.o build/history.o build/atomic_rename.o build/articlewebview.o build/zipfile.o build/indexedzip.o build/termination.o build/greektranslit.o build/webmultimediadownload.o build/forvo.o build/country.o build/about.o build/programs.o build/parsecmdline.o build/maintabwidget.o build/mainstatusbar.o build/gdappstyle.o build/ufile.o build/xdxf.o build/sdict.o build/decompress.o build/aard.o build/mruqmenu.o build/dictinfo.o build/zipsounds.o build/stylescombobox.o build/extlineedit.o build/translatebox.o build/historypanewidget.o build/wordlist.o build/mdictparser.o build/mdx.o build/voiceengines.o build/ffmpegaudio.o build/articleinspector.o build/delegate.o build/zim.o build/gddebug.o build/gestures.o build/tiff.o build/dictheadwords.o build/fulltextsearch.o build/ftshelpers.o build/dictserver.o build/helpwindow.o build/slob.o build/ripemd.o build/gls.o build/splitfile.o build/favoritespanewidget.o build/scanflag.o build/epwing.o build/epwing_book.o build/epwing_charmap.o build/qtsingleapplication.o build/qtlocalpeer.o build/moc_mainwindow.o build/moc_dictionary.o build/moc_config.o build/moc_sources.o build/moc_initializing.o build/moc_article_netmgr.o build/moc_groups.o build/moc_groups_widgets.o build/moc_article_maker.o build/moc_scanpopup.o build/moc_articleview.o build/moc_audioplayerinterface.o build/moc_ffmpegaudioplayer.o build/moc_multimediaaudioplayer.o build/moc_externalaudioplayer.o build/moc_externalviewer.o build/moc_wordfinder.o build/moc_groupcombobox.o build/moc_mouseover.o build/moc_preferences.o build/moc_mediawiki.o build/moc_hotkeywrapper.o build/moc_hotkeyedit.o build/moc_editdictionaries.o build/moc_loaddictionaries.o build/moc_website.o build/moc_orderandprops.o build/moc_dictionarybar.o build/moc_history.o build/moc_articlewebview.o build/moc_webmultimediadownload.o build/moc_forvo.o build/moc_about.o build/moc_programs.o build/moc_dictspanewidget.o build/moc_maintabwidget.o build/moc_mainstatusbar.o build/moc_gdappstyle.o build/moc_mruqmenu.o build/moc_dictinfo.o build/moc_stylescombobox.o build/moc_extlineedit.o build/moc_translatebox.o build/moc_historypanewidget.o build/moc_wordlist.o build/moc_ffmpegaudio.o build/moc_articleinspector.o build/moc_dictheadwords.o build/moc_fulltextsearch.o build/moc_helpwindow.o build/moc_favoritespanewidget.o build/moc_scanflag.o build/moc_qtsingleapplication.o build/moc_qtlocalpeer.o build/qrc_resources.o build/qrc_flags.o    -L/usr/lib/x86_64-linux-gnu -lz -lbz2 -llzo2 -lX11 -lXtst -ltiff -leb -lvorbisfile -lvorbis -logg -lhunspell-1.6 -lao -lavutil -lavformat -lavcodec -lQtHelp -lQtWebKit -lQtSvg -lQtSql -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread `

**Comment by vedgy** [comment]
No, this is not an error message, but normal build output. There are no "error" or even "warning" words in this output. Please close this issue if goldendict compiles and runs on your system.
