### ISSUE TITLE
Unable to open website

### ISSUE THREAD

**Issue by hosunleex** [goldendict/goldendict#1054]
Hello, there.

The below link does not works.
http://endic.naver.com/search.nhn?sLn=en&searchOption=all&query=%GDWORD%

![default](https://user-images.githubusercontent.com/29376135/44585927-e28ddf80-a7e8-11e8-961c-431bab21f36f.jpg)
Please let me use it again...

Thanks for your considerations.

Good day!

**Comment by nikita-moor** [comment]
What's wrong with the web site? It seems working well...
![image](https://user-images.githubusercontent.com/13879891/49346492-6129d100-f6a4-11e8-9f38-8fe91e72e9e1.png)

**Comment by hosunleex** [comment]
I have reused goldendict last day and it works well as you post. Indeed, the company blocked the scripts access like google, but now it appears to allow it.
Thanks a lot to let me know this happy news.
