### ISSUE TITLE
Folders inside "Favorites" bug

### ISSUE THREAD

**Issue by BettyJJ** [goldendict/goldendict#1059]
The "Favorites" feature is great, but there is a bug with nested folders. Say my folder structure is as  follows:
```
Favorites
  ├── aaaa
  ├── bbbb
  │    ├── aaaa
```
So there is an "aaaa" folder and a "bbbb" folder in the root, and another "aaaa" folder inside the "bbbb" folder. The "Favorites" feature allows folders with the same name as long as they are not in the same folder. 

This is all very good, until one day I accidentally dragged the first "aaaa" folder onto the "bbbb" folder. Without any notice, the "aaaa" folder just disappeared! Along with all the items inside it! 

I guess the app tried to move the "aaaa" folder inside the "bbbb" folder and failed because there was already one with the same name. But it could at least give us a notice, or just leave the folder at its original place. Now it just deletes the folders and everything inside it silently. I lost many favorited items because of this. 😭

Can you fix this bug? Thank you very much!

**Comment by Abs62** [comment]
Can't reproduce. If folder with same name already exist in target folder GD just don't perform move operation.

**Comment by BettyJJ** [comment]
@Abs62 Thanks for reply. Forgot to mention that I'm on Windows 10, and GD version is 1.5.0-RC2-311-g15062f7 (the latest version on the "Early Access Builds for Windows" page). May I ask which platform and version you are using? I really like the behavior of your version (just don't perform move operation). 😊 I just tested again on my GD, and it still make the folder disappear. 😭

**Comment by Abs62** [comment]
Win10, GD [1.5.0-RC2-327-g61325ac](http://www.mediafire.com/file/t5y9firm59a115w/goldendict-1.5.0-RC2-327-g61325ac%28EXE+only%29.7z), Qt5-based.

**Comment by BettyJJ** [comment]
@Abs62 I tried the Qt4 version from the link you gave, the result is the same. I tried the Qt5 version, it says missing dlls. So I downloaded the full Qt5 version from https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows (which is still 1.5.0-RC2-311-g15062f7), and it works like you said. 😊 So I guess it's a Qt4 only problem. Don't know what else is different. Will use the Qt5 version for now. Thank you very much!

**Comment by Abs62** [comment]
Looks like Qt4 don't check result of drop operation while Qt5 do it. I'll try to dig more deeply next days.

**Comment by BettyJJ** [comment]
@Abs62 Thank you very much!
How can I get your latest build that fixed this problem?
I just found that my SAPI5 TTS engine can't work in the Qt5 version, which is kind of a deal breaker for me, so I would like to continue using the Qt4 version.

**Comment by Abs62** [comment]
Take here: [1.5.0-RC2-331-g2bd422a](http://www.mediafire.com/file/5hu939fy86hdt8e/goldendict-1.5.0-RC2-331-g2bd422a%28EXE+only%29.7z).

**Comment by BettyJJ** [comment]
> Take here: [1.5.0-RC2-331-g2bd422a](http://www.mediafire.com/file/5hu939fy86hdt8e/goldendict-1.5.0-RC2-331-g2bd422a%28EXE+only%29.7z).
Thank you very much. However the Qt4 version from this link still has this problem. 😞

**Comment by Abs62** [comment]
Don't reproduced. Qt4-based version run now like Qt5-based version - just ignore illegal moving.

**Comment by BettyJJ** [comment]
@Abs62 Oops, my bad. RC2-331 indeed fixed the problem. When I was trying to download it, mediafire.com redirected me to the previous link which is RC2-327 (don't understand why that happened). I didn't notice that and left the previous comment. Now I've changed a browser and redownloaded RC2-331, and it works fine now. Many thanks for all your great work and patience! 👍
