### ISSUE TITLE
Save and move indexed dictionaries

### ISSUE THREAD

**Issue by tehkonst** [goldendict/goldendict#1060]
I have some heavy dictionaries and sometimes I need to move them to another machine or hdd or directory. And it always takes too much time and resources to index them for full text search. 
Is it possible to save index of certain dictionaries and copy it without re-indexing again and again?

I tried to copy files from dir - ".goldendict/index", but it didn't work.

**Comment by Abs62** [comment]
You can just use portable version (look GD help for details).

**Comment by tehkonst** [comment]
Thanks for advice. I compiled version for ubuntu with portable dir.  It seems to work fine.

**Comment by xiaoyifang** [comment]
can be closed as fixed.
