### ISSUE TITLE
Abnormal goldendict display

### ISSUE THREAD

**Issue by justitia00** [goldendict/goldendict#1062]
I can't see Example sentences in Longman DOCE but in other dictionaries is right.
![error](https://user-images.githubusercontent.com/24622471/46608935-de1f4b00-cb38-11e8-8d3e-7d703db0e7f8.png)

**Comment by vedgy** [comment]
Try checking the _Expand optional parts_ checkbox on the _Advanced_ tab of Goldendict Preferences.

**Comment by justitia00** [comment]
> Try checking the _Expand optional parts_ checkbox on the _Advanced_ tab of Goldendict Preferences.

Oh! This perfectly solved my problem！ THANK YOU!

**Comment by vedgy** [comment]
When the _Expand optional parts_ checkbox is unchecked, there is a '+' button at the top of each article that has optional parts. Clicking on this button expands them.

Please close this issue if it is resolved for you.

**Comment by loveAnkisomuch** [comment]
![image](https://user-images.githubusercontent.com/23467449/46915328-60de5500-cfd4-11e8-97fe-2a4e97f97948.png)

**Comment by xiaoyifang** [comment]
seems fixed,can be closed
