### ISSUE TITLE
Selecting the contents from a dictionary? 

### ISSUE THREAD

**Issue by HaitaoShi** [goldendict/goldendict#1063]
Hi, is it possible to select the contents from a dictionary so I can copy and paste it in another place where  I can easily review? I can only find the function of "Select word by single click". What if I want to select a sentence? Thank you very much.

**Comment by Abs62** [comment]
Just select it by mouse drag.
Also there are some shortcuts (look context menu):
Ctrl+A - select all page
Ctrl+Shift+A - select current article.

**Comment by HaitaoShi** [comment]
Thank you. After restarting it, it works!!!
