### ISSUE TITLE
The 'Copy' shortcut isn't working while the dictionary is running

### ISSUE THREAD

**Issue by luanrina** [goldendict/goldendict#1064]
Hello,

Since updating to Mac OS Mojave the shortcut for 'copy' stopped working correctly while the GoldenDict program is running. When I work in Pages or Safari or Notes without the program running, the 'Command + C' shortcut works just fine and copies the words that I need like it's supposed to. However, when I launch the GoldenDict, it stops functioning. And it's the only shortcut that does that. The 'Command + X' and 'Command + V' work correctly. Also, if I assign the 'copy' shortcut to some other keys combination (like 'Command + K'), it works the way it's supposed to. It's the same both when I enter under another user name or in the 'safe mode'. Thankfully, when I close the program, this issue disappears and the 'Command + C' works again, so it's not that crucial, but it's still annoying.

Is there a way to resolve this issue?

Thank you.

**Comment by darnn** [comment]
i'm not on a mac, but: in edit->preferences, check the "scan popup" and "hotkeys" tabs. maybe something there creates a conflict.

**Comment by luanrina** [comment]
> i'm not on a mac, but: in edit->preferences, check the "scan popup" and "hotkeys" tabs. maybe something there creates a conflict.

OMG it actually WORKED! O_O I went to those preferences and unchecked all the boxes (don't use those shortcuts and pop-ups anyway), and now the 'Command + C' works as it should even with the program running. Thank you so much!!
