### ISSUE TITLE
hide text

### ISSUE THREAD

**Issue by loveAnkisomuch** [goldendict/goldendict#1065]
text: hide 

![image](https://user-images.githubusercontent.com/23467449/46912786-75f1be80-cfa9-11e8-88f8-3c583de3e6c9.png)

**Comment by vedgy** [comment]
Check out the comments under #1062 to restore the example text. Please close this issue if those comments fix it for you.

**Comment by loveAnkisomuch** [comment]
Thank you so much for all of your support! <3
![image](https://user-images.githubusercontent.com/23467449/46915782-9a19c380-cfda-11e8-977a-bca98ebb91f0.png)

**Comment by gavenkoa** [comment]
Newer versions have "Preference" => "Advanced" => "Expand optional parts". No more CSS hacks.
