### ISSUE TITLE
Translate a word from clipboard: popup window too small

### ISSUE THREAD

**Issue by tungmilan** [goldendict/goldendict#1066]
Hello,

I'm having this problem but couldn't find any setting to increase the size of the pop up window when translating a word from clipboard. It wasn't possible to increase the size of the window by the mouse either

How can I fix it? Thanks!

**Screenshot**:

<img width="847" alt="goldendict_01" src="https://user-images.githubusercontent.com/6590141/46929750-1d94de00-cff6-11e8-906c-e780d1620abf.png">

<img width="440" alt="goldendict_02" src="https://user-images.githubusercontent.com/6590141/46929584-2933d500-cff5-11e8-946f-742715a96713.png">

**System info**: 

- GoldenDict 311-g15062f7. Based on Qt 5.9.5 (gcc 7.3.0, 64-bit)
- Surface Pro 3, Windows 10 Pro w/ latest update

<img width="584" alt="goldendict_03" src="https://user-images.githubusercontent.com/6590141/46929585-2933d500-cff5-11e8-882a-652d72ab8bff.png">

**Comment by vedgy** [comment]
Press the _Pin_ button in the top right corner of the popup window; resize the window to you liking; then press the _Pin_ button again (unless you would prefer to use the popup in the pinned mode).

**Comment by tungmilan** [comment]
Thanks @vedgy ! That did it

**Comment by escape0707** [comment]
In case the popup is too large to display in your screen (maybe after a remote desktop session), you can pin the popup and use <kbd>Alt</kbd>+<kbd>Space</kbd>+<kbd>M</kbd> to move one edge into the screen and change the windows size.

If the popup window is not in pinned mode, you can fire up the popup, press <kbd>Tab</kbd> to focus on the first hyperlink in the dictionary lookup document, then <kbd>Shift</kbd>+<kbd>Tab</kbd> to the last of the menu button which is exactly the pin toggle button, then hit <kbd>Space</kbd> to pin it.

If you want to do it programmatically, you can use a text editor to change the corresponding value 
`<pinPopupWindow>0</pinPopupWindow>` to `1` in `%AppData%\GoldenDict\config` for Windows (or `.GoldenDict/config` for Linux maybe).

If the exact location of the config file is in doubt, you can use some sort of file access monitor like ProcessMonitor for Windows to track it.

**Comment by vedgy** [comment]
> If the exact location of the config file is in doubt, you can use some sort of file access monitor like ProcessMonitor for Windows to track it.

Or use GoldenDict's built-in functionality: _main menu => Help => Configuration Folder_
