### ISSUE TITLE
DICT: HTML article is rendered as plain text

### ISSUE THREAD

**Issue by sikmir** [goldendict/goldendict#1069]
### Steps to reproduce
1. Add DICT Server that responses HTML content on `DEFINE` requests.
2. Lookup some word.

### Actual behaviour
HTML article is rendered as plain text.

### Expected behavior
HTML article should be rendered as HTML.

### RSA
https://github.com/goldendict/goldendict/blob/2bd422ad73ea6ed37a2eab0f3400371d6277bd58/dictserver.cc#L779

`Html::preformat()` converts plain text to HTML, but `articleText` is maybe already HTML (depending on MIME type).

### Proposed Solution
1. Get MIME header with responses ([OPTION MIME](https://tools.ietf.org/html/rfc2229#section-3.10.1))
2. If `Content-Type` is `text/html`, don't preformat response with `Html::preformat()`.

**Comment by Abs62** [comment]
I have add your pull request with some fixes. Test it now, please.

PS. How about "content-transfer-encoding" handling? Do you know servers which can send articles in encoding other than UTF-8?

**Comment by sikmir** [comment]
> I have add your pull request with some fixes. Test it now, please.

Thanks, it works.

> PS. How about "content-transfer-encoding" handling? Do you know servers which can send articles in encoding other than UTF-8?

If you are saying about public DICT servers, I don't know such ones. If you are saying about DICT server implementations, sure, it can be configured with encoding other than UTF-8. As for me. I mostly use non-public DICT servers, but locally hosted ones. But anyway, "content-transfer-encoding" handling is the next feature to be implemented.

**Comment by Abs62** [comment]
OK.
