### ISSUE TITLE
Goldendict doesn't show examples

### ISSUE THREAD

**Issue by petsyk** [goldendict/goldendict#1074]
Goldendict 1.5.0-RC2+git (openSUSE Tumbleweed, KDE Plasma) doesn't show examples (content of [ex] tags) from DSL dictionaries.

![screenshot_20181026_122949](https://user-images.githubusercontent.com/44496784/47561231-fb1a9300-d91a-11e8-9d68-5a955b7ae263.png)
![screenshot_20181026_123022](https://user-images.githubusercontent.com/44496784/47561232-fb1a9300-d91a-11e8-9ada-d9904fffb60e.png)

**Comment by vedgy** [comment]
This issue must be a duplicate of #1062. Check out the comments there for the 2 ways to show the examples. Then close this issue please.

**Comment by petsyk** [comment]
Thank you
