### ISSUE TITLE
Results won't be highlighted when using certain Regex syntax in full text search mode

### ISSUE THREAD

**Issue by GunKneeNeon** [goldendict/goldendict#1082]
The Qt5 based version does support all the syntaxes in the below images, but GD won't show up the results in highlighted background when using certain syntaxes.
![image](https://user-images.githubusercontent.com/44884598/48571164-2f450a80-e941-11e8-86c4-3ba203575e12.png)
![image](https://user-images.githubusercontent.com/44884598/48571173-353aeb80-e941-11e8-915e-94cf3b175cfc.png)
![image](https://user-images.githubusercontent.com/44884598/48571186-3b30cc80-e941-11e8-8886-5e6e189c60b3.png)
![image](https://user-images.githubusercontent.com/44884598/48571197-408e1700-e941-11e8-869a-39dfa11680ec.png)

**Comment by Abs62** [comment]
Fixed in last build.
