### ISSUE TITLE
Italian translation update

### ISSUE THREAD

**Issue by orecchionebruno** [goldendict/goldendict#1083]
Hei guys,
I would update the Italian translation (I'm Daniele, the official Italian translator), I've downloaded last translation file from the code page but I need an early Windows GoldenDict to check some new features. Could you please update Early Compiled GoldenDict for Windows? 
Thankss

**Comment by Abs62** [comment]
Last exe: [1.5.0-RC2-335-g0d9a12a](http://www.mediafire.com/file/g9eh4vf1c8gcb26/goldendict-1.5.0-RC2-335-g0d9a12a%28EXE+only%29.7z).

**Comment by orecchionebruno** [comment]
Great, thank you!

**Comment by Abs62** [comment]
These options are Linux-specific. Look issues #848 and #645.

**Comment by orecchionebruno** [comment]
ok Abs62, thank you!

**Comment by orecchionebruno** [comment]
Hi Abs62,

I'm ready to upload here the translation but I found two missing string for translation:

This two strings ("Select All" and "Copy") are not shown with QT Linguist.
Is it a bug this missing? 

![immagine](https://user-images.githubusercontent.com/861074/48720930-1c705580-ec21-11e8-8df5-6ce6727b241e.png)

![immagine](https://user-images.githubusercontent.com/861074/48720934-2003dc80-ec21-11e8-8567-1991f34d6b6c.png)

**Comment by Abs62** [comment]
There are standard Qt actions (QWebPage::SelectAll and QWebPage::Copy), ones should be translated in Qt translations.

**Comment by orecchionebruno** [comment]
ok, I'll upload also QT translation file ;)

**Comment by orecchionebruno** [comment]
Hi Abs62, I've found those strings in qtbase_it.qm and they are still translated.

I see that qt_it.qm is an empty file, maybe it should be there.
I haven't QT installed, could you please send me your qt_it.qm from your QT installation ?

Thankss

**Comment by orecchionebruno** [comment]
Great, thank you

Here last Italian translation

Cheers

[italian.zip](https://github.com/goldendict/goldendict/files/2599043/italian.zip)

**Comment by orecchionebruno** [comment]
oppss this file was expected 

[locale.zip](https://github.com/goldendict/goldendict/files/2600684/locale.zip)
