### ISSUE TITLE
'QWebSecurityOrigin' file not found

### ISSUE THREAD

**Issue by JonahWong** [goldendict/goldendict#1087]
During it does the 'make' operation, an error happens as below:

In file included from ./mainwindow.hh:17:
./article_netmgr.hh:10:10: fatal error: 'QWebSecurityOrigin' file not found
#include < QWebSecurityOrigin >
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [build/main.o] Error 1

I'm building on Mac OS 10.14 usingQT5.11.2, QtWebKit 5.212.0 Alpha 2

**Comment by Abs62** [comment]
Try to use Qt 5.9.x (long-term support version) and QtWebKit 5.9.

**Comment by JonahWong** [comment]
> Try to use Qt 5.9.x (long-term support version) and QtWebKit 5.9.

Thanks. It has worked.
