### ISSUE TITLE
Scan popup function does not translate Text that has been copied to clipboard automatically on Windows 10

### ISSUE THREAD

**Issue by M1suzu** [goldendict/goldendict#1089]
I tested with Qt 5 based version, both 32 bit and 64 bit and QT 4.8.6 based version too.   

goldendict version: `1.5.0-RC2-311` & `1.5.0-RC2-254`
windows version: `windows 10 pro x64 redstone 5 Version 1809 (October 2018 Update)`

the problem: goldendict Scan popup function does not translate Text that has been copied to clipboard automatically like `version 1.0.1` which work perfectly and can translate Text that has been copied to clipboard automatically.

**Comment by Abs62** [comment]
Read GD help, chapter 6.8 "Options adjustable via config file", parameter "trackClipboardChanges".

**Comment by Abs62** [comment]
Looks like you don't read chapter 6.8 completely. Last sentence:  
>>Note: Before manual editing of the configuration file GoldenDict must be closed or all changes will be cancelled.

**Comment by M1suzu** [comment]
My bad I failed to notice that.
