### ISSUE TITLE
RC2-359 can't parse dict directory using link type

### ISSUE THREAD

**Issue by WanderMax** [goldendict/goldendict#1131]
I try the latest build RC2-359, find this version can't parse dict directory using link type (.lnk), link to another folder.
I try the RC2-311, it can parse dict directory using link type.
Is this feature removed or a one issue?
Thanks!

**Comment by Abs62** [comment]
Under Windows? If yes, try to create symbolic link instead of .lnk file.

**Comment by WanderMax** [comment]
Use mklink, it works, Thanks.
