### ISSUE TITLE
XDXF files doesn't stop indexing if abbreviation element is empty.

### ISSUE THREAD

**Issue by Timofeuz** [goldendict/goldendict#1132]
Adding xdxf files with empty abbreviation xml field will result in indefinite process of initial dictionary indexing.
For example you can try the file attached.

[RuFinance.zip](https://github.com/goldendict/goldendict/files/2975474/RuFinance.zip)

**Comment by Abs62** [comment]
Should be fixed now.

**Comment by nikita-moor** [comment]
Confirm, bug was fixed.
