### ISSUE TITLE
No option to supress the tilde behaviour in DSL dictionaries.

### ISSUE THREAD

**Issue by Timofeuz** [goldendict/goldendict#1133]
Если не против, продолжу на русском. Как я понял, в DSL знак тильды ~ подставляет на её  место словарную статью. Имеются портированные в DSL словари, где подобное поведение не планировалось. Например, если слово
**дама**, то **~ы** подрузамевает **дамы**, но выходит **дамаы**.
Было бы неплохо иметь возможность отключить подстановку слова вместо тильды.

**Comment by Abs62** [comment]
Как по мне, если словарь кривоват, то надо править его, а не словарную оболочку. Это же DSL, голый текст, правится любым редактором.

**Comment by Timofeuz** [comment]
Я думаю, в лингво замена тильды планировалась для языков типа английского, где нет окончаний.
Тильды очень органично вписывается в текст, замена в словаре её на другой знак сделает статьи менее удобочитаемыми, имхо.

**Comment by goodenoughcui168** [comment]
> 
> 
> Как по мне, если словарь кривоват, то надо править его, а не словарную оболочку. Это же DSL, голый текст, правится любым редактором.

Abs62, can you help me solve a problem related with goldendict? When I use a online dict named BAIDUFANYI (https://fanyi.baidu.com/), I find I can not input words in the webpage. I do not know why. I guess whether wetkit can display the page correctly in QT. Thanks in advance and looking forward to your reply.

**Comment by nikita-moor** [comment]
@Timofeuz 
You could escape tilde to prevent substitution:

```
#NAME "Test DSL: tilde"
#INDEX_LANGUAGE	"English"
#CONTENTS_LANGUAGE	"English"

test
  In this line, tilde will be substituted with the article's headword:
  * "~ing"
  Now it is escaped:
  * "\~ing"
```
