### ISSUE TITLE
XDXF: examples rendering

### ISSUE THREAD

**Issue by nikita-moor** [goldendict/goldendict#1135]
XDXF format for examples (quotes) is not fully supported by GoldenDict.
For example, the next code (from a Latin dictionary)
```xml
<ex type="exm" author="Cic.">
  <ex_orig>Quæ supra dixi.</ex_orig>
  <ex_tran>What I have said above or before.</ex_tran>
</ex>
```
will be rendered as:

> Quæ supra dixi. What I have said above or before.

I would like to clearly distinguish quotation and commentary (translation), and add author of the moto. Something like this:

![Screenshot_2019-03-31_23-59-08](https://user-images.githubusercontent.com/13879891/55295003-1a10da00-5411-11e9-841d-5dfec0f413de.png)

I could reach such a result adding styles into `article-style.css`, but have to hardcode the layout (pseudo-code):

```xml
<!-- variant 1 -->
<ex_orig>. — <ex_tran>. [<ex@author> <ex@source>]
<!-- variant 2 -->
<ex_orig>. [<ex@author> <ex@source>] <ex_tran>.
```

GoldentDict is quite tolerant, but it would be better to have valid XDXF file for interoperability with other dictionary shells.

CSS style you may find usefull:

```css
.xdxf_ex:before { content:"• "; }
.xdxf_ex {
    color: #000;
    text-indent: -13px;
}
ex_orig { color: #3465a4; }
ex_tran { font-style: italic; }
```

Here attached is a sample dictionary with one article (key: antea) demonstrating use of `<ex>` with different attributes and subelements. File is fully correct and was validated against DTD schema:
[example-issue.zip](https://github.com/goldendict/goldendict/files/3027153/example-issue.zip)

**Comment by Abs62** [comment]
I made some changes, try now.

**Comment by nikita-moor** [comment]
So fast and right, your are awesome!
