### ISSUE TITLE
suggestion: add vimium-like page scroll operation

### ISSUE THREAD

**Issue by roro4ever** [goldendict/goldendict#1153]
Vimium is an extension for chrome, the user can scrolls webpage by j,k for up and down,h and l for left and right.

Many goldendict users suggest introduce this feature. 

If it comes true, you can type "gi" move cursor into the textbox,then typein the word for lookup, enter for complete. 

Then it will automatically focus on the result page, waiting you hit j,k,h,l keys for scrolling the page.

That would be a great operation revolution for pure keyboard users.

**Comment by vedgy** [comment]
It is possible to configure arrows and other often-used keys (e.g. PageDown, Home, Delete) at the third level of alphanumeric keys. On GNU/Linux this can be done via xkb symbols tweaking, on Windows - with a custom keyboard layout and/or AutoHotkey. This way the same keys work across all applications (sans rare bugs), without a need to complicate every application's code. I'm using such configuration on Linux for years now. I have used it on Windows too (but with an unreliable Delete key AutoHotkey shortcut). I haven't managed to configure this on Mac though.

**Comment by roro4ever** [comment]
em...you are right, AHK is a better solution, thank you.

**Comment by vedgy** [comment]
I used [Microsoft Keyboard Layout Creator 1.4](https://www.microsoft.com/en-us/download/details.aspx?id=22339) to create a custom keyboard layout. But it was not sufficient. So I also created an AutoHotkey script with 3rd and 4th level shortcuts for my preferred keyboard layout. In order to facilitate access to the 3rd level keys, I remapped my Caps Lock key to AltGr via a registry tweak. The [attached files](https://github.com/goldendict/goldendict/files/3201221/keyboard_tweaks.zip) worked on my Windows 7 systems. Feel free to use my AutoHotkey script as a starting point.

If you no longer need this vimium-like feature, please close the issue.

**Comment by roro4ever** [comment]
Today, I want to write a very simple ahk script to solve my problem.
The thought is Remap the {WheelDown}{WheelUp} to J K using SendInput.
But first I should make sure the focus is stop on the ResultPage.
So I'v tried AHK's Window Spy to get the ResultPage's controlNN, but failed, coz GoldenDict is written by QT. 
Then i tried MASS(microsoft active accessibility 2.0), but it's too old to installed on Windows 10.
Is there any way to get the runtime info of QT app on Windows 10?

**Comment by roro4ever** [comment]
> I used [Microsoft Keyboard Layout Creator 1.4](https://www.microsoft.com/en-us/download/details.aspx?id=22339) to create a custom keyboard layout. But it was not sufficient. So I also created an AutoHotkey script with 3rd and 4th level shortcuts for my preferred keyboard layout. In order to facilitate access to the 3rd level keys, I remapped my Caps Lock key to AltGr via a registry tweak. The [attached files](https://github.com/goldendict/goldendict/files/3201221/keyboard_tweaks.zip) worked on my Windows 7 systems. Feel free to use my AutoHotkey script as a starting point.
> 
> If you no longer need this vimium-like feature, please close the issue.

I download the files, tried it later. Thanks.

**Comment by vedgy** [comment]
>  But first I should make sure the focus is stop on the ResultPage.

So is there some problem with focus? Is this a bug that can be fixed in Goldendict code?

**Comment by roro4ever** [comment]
No, it's not a bug of goldenDict, it's a problem about how to get the control's ClassNN (the classname and instance number of the control) of a QT application using AHK Window Spy(or any other windows spy tool).

If we got the ClassNN of resultPage, we could use
```
ControlFocus [, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]
```
to focus on it, then remap hotkey
```
^j::SendInput {WheelDown}
^k::SendInput {WheelUp}
```
But now, all controlNN show as "QWidget".
This problem have been discussed many years ago.
[Access QT Framework controls (QWidget) in applications like VLC](https://autohotkey.com/board/topic/96270-access-qt-framework-controls-qwidget-in-applications-like-vlc/)

I think, there is another way to complete it.
```
ControlFocus [, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]
```
the first "Control" argument also accept "the control's text", so we can fill it with some text comes from resultpage, maybe the dictionary's name, like "Macmillan English Dictionary 2nd Edition","Collins Thesaurus",etc.
That will be a dictionary-related statment, and the execute speed may be slow.

**Comment by vedgy** [comment]
Why not just map the keys to arrow buttons instead of mouse wheel events? They should work as long as the Goldendict article view has focus. If it doesn't have focus, you can transfer it with the Ctrl+N shortcut. From my AutoHotkey script:
```
<^>!+h::Send {NumpadLeft}
<^>!t::Send {NumpadDown}
```

**Comment by roro4ever** [comment]
I am using a portable version goldendict, no help file.
It's my first time knowing there are some shortcuts inside goldendict.
Ctrl + N is what I need. 
thanks,problem resolved.
