### ISSUE TITLE
Any update on google translate implementation?

### ISSUE THREAD

**Issue by andradadad** [goldendict/goldendict#1170]
I remember using google translate in early GD.

**Comment by darnn** [comment]
I think this is your best bet at the moment: https://github.com/xinebf/google-translate-for-goldendict

**Comment by Symbian9** [comment]
Alternatively to described above Python script, there is pure Bash script for same purpose:

- https://github.com/OPHoperHPO/GT-bash-client/issues/3

**Comment by sikmir** [comment]
For Nix users:
* [nur.repos.sikmir.gt4gd](https://github.com/nix-community/nur-combined/tree/master/repos/sikmir/pkgs/gt4gd)
* [nur.repos.sikmir.gt-bash-client](https://github.com/nix-community/nur-combined/tree/master/repos/sikmir/pkgs/gt-bash-client)
