### ISSUE TITLE
[slob] header

### ISSUE THREAD

**Issue by nikita-moor** [goldendict/goldendict#1176]
# Feature request

GoldenDict adds an unwanted header to every Slob article (see `<h3>` tag):

```html
<div class="gdarticlebody">
    <h3>test</h3>
    <div class="slobdict">definition<br style="clear:both;"></div>
</div>
```

Slob article is encapsulated into `<div class="slobdict">` and all CSS styles are escaped within `.slobdict` class, so I cannot hide this header.

There are two possible ways to solve the problem:

1. Remove the header completely, parsers of other formats do not adding headers voluntary.
1. Put `<h3>` tag inside of `<div class="slobdict">`, so it could be managed by the styles embedded into Slob-file.

Test dictionary (key "test"): [slob-test-h3.zip](https://github.com/goldendict/goldendict/files/3415237/slob-test-h3.zip)

P.S. XDXF parser makes headers from the keys, it's correct. But in case of Slob, GoldenDict adds only 1 header even if the article has several attached keys: see keys "test1" and "test2" of the test dictionary.
P.P.S. I could hide the header through `article-style.css`.

**Comment by Abs62** [comment]
Try now, please (and also two other issues).

**Comment by nikita-moor** [comment]
Confirm, the problem has been solved.

**Comment by nikita-moor** [comment]
@Abs62 you are awesome!
