### ISSUE TITLE
Problem compiling  on Win 7 with Qt 5.10.1 MinGW 5.3.0 32bits

### ISSUE THREAD

**Issue by typename** [goldendict/goldendict#1180]
Hello,
I'm getting this error:

> 15:14:36: Running steps for project goldendict...
> 15:14:36: Configuration unchanged, skipping qmake step.
> 15:14:36: Starting: "C:\Qt\Tools\mingw530_32\bin\mingw32-make.exe" -j4
> C:/Qt/Tools/mingw530_32/bin/mingw32-make -f Makefile.Debug
> mingw32-make[1]: Entering directory 'C:/Users/user/Documents/Qt/build-goldendict-Qt_5_10_1_MinGW_32-Debug'
> C:\Qt\5.10.1\mingw53_32\bin\rcc.exe -name resources ..\goldendict\resources.qrc -o build\qrc_resources.cpp
> g++ -c -fno-keep-inline-dllexport -std=c++11 -Wextra -Wempty-body -g -std=gnu++11 -frtti -fexceptions -mthreads -Wall -W -Wextra -DUNICODE -D_UNICODE -DWIN32 -DMAKE_QTMULTIMEDIA_PLAYER -DMAKE_FFMPEG_PLAYER -DPROGRAM_VERSION=\"1.5.0-RC2+git\" -DMAKE_ZIM_SUPPORT -DMAKE_EXTRA_TIFF_HANDLER -DMAKE_CHINESE_CONVERSION_SUPPORT -DQT_QML_DEBUG -DQT_SVG_LIB -DQT_WEBKITWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_HELP_LIB -DQT_WIDGETS_LIB -DQT_WEBKIT_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I..\goldendict -I. -I..\goldendict -I..\goldendict\winlibs\include -I..\goldendict\qtsingleapplication\src -IC:\Qt\5.10.1\mingw53_32\include -IC:\Qt\5.10.1\mingw53_32\include\QtSvg -IC:\Qt\5.10.1\mingw53_32\include\QtWebKitWidgets -IC:\Qt\5.10.1\mingw53_32\include\QtPrintSupport -IC:\Qt\5.10.1\mingw53_32\include\QtHelp -IC:\Qt\5.10.1\mingw53_32\include\QtWidgets -IC:\Qt\5.10.1\mingw53_32\include\QtWebKit -IC:\Qt\5.10.1\mingw53_32\include\QtMultimedia -IC:\Qt\5.10.1\mingw53_32\include\QtGui -IC:\Qt\5.10.1\mingw53_32\include\QtANGLE -IC:\Qt\5.10.1\mingw53_32\include\QtXml -IC:\Qt\5.10.1\mingw53_32\include\QtNetwork -IC:\Qt\5.10.1\mingw53_32\include\QtSql -IC:\Qt\5.10.1\mingw53_32\include\QtCore -Ibuild -Ibuild -IC:\Qt\5.10.1\mingw53_32\mkspecs\win32-g++  -o build\qrc_resources.o build\qrc_resources.cpp
> g++ -Wl,--large-address-aware -Wl,-subsystem,console -mthreads -o debug\GoldenDict.exe object_script.GoldenDict.Debug  -lz -lbz2 -llzo2 -LC:\Users\user\Documents\Qt\goldendict\winlibs\lib -lhunspell-1.6.1 -liconv -lwsock32 -lpsapi -lole32 -loleaut32 -ladvapi32 -lcomdlg32 -lvorbisfile -lvorbis -logg -lao -lavutil-gd -lavformat-gd -lavcodec-gd -luxtheme -llzma -ltiff -leb -lopencc -LC:\Qt\5.10.1\mingw53_32\lib C:\Qt\5.10.1\mingw53_32\lib\libQt5Svgd.a -lQt5WebKitWidgetsd C:\Qt\5.10.1\mingw53_32\lib\libQt5PrintSupportd.a C:\Qt\5.10.1\mingw53_32\lib\libQt5Helpd.a C:\Qt\5.10.1\mingw53_32\lib\libQt5Widgetsd.a -lQt5WebKitd C:\Qt\5.10.1\mingw53_32\lib\libQt5Multimediad.a C:\Qt\5.10.1\mingw53_32\lib\libQt5Guid.a C:\Qt\5.10.1\mingw53_32\lib\libQt5Xmld.a C:\Qt\5.10.1\mingw53_32\lib\libQt5Networkd.a C:\Qt\5.10.1\mingw53_32\lib\libQt5Sqld.a C:\Qt\5.10.1\mingw53_32\lib\libQt5Cored.a build\goldendict_res.o 
> ./build\hunspell.o: In function `run':
> C:\Users\user\Documents\Qt\build-goldendict-Qt_5_10_1_MinGW_32-Debug/../goldendict-master/hunspell.cc:274: undefined reference to `Hunspell::spell(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
> C:\Users\user\Documents\Qt\build-goldendict-Qt_5_10_1_MinGW_32-Debug/../goldendict-master/hunspell.cc:286: undefined reference to `Hunspell::suggest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> ./build\hunspell.o: In function `suggest':
> C:\Users\user\Documents\Qt\build-goldendict-Qt_5_10_1_MinGW_32-Debug/../goldendict-master/hunspell.cc:508: undefined reference to `Hunspell::analyze(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> ./build\hunspell.o: In function `run':
> C:\Users\user\Documents\Qt\build-goldendict-Qt_5_10_1_MinGW_32-Debug/../goldendict-master/hunspell.cc:668: undefined reference to `Hunspell::spell(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
> ./build\chinese.o: In function `ZN7Chinese29CharacterConversionDictionaryC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_5QIconRK7QString':
> C:\Users\user\Documents\Qt\build-goldendict-Qt_5_10_1_MinGW_32-Debug/../goldendict-master/chinese.cc:53: undefined reference to `_imp___ZN6opencc15SimpleConverterC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'
> ./build\chinese.o: In function `ZN7Chinese29CharacterConversionDictionary20getAlternateWritingsERKNSt7__cxx1112basic_stringIjSt11char_traitsIjESaIjEEE':
> C:\Users\user\Documents\Qt\build-goldendict-Qt_5_10_1_MinGW_32-Debug/../goldendict-master/chinese.cc:97: undefined reference to `_imp___ZNK6opencc15SimpleConverter7ConvertERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'
> collect2.exe: error: ld returned 1 exit status
> mingw32-make[1]: *** [debug\GoldenDict.exe] Error 1
> mingw32-make: *** [debug] Error 2
> 
> 
> Makefile.Debug:698: recipe for target 'debug\GoldenDict.exe' failed
> mingw32-make[1]: Leaving directory 'C:/Users/user/Documents/Qt/build-goldendict-Qt_5_10_1_MinGW_32-Debug'
> Makefile:36: recipe for target 'debug' failed
> 15:14:57: The process "C:\Qt\Tools\mingw530_32\bin\mingw32-make.exe" exited with code 2.
> Error while building/deploying project goldendict (kit: Qt 5.10.1 MinGW 32)
> When executing step "Make"

Any ideas what's going on here?

 Regards.

**Comment by nonwill** [comment]
You need rebuild  the [winlib](https://github.com/nonwill/goldendict/tree/master/winlibs/lib) all with your current gcc+mingw, or you can try a more modern gcc+mignw to rebuild Qt+QWebKit and the [winlib](https://github.com/nonwill/goldendict/tree/master/winlibs/lib), then give a second try to build GoldenDict.

**Comment by typename** [comment]
Done with your git repo and, qt 5.12 + mingw 7

Thanks.
