### ISSUE TITLE
GoldenDict for windows has built-in virus programs!

### ISSUE THREAD

**Issue by sstaroom** [goldendict/goldendict#1199]
As soon as it is started, the Total Commander directory is always positioned to "\*.EXE;*.COM;*.BAT;*.PIF;*.CMD". All directories become executable directories and cannot be cancelled! I'm using the latest version(1.5.0-RC2-372-gc3ff15f).

![gd](https://user-images.githubusercontent.com/21096437/65851228-be55e800-e384-11e9-84d0-ac735ef2d3f5.png)

**Comment by nikita-moor** [comment]
VirusTotal says [it is clean](https://www.virustotal.com/gui/url/0dde9e9540b041d765b85e5d0539fc681fa50d74a127b69e4e786c3cdd675478/detection).
