### ISSUE TITLE
Invalid character sequence encountered during character conversion

### ISSUE THREAD

**Issue by ReichKV** [goldendict/goldendict#1203]
Hi,

I have few dictionaries with UTF-16LE encoding. In order to slightly edit these dictionaries in Linux I converted them to UTF-8 with (dos2unix tool). I packed them back with dictzip. However goldendict cannot index such dictionaries. Namely it writes:

DSL dictionary reading failed: /home/user/DICTS/En-En-Longman_DOCE5_Extras/En-En-Longman_DOCE5_Extras.dsl:2168, error: Invalid character sequence encountered during character conversion. 

The error occurs on characters like: ˘,` and so on..

My steps are the following:
1. dictunzip A.dsl.dz 
2. dos2unix A.dsl  ( Also i used iconv -f utf-16le -t utf-8 A.dsl > AA.dsl)
3. dictzip A.dsl

Does goldendict support only dictionaries in utf-16le encoding?

**Comment by Abs62** [comment]
GD allow UTF-8 encoding in DSL but BOM must be presented in such files. Try "--add-bom" option for dos2unix while converting files.

**Comment by ReichKV** [comment]
Thank you for the help. It works
