### ISSUE TITLE
Cannot use ibus on Manjaro to type Vietnamese [RC2-408-gdf92b38e]

### ISSUE THREAD

**Issue by Hassenky** [goldendict/goldendict#1206]
Hi developers,

I have Goldendict version RC2-408-gdf92b38e in my laptop running Manjaro 18.10, but cannot use ibus bamboo to type vietnamese. Could you please check this issue?

Many thanks.

Hassen

**Comment by nikita-moor** [comment]
* Manjaro 18.10
* ibus 1.5.21
* ibus-bamboo 0.5.8 (AUR)
* goldendict-git 1.5.0.RC.1033.gc53fe1c6 (AUR)

I am not familiar with `bamboo`, but typing in GoldenDict's search field `dd` makes `đ`, so it seems working. I use  several `ibus` keyboards (`ibus-libpinyin` and `ibus-keyman`) every day and `ibus` works fine in GoldenDict.

Maybe you mean that GoldenDict does not set focus on the search field when you start typing? Yes, it is not convenient. I have to press Ctrl-L or use mouse.

**Comment by Hassenky** [comment]
Thanks for your answer Nikita. I tried every version from AUR but the same thing happens. Maybe something wrong with ibus Bamboo.

**Comment by nikita-moor** [comment]
I would recommend you trying other applications based on Qt libraries, such as `Notepadqq`. Does `ibus-bamboo` work with them correctly?

**Comment by Hassenky** [comment]
`ibus-bamboo` does not work as well.

**Comment by nikita-moor** [comment]
Use recommendations from Arch Linux wiki and forums:
* https://wiki.archlinux.org/index.php/IBus#Initial_setup
* https://bbs.archlinux.org/viewtopic.php?id=173675

**Comment by Hassenky** [comment]
Thanks for your help Nikita.

I found that this is a universal error of ibus. Someone reported it in the repository of ibus already [ibus/ibus#2137](https://github.com/ibus/ibus/issues/2137). This error happens to all of QT apps (calibre, goldendict, telegram, keepassX, ...).

**Comment by Hassenky** [comment]
issued has been solved in a recent version of iBus BamBoo.  Many thanks.
