### ISSUE TITLE
After minimize Gold Dict to the tray-bar for few hours,  "Ctrl-C-C" popup slow response.

### ISSUE THREAD

**Issue by holahapi** [goldendict/goldendict#1209]
After minimize Gold Dict to the tray-bar for few hours.
The Ctrl-C-C need 4+ seconds to show the popup.
I tried to set GD as "high property" in "Task-Manager", but it seems not helping.

Is there any way to improve it?

**Comment by saeidscorp** [comment]
Not sure about the exact cause, but it seems to me that GoldenDict gets swapped out to the virtual page file, hence the slowdown after a few hours.

**Comment by holahapi** [comment]
Thank you **saeidscorp**, I will check that out and do some tests.

**Comment by holahapi** [comment]
After 2 weeks tests, it seems caused by virtual page file.
Here is a tutorial [link ](https://www.tomshardware.com/reviews/ssd-performance-tweak,2911-4.html)to turn it off in case some one needs it.
