### ISSUE TITLE
Problems compiling linux current version github

### ISSUE THREAD

**Issue by Nick-us** [goldendict/goldendict#1216]
I am following the instructions on the site but it doesn't work!
I downloaded: git clone git://github.com/goldendict/goldendict.git
**When having run:**
`qmake-qt4 OR qmake`

Returns his help page
```
# qmake
Usage: qmake [mode] [options] [files]
```

The only version I can compile is: goldendict-1.5.0-RC2.tar.gz
And even this version, I was forced to disable ffmpeg because it seems to be outdated with the current version and generated many errors and did not complete the compilation, with ffmpeg enabled

I have the impression something is missing from the current github source
Can someone help me? Compiling the current Github Source?

System: Linux / Slackware64-Current

**Comment by vedgy** [comment]
First of all, Qt4 is obsolete and is unsupported since 2015, so prefer Qt5. Try `qmake-qt5`.
Make sure that you are in the goldendict root directory when you run any qmake version (the directory, which contains the *goldendict.pro* file).
If this still doesn't work, try `qmake goldendict.pro` (you can replace `qmake` with `qmake-qt5` or `qmake-qt4` in this command).

**Comment by Nick-us** [comment]
> Try `qmake-qt5`.

I tried it in 2 ways, but something is still missing
```
bash-5.0# qmake-qt5 goldendict.pro
fatal: not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Project MESSAGE: Failed to precisely describe the version via Git -- using the default version string
Project MESSAGE: Install Prefix is: /usr/local
Project ERROR: Unknown module(s) in QT: webkitwidgets

bash-5.0# qmake goldendict.pro
fatal: not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Project MESSAGE: Failed to precisely describe the version via Git -- using the default version string
Project MESSAGE: Install Prefix is: /usr/local
```

**Comment by vedgy** [comment]
> fatal: not a git repository (or any parent up to mount point /mnt)
1. Did you actually clone the repository with this command `git clone git://github.com/goldendict/goldendict.git` and still have *git* installed?
> bash-5.0# qmake-qt5 goldendict.pro
2. It looks like you are running `qmake` as root. If that is the case, run it as a regular user; you may have to delete already generated files as root though. Run `git status --ignored` to get the list of ignored files, which you probably should delete.
> Project ERROR: Unknown module(s) in QT: webkitwidgets
3. For Qt5 you'll need to install QtWebKit package with your package manager. _If you are using non-system Qt5 (downloaded from the official Qt website), then you'll have to build QtWebKit manually, which won't be easy, or use Qt 5.5 or earlier._
