### ISSUE TITLE
Multiple data races on DataRequest::hasAnyData and DataRequest::data

### ISSUE THREAD

**Issue by vedgy** [goldendict/goldendict#1218]
While investigating GCC's *-fsanitize=thread* output (#976), I've found several similar data races:
1. [Here](https://github.com/goldendict/goldendict/blob/1cef1a8733ae3b03ac41182da1906a8d0922c471/gls.cc#L1538) `hasAnyData` is written to without locking `dataMutex`. [Here](https://github.com/goldendict/goldendict/blob/1cef1a8733ae3b03ac41182da1906a8d0922c471/mdx.cc#L700) `hasAnyData` is written to, then read without locking the mutex. There are similar data races on `hasAnyData` in *stardict.cc*, *slob.cc* and *zim.cc*.
2. [Here](https://github.com/goldendict/goldendict/blob/1cef1a8733ae3b03ac41182da1906a8d0922c471/slob.cc#L1627) `data` is accessed without locking. There is a very similar issue in *zim.cc*.

**Comment by Abs62** [comment]
Thanks, should be fixed now.

**Comment by vedgy** [comment]
Your fixes look good. Thank you.
