### ISSUE TITLE
Feature request: Proxy for online dictionarys.

### ISSUE THREAD

**Issue by SainoNamkho** [goldendict/goldendict#1219]
The Wikipedia website is blocked in my region, so the connection is always closed for internet looking up.
Can you add any proxy settings? Thanks a lot.

**Comment by darnn** [comment]
have you tried this mirror? https://en.vikiansiklopedi.org/wiki/Main_Page

**Comment by SainoNamkho** [comment]
@darnn Thank you very much!

**Comment by SainoNamkho** [comment]
I didn't close this issue for concern on lifetime of the mirror. Last year I've changed more than 12  mirror sites, either closed or blocked.

**Comment by darnn** [comment]
Oh, no problem, I just thought it might be useful. Have you tried using the proxy server thing that's already in Goldendict (prefereces, network)?

**Comment by SainoNamkho** [comment]
Well I just remember I've looked through preferences and didn't find such settings … but emmm, I can't understand why I'm so careless. So sorry to bother.
