### ISSUE TITLE
hunspell not found?

### ISSUE THREAD

**Issue by bigbagboom** [goldendict/goldendict#1250]
hi, i am not sure it's an issue related to goldebdict, but i have stucked for days. maybe someone can help.

when i try to compile from the source, i got following messages: 

xxxxx@xxxx : ~/goldendict/goldendict$ qmake-qt4 && make
Project MESSAGE: Install Prefix is: /usr/local
Project ERROR: Package hunspell not found
xxxxx@xxxx : ~/goldendict/goldendict$ hunspell -v
@(#) International Ispell Version 3.2.06 (but really Hunspell 1.7.0)

Copyright (C) 2002-2014 László Németh. License: MPL/GPL/LGPL.

Based on OpenOffice.org's Myspell library.
Myspell's copyright (C) Kevin Hendricks, 2001-2002, License: BSD.

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE,
to the extent permitted by law.
xxxxx@xxxx :~/goldendict/goldendict$ 

I googled a lot, but no one got same situation, so I try here.  Many thanks.

**Comment by vedgy** [comment]
First of all, Qt4 [has been unsupported since 2015](https://en.wikipedia.org/wiki/Qt_version_history#Qt_4). Build Goldendict with Qt5 unless there is some Qt5-specific bug that is a unacceptable to you.

One possible reason for this error is that you are reusing the same build directory you used in the past to build with an older hunspell version. Perhaps you have passed `"CONFIG+=old_hunspell"` to `qmake`. Try in a clean and empty build directory:

```bash
git clean -xdn
# If you have valuable files in this directory that are listed by the above command,
# don't run the following command! You can probably safely skip this step.
git clean -xdf
mkdir build
cd build
qmake ../goldendict.pro
make -j5
```

**Comment by bigbagboom** [comment]
> First of all, Qt4 [has been unsupported since 2015](https://en.wikipedia.org/wiki/Qt_version_history#Qt_4). Build Goldendict with Qt5 unless there is some Qt5-specific bug that is a unacceptable to you.
> 
> One possible reason for this error is that you are reusing the same build directory you used in the past to build with an older hunspell version. Perhaps you have passed `"CONFIG+=old_hunspell"` to `qmake`. Try in a clean and empty build directory:
> 
> ```shell
> git clean -xdn
> # If you have valuable files in this directory that are listed by the above command,
> # don't run the following command! You can probably safely skip this step.
> git clean -xdf
> mkdir build
> cd build
> qmake ../goldendict.pro
> make -j5
> ```

Thank you for your reply/suggestion. But I have got no lucky. I did everything you told, but still got same error msg, following are some edited output:

myname@mypc:~/goldendict$ **sudo apt install libhunspell-dev**
Reading package lists... Done
Building dependency tree
Reading state information... Done
**libhunspell-dev is already the newest version (1.7.0-2build1).**
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

myname@mypc:~/goldendict$ **hunspell -v**
@(#) International Ispell Version 3.2.06 (but really Hunspell 1.7.0)


Copyright (C) 2002-2014 László Németh. License: MPL/GPL/LGPL.

Based on OpenOffice.org's Myspell library.
Myspell's copyright (C) Kevin Hendricks, 2001-2002, License: BSD.

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE,
to the extent permitted by law.

myname@mypc:~/goldendict$ **git clean -xdn**
will delete .qmake.stash
will delete locale/ar_SA.qm
will delete locale/ay_WI.qm
... ...
will delete locale/zh_TW.qm
will delete version.txt

myname@mypc:~/goldendict$ **git clean -xdf**
deleting .qmake.stash
deleting locale/ar_SA.qm
deleting locale/ay_WI.qm
... ...
deleting locale/zh_CN.qm
deleting locale/zh_TW.qm
deleting version.txt

myname@mypc: ~/goldendict $ **mkdir build**
myname@mypc: ~/goldendict $ **cd build**
myname@mypc: ~/goldendict/build $ **qmake ../goldendict.pro**
Info: creating stash file /home/josephshi/goldendict/build/.qmake.stash
Project MESSAGE: Install Prefix is: /usr/local
Info: creating stash file /home/josephshi/goldendict/.qmake.stash
Project ERROR: hunspell development package not found
myname@mypc: ~/goldendict/build$

**Comment by vedgy** [comment]
I don't know what the problem might be. I just built the latest goldendict master (somewhat customized with my patches that are totally unrelated to hunspell) on Manjaro with "International Ispell Version 3.2.06 (but really Hunspell 1.7.0)". Are you building the latest git version of goldendict or an older version? You can check/update with
```bash
cd goldendict
git status
git pull
```

If this doesn't help:

1. Please post your Qt version (`qmake -v`).
2. Are you using system packages for Qt and all other goldendict's dependencies?
3. Which version of what distribution are you trying to build goldendict on?
4. 32- or 64-bit system?
5. Have you [installed all dependencies](https://github.com/goldendict/goldendict#installing-external-deps-on-ubuntu-linux-for-qt5)?
6. Post the output of the following commands: `locate libhunspell`, `locate hunspell.pc`, `pkg-config --version`, `pkg-config --path hunspell`, `pkg-config --libs hunspell`, `pkg-config --print-variables hunspell`, `pkg-config --print-provides hunspell`.

**Comment by bigbagboom** [comment]
thank you vedgy, after add `export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig` the problem is gone. although there have some new... anyway, thank you.
