### ISSUE TITLE
New Windows Build?

### ISSUE THREAD

**Issue by loyukfai** [goldendict/goldendict#1254]
The last Windows build is almost an year old...

https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows

Cheers.

**Comment by nonwill** [comment]
[I've a private build with the most recent source and newer Qt(and newer 3rd-party libs). I also Added two Built-in-OCR Engines(Nicomsoft+Tesseract) for it. It functions well and effectively. I'm glad if you can give it a try.
https://nonwill.github.io/post/goldendict/)](https://nonwill.github.io/post/goldendict/)

**Comment by loyukfai** [comment]
@Abs62 Hi there! Hope everything is fine, any updates for us? Thx a lot in advance.

**Comment by Shen897** [comment]
@nonwill can you sent in the pull requests so they can be in the main stream channel?  
Your Built-in-OCR feature is amazing and really helpful.

**Comment by nonwill** [comment]
@Shen897
All changes after [pull request](https://github.com/goldendict/goldendict/pull/1129) have not pushed in yet.

**Comment by loyukfai** [comment]
Wondering if the original dev has gone missing, maybe someone can fork the project and release something like GoldenDict-NG.

Apparently the Android and Mac apps are quite out-of-date as well.

Cheers.

**Comment by nonwill** [comment]
Things are a bit complicated，all contributors have life and work and maintenance work also takes time.

**Comment by loyukfai** [comment]
Of course, and this is one beauty possibility of open source, that others can build upon the foundation established by others and continue the work beyond one's lifetime.

Cheers.

**Comment by loyukfai** [comment]
A new Android build was just released, so perhaps we'll see new releases for Mac and Windows soon as well.

Cheers.
