### ISSUE TITLE
Scan Popup in Linux?

### ISSUE THREAD

**Issue by Golddouble** [goldendict/goldendict#1263]
Do I understand right, that in MX Linux 19 only "CTRL+C+C" works,but not Scan popup?

In my experience, settings I make in the tab "scan popup" have no effect. I have tried out different combinations. Is this right?

If this is true: Why do you not remove this tab in the Linux version of GD?

Thank you for an answer.

**Comment by vedgy** [comment]
I don't recall anyone reporting such an issue. It must work for all (or most) other GNU/Linux users. Did you forget to turn the scan popup on? There is a checkable Scan Popup tool button on the Goldendict's main window top toolbar and a checkable Scan Popup context menu item in the notification area (aka system tray) icon's context menu.

**Comment by Golddouble** [comment]
This is what I have:
![This is what I have in in the notification area-1](https://user-images.githubusercontent.com/13977359/83326018-242aa480-a271-11ea-9296-d99c6bf1d607.png)
![This is what I have in in the main window](https://user-images.githubusercontent.com/13977359/83326020-268cfe80-a271-11ea-814b-221bab1d7bff.png)
![This are my settings](https://user-images.githubusercontent.com/13977359/83326025-2987ef00-a271-11ea-8c81-acbede6a03d7.png)

Does simply not work. (?)

**Comment by vedgy** [comment]
There might be some issues with the "selected keys". Try unchecking the *Only show popup when all selected keys are kept pressed* checkbox. If the Scan Popup starts working, re-check the checkbox and test if other modifier key combinations work.

**Comment by Golddouble** [comment]
I have unchecked this. But when the mouse is over a word in Featherpad nothing happens.

**Comment by Golddouble** [comment]
Edit: 
When I double click words, it works.

**Comment by vedgy** [comment]
Yes, that is how the feature works under GNU/Linux - via [primary selection](https://doc.qt.io/qt-5/qclipboard.html#Mode-enum).

**Comment by Golddouble** [comment]
Huch! Thank you. 

Until now I only used GD under Windows. There it was not needed to mark a word first. We were able to simply press some defined keys (like "shift") and when then the mouse cursor was placed above of a word the DG-window was popping up. No need to select the word first.

**Comment by vedgy** [comment]
The feature just works differently on different OSs. In fact some users have grown accustomed to the way it works on Linux and miss it on Windows. In addition the feature is application-dependent and doesn't always work on Windows. There are bugs with the selection scan popup on GNU/Linux too. So these are the tradeoffs.

**Comment by Golddouble** [comment]
Indeed: In Wine only CTR+C+C seems to work. Right?

**Comment by vedgy** [comment]
Never tried it in Wine. You can search the issue tracker for such bug reports.

**Comment by Golddouble** [comment]
Thank you.
