### ISSUE TITLE
Dark mode (Qt)

### ISSUE THREAD

**Issue by r-o-o-t-y** [goldendict/goldendict#1278]
Hey, I hate to bother anyone with this but - while I do realize that Linux users can just select a dark qt (kde) theme and be done with it, would it be possible to make GoldenDict dark on Windows/macOS? 

Perhaps by implementing this: https://forum.qt.io/topic/101391/windows-10-dark-theme/2. 

The link mentions this: https://github.com/ColinDuquesnoy/QDarkStyleSheet
and this: https://github.com/Jorgen-VikingGod/Qt-Frameless-Window-DarkStyle?

I don't know how to code so I don't know how to implement those :/

This is how GoldenDict appears at present
![image](https://user-images.githubusercontent.com/36138721/91213970-b3314680-e712-11ea-82d0-b3caa2624342.png)

Thanks!

**Comment by r-o-o-t-y** [comment]
Hey I managed to get this working using a different Windows 10 theme so ... I'm gonna close this.

![image](https://user-images.githubusercontent.com/36138721/91349476-9fa2e000-e7e5-11ea-929c-7fee01dba141.png)

**Comment by IAmNotAJerk** [comment]
> 
> 
> Hey I managed to get this working using a different Windows 10 theme so ... I'm gonna close this.
> 
> ![image](https://user-images.githubusercontent.com/36138721/91349476-9fa2e000-e7e5-11ea-929c-7fee01dba141.png)

Mind sharing how it's done?
Windows user who is encounter the similar problem as you.
