### ISSUE TITLE
[Feature Request] Open images in external image viewer

### ISSUE THREAD

**Issue by nikita-moor** [goldendict/goldendict#1279]
It **does work** in the main window when I double-click on the image, but not in the secondary(?) window opened with hotkey Ctrl-C-C.

**System:** Linux/Manjaro
**GoldenDict**: GIT (gdda311cf) + Qt5 / build 2020-08-26

[This dictionary][1] can be used for testing (look for 'amor').

[1]: https://github.com/nikita-moor/latin-dictionary/releases/tag/2020-08-23

**Comment by nikita-moor** [comment]
My problem can be solved by changing one line:

https://github.com/goldendict/goldendict/blob/30a61c0ee0f6ae250756a115e1e4bcb221e5a163/articleview.cc#L2233

Condition `!popupView` is unnecessary here.

Also, it would be very nice if you [add cache](https://doc.qt.io/qt-5/qnetworkdiskcache.html) to objects of `ArticleNetworkAccessManager`. I link big images (scans of the dictionary pages), and it takes time to download them from a slow website (archive.org). When I double-click on them, images are being downloaded again. So, some caching would save the day.

**Comment by Abs62** [comment]
Popup window have limited funtionality by design.

**Comment by nikita-moor** [comment]
Our group provides [a dozen of dictionaries](https://nikita-moor.github.io/dictionaries/dictionaries.html) based on page scans, so double-click will be really convenient. In website-style dictionaries, it can be bypassed adding links:

```html
<a href="file://…">
  <img src="file://…"><img>
</a>
```

But it doesn't work with `http://…` sources and normal dictionary formats (Stardict, Slob, Mdict). So I ask you to reconsider such limitation.

**Comment by nikita-moor** [comment]
The proposed change is not big, and it's nothing bad if a user wants to have a good look at pictures.

**Comment by Abs62** [comment]
Popup window was designed for fast lookup in small group of dictionaries. As popup hint instead of documentation chapter. Why do you don't want to use main window?
About caching. How about cache cleanup on quit (at least in the portable version)?

**Comment by nikita-moor** [comment]
Popup window:
1. select a word
1. press <kbd>Ctrl</kbd>+<kbd>C</kbd>+<kbd>C</kbd>
1. profit.

Main window:
1. select a word
1. copy <kbd>Ctrl</kbd>+<kbd>C</kbd>
1. open window <kbd>Ctrl</kbd>+<kbd>F11</kbd>+<kbd>F11</kbd>
1. navigate to the search pane <kbd>Ctrl</kbd>+<kbd>L</kbd>
1. past the text <kbd>Ctrl</kbd>+<kbd>V</kbd>
1. finally <kbd>Enter</kbd>
1. soooooo long way

> About caching. How about cache cleanup on quit (at least in the portable version)?

It says, QNetworkDiskCache is [limited to 50MB](https://doc.qt.io/qt-5/qnetworkdiskcache.html#details). On the termination, one could use [QNetworkDiskCache::clear()](https://doc.qt.io/qt-5/qnetworkdiskcache.html#clear). I am not familiar with Qt and even C++ development, so don't expect deep insight from me.

**Comment by Abs62** [comment]
>> soooooo long way

"Preferences -> Scan popup -> Send translated word to main window". Or button in popup window.

>> It says, QNetworkDiskCache is limited to 50MB. 

Portable version shouldn't to retain traces on computer where it run. By definition.

**Comment by nikita-moor** [comment]
> "Preferences -> Scan popup -> Send translated word to main window". Or button in popup window.

Thank you, it works very nice. However, I would prefer to have two different windows, one compact (popup) and another complete with search pane, history, favorites, etc. So, why artificially restrict functionality if it already exists? Popup window can process double-click as well as the main window.

> Portable version shouldn't to retain traces on computer where it run. By definition.

If  `QNetworkDiskCache::clear()` is not enough, then I have no idea what to do. Add pragma to turn caching off for portable version? Adapt cache path to a local folder? Portable GD should save somewhere configuration files, could the cache be placed there?

I miss the goal of this discussion. I propose a functionality, it doesn't change anything existed before, but may be convenient for some users (me). If it's a principal question, then simply reject my pull request. If you are asking me to elaborate caching functionality then I am not competent in C++/Qt and all I can do is to propose draft code. I am developing dictionaries, not dictionary shells, and trying to fit into the application's features, but sometimes it's not enough or can be simplified from the shell's side.

**Comment by nikita-moor** [comment]
[Windows issue]

When a user double-clicks on the image, it will be saved into tmp file named as a combination of random chars and URL. Sometimes, this approach is not successful and the resulting filename doesn't end with correct extension (for images: JPG, PNG, TIF and so on).

For example, such URL as `https://babel.hathitrust.org/cgi/imgsrv/image?id=loc.ark:/13960/t2r50vd2k;res=0;seq=41` will result in tmp-file `ECpIJc-0305`. See file for testing: [test.zip](https://github.com/goldendict/goldendict/files/5463448/test.zip).

It's not a problem on Linux, but Window shows the dialog for choosing with which application this file to be open.

I wrote some draft code to detect MIME and add correct file extension. Hope you find it useful for GoldenDict.

**Comment by nikita-moor** [comment]
> "Preferences -> Scan popup -> Send translated word to main window". Or button in popup window.

After some experiments, I find it not good as I expected. When I send word to main window it doesn't switch to the desired group. Id est if the main window shows group of dictionaries "A" and popup shows "B", then on switching GD lookups for correct word but in the incorrect group.

Also, sometimes I like to work with two windows simultaneously. For example, to lookup Arabic words in Arab-French dictionary, and then check some French words in French-English vocabulary. So main window shows Arab-French group of dictionaries, and popup window holds open French-English group. That is why I would like to have fully-functional popup. Tabs may be a solution, but <kbd>Ctrl</kbd>+<kbd>C</kbd>+<kbd>C</kbd> is quicker.

**Comment by nikita-moor** [comment]
Another example of dubious remove image extention:
```
https://reader.digitale-sammlungen.de/object/bsb10585036_00015.svg
```
URL suggest it's SVG, but content-type `image/jpeg`.

**Comment by vedgy** [comment]
Restricting downloading images by double click to the main window doesn't make sense to me either. 

> Popup window was designed for fast lookup in small group of dictionaries. As popup hint instead of documentation chapter. Why do you don't want to use main window?

I cannot see how downloading an image on double click prevents using the popup window for fast lookup and as popup hint. I don't expect anyone to double click an image accidentally.

As it is, double clicking an image in the scan popup translates selected text. Definitely a bug. Fixing it to do nothing in this case would make the code slightly more complex. Letting the double click work the same in the main window and the scan popup, on the other hand, would simplify the code a bit.

Is there any benefit of doing nothing on image double click in the scan popup?
