### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by articlecat** [goldendict/goldendict#1285]
It would be nice to see GoldenDict be packaged as a [Flatpak](https://github.com/flatpak/flatpak). If GoldenDict were available on [Flathub](https://www.flathub.org/home), users of [CentOS](https://www.centos.org/), [elementary OS](https://elementary.io/), [Endless OS](https://endlessos.com/home/), [Fedora](https://getfedora.org/), [Linux Mint](https://linuxmint.com/), [Pop!_OS](https://pop.system76.com/), and [PureOS](https://www.pureos.net/) would be able to install GoldenDict through Flatpak with the included app store.

**Comment by proletarius101** [comment]
I submitted it to flathub: https://github.com/flathub/flathub/pull/2126

**Comment by articlecat** [comment]
Thank you, @proletarius101! This works perfectly.
