### ISSUE TITLE
Mac OS X: Scan popup and Global hotkey don't work

### ISSUE THREAD

**Issue by chulai** [goldendict/goldendict#129]
Scan popup and Global hotkey don't work.

These  functionalities are platform-specific and no effort has been done to add support for them in Mac OS X yet.

More info:
http://goldendict.org/forum/viewtopic.php?f=6&t=1584
http://goldendict.org/forum/viewtopic.php?f=4&t=1213#p5277
http://goldendict.org/forum/viewtopic.php?f=4&t=1611#p7274

**Comment by barracuda156** [comment]
@chulai Are these suppose to build in 10.5–10.6?
