### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Hot-Doc** [goldendict/goldendict#1295]
Hello! Why I see this 
![image](https://user-images.githubusercontent.com/68231550/96928014-86b76200-14ea-11eb-81b2-7dd723d43969.png)

but not like this 
![image](https://user-images.githubusercontent.com/68231550/96928191-cc742a80-14ea-11eb-8484-facf46fc65b6.png)
I did all from this "https://github.com/goldendict/goldendict/wiki/GoldenDict-Dark-Theme" instruction

**Comment by nonwill** [comment]
Just add one block to the end of your qt-style.css and you can change it to any other color which you like:
>QWidget
{
	background: #201F1F;
	color: #D4D2CF;
}

And if you dig it deep, you will always get yourself satisfied.

**Comment by Hot-Doc** [comment]
> Just add one block to the end of your qt-style.css and you can change it to any other color which you like:
> 
> > QWidget
> > {
> > background: #201F1F;
> > color: #D4D2CF;
> > }
> 
> And if you dig it deep, you will always get yourself satisfied.

Thank you so much.

**Comment by 42531ljm** [comment]
thx
