### ISSUE TITLE
Custom icon not work

### ISSUE THREAD

**Issue by slideray** [goldendict/goldendict#1304]
How do I change the tray icon to a custom one?
I place the icon here:
`~/. icons/sys-theme/scalable/apps/goldendict.SVG`
but it does not apply.
It was applied correctly on previous versions.
Where should it be located and what should it be called?

- ОС: Ubuntu 18.04.5 LTS x86_64
- GoldenDict 1.5.0-RC2+git
- На базе Qt 5.9.5 (GCC 7.2.0, 64 бит)

**Comment by vedgy** [comment]
If you want to replace the notification area (aka system tray) icons, the icons' base names should be *goldendict-tray* and *goldendict-scan-tray*. See [the pull request that introduced the icon substitution feature](https://github.com/goldendict/goldendict/pull/996/files). As for the location, see the [relevant specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout).

**Comment by slideray** [comment]
Yes, I also tried to do this by placing an icon file with the name
«**goldendict-tray**» and «**goldendict-scan-tray**»
in the directory
`~/.icons/sys-theme/scalable/apps/goldendict-tray.svg`

But it doesn't work for my ((
Tell me please, does this method work for you?

**Comment by vedgy** [comment]
I placed a custom icon in `~/.icons/hicolor/scalable/apps/goldendict.svg` and it was picked up by GoldenDict. Though it was used regardless of the scan popup state. `~/.icons/hicolor/scalable/apps/goldendict-tray.svg` was picked up as well and used only when the scan popup was disabled. The `sys-theme` part must be your mistake.

**Comment by slideray** [comment]
Tried, still nothing comes out.

Tried:
~/.icons/hicolor/scalable/apps/goldendict.svg
~/.icons/hicolor/scalable/apps/goldendict-tray.svg
~/.icons/hicolor/scalable/apps/goldendict.png
~/.icons/hicolor/scalable/apps/goldendict-tray.png

Tried to change the icon size 16/22/48
Doesn't pick up the custom icon.

It used to work, the version was older, but when it was updated to 1.5, it stopped working. Even if you build it from the source code, it still doesn't work.

When building, of course, you can throw your own icon, but this is not the best option.

**Comment by vedgy** [comment]
The GoldenDict window/About window icon is hardcoded to [`:/icons/programicon.png`](https://github.com/goldendict/goldendict/blob/master/icons/programicon.png). And it was always hardcoded in the _official_ GoldenDict version, since at least 2009, according to git history (though the default icon was replaced in 2013 - #183). I assume you are trying to replace the system-tray/notification-area icon. This is possible since #996 was merged on Apr 17, 2018. The GoldenDict version in Ubuntu 18.04 repositories is more than 3 years old, so it cannot possibly support custom theme icons. Compile the latest *master* version of GoldenDict from sources. Place both *goldendict-tray.svg* and *goldendict-scan-tray.svg* into *~/.icons/hicolor/scalable/apps/*

**Comment by slideray** [comment]
Yes, i'm compile git-version, this been correct installed, but icon goldendict-tray.svg and goldendict-scan-tray.svg into ~/.icons/hicolor/scalable/apps/ do not work.

For install i'm doing thats:
```
sudo apt install make gcc git pkg-config build-essential qt4-qmake libvorbis-dev zlib1g-dev libhunspell-dev x11proto-record-dev libqt4-dev libqtwebkit-dev libxtst-dev liblzo2-dev libbz2-dev libao-dev libavutil-dev libavformat-dev libtiff5-dev libeb16-dev

git clone git://github.com/goldendict/goldendict.git
cd goldendict && qmake-qt4 && make
make install
```

and after the installation window «about» look like this:
```version: 1.5.0-RC2-452-g63aeb0e-dirty```

**Comment by vedgy** [comment]
Why are you using the obsolete Qt4, which is unmaintained for many years now? Could you try compiling GoldenDict with Qt5 instead? The dependencies are different (see GoldenDict's README) and the penultimate command should be `cd goldendict && qmake-qt5 && make` or, if `qmake-qt5` does not exist, simply `qmake` - but check that `which qmake` belongs to a Qt5 package, not Qt4.

**Comment by slideray** [comment]
Thank you very much! On Qt5, it really worked as it should. 
It even picks up an icon named «goldendict.svg» in the system theme directory
