### ISSUE TITLE
[feature request] a quick way to select dictionaries

### ISSUE THREAD

**Issue by Aliaksandr3by** [goldendict/goldendict#1308]
a quick way to select dictionaries
![image](https://user-images.githubusercontent.com/11432724/98668366-d4dcba00-2360-11eb-900b-d13f7aeb9046.png)

**Comment by nonwill** [comment]
Then you will lose the way to use Ctrl or Shift to accelerate selections...

**Comment by Aliaksandr3by** [comment]
thx

**Comment by Aliaksandr3by** [comment]
> 
> 
> Then you will lose the way that Ctrl or Shift accelerates selections...

if do I use ctrl+left mouse click on the desired dictionary in group dictionary? 
How can I return the selection of all dictionaries?
![image](https://user-images.githubusercontent.com/11432724/99461058-19a8b800-2942-11eb-9d2c-bed3d7c2cf12.png)

**Comment by Aliaksandr3by** [comment]
> 
> 
> Then you will lose the way that Ctrl or Shift accelerates selections...

I figured out that a "ctrl+double left click" selects all dictionaries .
