### ISSUE TITLE
How exactly should I set GD to portable mode in linux?

### ISSUE THREAD

**Issue by arsCom** [goldendict/goldendict#1321]
sorry as much as it sounds stupid, I couldn't figure it out on my own. according to GD reference manual in the program

> To turn on portable mode it needs only create "portable" folder beside the main program file. If such folder exists GoldenDict will launched in portable mode. 

I really didn't understand what it means by "beside the main program" in the quote. should I add a "portable" directory inside the .goldendict ? where exactly  I'm supposed to create a "portable" directory in linux?
I use arch and installed goldendict-1.5.0RC2-9 package in the arch repository.

**Comment by vedgy** [comment]
Create a directory named *portable* beside the *goldendict* executable. GoldenDict checks if the directory [`QCoreApplication::applicationDirPath()`](https://doc.qt.io/qt-5/qcoreapplication.html#applicationDirPath) `+ "/portable"` exists. In the case of the package installed from the repository, the path is probably */usr/bin/portable*. You can check with the `which goldendict` command.

**Comment by asgharam** [comment]
@vedgy Thanks brother.

**Comment by arsCom** [comment]
@vedgy Thanks brother.
