### ISSUE TITLE
Looking for abbreviation

### ISSUE THREAD

**Issue by nikita-moor** [goldendict/goldendict#1350]
When I look for "etc.", GoldenDict automatically removes dot "." from the request. Usually, it is useful, but not in the case of abbreviation. Could you add, please, some smart check, so if a word ends with dot to check it twice (1) with dot, (2) without dot.

For testing, you could use [this dictionary](https://github.com/latin-dict/Reyher1712/releases/tag/v0.4) and the following keywords:

- dn.
- d. n.
- D. E. R. I. C.
- D. AVG.

**Comment by Arnie97** [comment]
Will this be handled by morphology dictionaries if we just keep all the dots as-is?

**Comment by nikita-moor** [comment]
It seems to work, Hunspell cleans garbage:

~~~sh
hunspell -m -d en_US
-="loves.,?
loves  st:love fl:S
~~~

But we should take into account that morphology is optional and not every language has Hunspell dictionary.

**Comment by Aliaksandr3by** [comment]
maybe will be best if it do not trim last point if word has many dots?
![image](https://user-images.githubusercontent.com/11432724/111464766-47580f00-8732-11eb-995e-885d7b720d90.png)

**Comment by nikita-moor** [comment]
> maybe will be best if it do not trim last point if word has many dots?

Abbreviations with only one dot are common as well: "etc.", "st.", "uzw.".

**Comment by Aliaksandr3by** [comment]
Assoc. ; Bros. ; C.-in-C. ; Co. ; Col. ; Con. ; Corp. ; Dec. ; Dem. ; Esq. ; Fr. ; Fri. ; Hon. ; Inc. ; Lab. ; Lib. ; Lieut. ; Mon. ; Op. ; Pres. ; Prof. ; Rep. ; Rev. ; Rt. Hon. ; S.O.B. ; Sat. ; Sen. ; St. ; Sun. ; Thur. ; Thurs. ; Tue. ; Tues. ; Verb Endings for p.o.q. ; Wed. ; a.m. ; and co. ; anon. ; approx. ; arr. ; b. ; c. ; cert. ; cf. ; chap. ; col. ; cont. ; d. ; dep. ; e.g. ; enc. ; encl. ; esp. ; est. ; et al. ; etc. ; excl. ; fem. ; fig. ; i.e. ; ibid. ; incl. ; lat. ; masc. ; min. ; misc. ; msec. ; no. ; nos. ; o.n.o. ; oh yeah. ; op. cit. ; p. ; p. and p. ; p.a. ; p.c.m. ; p.m. ; p.o.q. ; p.p. ; p.w. ; pg. ; pl. ; pop. ; pp. ; sec. ; sq. ; tbsp. ; tel. ; tel. no. ; tsp. ; usu. ; v. ; viz. ; vol. ; 

maybe don't trim right point?

**Comment by Arnie97** [comment]
> TRY option in the .aff files (e.g. en_US.aff) controls which characters are allowed, so the resting ones will be removed

Oh, that makes sense. Did it simply depend on the usage of a specific morphology dictionary? I just realized I could not reproduce this issue on a Mac, which might be attributed to a different set of default morphology dictionaries.

<img width="765" alt="result of d. avg." src="https://user-images.githubusercontent.com/10341686/111601843-ba828380-880d-11eb-9b94-9befd2a31654.png">
<img width="765" alt="result of e.g." src="https://user-images.githubusercontent.com/10341686/111598149-ddab3400-8809-11eb-9078-738bcf3e8cd3.png">
<img width="765" alt="result of eg, with the same dictionaries" src="https://user-images.githubusercontent.com/10341686/111598136-d97f1680-8809-11eb-819a-1868e1930ad3.png">

**Comment by nikita-moor** [comment]
@Arnie97, thank you for the test. Now, I should specify, that the issue comes forth only if I paste <kbd>Ctrl</kbd><kbd>C</kbd> a text into the open GoldenDict window  or use hotkey <kbd>Ctrl</kbd><kbd>C</kbd><kbd>C</kbd>. Typing it into the search field in the GoldenDict's window doesn't trigger the problem.

> Did it simply depend on the usage of a specific morphology dictionary?

No, it doesn't depend on morphology dictionaries. It's an internal function `trimWhitespaceOrPunct` called in several places, such as [ArticleView::pasteTriggered](https://github.com/goldendict/goldendict/blob/b2e673961d28ca5eb920a909091252d3321f09d6/articleview.cc#L2086) > [ArticleView::sanitizeInputPhrase](https://github.com/goldendict/goldendict/blob/b2e673961d28ca5eb920a909091252d3321f09d6/articleview.cc#L2086).

https://github.com/goldendict/goldendict/blob/b2e673961d28ca5eb920a909091252d3321f09d6/folding.cc#L607-L625

**Comment by vedgy** [comment]
The dictionaries I use contain articles both for `etc` and `etc.`, but the article sets are different. So checking with punctuation marks at the end after a request without them produced no result is not a bulletproof fix. Ideally GoldenDict should display both sets of articles. However, this probably won't be easy to implement: my quick look at the relevant code indicates that GoldenDict always shows a definition of a single word and never combines results for multiple words in one page.

**Comment by nikita-moor** [comment]
@vedgy

> However, this probably won't be easy to implement: my quick look at the relevant code indicates that GoldenDict always shows a definition of a single word and never combines results for multiple words in one page.

It works with synonyms in StarDict.

![screenshot](http://i.szoter.com/8794521a9a3cef0d.jpg)

GoldenDict (1) finds a key, (2) realizes that it's an alias of another keyword, (3) finds all articles with this keyword. Probably, this code:

https://github.com/goldendict/goldendict/blob/b2e673961d28ca5eb920a909091252d3321f09d6/stardict.cc#L1388-L1394

Could it be adapted for this issue?

**Comment by vedgy** [comment]
@nikita-moor, you are right. How could I forget about morphology, enabling which shows multiple articles from a single dictionary... This code indeed looks promising. Perhaps matches for both variants of the input phrase can be placed into [`WordSearchRequest::matches`](https://github.com/goldendict/goldendict/blob/b2e673961d28ca5eb920a909091252d3321f09d6/dictionary.hh#L168). Still, some code infrastructure will have to be introduced to allow passing multiple words where only one is currently accepted.

**Comment by vedgy** [comment]
Hacked together a prototype implementation in [this branch](https://github.com/vedgy/goldendict/tree/sanitize-preserve-punctuation). If someone volunteers review/testing/feedback, I could implement this properly and create a pull request. I have only briefly tested several English DSL dictionaries, English Wikipedia and English Wiktionary. Several more dictionary formats with morphology on and off should be tested to make sure that this idea works more or less universally. And perhaps other sources (Websites, DICT servers, Programs, Forvo, Transliteration) have to be tested too. `PRIMARY_WORD_NO_PUNCT` can be defined as `0` in *article_maker.cc* to test a different primary word choice. See the commit message for more details.

**Comment by nikita-moor** [comment]
@vedgy, thank you! I have tested your patch, and it seems working very well with Slob, Websites and Programs. I will continue using it for some time, and will tell you if encounter with some bugs.

**Comment by vedgy** [comment]
@nikita-moor, thanks for testing! Have you tried defining `PRIMARY_WORD_NO_PUNCT` to `0`? Do you think that all 4 versions of the input phrase are useful - complete, w/o punctuation prefix, w/o punctuation suffix, w/o punctuation prefix and suffix?

**Comment by nikita-moor** [comment]
Websites receive only the first variant in `%GDWORD%`, so it should be the cleaned one. There is some inconsistency when switching between groups. Could you wait a little more, please, I need some time to properly test the new feature.

**Comment by vedgy** [comment]
I can wait, no problem :)

**Comment by vedgy** [comment]
I also can't think of an example where the "w/o punctuation suffix" variant is useful, so this one clearly can be dropped. #1375 does not really ask for the complete variant as I doubt many dictionaries contain phrases like "(very) much". So I suppose the complete variant can be dropped too - why waste the CPU time and risk bugs for a feature without a use case? When a valid and common enough use case is discovered, it should be easy enough to adjust the implementation accordingly.

I'll work on a proper implementation when I am less busy (perhaps in a week or two). I'll try to somehow filter out a duplicate MediaWiki (e.g. English Wiktionary) article described in the prototype commit message.

@Abs62, what do you think about the discussed feature and its proposed implementation? Any design or implementation feedback is welcome.

**Comment by vedgy** [comment]
The scan popup may send the current word/phrase to the main window if a) _Preferences=>Scan Popup=>Send translated word to main window_ option is on; b) the user clicks the _Send word to main window (Alt+W)_ button. I suppose the whitespace/punctuation suffix should be sent along in both cases so that the articles displayed in the main window are the same as the articles that would be/are displayed in the scan popup. Is that right?

**Comment by nikita-moor** [comment]
@vedgy 
I think it should be the original input (non-cleaned) to be sent to the main windows, so it will treat it (clean) by itself. Also, check, please, how it works while switching between groups.

**Comment by vedgy** [comment]
The structure I am currently using in place of a simple `QString` is:
```cpp
struct InputPhraze
{ 
  QString phraze;
  QString punctuationSuffix;
};
```

I plan to pass this struct to the main window in the two described cases and let it display articles for both `phraze` and `phraze + punctuationSuffix`, the same as in the scan popup.

>  Also, check, please, how it works while switching between groups.

Yes, not losing the suffix in this situation requires additional storage in `ScanPopup`. Thanks for the reminder.

**Comment by vedgy** [comment]
Finally completed the implementation, developer testing and created the promised pull request: #1389. Please review/test it.
