### ISSUE TITLE
How to PERMENENTLY hide result navigation pane and history pane?

### ISSUE THREAD

**Issue by lefthairynut** [goldendict/goldendict#1351]
I have to uncheck result navigation pane and history pane every time I open goldendict. In the preference there is no option for this and I also didn't find any text related in the `config` file in `~/.goldendict/` for that matter which was strange.  Is there any option to do this? or should I recompile the goldendict with some option?

**Comment by vedgy** [comment]
What's your GoldenDict version? GoldenDict remembers hiding these docks on my GNU/Linux system after restarting. Could it be that you don't exit GoldenDict cleanly and so configuration isn't saved? Try hiding the panes, quitting GoldenDict, then starting it again. In the `config` file, the [`mainWindowState`](https://doc.qt.io/qt-5/qmainwindow.html#saveState) entry should be responsible for the [dockwidgets](https://github.com/goldendict/goldendict/blob/7db077bd0310ceb42e836f8721a3fddf9144e1b3/mainwindow.ui#L287)' state.

**Comment by lefthairynut** [comment]
The problem solved once I quit the program cleanly. thank!
out of curiosity why mainWindowState content seems like an encrypted text? at first glance it seems like a gibberish. why its not like other entries clean and understandable?

**Comment by vedgy** [comment]
> out of curiosity why mainWindowState content seems like an encrypted text? at first glance it seems like a gibberish. why its not like other entries clean and understandable?

That's how Qt framework represents the UI state - in a binary format. On exit GoldenDict simply writes the byte array retrieved from Qt API to disk. On startup - passes the byte array back to Qt.

GoldenDict should save its settings when you log out if your desktop environment supports session management (most mainstream ones do) and if your GoldenDict version is fresh enough (March 28, 2018 or later code version - when #979 was fixed).

Please close the issue if it is resolved for you.

**Comment by lefthairynut** [comment]
Thanks for clarifying. kudos!
