### ISSUE TITLE
[function] to adds the "maximize" button on  the Dictionary(F3) window

### ISSUE THREAD

**Issue by Aliaksandr3by** [goldendict/goldendict#1359]
Add the Maximization button on the dictionary window (F3) 

![image](https://user-images.githubusercontent.com/11432724/110088230-a5d1d480-7da5-11eb-8938-67a0b1a27658.png)

**Comment by nonwill** [comment]
Add the following lines in EditDictionaries's constructor to fix the feather：
>#if QT_VERSION >= QT_VERSION_CHECK(5, 9, 0)
>  setWindowFlag(Qt::WindowMinMaxButtonsHint, true);
>#else
>  setWindowFlags(windowFlags() | Qt::WindowMinMaxButtonsHint);
>#endif

**Comment by Aliaksandr3by** [comment]
for now I use a double click the left button of mouse on edge of window (as shows on picture below) - but it is not comfortable;
I would like have the "maximize" button.
on win10_64 work.
![image](https://user-images.githubusercontent.com/11432724/110241135-4ec42f00-7f60-11eb-9516-6eb25b0f08e6.png)
