### ISSUE TITLE
[Feature request] CSV dictionary support (...for Taiwan MOE dictionaries with No Derivatives licences)

### ISSUE THREAD

**Issue by lxs602** [goldendict/goldendict#1363]
Hi,

Could Goldendict support dictionaries as CSV files? 

The Taiwanese Ministry of Education has released several Mandarin dictionaries under a CC 3.0 No Derivatives, as below. They have also made Hakka and Minnan (Hokkien) dictionaries elsewhere.
https://language.moe.gov.tw/001/Upload/Files/site_content/M0001/respub/index.html

The No Derivatives licence is frustrating, as each headword has many fields, which would need headings on the definition for each term. To produce e.g. a Stardict dictionary, headings would need to be taken from the top row and added to each term, so under the licence I presume it would then not be redistributable.

I note that Pleco has agreed a dictionary with the Taiwanese MOE, which does seem to be a competitive advantage:
https://www.plecoforums.com/threads/the-moe-dictionary-is-now-open-source.3606/
http://www.plecoforums.com/threads/official-moedict-pleco-release.4915/

A CSV file would be the simplest of all formats, headings on the top row, with terms underneath.

EDIT: It seems to me the above would break the licence. It would not change any of the actual meaning/content of the dictionary would change (which I assume is what the Taiwanese MOE are protecting), just moving headings to each row instead of on the top line! 

Please say if you have an opinion.

**Comment by shawkynasr** [comment]
From 2013, There are many mdx version. There are many people contacted with ministry.

here the first person Mr Wang make it as mdx[blog](http://fgwang.blogspot.com/2018/02/blog-post_14.html)

mdx is better than csv, mdx built on html, these dictionaries with csv, i don't think will be ok without issues. There many 生僻字.

if you want it as csv, you can convert it. Here is best solution:

You can use [pyglossary beta verison 4.0.11](https://github.com/ilius/pyglossary) to convert to csv.

**Comment by shawkynasr** [comment]
[For idioms 教育部《成語典》離線辭典](http://fgwang.blogspot.com/2015/12/blog-post.html)

**Comment by shawkynasr** [comment]
Steps:
1. Download [pyglossary 4.0.11](https://github.com/ilius/pyglossary/releases/tag/4.0.11)
2. You need put this gist file on plugin folder [mdict](https://gist.github.com/ilius/88d11fa37a4a40cd0d7f6535120b0693)

3. Open main.py and import mdx file.
4. Output choose csv

**Comment by lxs602** [comment]
Thank you.

I was worried that it would break the licence to convert the official csv files. 

I will just use the mdx fictionary from the link.

L
