### ISSUE TITLE
[Question] How to embed audio files in Stardict format?

### ISSUE THREAD

**Issue by fenuks** [goldendict/goldendict#1364]
I'm sorry if this is easy question, but I couldn't find any answer that would work.

I have script to convert proprietary dictionary format into StarDict. Html is being used inside `.dict` file. Dictionary comes with audio recording for each word (in fact, when one word can be pronounced in different ways, more than one file is present).

How can I add audio to definitions? I've found old issue about HTML `<audio>` support. I have few problems with that. First, it seems that folder I've added in sound files sources settings is not used at all. I was only able to make GoldenDict to play audio if I used absolute path to file like so: `<audio src="file:///path/to/my/file.wav"></audio>`. Another problem is that sound is not played automatically unless `autoplay` attribute is added, which is far from ideal, because you cannot turn it off easily. Additionally, all audio files are played at the same time. And third problem is that you cannot repeat sound (well, it can be done by adding `controls` attribute to the `audio` tag, but it's ugly, and not as comfortable as with shortcut GoldenDict provides to replay sound.

I would be very grateful for any suggestions how audio files are supposed to word definitions in standard manner.

**Comment by nikita-moor** [comment]
GoldenDict has a limited support of external resources in StarDict format. Simply saying, you could put all audio files into the `res` directory (the name is predefined) next to your `.ifo` file and use relative links, such as "res/file.wav". File `stardict-test-img.zip` from [this thread](https://github.com/nikita-moor/latin-dictionary/issues/2#issuecomment-496029572) demonstrates how images can be embedded, audio files should be references similarly.

**Comment by fenuks** [comment]
Thank you, this is satisfying solution for me.
