### ISSUE TITLE
Webpage dictionaly go to unlimited length: restrict the length of webpage dictionaries.

### ISSUE THREAD

**Issue by pankaj4u4m** [goldendict/goldendict#1374]
e.g. websites
https://www.linguee.com/english-german/search?source=auto&query=%GDWORD%
https://dict.leo.org/englisch-deutsch/%GDWORD%

they go like unlimited length

**Comment by nikita-moor** [comment]
I don't see a problem with both web-sites, they are lengthy but limited. May it happen with some specific keyword?

**Comment by darnn** [comment]
This happens for me as well on a different website, which only suggests further that this is how GoldenDict renders them. The length is not infinite, but it is much greater than it would be in a regular browser. This is in the most recent early access build, from 2019 (GoldenDict-1.5.0-RC2-372-gc3ff15f_(QT_486)):
![goldendict-morfix](https://user-images.githubusercontent.com/19672444/119703709-7d66ed00-be5f-11eb-8da2-8afb94f52b4f.gif)

Compare with the actual website:
https://www.morfix.co.il/pair

**Comment by nikita-moor** [comment]
Turning parameter "As link" off solves the problem. When the web-site is rendered inside the frame ("As link" is on), GoldenDict wrongly estimates its height.

I don't know where is the problem. HTML engine used in GoldenDict is somewhat outdated and migration to Qt WebEngine (some day) will affect this problem, so I doubt anyone will discover it now.

**Comment by darnn** [comment]
It solves that problem, but introduces several others. This is with "as link" on:
![gd-aslinkon](https://user-images.githubusercontent.com/19672444/119707718-244d8800-be64-11eb-8601-1a5f90c0208e.png)

And this is with "as link" off:
![gd-aslinkoff](https://user-images.githubusercontent.com/19672444/119707745-2adbff80-be64-11eb-8003-f2e98e639dd6.png)

As you can see, other than the several things that are rendered strangely, a horizontal scrollbar is created (regardless of the window's width) for no reason. What's worse, whatever is doing it causes the contents of other dictionaries to become obscured:
![gd-aslinkoff2](https://user-images.githubusercontent.com/19672444/119708667-0d5b6580-be65-11eb-849f-a20ee2f82f61.png)

**Comment by nikita-moor** [comment]
> What's worse, whatever is doing it causes the contents of other dictionaries to become obscured

I agree, wrapping an external website content into a frame is a good solution.

The problem is probably here:

https://github.com/goldendict/goldendict/blob/b2e673961d28ca5eb920a909091252d3321f09d6/articleview.cc#L489-L491

**Comment by darnn** [comment]
If it is, I hope the appropriate changes can be made to it. I don't know the first thing about code myself, sadly.

**Comment by darnn** [comment]
Also, since this is at least somewhat relevant, I still wish it was possible to implement something like uBlock Origin's element picker, i.e. a tool where you could select an element to be added to a custom style file for that dictionary, so that it's hidden. Dictionary sites have ads, but there are usually also various UI elements that are unnecessary and distracting if you're only viewing them through GD to look up a definition. See here:
https://github.com/goldendict/goldendict/issues/105#issuecomment-274261672

**Comment by pankaj4u4m** [comment]
So finally I worked on it myself and override following  elements for linguee to work.
here is the full path file https://github.com/pankaj4u4m/goldendict/tree/main/.goldendict/styles/ark-dark

@darnn you should be able to take everything from uBlock and all items display:none to remove all ads.

```
a:link {
	color: #0dc5fb !important;
}

#outer_div {
	max-width: 570px !important;
	min-width: 270px !important;
	margin-left: 0px !important;
	margin-right: 0px !important;
	max-height: 1000px !important;
}

.ad_leftAndRight #mainlayout {
	padding-right: 0px !important;
	padding-left: 0px !important;
}

.mwiki * {
	background: #2f333f !important;
	color: white !important;
}

.website * {
	background: #2f333f !important;
	color: white !important;
	border-color: #4b5162 !important;
	/* filter: invert(100%); */
	box-shadow: none !important;
	min-height: 0 !important;
	max-height: 1000px !important;
}

.design2019 .lQueryHeader .lQueryHeader__langSelector #langPair-button {
	display: none !important;
}
#result_container.webservice {
	display: none !important;
}
.l_deepl_ad_container {
	display: none !important;
}
.design2019 #footer {
	display: none !important;
}
.design2019 #lingueecontent {
	margin-bottom: 0 !important;
	margin: 0 0 0 0 !important;
}
.design2019 #header {
	display: none !important;
}
nav.lMainNavbar.wide_in_main {
	display: none !important;
}
#wikipedia-header {
	display: none !important;
}
div#banners_top {
	display: none !important;
}
div#banners_left {
	display: none !important;
}
div#banners_right {
	display: none !important;
}
```
