### ISSUE TITLE
"start to system tray" doesn't work

### ISSUE THREAD

**Issue by dfliaoyue** [goldendict/goldendict#1380]

**Comment by vedgy** [comment]
Works for me (Manjaro GNU/Linux, Xfce, GoldenDict version close to current *master*). Haven't had any issues with this option for many years.

**Comment by dfliaoyue** [comment]
Done

**Comment by vedgy** [comment]
Why did you create the issue in the first place? Is the option broken on your system? Which system is it?

**Comment by dfliaoyue** [comment]
> Why did you create the issue in the first place? Is the option broken on your system? Which system is it?

Seems just because some files were wrongly blocked by security software. Solved.
