### ISSUE TITLE
Add the custom website "https://www.quword.com/etym/" to goldendict.

### ISSUE THREAD

**Issue by hongyi-zhao** [goldendict/goldendict#1382]
On Ubuntu 20.04, I compiled the git master version of `goldendict` and I want to add [the custom website](https://www.quword.com/etym/) to `goldendict`. What is the exact address pattern string that should be used in this case?

Regards,
HY

**Comment by nikita-moor** [comment]
Address: `https://www.quword.com/etym/s/%GDWORD%`

**Comment by hongyi-zhao** [comment]
Thank you.
