### ISSUE TITLE
SVG animations no longer visible

### ISSUE THREAD

**Issue by lxs602** [goldendict/goldendict#1385]
Hi,

I made a HTML dictionary of SVG animations of Chinese characters, and how they are drawn.

One example:
https://github.com/skishore/makemeahanzi/blob/master/svgs/20024.svg

Source dictionary:
https://github.com/lxs602/Chinese-Mandarin-Dictionaries/tree/main/MakeMeaHanzi%20(Stroke%20animations)

The animations were present in 1.5.0-RC2+git, but no longer works with the latest continous release (continuous-2-gb2e6739). 

Is there any possible fix?

Thank you

**Comment by nonwill** [comment]
Are you use a version based on Qt4? The Qt5 version is OK with svg animations:
![92g6p-q1cji](https://user-images.githubusercontent.com/46510529/120944542-a6dd1e00-c767-11eb-92c9-04a6e615b655.gif)

**Comment by lxs602** [comment]
@nonwill
It did turn out to be qt4, thanks.

I was using the continous release by Abs62 here, based on qt4:
https://github.com/Abs62/goldendict/releases/tag/continuous

I compiled goldendict with qt5 and the problem was fixed.
