### ISSUE TITLE
any plan to upgrade the   qt version?

### ISSUE THREAD

**Issue by xiaoyifang** [goldendict/goldendict#1393]

**Comment by nikita-moor** [comment]
Duplicate #1081

**Comment by nonwill** [comment]
Just tested Qt-5.12.12, the core module still has memory leaks which was fixed in Qt-6.2.2 and the latest commercial version of Qt-5.15.
![Video_20211208140040](https://user-images.githubusercontent.com/46510529/145158696-9692c3df-d0c4-4ff3-8953-7f99a3cb9507.gif)

**Comment by nikita-moor** [comment]
## QT 5.15 Pre-release (2020-12-14)

I have tested the recent release in Arch Linux using my collection of dictionaries and have found several issues:

1. GD doesn't load external CSS in Slob and MDict formats. For example, [Popma1865](https://github.com/latin-dict/Popma1865/releases/tag/v1.0), look up for "amo". (I think it does load CSS, but does not apply styles to the content.)
1. Websites made as frame (as link: true) now contain `display:none;` in the frame's styles, so their content is not rendered. For example, [Whitaker](https://latin-dict.github.io/dictionaries/Whitaker.html), look up for "amo". If it was made intentionally, I can fix it from my side (`window.frameElement.style.display = "initial"`), but it could break others dictionaries.
1. Websites made as frame: open links in external application. For example, [Hederich1825](https://github.com/latin-dict/Hederich1825/releases/tag/v1.3), look up for "amo". Before, I could click on an image to open it in the external image viewer.

**Comment by xiaoyifang** [comment]
> ## QT 5.15 Pre-release (2020-12-14)
> I have tested the [recent release](https://github.com/xiaoyifang/goldendict/releases/tag/qt5.15-windows) in Arch Linux using my collection of dictionaries and have found several issues:
> 
> 1. GD doesn't load external CSS in Slob and MDict formats. For example, [Popma1865](https://github.com/latin-dict/Popma1865/releases/tag/v1.0), look up for "amo". (I think it does load CSS, but does not apply styles to the content.)
> 2. Websites made as frame (as link: true) now contain `display:none;` in the frame's styles, so their content is not rendered. For example, [Whitaker](https://latin-dict.github.io/dictionaries/Whitaker.html), look up for "amo". If it was made intentionally, I can fix it from my side (`window.frameElement.style.display = "initial"`), but it could break others dictionaries.
> 3. Websites made as frame: open links in external application. For example, [Hederich1825](https://github.com/latin-dict/Hederich1825/releases/tag/v1.3), look up for "amo". Before, I could click on an image to open it in the external image viewer.
> 4. If the input field in the main window is not active, and a user starts typing a word to look up, GD should set focus on this field automatically.
> 
> P.S. Thank you for the work on upgrading GD, I already can do several nice things impossible in old WebKit.

1,2,4 fixed.
3 need further investigation.

**Comment by nikita-moor** [comment]
Confirm, **problems 1-2** were fixed.

**Problem 4** is somewhat tricky:

* pop-up window — it works, but the first letter is doubled. For example, I type "love" and get "llove"
* main window — I can type only 1 letter (here, I type "love"):
![gd-qt5](https://user-images.githubusercontent.com/13879891/146221121-4b2a3cc1-008d-47a7-9685-36687731cd12.gif)

The **3rd problem** was sort of undocumented feature. If it's impossible to recreate, then old double-click on the image (to open it in an external viewer) would be acceptable too.

**Problem 5**: select word by single click doesn't work — it's not a critical feature and can be put off to a later release.
![Screenshot_2021-12-15_21-15-15](https://user-images.githubusercontent.com/13879891/146224583-2d50c300-6fbf-4024-9ead-d23f2b99dd5c.png)

**Comment by xiaoyifang** [comment]
> **Problem 5**: select 

I think I have fixed it before,does it still not work.

**Comment by nikita-moor** [comment]
> **Problem 4**: If the input field in the main window is not active…

This issue was fixed for alphabetic scripts (Latin, Cyrilic), but there is still a problem with complex scripts, such as Chinese. Using IBus with Intelligent Pinyin, the first typed letter is not processed by the input method. 

![Screenshot_2021-12-26_18-49-27](https://user-images.githubusercontent.com/13879891/147410217-8acf3ac4-0cb2-42bd-92e3-4c6a7da4e54a.png)

> **Problem 5**: select

It doesn't work fine, but I need more time to investigate the problem.

**Comment by nikita-moor** [comment]
**Probem 1** (again). When I switch between groups of dictionaries, CSS styles are not applied. After some time, GoldenDict stops applying CSS styles completely.

**Problem 6**: on closing the main window and opening it again, GD does not remember the word in the search bar.

**Comment by xiaoyifang** [comment]
> **Problem 6**: on closing the main window and opening it again, GD does not remember the word in the search bar.

has not reproduced.
![test](https://user-images.githubusercontent.com/105986/147470284-cadf0e13-c436-47d5-b604-540f2f3f9a9f.gif)

Problem 4 "double character" fixed,use the latest code.

**Comment by nikita-moor** [comment]
> Problem 4 "double character" fixed,use the latest code.

Yes, confirm. Thank you.

**Comment by nikita-moor** [comment]
> > **Problem 6**: on closing the main window and opening it again, GD does not remember the word in the search bar.

> has not reproduced.

Reproduction steps:

1. Open the main windows with <kbd>Ctrl</kbd> <kbd>F11</kbd> <kbd>F11</kbd>
1. Type in a word into the search bar (e.g. "love") and press <kbd>Enter</kbd>
1. Close the main window with <kbd>Esc</kbd>
1. Press <kbd>Ctrl</kbd> <kbd>F11</kbd> <kbd>F11</kbd> — search bar is empty.

**Comment by xiaoyifang** [comment]
> 3\. Before, I could click on an image to open it in the external image viewer.

this function only work with external images ,such as images in the wiki .

**Comment by xiaoyifang** [comment]
> **Problem 6**: on closing the main window and opening it again

try again .

**Comment by nikita-moor** [comment]
> > **Problem 6**: on closing the main window and opening it again
> 
> try again .

Fixed, confirm.

**Comment by xiaoyifang** [comment]
> > **Problem 5**: select
> 
> I think I have fixed it before,does it still not work. is the word inside the iframe ?

Fixed now ,can work inside iframe.

**Comment by nikita-moor** [comment]
> > > **Problem 5**: select
> > 
> > 
> > I think I have fixed it before,does it still not work. is the word inside the iframe ?
> 
> Fixed now ,can work inside iframe.

Using offline dictionaries, whenever I click a word, GD selects the first word on the screen.

https://user-images.githubusercontent.com/13879891/148119615-14b14927-3fee-4646-80b2-a1b0e552eafa.mp4

**Comment by nikita-moor** [comment]
@xiaoyifang 
Your current approach emulating double-click to select a complete word is very simple yet effective, but it does not let selecting several words, and it is a big problem. I used to select multiple words, so old javascript code would be a better way to do it.

The problem is important for me, but not indispensable. I would recommend postponing this issue and concentrate on general migration to Qt5.

**Comment by xiaoyifang** [comment]
close ,comments move on to #1400
