### ISSUE TITLE
Use the following hotkey to translate a word from clipboard, some letters are missing

### ISSUE THREAD

**Issue by HarryRen** [goldendict/goldendict#1396]
When I copy some words (e.g. "\*dem-") from text and then Use the hotkey to translate it from clipboard, I can olny get "dem" in the search bar of goldendict. The letter "\*" and "-" are missing, so I have to type "\*dem-"  in the search bar to get what really I want. Can anyone fix it? It is annoying.

**Comment by vedgy** [comment]
See comments to #1350. Thanks to a recent fix for that issue, in current GoldenDict git master you'll see translations for both "dem" and "dem-" in your example. What is the use case for the punctuation prefix? (such as '*' in your example)

**Comment by HarryRen** [comment]
I have an Etymology Online Dictionary, so "\*dem\-" is a root word, I alawys search root word in anki so frequently. 

I think if someone who wants to search  "\*dem\-" in a way of  a regular expression，which should be "\\\*dem\-\\" in startdict search bar, or just "\\\*dem\-\" simply. '\\' or something else represent a begin of a regular expression, then it will be clean&clear.

**Comment by vedgy** [comment]
Would showing translations for all 3 variants - "*dem-", "dem-" and "dem" - work for you? You can try how this works by hotkey-translating a word with a punctuation suffix, for which your dictionaries have translations both with and without the suffix. For example, my dictionaries contain articles for "ETC" and "etc.", so hotkey-translating "etc." shows both sets of articles.

**Comment by HarryRen** [comment]
I am using GoldenDict-1.5.0-RC2-372-gc3ff15f_(QT_5123)(64bit) . Yes, it show  all 3 variants -   "dem", "*dem-" and "dem-" in search pane.

But I just want to go to "*dem-" directly, I really don't want to click  "*dem-" again again and again.

**Comment by vedgy** [comment]
I did not mean the variants in the search pane, but merged articles in the article view. The recently implemented feature I had described is absent from your GoldenDict version. You could get a feel how this works by trying out Morphology dictionaries: for example, when an English Morphology dictionary is enabled, looking up "windows" produces articles for both "Windows" (the operating system) and "window" (for which "windows" is the plural form).

Similarly, in the current git master GoldenDict version looking up "etc.", in the context where the last dot is normally stripped (such as when the hotkey is used), the articles for both "ETC" (an acronym) and "etc." (an abbreviation) are produced. See #1350 for more details.

The original reason for stripping punctuation in some cases: let the user be sloppy with their text selection and don't require carefully selecting words without surrounding punctuation marks (such as .,-). Such hotkey/scan popup translations are meant to assist reading and comprehension, in which case extra precision requirement is an unnecessary burden.

During the discussion in comments to #1350, no one presented a use case for showing translation of the entire phrase (with the punctuation prefix and the punctuation suffix intact). So I implemented only one alternative form, which preserves the punctuation suffix for abbreviations like "etc.", "e.g.", "i.e.".

I personally don't use websites as dictionaries. If I understand [this comment](https://github.com/goldendict/goldendict/issues/1350#issuecomment-838423313) correctly, websites don't receive alternative forms anyway. So even if an alternative form preserving the entire word were added, it wouldn't help you. I guess the only solution to your issue would be to add an option that disabled stripping punctuation entirely.

> When I input dog ,then do-gooder is matched, it is a little weird.

The search pane contains headwords from the enabled dictionaries, which most closely match the input text.

**Comment by HarryRen** [comment]
" I guess the only solution to your issue would be to add an option that disabled stripping punctuation entirely."  Yes, it is. I need that option.

"Similarly, in the current git master GoldenDict version looking up "etc.", in the context where the last dot is normally stripped (such as when the hotkey is used), the articles for both "ETC" (an acronym) and "etc." (an abbreviation) are produced. See #1350 for more details." I get it.

So, When the lastest version of GoldenDict will be released?  Can I have a temporary windows version of current git master with an option that disabled stripping punctuation entirely? Thanks.

**Comment by Abs62** [comment]
Last version of GoldenDict.exe you can always take [here](https://forum.ru-board.com/topic.cgi?forum=5&topic=49149#1) (in Russian, look first post on page).

**Comment by vedgy** [comment]
> But when I input "*dem-" in the search bar , it takes a long time when I press the last character '-' in the search progress, so I think the search progress with punctuations should not be sloppy when the option is checked.

The asterisk in the search bar is treated as a wildcard symbol. A lot of headwords have to be searched when the asterisk is in front of the input phrase. It can be escaped with a backslash: \\*. See also the search bar's tooltip.

> Is there a hotkey binding with English Morphology dictionary enabled/disabled?

You can create two groups: with and without the English Morphology dictionary. It is possible to assign a custom shortcut to each group.

> Can I have a temporary windows version of current git master with an option that disabled stripping punctuation entirely?

This isn't implemented yet. And I don't really need this option, so do not plan to work on this.

**Comment by vedgy** [comment]
You could leave the issue open in case others have similar needs. Someone else could implement the option (s)he needs or in response to popular request.
