### ISSUE TITLE
Prebuilt binaries are too old, any newer ones?

### ISSUE THREAD

**Issue by playgithub** [goldendict/goldendict#1398]
The latest prebuilt binaries are on Apr 27, 2016.
And recent commits are very new.
And it needs  user info when I try to install qt on Windows.
Will there be newer prebuilt binaries?

**Comment by darnn** [comment]
There are more recent builds here:
https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows

And if you download those, here you can get just the modified files for even more recent ones:
https://www.mediafire.com/file/pxast7f5bgnjre8/goldendict-1.5.0-RC2-484-ge1c9a0d%2528EXE_only%2529.7z

(Just make sure to match the proper version, QT5x64 to QT5x64 and so on)

**Comment by playgithub** [comment]
> There are more recent builds here:
> https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows

27 April 2019 is not new enough.

> And if you download those, here you can get just the modified files for even more recent ones:
> https://www.mediafire.com/file/pxast7f5bgnjre8/goldendict-1.5.0-RC2-484-ge1c9a0d%2528EXE_only%2529.7z

I can't trust third party binaries.

**Comment by darnn** [comment]
Fair enough, but I fear that short of compiling them yourself, this is about as good as it gets. FWIW, it seems like there isn't a very noticeable difference between the 2019 ones and the newer ones.

**Comment by playgithub** [comment]
OK, thanks.
