### ISSUE TITLE
[Feature Request] Audio Auto-Pronunciation before all articles are loaded

### ISSUE THREAD

**Issue by marreromarco** [goldendict/goldendict#1402]
The Audio Auto-Pronunciation feature works only after all articles in a Group are shown (loaded).

If in a group there is a custom  "Website Dictionary" as "Yandex Images" or "Google Images" the Auto-Pronunciation does not work until all the web images are loaded.

For those with slow internet speed, the delay of the pronunciation can be quite long if in a Group there is a website dictionary with many images (e.g. "Bing Image", "Yandex Image", "Google Images", etc.). 

**Would it be possible to allow the Auto-Pronunciation feature to work before all articles in a Group are loaded ?**

**Comment by vedgy** [comment]
Everything is possible given enough motivation and time :)
However auto-pronouncing before all articles are loaded is not so easy to implement correctly. See: https://github.com/goldendict/goldendict/blob/baff02a14b3f70f0d0a55bef550dbb74dcbf0ce8/articleview.cc#L1676

`ArticleView::playSound()` first tries to pronounce the current audio link - the one that is inside the current article (which is not always the top article, depends on how the translation was requested). If the current article is a website article, then it must be loaded before the auto-pronunciation. Of course, one could look for an audio link before all images are loaded, but that would require some sort of interaction/cooperation between `ArticleView` and the website dictionaries, which is an extra implementation hurdle.

I prefer to separate offline and online dictionaries into groups: offline-only group loads much faster; not querying online dictionaries each time is better for privacy. If you assign shortcuts to frequently used groups on the Dictionaries=>Groups tab, switching between them becomes very convenient and natural after a few days of practice.

**Comment by marreromarco** [comment]
@vedgy It is true ! For privacy reasons, is better to separate off-line and online dictionaries. Thanks for your kind reply.

I will let the issue open just in case someone would like to work on the idea later...

**Comment by vedgy** [comment]
I think this feature could be useful. Even when all dictionaries are offline, pronouncing a word, say, half a minute earlier is already a win.

Unfortunately, I realized that there is a more substantial hurdle than `ArticleView::playSound()` to implementing this feature. The comments to #970 describe the "search" audio feature: if a referenced audio file is not found in a DSL or an XDXF dictionary, an audio file with the same name is searched for in all dictionaries within the current group. If some of the dictionaries are not loaded yet, some sort of delayed playback request would have to be implemented.
