### ISSUE TITLE
How to add a missing language / custom webfont for specific missing language in article-style.css

### ISSUE THREAD

**Issue by pod-o-mart** [goldendict/goldendict#1407]
Hi,

Goldendict doesn't recognize all languages. I would like to ask if there is a possibility to custom add a language. If not possible I would like to ask if it would be possible to implement custom languages in a future build.

## Background

I offer some dictionaries for Old Russian and Old Church Slavonic [in my "lingvo" repository](https://github.com/pod-o-mart/lingvo). GoldenDict dos not recognize these languages, what usually wouldn't be a bigger problem.

My point is that I want to define a [custom Old Cyrillic](https://sci.ponomar.net/fonts.html#fonts-for-academic-work) [webfont](https://sci.ponomar.net/tools.html#web-fonts) for these languages. 

According to [the FAQ](http://goldendict.org/wiki/index.php/FAQ) I have created an `article-style.css` which perfectly works with Russian, without installing any font locally:
```
@font-face {
    font-family: 'Monomakh Unicode';
    src: url('https://sci.ponomar.net/fonts/MonomakhUnicode.eot');
    src: url('https://sci.ponomar.net/fonts/MonomakhUnicode.eot?#iefix') format('embedded-opentype'),
	url('https://sci.ponomar.net/fonts/MonomakhUnicode.woff2') format('woff2'),
	url('https://sci.ponomar.net/fonts/MonomakhUnicode.woff') format('woff'),
	url('https://sci.ponomar.net/fonts/MonomakhUnicode.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
}

:lang(ru), .gdlangfrom-ru {
	font-family: 'Monomakh Unicode';
	font-size: 1.1em;
}
```
That is why I need Goldendict to understand the [ISO 639-1 code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) "cu" for [Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=cu) and "orv" (only ISO 639-3)  [Old Russian](https://iso639-3.sil.org/code/orv).

I am aware that it is also possible to define the css by the indiviual dictionary IDs. But these are not persistent and different from installation to installation. I would like to add to my [ditionary repository](https://github.com/pod-o-mart/lingvo) a ready-to-use `article-style.css` file for Old Slavic.

My problem would be solved if there was a possibility to manually define languages in GoldenDict, maybe in some config file like this:
```
"Church Slavic" = "cu"
"Old Slavonic" = "cu"
"Church Slavonic" = "cu"
"Old Bulgarian" = "cu"
"Old Church Slavonic" = "cu"
"Old Russian" = "orv"
```
Thank you in advance!

Martin

**Comment by nikita-moor** [comment]
It's called "Church Slavic" in Goldendict:

https://github.com/goldendict/goldendict/blob/baff02a14b3f70f0d0a55bef550dbb74dcbf0ce8/language.cc#L84

Change DSL header to be compatible with GoldenDict:

```
#NAME	"Церковно-славянский словарь (Chu-Rus) Unicode"
#INDEX_LANGUAGE	"Church Slavic"
#CONTENTS_LANGUAGE "Russian"
```

Language code of the articles is assigned according to the `CONTENTS_LANGUAGE`, so if you want to render definitions with your custom font, then set it to "Church Slavic" as well.

Hope I understood your problem correctly.

**Comment by pod-o-mart** [comment]
Hi nikita-moor,

Thank you for your answer. The fact that there is a tag for "Church Slavic" absolutely solves my problem.

I have now created an [`article-style.css`, a `qt-style.css`]( https://github.com/pod-o-mart/lingvo/tree/main/_FONT_CONFIG_old_cyrillic), adapted the DSL files to it with "Church Slavic" as `#INDEX_LANGUAGE` resp. `#CONTENTS_LANGUAGE` and `[lang]` tags in the articles. You can see the result here: https://doi.org/10.5281/zenodo.5165145

There is only the one problem remaining that the `qt-style.css` doesn't have any effect on my installation but I'll post another issue on that.

Thank you very much again!
Martin
