### ISSUE TITLE
Scan popup interferes with text selection (can't copy text)

### ISSUE THREAD

**Issue by kevinsung** [goldendict/goldendict#1410]
The scan popup causes the selected text to be unfocused, so that, for instance, Ctrl-C does not copy the text. The correct behavior should be to have the selected text still focused, so it can be copied with Ctrl-C. For example, Stardict has the correct behavior.

Operating system: Arch Linux
Desktop environment: Cinnamon
Display server: X

**Comment by vedgy** [comment]
Please close this issue as a duplicate of #310.

I personally like that the scan popup has focus when it appears: this allows to navigate the translation articles with the keyboard. It is unlikely anyone would implement an option to *not* focus the scan popup anytime soon. There are several ways to avoid the scan popup when it is unwanted:
1. try various options on the *Scan Popup* tab of GoldenDict Preferences;
2. enable the scan popup only when you want it to appear. The current GoldenDict *master* version does not support a keyboard shortcut for quick toggling of the scan popup. But you could test and give feedback on #965 that implements it.

**Comment by kevinsung** [comment]
I see, thanks.
