### ISSUE TITLE
ctrl+c+c popup doesn't work on Ubuntu 21.10 with firefox, evince, sublime text

### ISSUE THREAD

**Issue by aXynt** [goldendict/goldendict#1420]
ctrl+c+c clipboard popup doesn't work on Ubuntu 21.10 (Gnome Shell 40.5) with firefox, evince, sublime text,... but works with chromium, chrome, VS code,...

**Comment by commandgjj** [comment]
It is the same issue with Debian 11. goldendict version: 1.5.0-RC2+git

**Comment by vedgy** [comment]
Scan popup works perfectly for me on Manjaro+Xfce. Things to test:
1) the *Ignore input phrases longer than N symbols* in the Advanced tab of GoldenDict Preferences disables translation of overly long phrases;
2) pin the scan popup window (check the pin tool button in the top right corner of the scan popup);
3) try different options in the Scan Popup tab of GoldenDict Preferences;
4) try all possible combinations of **ScanPopup unpinned window flags** and *Bypass window manager hint* in the Advanced tab of GoldenDict Preferences.

**Comment by RistoJu** [comment]
Same here, Deb 11, XFCE, 1.5.0~rc2+git20200409+ds-2
