### ISSUE TITLE
Donations to support GoldenDict Development (e.g. Open Collective )

### ISSUE THREAD

**Issue by nonwill-fan** [goldendict/goldendict#1432]
The main developer of GoldenDict @Abs62 has been working since 2011 on this project and has written more than  347.000 lines of code. "Vedgy" has also been very active in recent years and also deserves a financial reward.

**I would like to propose to create a method to support the development of GoldenDict.** OpenCollective would be an excellent option.

_With enough donations, more features could be implemented on GoldenDict and even external developers might be hired._ As an example, AnkiDroid has an [Open Collective website](https://opencollective.com/ankidroid) that has raised more than 36.000 USD. They have used part of donations to pay developers to improve some features !

**Comment by nonwill** [comment]
[@marreromarco](https://github.com/FyTpodQUuWvQNTh) [@medp7060](https://github.com/medp7060) [@xiaoyifang](https://github.com/xiaoyifang) :
As https://github.com/goldendict/goldendict/issues/1424 mentioned, You can contact Eudic for financial support and assistance. But I think Mr. Zou will be of considerable financial help to you and the entire GoldenDict development team, SO you would do well to contact her/him who comes from FreeMdict as you do:
![20211202230459](https://user-images.githubusercontent.com/46510529/144449171-08027216-2d6b-481b-b7ae-0b177608167f.png)
![20211202230837](https://user-images.githubusercontent.com/46510529/144449197-04612496-2d05-4bfd-a795-22dea5a3d486.png)

**Comment by nonwill-fan** [comment]
@nonwill stop your spammer behaviour. I will close this usse because "nonwill" will continue with useless comments on this thread. :sweat_smile:    Poor" nonwill" is desperate because users are deleting his GD++ malware... :laughing:
