### ISSUE TITLE
Add Qt4 version to AUR

### ISSUE THREAD

**Issue by majidmadadi** [goldendict/goldendict#1433]
The downloaded version in aur repository is based on qt5 which donsn't properly show rtl dictionaries. Please add a qu4 version into the AUR.

![scr](https://user-images.githubusercontent.com/12540187/144626039-3f9731b9-b61b-4674-8310-a002f727670d.png)

**Comment by vedgy** [comment]
[goldendict-git](https://aur.archlinux.org/cgit/aur.git/log/?h=goldendict-git) depended on Qt4 until 2019. Feel free to submit that old PKGBUILD version (possibly with some corrections) to AUR yourself.

And please close this issue because GoldenDict developers don't maintain distribution packages.

**Comment by majidmadadi** [comment]
Thank you
