### ISSUE TITLE
Problem with RTL dictionaries

### ISSUE THREAD

**Issue by majidmadadi** [goldendict/goldendict#1434]
Hi,
The versions which have build by Qt5 can't render RTL dictionaries properly. The windows version working perfectly fine but the linux version doesn't work.

![goldendict](https://user-images.githubusercontent.com/12540187/144679660-12a8047a-9f80-4da9-a97e-f7cef4a36020.png)

**Comment by vedgy** [comment]
Duplicate of #1052? Why'd you comment in that issue and then create this one?

**Comment by majidmadadi** [comment]
That was more than a year ago. I haven't managed to solve the problem. The link provided for older app image returns 404.
________________________________

**Comment by vedgy** [comment]
There are several duplicates of that issue already, so please close this one.

You could check out #1400 and see if it eliminates the bug.

**Comment by majidmadadi** [comment]
I close this because of duplication. Thanks for the help by the way.
