### ISSUE TITLE
warning: audio player: codec [id: 86051 ] not found

### ISSUE THREAD

**Issue by Aliaksandr3by** [goldendict/goldendict#1436]
in Oxford Advanced American Dictionary for learners of English 2011, 16-2-1, there is a problem with audio

warning: audio player: codec [id: 86051 ] not found.

![image](https://user-images.githubusercontent.com/11432724/147602808-dbaf2a53-352f-4bd3-8897-6c3454c3781d.png)

1.5.0-RC2-497-gb10cdf6

**Comment by vedgy** [comment]
What is your **Playback** configuration on the Audio tab of GoldenDict preferences? Does the pronunciation work with other internal player backends or external programs?

**Comment by Aliaksandr3by** [comment]
work with MPC-HC
don't work with internal ones

![image](https://user-images.githubusercontent.com/11432724/147667973-64c46b28-5bc0-4453-8b7a-1a37e75333c4.png)

**Comment by vedgy** [comment]
So the same warning appears and the pronunciation is not audible with both internal player backends?

Looking at https://github.com/FFmpeg/FFmpeg/blob/4ff884069787161138e604b7aae495d27c457287/libavcodec/codec_id.h#L423 and subtracting `86051-0x15000 = 35`. Add 35 to the line 423 => line 458 => `AV_CODEC_ID_SPEEX`. Looks like this codec is not supported by GoldenDict on Windows.

Can you test the GNU/Linux GodlenDict version or share the dictionary somehow to let me test it?

**Comment by nonwill** [comment]
>AV_CODEC_ID_SPEEX
>codec is not supported

To fix the issue, please rec[ompile ffmpeg according to the instructions strictly](https://github.com/goldendict/goldendict/blob/master/winlibs/scripts/00README.txt).

**Comment by vedgy** [comment]
@nonwill, is the problem in outdated ffmpeg binaries in the GoldenDict Windows build?

**Comment by vedgy** [comment]
I guess the latest commit 0e888db8746766984a4422af9972de8753d4d6c4 fixes this issue. @Aliaksandr3by, could you check it and close this issue if fixed?

**Comment by Aliaksandr3by** [comment]
> Can you test the GNU/Linux GodlenDict version or share the dictionary somehow to let me test it?

https://mega.nz/folder/84NgxRrZ#P8mE2YcMEIebwfSry9J6GQ

**Comment by Aliaksandr3by** [comment]
I use win_64
Version	10.0.19044 Build 19044

**Comment by Aliaksandr3by** [comment]
> So the same warning appears and the pronunciation is not audible with both internal player backends?

the ff*** got the WARNING.
the qt*** did nothing.

**Comment by Aliaksandr3by** [comment]
the 1.5.0-RC2-499-g0e888db version is working:
all thank

**Comment by nonwill** [comment]
> outdated ffmpeg binaries

It should be issue that libspeex was not found by pkgconfig when ffmpeg was being configured.
Nice to see the issue was fixed.

**Comment by Aliaksandr3by** [comment]
with LavFilters the qtmultimedia is work too
