### ISSUE TITLE
put same dictionary in different folders. add folders  to goldendict.the same dictionary will appear multi times.

### ISSUE THREAD

**Issue by xiaoyifang** [goldendict/goldendict#1438]
as title.

is this a feature or a bug?

**Comment by vedgy** [comment]
Does detecting duplicates require extra hash sum computation of each dictionary file? Or is this easily detectable with the information already gathered about the dictionaries?

**Comment by xiaoyifang** [comment]
I think change the following function seems ok.
` makeDictionaryId `
use relative file name ,just as portable version.

**Comment by vedgy** [comment]
`makeDictionaryId()` hashes only filenames, not file contents. There can be different dictionaries that consist of files whose names are exactly the same, but contents different. The portable version uses paths relative to one specific directory, which does *not* eliminate duplicates inside this portable-dictionary directory.

**Comment by xiaoyifang** [comment]
what about filename + filesize
then chances of different dicts have same hash will be really low  .

**Comment by vedgy** [comment]
The user could copy and change/fix a dictionary without affecting its size (maybe some word or style), then try to compare the results. With your proposed change the user would be unpleasantly surprised that only one of the dictionaries is loaded.

What are you trying to achieve? Why not let the user deduplicate the dictionaries manually and save disk space?

**Comment by xiaoyifang** [comment]
This is a also a way.

**Comment by xiaoyifang** [comment]
just find a way to fast compute the hash
```
    QFile file("a big file 1G");
    QCryptographicHash hash(QCryptographicHash::Md5);
    hash.addData(&file);
    qDebug() << hash.result().toHex();
```
really fast to zero seconds.

**Comment by vedgy** [comment]
The time depends on whether the dictionary file is in disk cache. If it is not, merely reading the file can be very slow, especially if it is stored on an HDD. Some dictionary files occupy several gigabytes and may not even fit into the disk cache.

Assuming you find a way to determine whether or not two dictionaries are the same, what would you do? Load the arbitrary one out of several duplicates and print a warning in log or show a warning message box?

**Comment by xiaoyifang** [comment]
got it ,this issue will be closed.
