### ISSUE TITLE
where can I set the addonStyle value ,I did not find it in the edit=>preference 

### ISSUE THREAD

**Issue by xiaoyifang** [goldendict/goldendict#1439]

**Comment by vedgy** [comment]
Found the answer by quickly grepping GoldenDict code:
1. Create more than one addon style file in the directory referenced in *stylescombobox.cc*.
2. Select one of the styles on the *Interface* tab of GoldenDict Preferences. The Add-on style combobox will appear when there are multiple addon styles thanks to the following code in *preferences.cc*:
```cpp
ui.addonStylesLabel->setVisible( ui.addonStyles->count() > 1 );
```

**Comment by xiaoyifang** [comment]
ok ,i will check that.

then should the the user defined addonStyle files put at the bottom of the html .in order to override styles embed in dictionary.
