### ISSUE TITLE
high dpi image support(existed icon),help needed.

### ISSUE THREAD

**Issue by xiaoyifang** [goldendict/goldendict#1441]
![image](https://user-images.githubusercontent.com/105986/150461085-61001420-26f3-44a1-b754-45a1ea319281.png)

the icons in high dpi screen are fuzzy.
need help to  recommend license compatible icons?

any ideas are welcomes.
icons replacement table record,  images size can be 64x64 or 128x128,need help to find the icons ,format can be png
gnome:https://packages.debian.org/bullseye/gnome-icon-theme
tango:https://commons.wikimedia.org/wiki/Tango_icons    license:public domain
|name| goldendict original icon  | to be replace by | source |license|
| -----|-------- | ------------- |---|---|
|addTab.png|![addtab](https://user-images.githubusercontent.com/105986/150640539-274b4821-88ac-4042-b8b3-48a5d89005f6.png)| ![addtab](https://user-images.githubusercontent.com/105986/150665443-99ca61e0-f12c-4f65-ab56-2ec4e26a9f0a.png)  |Tango |gplv3|
|book.png| ![book](https://user-images.githubusercontent.com/105986/150640556-54f85c0e-2605-42d6-9ddf-b2cd80a60bb0.png)  |![image](https://user-images.githubusercontent.com/105986/150808156-890bcfa6-4a63-44ce-8635-5cf525501354.png)|https://commons.wikimedia.org/wiki/File:Foliate_icon_2020.svg|gpl3|
| bookcase.png|![bookcase](https://user-images.githubusercontent.com/105986/150640613-e7bf466c-2e33-4f86-b5f5-43eae2366f9d.png) |![image](https://user-images.githubusercontent.com/105986/150733025-47058c5d-622b-435e-bb1f-ac67f6440bbf.png)|https://commons.wikimedia.org/wiki/File:Nuvola_apps_bookcase.svg    recommend by:@shawkynasr ||
|clear.png|![clear](https://user-images.githubusercontent.com/105986/150640641-7f79170a-4d6d-4c90-a518-85cbefd30286.png)|![clear](https://user-images.githubusercontent.com/105986/151464518-95acfeca-2b53-482d-85f5-1522e7771110.png)|gnome|gplv3|
|closetab.png|![closetab](https://user-images.githubusercontent.com/105986/150640673-e06484e8-0f90-4aad-979e-8bf9f82ca126.png)|![image](https://user-images.githubusercontent.com/105986/151475421-341a9dc0-689f-4ad0-899f-b3d0ee542d0b.png)|tango|gplv3|
|configure.png|![configure](https://user-images.githubusercontent.com/105986/150640686-546ee3a1-8543-4cf9-acbf-e5491e306e03.png)|![configure](https://user-images.githubusercontent.com/105986/150665466-7cd029db-a204-4722-b71f-288ff7baa826.png)|tango||
|error.png|![error](https://user-images.githubusercontent.com/105986/150641444-b5c5ac31-6af3-41cf-9559-c24037965d91.png)|![image](https://user-images.githubusercontent.com/105986/150780428-9eec85c8-64bd-4280-8294-33cdb7c02060.png)|tango|gplv3|
|fileopen.png|![fileopen](https://user-images.githubusercontent.com/105986/150640751-74b5cfe3-314c-420c-a2cf-0cae30d168c1.png)|![fileopen](https://user-images.githubusercontent.com/105986/150665478-cdd2f87f-14f4-4fc7-b1b1-aef061fabc00.png)|tango||
|filesave.png|![filesave](https://user-images.githubusercontent.com/105986/150640767-da892ef3-1cd3-42d1-950e-25080b85e7de.png)|![image](https://user-images.githubusercontent.com/105986/151476497-e24339a8-4c90-4d7b-9cc8-7eaeef6cf334.png)|tango||
|folder.png|![folder](https://user-images.githubusercontent.com/105986/150640794-e3c9fa76-24bc-4565-9593-ab451c1383fc.png)|![folder](https://user-images.githubusercontent.com/105986/150665932-cd9f30ed-6c0a-4481-a4d8-5a33f18458e6.png)|tango||
|home.png|![home](https://user-images.githubusercontent.com/105986/150640819-c002df8c-cd41-4298-a146-03f1456cd0e4.png)|![home](https://user-images.githubusercontent.com/105986/150665544-810a825c-bdd7-4e6a-8154-ee6b942efb0c.png)|tango||
|icon32_zoombase.png|![icon32_zoombase](https://user-images.githubusercontent.com/105986/150640889-71921599-587a-4eb1-8dee-f6ce78069126.png)|![image](https://user-images.githubusercontent.com/105986/151465553-f5124971-c875-421f-8943-a914d9eae71b.png)|tango||
|icon32_zoomin|![icon32_zoomin](https://user-images.githubusercontent.com/105986/150640903-c9f5688f-7561-4256-8f86-bf6717674d9b.png)|![image](https://user-images.githubusercontent.com/105986/151465650-03b9909b-c824-4aca-bbfc-0e6f9b58c3de.png)|tango||
|icon32_zoomout|![icon32_zoomout](https://user-images.githubusercontent.com/105986/150640914-83227a8a-b7c7-4dcd-8110-8c8b49ef0d37.png)|![image](https://user-images.githubusercontent.com/105986/151465603-6dd7a891-becb-4f7b-940e-8f7d2c85173f.png)|tango||
|interface|![interface](https://user-images.githubusercontent.com/105986/150640931-ab5e8b04-7815-48c0-93ab-4859c039e5f6.png)|![image](https://user-images.githubusercontent.com/105986/151465855-c4728f68-068b-491e-9836-c98a8750dfa0.png)|tango||
|internet|![internet](https://user-images.githubusercontent.com/105986/150640940-d63fe6d1-8eb8-42c6-b242-756533982793.png)|![internet](https://user-images.githubusercontent.com/105986/150661484-eab5f908-0018-452a-9a8a-7f18474ecf43.png)|http://tango.freedesktop.org/Tango_Desktop_Project|gpl|
|nework|![network](https://user-images.githubusercontent.com/105986/150641470-1cdacc18-265e-4c4d-b1b8-46cc39250ab7.png)|![network](https://user-images.githubusercontent.com/105986/150665616-e9e1ef73-4e8f-4530-a6ea-b7e926440ee6.png)|tango|gplv3|
|next|![next](https://user-images.githubusercontent.com/105986/150641038-428dd01f-f499-4ca8-a97e-af6adfde8db4.png)|![image](https://user-images.githubusercontent.com/105986/151473795-4d34b149-7aea-4102-b1b6-0b63d953a23c.png)|tango||
|playsound_color|![playsound_color](https://user-images.githubusercontent.com/105986/150641066-fd2903f3-6297-4e42-bddc-44eac5000973.png)|![image](https://user-images.githubusercontent.com/105986/151473901-b1f044e6-2f5c-4325-b5c7-4b5ac496e997.png)|tango||
|previous|![previous](https://user-images.githubusercontent.com/105986/150641081-f8fb95e8-a11e-4395-832f-6e1a40e33529.png)|![image](https://user-images.githubusercontent.com/105986/151473829-f9d8c5d3-0706-4cc7-bc54-03623579866d.png)|tango||
|print|![print](https://user-images.githubusercontent.com/105986/150641088-31a661cc-112a-4be2-be09-0b4d56011ce1.png)|![image](https://user-images.githubusercontent.com/105986/150780064-2d8ffa09-d1d4-43f0-9e34-f0de04a2d3f5.png)|tango||
|programs|![programs](https://user-images.githubusercontent.com/105986/150641100-fe65f1a4-f89d-4f0f-8a8b-85df203f05a3.png)|![image](https://user-images.githubusercontent.com/105986/150780737-536c8215-d6cb-4082-8b74-41073732fa80.png)|tango||
|reload ,used on dictionaries->sources tab|![reload](https://user-images.githubusercontent.com/105986/150641112-22fbb2c4-c823-47e8-b72a-26d31cb7e8de.png)|![image](https://user-images.githubusercontent.com/105986/151100258-ef9e83c0-8004-40a0-8436-784125bf4830.png)|tango||
|system-search|![system-search](https://user-images.githubusercontent.com/105986/150641132-60a99003-d929-4c4b-b982-dce604b23da9.png)|![system-search](https://user-images.githubusercontent.com/105986/150665811-746d7a72-98d7-4e9a-8a62-809c871c3dec.png)|tango||
|star|![star](https://user-images.githubusercontent.com/105986/150641490-3feca513-cc72-4714-917d-6c8d3dc4373c.png)|![image](https://user-images.githubusercontent.com/105986/150781713-72ab36f5-0e79-457a-b7bd-f3eaca204183.png)|tango|gplv3|
|star_blue|![star_blue](https://user-images.githubusercontent.com/105986/150641501-9e2ee21c-fec0-4faf-8988-a2eb5ad631d0.png)|![image](https://user-images.githubusercontent.com/105986/150781802-d94cd46d-9d0b-4f76-ab5b-6f1ab72d6dff.png)|tango|gplv3|
|windows-list|![windows-list](https://user-images.githubusercontent.com/105986/150641202-194bb1e5-dff0-4d69-9d6c-cfc7ee8f6c25.png)|![image](https://user-images.githubusercontent.com/105986/151473989-3f812f64-aba8-48c7-9b40-a14baf057ad9.png)|tango||
|wizard|![wizard](https://user-images.githubusercontent.com/105986/150641230-6fe3b91c-4ef7-42bb-82e5-c88fbe40907d.png)|![image](https://user-images.githubusercontent.com/105986/151475348-4329d2fd-bdd4-4e3b-9c86-dc369c736865.png)|tango||
|hotkey|![hotkeys](https://user-images.githubusercontent.com/105986/150896338-2f5bebd0-28dc-42f5-9cbd-ae4c5047e5cb.png)|![image](https://user-images.githubusercontent.com/105986/151474268-e07b198b-7a0a-424f-8f63-c1e8ec65c93f.png)|tango||
|edit dictionary windows icon|reuse book|![image](https://user-images.githubusercontent.com/105986/150806910-de4a766c-4acb-4304-8c12-0ef2b39c998d.png)|https://commons.wikimedia.org/wiki/File:Accessories-dictionary.svg||
|sound dirs|reuse fileopen|![image](https://user-images.githubusercontent.com/105986/150809353-21e4ca9a-bbbb-49cd-9abe-93bfa52e4c26.png)|https://commons.wikimedia.org/wiki/File:Oxygen480-places-folder-sound.svg|lgpl|
|full text |reuse search|![image](https://user-images.githubusercontent.com/105986/150918827-a1db4710-ee9a-48dc-a567-7514bd6f8265.png)|tango||
|advanced|none|![image](https://user-images.githubusercontent.com/105986/151474973-aecc7327-d9b5-46fb-a902-872656fc0b06.png)|tango||
|text to speech |reuse ![playsound_color](https://user-images.githubusercontent.com/105986/150919709-5ad6451f-38e9-4371-a3b7-5b6409c3fc83.png)|![image](https://user-images.githubusercontent.com/105986/150920022-fe65af98-3eed-4866-a75e-04745847e523.png)|tango||
|pushpin|![pushpin](https://user-images.githubusercontent.com/105986/150922091-6ad3cb2c-3519-45b0-bc4d-d63a5f707d08.png)|![image](https://user-images.githubusercontent.com/105986/150923131-bfd34d37-8479-45a8-afc5-b3a0945e4b50.png)|https://freesvg.org/pushpin-vector-image|public domain|
|dictionary bar ,website dictionary|reuse internet|![image](https://user-images.githubusercontent.com/105986/151474831-365b0f68-fa83-4967-a47d-71fe69795f2d.png)|tango||
|transliteration|none|![image](https://user-images.githubusercontent.com/105986/151475142-bf92656d-5244-4bc5-b1ba-0f22d88d4d2b.png)|tango||
||![1downarrow](https://user-images.githubusercontent.com/105986/151090002-ff22cfbe-5c7c-441f-a137-f3b67551e44e.png)|![image](https://user-images.githubusercontent.com/105986/151090764-54027e66-9ce5-4899-a249-65111689ad7b.png)|https://commons.wikimedia.org/wiki/File:Arrow_bottom_svg.svg|public domain|
|menu|![menu_button](https://user-images.githubusercontent.com/105986/151650586-2327312d-6be6-4a8f-8b94-fe8b9e37970e.png)|![image](https://user-images.githubusercontent.com/105986/151650552-c9229411-fb55-4359-97f5-8dd263403e84.png)|tango||

**Comment by vedgy** [comment]
See #1327 for icon revamping ideas and discussion.

**Comment by xiaoyifang** [comment]
this is my decision:
replace the default goldendict icon with a more large png image.
and use system theme icon.

the result :on theme support platform ,the platform theme maybe used ,if not ,fallback to goldendict's own icons

**Comment by xiaoyifang** [comment]
where to find all the free license icons? any places recommended.
is it ok to use icons in https://www.flaticon.com/

**Comment by xiaoyifang** [comment]
> where to find all the free license icons? any places recommended. is it ok to use icons in https://www.flaticon.com/

reply myself ,seems not ok. 
I'll found other places.

**Comment by xiaoyifang** [comment]
icons replace recommends,
|name| goldendict original icon  | to be replace by | source |license|
| -----|-------- | ------------- |---|---|
|addTab.png|![addtab](https://user-images.githubusercontent.com/105986/150640539-274b4821-88ac-4042-b8b3-48a5d89005f6.png)|   | ||
|book.png| ![book](https://user-images.githubusercontent.com/105986/150640556-54f85c0e-2605-42d6-9ddf-b2cd80a60bb0.png)  |   |||
| bookcase.png|![bookcase](https://user-images.githubusercontent.com/105986/150640613-e7bf466c-2e33-4f86-b5f5-43eae2366f9d.png) ||||
|clear.png|![clear](https://user-images.githubusercontent.com/105986/150640641-7f79170a-4d6d-4c90-a518-85cbefd30286.png)||||
|closetab.png|![closetab](https://user-images.githubusercontent.com/105986/150640673-e06484e8-0f90-4aad-979e-8bf9f82ca126.png)||||
|configure.png|![configure](https://user-images.githubusercontent.com/105986/150640686-546ee3a1-8543-4cf9-acbf-e5491e306e03.png)||||
|error.png||![error](https://user-images.githubusercontent.com/105986/150640713-8f6c467a-2212-46ac-a909-d00df63d6aa3.png)|https://github.com/zayronxio/Zafiro-icons|gplv3|
|fileopen.png|![fileopen](https://user-images.githubusercontent.com/105986/150640751-74b5cfe3-314c-420c-a2cf-0cae30d168c1.png)||||
|filesave.png|![filesave](https://user-images.githubusercontent.com/105986/150640767-da892ef3-1cd3-42d1-950e-25080b85e7de.png)||||
|folder.png|![folder](https://user-images.githubusercontent.com/105986/150640794-e3c9fa76-24bc-4565-9593-ab451c1383fc.png)||||
|home.png|![home](https://user-images.githubusercontent.com/105986/150640819-c002df8c-cd41-4298-a146-03f1456cd0e4.png)||||
|icon32_wiki|![icon32_wiki](https://user-images.githubusercontent.com/105986/150640870-e4a664e8-b071-460e-b688-fb70f5adc609.png)||||
|icon32_zoombase.png|![icon32_zoombase](https://user-images.githubusercontent.com/105986/150640889-71921599-587a-4eb1-8dee-f6ce78069126.png)||||
|icon32_zoomin|![icon32_zoomin](https://user-images.githubusercontent.com/105986/150640903-c9f5688f-7561-4256-8f86-bf6717674d9b.png)||||
|icon32_zoomout|![icon32_zoomout](https://user-images.githubusercontent.com/105986/150640914-83227a8a-b7c7-4dcd-8110-8c8b49ef0d37.png)||||
|interface|![interface](https://user-images.githubusercontent.com/105986/150640931-ab5e8b04-7815-48c0-93ab-4859c039e5f6.png)||||
|internet|![internet](https://user-images.githubusercontent.com/105986/150640940-d63fe6d1-8eb8-42c6-b242-756533982793.png)||||
|nework||![network](https://user-images.githubusercontent.com/105986/150640951-5655ea67-a55c-47b0-a822-21310cdcd841.png)|https://github.com/elementary/icons|gplv3|
|next|![next](https://user-images.githubusercontent.com/105986/150641038-428dd01f-f499-4ca8-a97e-af6adfde8db4.png)||||
|playsound_color|![playsound_color](https://user-images.githubusercontent.com/105986/150641066-fd2903f3-6297-4e42-bddc-44eac5000973.png)||||
|previous|![previous](https://user-images.githubusercontent.com/105986/150641081-f8fb95e8-a11e-4395-832f-6e1a40e33529.png)||||
|print|![print](https://user-images.githubusercontent.com/105986/150641088-31a661cc-112a-4be2-be09-0b4d56011ce1.png)||||
|programs|![programs](https://user-images.githubusercontent.com/105986/150641100-fe65f1a4-f89d-4f0f-8a8b-85df203f05a3.png)||||
|reload|![reload](https://user-images.githubusercontent.com/105986/150641112-22fbb2c4-c823-47e8-b72a-26d31cb7e8de.png)||||
|system-search|![system-search](https://user-images.githubusercontent.com/105986/150641132-60a99003-d929-4c4b-b982-dce604b23da9.png)||||
|star||![star](https://user-images.githubusercontent.com/105986/150641143-42057a57-e1f8-4bea-a45e-6c87cf1db64e.png)|https://github.com/elementary/icons|gplv3|
|star_blue||![star_blue](https://user-images.githubusercontent.com/105986/150641172-7cfdd64c-c8b1-4d5c-8bb2-0144b5b812a1.png)|https://github.com/elementary/icons|gplv3|
|warning|![warning](https://user-images.githubusercontent.com/105986/150641192-6f01744d-d2c6-4369-928a-06b8c69bc260.png)||||
|windows-list|![windows-list](https://user-images.githubusercontent.com/105986/150641202-194bb1e5-dff0-4d69-9d6c-cfc7ee8f6c25.png)||||
|wizard|![wizard](https://user-images.githubusercontent.com/105986/150641230-6fe3b91c-4ef7-42bb-82e5-c88fbe40907d.png)||||

**Comment by vedgy** [comment]
Please remove the duplicate icon table from the previous comment.

Many current GoldenDict icons were borrowed from Qt source code repository. I can see the dictionary icon; Prev, Next icons in Qt Linguist. Perhaps the current versions of these Qt icons have higher resolutions.

The reporter of #1327 suggested Adwaita icons. You can also search for other icon themes designed for GNU/Linux.

**Comment by xiaoyifang** [comment]
handled in this branch https://github.com/xiaoyifang/goldendict/tree/feature/highdpi-icon
based on #1400

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/150726182-aadcabbc-e8e1-49ff-a9b6-094202533e62.png)
the icons take effect,but under high dpi still looks fuzzy. 
maybe I did it in the wrong way.

**Comment by shawkynasr** [comment]
for bookcase.png
[Nuvola apps bookcase](https://commons.wikimedia.org/wiki/File:Nuvola_apps_bookcase.svg)

**Comment by vedgy** [comment]
> the icons take effect,but under high dpi still looks fuzzy. maybe I did it in the wrong way.

Does an icon look fuzzy in an image viewer when you shrink it to the size used by GoldenDict?

**Comment by xiaoyifang** [comment]
> > the icons take effect,but under high dpi still looks fuzzy. maybe I did it in the wrong way.
> 
> Does an icon look fuzzy in an image viewer when you shrink it to the size used by GoldenDict?

no ,the resized image is just ok.
maybe change the image format from png to svg? or maybe has something with pixelDeviceRatio.

**Comment by vedgy** [comment]
1. Have you compared how it looks on Windows and on GNU/Linux?
2. SVG is an option worth testing.
3. Check out ideas and code samples [here](https://forum.qt.io/topic/65464/hi-dpi-and-svg-icons/5) and [here](https://forum.qt.io/topic/108274/hidpi-and-svg-icon-resolution/24).

**Comment by xiaoyifang** [comment]
I only have high dpi windows environment ,
have not checkout the appearance in linux ,can someone check it with the latest release .

I'll try the svg .

**Comment by vedgy** [comment]
I don't have a high-DPI screen at all, so someone else will have to volunteer. Or perhaps it is possible to configure high DPI in a virtual machine.

**Comment by xiaoyifang** [comment]
working now,seems large png image and svg both work:
125% screen
![image](https://user-images.githubusercontent.com/105986/150895082-9b562ef1-5fa7-457b-9b1b-382b48c688be.png)

175% screen
![image](https://user-images.githubusercontent.com/105986/150895242-54b19afd-d5b4-4c86-a0b6-6f22cdb6a788.png)

**Comment by vedgy** [comment]
> working now,seems both large png image and svg work

So what was wrong before? Why were the icons fuzzy?

**Comment by xiaoyifang** [comment]
`QApplication::setAttribute(Qt::AA_UseHighDpiPixmaps);`

**Comment by nonwill** [comment]
>Why were the icons fuzzy?

> `QApplication::setAttribute(Qt::AA_UseHighDpiPixmaps);`

BTW, without QApplication::setAttribute(Qt::AA_UseHighDpiPixmaps), on windows 10, the original icons display well with my 3K and 4K monitors, even after I had compressed them several times with tinypng.com.

**Comment by xiaoyifang** [comment]
final state: 175%
![image](https://user-images.githubusercontent.com/105986/151088234-85863e9a-3b0f-45eb-b67d-b04cd69e7d52.png)

**Comment by nonwill** [comment]
> final state: 175%
> ![image](https://user-images.githubusercontent.com/105986/151088234-85863e9a-3b0f-45eb-b67d-b04cd69e7d52.png)

A little gorgeous, and more like an embroidered pillow, not as elegant as the original... But that's the spirit, great!

**Comment by xiaoyifang** [comment]
https://doc.qt.io/qt-5/highdpi.html#:~:text=High%20DPI%20displays%20have,barely%20exceeds%20this%20resolution.

**Comment by vedgy** [comment]
The linked gnome icons page states:
> All icons are licensed under GNU General Public License version 2. 

GPLv2 is incompatible with GoldenDict's GPLv3. But you could download the latest versions of the icons licensed under GNU LGPL v.3 from https://packages.debian.org/bullseye/gnome-icon-theme [_gnome-icon-theme_3.12.0.orig.tar.xz_].

**Comment by xiaoyifang** [comment]
ok I'll the change gnome icons

**Comment by xiaoyifang** [comment]
replace them with tango.
