### ISSUE TITLE
what about to embed capture2text ocr to goldendict?

### ISSUE THREAD

**Issue by xiaoyifang** [goldendict/goldendict#1445]
https://sourceforge.net/projects/capture2text/    is gpl ,cross platform.
ocr is what goldendict lacks though in no emergence.

**Comment by xiaoyifang** [comment]
close for the reason : seems only on windows.

**Comment by xiaoyifang** [comment]
https://github.com/GSam/Capture2Text   linux port .

**Comment by nonwill** [comment]
> https://github.com/GSam/Capture2Text linux port .

And it would be a great credit if y**ou could port it to mac**!?

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/151286359-49fd3d27-961e-4105-916f-c5b69def6be0.png)

capture2text can work seamlessly with goldendict.
I think this way will be ok for now.

**Comment by sikmir** [comment]
Here is original capture2text (CLI only, with some patches) packaged for linux (NixOS or any other distro) and macos: https://github.com/sikmir/nur-packages/blob/7c876e3fb20160781207a8f652fb052647e6da0d/pkgs/misc/capture2text/default.nix

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/blob/branch-qt-5.15/howto/How%20to%20use%20ocr%20together%20with%20GoldenDict.md

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/capture2text   make the Capture2Text GUI work on linux.

**Comment by sikmir** [comment]
I still can't build GUI since it requires `texttospeech` Qt module, that's missing on NixOS.

**Comment by xiaoyifang** [comment]
can nixos install texttospeech module?

**Comment by sikmir** [comment]
I found, that's `qtspeech` package in NixOS that provide texttospeech. Will adopt my package to build GUI.

**Comment by xiaoyifang** [comment]
any luck in NixOS?

**Comment by nonwill** [comment]
> > https://github.com/GSam/Capture2Text linux port .
> 
> And it would be a great credit if **you could port it to mac**!? Seems not a so difficult thing, just do it please.

@xiaoyifang : Any luck?

**Comment by data-man** [comment]
@xiaoyifang [crow-translate](https://github.com/crow-translate/crow-translate) uses [ocr folder](https://github.com/crow-translate/crow-translate/tree/master/src/ocr) Tesseract.
I think it's better choice.

**Comment by nonwill** [comment]
Yes，port or embed [crow-translate](https://github.com/crow-translate/crow-translate) to GoldenDict would be a more better choice！

**Comment by data-man** [comment]
> port or embed [crow-translate](https://github.com/crow-translate/crow-translate)

Instead, I propose to @Shatur to extract the OCR-related code into a separate repository.

**Comment by nonwill** [comment]
> the OCR-related code into a separate repository

Good idea! That does really not need lot of efforts, compared to taking three or four hours to implement a new one(as ++OCR did).

**Comment by xiaoyifang** [comment]
> @xiaoyifang [crow-translate](https://github.com/crow-translate/crow-translate) uses ([ocr folder](https://github.com/crow-translate/crow-translate/tree/master/src/ocr)) Tesseract. I think it's better choice.

that's good .
 Capture2Text also use ocr. I still struggle with the idea to embed ocr into goldendict or use ocr seperately with goldendict.  
I just ported Capture2Text to linux now. which can solve my requirement for now. 
[how to use with ocr](https://github.com/xiaoyifang/goldendict/blob/dev/howto/How%20to%20use%20ocr%20together%20with%20GoldenDict.md)

**Comment by xiaoyifang** [comment]
> > > https://github.com/GSam/Capture2Text linux port .
> > 
> > 
> > And it would be a great credit if **you could port it to mac**!? Seems not a so difficult thing, just do it please.
> 
> @xiaoyifang : Any luck?

Linux is done ,do not have a mac to verify ,I willl leave it to others.

**Comment by nonwill** [comment]
> Linux is done ,do not have a mac to verify ,I willl leave it to others.

This also brings Capture2Text back to life, great and congratulations!
