### ISSUE TITLE
How increase its font size on Linux ?

### ISSUE THREAD

**Issue by abdulbadii** [goldendict/goldendict#1446]
How can Goldendict font size, of any: GUI, content etc, be increased for the one on Linux ?

**Comment by xiaoyifang** [comment]
I think you can use qt-style.css .
following the syntax https://doc.qt.io/qt-5/stylesheet-reference.html
example https://github.com/goldendict/goldendict/wiki/GoldenDict-Dark-Theme
other related issues: https://github.com/goldendict/goldendict/issues?q=is%3Aissue+is%3Aopen+style

**Comment by vedgy** [comment]
GoldenDict's UI follows system settings on GNU/Linux. Use your system settings tool to adjust font sizes. If you are using a GTK-based desktop environment, configure fonts for Qt-based applications in [qt5ct](https://sourceforge.net/projects/qt5ct).

**Comment by abdulbadii** [comment]
Okay, I think it's solved
