### ISSUE TITLE
use clang-format to format new incoming commits

### ISSUE THREAD

**Issue by xiaoyifang** [goldendict/goldendict#1454]
the goldendict has not use a consistency format style.
some files use 4 indentation while others use 2 space indentation
how about to offer an official style format based on clang-format as the link
https://clang.llvm.org/docs/ClangFormatStyleOptions.html
https://clangpowertools.com/clang-format-editor.html

**Comment by xiaoyifang** [comment]
```
# Format Style Options - Created with Clang Power Tools
---
AllowShortFunctionsOnASingleLine: None
AllowShortIfStatementsOnASingleLine: true
BasedOnStyle: LLVM
BinPackParameters: false
BinPackArguments: false
BreakBeforeBraces: Allman
BreakConstructorInitializers: AfterColon
ColumnLimit: 160
ConstructorInitializerAllOnOneLineOrOnePerLine: true
ConstructorInitializerIndentWidth : 2
ContinuationIndentWidth: 2
MaxEmptyLinesToKeep: 2
...
```

I would recommend the above clang format ,which mostly consistent with current goldendict code style.

**Comment by vedgy** [comment]
> the goldendict has not use a consistency format style.

The style is *mostly* consistent, though w/o the automatic formatting, understandably, not perfectly consistent.

Do your proposed options reformat code to:
* `int * x` - middle pointer/reference alignment;
* `int f( bool x )` - space padding inside parentheses?

Run `clang-format` with your config on the entire GoldenDict code base and see if something needs to be adjusted. Then create a PR that adds the `.clang-format` file (and optionally some GitHub integration for new commits/PRs).

**Comment by xiaoyifang** [comment]
> The style is _mostly_ consistent, though w/o the automatic formatting, understandably, not perfectly consistent.

check this method https://github.com/goldendict/goldendict/blob/a35f9a14d0c0b1a752984cebcd1f200b19cca92a/articleview.cc#L2745
indent 4 space .

>Do your proposed options reformat code to:
>
>int * x - middle pointer/reference alignment;
>int f( bool x ) - space padding inside parentheses?

may still need help from others to add new style to perfect the clang-format.

**Comment by xiaoyifang** [comment]
> Note that this PR must not reformat the existing code 

understandable ,only the changed lines need to use the new clang-format style.

**Comment by vedgy** [comment]
Check this online *clang-format* configurator out: https://zed0.co.uk/clang-format-configurator/

**Comment by xiaoyifang** [comment]
I know this website ,the clang-format need someone who is very familar with current code style .to adjust the style option.

**Comment by xiaoyifang** [comment]
```
# Format Style Options - Created with Clang Power Tools
---
AllowShortFunctionsOnASingleLine: None
AllowShortIfStatementsOnASingleLine: true
BasedOnStyle: LLVM
BinPackArguments: false
BinPackParameters: false
BreakBeforeBraces: Allman
BreakConstructorInitializers: AfterColon
ColumnLimit: 160
ConstructorInitializerAllOnOneLineOrOnePerLine: true
ConstructorInitializerIndentWidth : 2
ContinuationIndentWidth: 2
MaxEmptyLinesToKeep: 2
PointerAlignment: Middle
SpacesInAngles: true
SpacesInParentheses: true
...
```

the three line was new added.
```
PointerAlignment: Middle
SpacesInAngles: true
SpacesInParentheses: true
```

**Comment by xiaoyifang** [comment]
https://github.com/goldendict/goldendict/pull/1458
