### ISSUE TITLE
Full text search in Android

### ISSUE THREAD

**Issue by Devamitta** [goldendict/goldendict#1457]
GoldenDict it is the best dictionary base what I ever try. Thank you for maintaining it.

There is a very useful function in GoldenDict on PC - full text search. (Ctrl Shift F)

Is it possible to make this function in Android full golden dictionary application?

Thank you.

**Comment by xiaoyifang** [comment]
does goldendict support android already?

**Comment by darnn** [comment]
They're probably talking about this or some of its offshoots, since it's sold by the original developers of the desktop version (or, at least, is linked on goldendict.org):
http://goldendict.mobi/

**Comment by Devamitta** [comment]
Is it a correct place to give a suggestions for GoldenDict Android app?

**Comment by vedgy** [comment]
> Is it a correct place to give a suggestions for GoldenDict Android app?

Certainly not. This issue tracker is for the free/libre desktop version. Use the email or other means specified in the Android app or its website.
