### ISSUE TITLE
Popup window is too big

### ISSUE THREAD

**Issue by samocite** [goldendict/goldendict#1461]
When I use the hotkey "Ctrl + C + C", the popup window is too big that I can't reach the pin.
Is it possible to modify the popup window size?
![屏幕截图 2022-02-14 120834](https://user-images.githubusercontent.com/57068773/153798700-6cdcb359-c15d-4dfc-8846-2ffeb98fb2fd.png)

**Comment by vedgy** [comment]
1. GoldenDict main menu => Help => Configuration Folder.
2. Locate the file named "config" in the opened directory.
3. Quit GoldenDict.
4. Remove the lines from "config" that start with `<popupWindowState>` and `<popupWindowGeometry>`; save the file.

**Comment by samocite** [comment]
It works! Thank you very much.
