### ISSUE TITLE
Libeb dependency flagged out of date in the Arch User Repository (AUR)

### ISSUE THREAD

**Issue by JimPix1** [goldendict/goldendict#1470]
One of Goldendict's required dependencies is libeb from the AUR and it's been flagged as out of date recently. It's been out of date for months now.
https://aur.archlinux.org/packages/libeb

**Comment by xiaoyifang** [comment]
epwing dictonary use this,seems not much such dictionary and no alternative of libeb
https://github.com/goldendict/goldendict/pull/1344

**Comment by xiaoyifang** [comment]
> Building without Epwing format support
If you have problem building with libeb-dev package, you can pass "CONFIG+=no_epwing_support" to qmake in order to disable Epwing format support

qmake "CONFIG+=no_epwing_support"

**Comment by JimPix1** [comment]
Doing that has let me remove libeb! Thanks
