### ISSUE TITLE
[question] what is the expected behavior when click dictionary in the popup dictionary bar?

### ISSUE THREAD

**Issue by xiaoyifang** [goldendict/goldendict#1475]
![image](https://user-images.githubusercontent.com/105986/159237755-1b7c9dae-05cb-442e-b755-962ea11fb681.png)

in first instinct that it give an impression to navigate through different dictionaries. but actually it behaved the same as mainwindow.

and the dictionaries seems default to the all dictionaries while I think maybe only current group's enabled dictionaries should be there.

any ideas or suggestions?

**Comment by shenlebantongying** [comment]
I think the dropdown beside the search can change group, thus reducing the number of dicts on the vertical popup dictionary bar.

The state of dropdown wills persist during the lifetime of GD. 

![image](https://user-images.githubusercontent.com/20123683/159242889-fc0de066-ab58-48d8-879a-466f27397398.png)

**Comment by xiaoyifang** [comment]
resonable,I think it is the current behavior.

**Comment by shenlebantongying** [comment]
I think an alternative approach as the instinct of yours also makes a lot of sense: 

Show all dict by default:

Click one dict (select) → the popup only show one dict → click again (unselect) → the popup show all dict again.

Pros of this approach:
+ much faster navigation between diets

Cons of this approach:
+ for large groups, someone may only want to narrow to a few dicts (however, create a new group probably solve this problem better?)
+ Impossible to show two dicts at the same time (but if you can just switching around, this doesn't seems necessary?)
+ certainly will break some users' workflow
