### ISSUE TITLE
Can't open in Qt 5.15.4 Linux

### ISSUE THREAD

**Issue by Fince10086** [goldendict/goldendict#1483]
open goldendict and an error occurs below:

goldendict: symbol lookup error: goldendict: undefined symbol: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc, version Qt_5

I use Arch Linux, which updated Qt to 5.15.4+kde+r135-1 yesterday; my Goldendict version is 1.5.0rc2.r508.gf810c6bd-1.

**Comment by nonwill** [comment]
Please give it a try:
https://github.com/xiaoyifang/goldendict
or:
https://www.autoptr.top/gdocr/GoldenDict-OCR-Deployment/

**Comment by nghialm269** [comment]
> open goldendict and an error occurs below:
> 
> goldendict: symbol lookup error: goldendict: undefined symbol: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc, version Qt_5
> 
> I use Arch Linux, which updated Qt to 5.15.4+kde+r135-1 yesterday; my Goldendict version is 1.5.0rc2.r508.gf810c6bd-1.

just compile it again so that it links with the new libraries

**Comment by Fince10086** [comment]
> just compile it again so that it links with the new libraries

problem solved. thank you
