### ISSUE TITLE
recommended default font-size ,13px or 16px?

### ISSUE THREAD

**Issue by xiaoyifang** [goldendict/goldendict#1484]
chrome's default font size is 16px while gd is 13px.   It means when displayed in gd,the font is a little smaller than that when displayed in chrome.
which is better ?
any considerations when try to find a proper font size? 

![image](https://user-images.githubusercontent.com/105986/169176429-2dc729eb-b5aa-42cb-87bc-9eea4e494348.png)

**Comment by xiaoyifang** [comment]
after using zoom function to adjust the font ,each new word search will try to set zoomfactor , due to a webengine bug .
the zoomfactor can not maintain during two successive page loading, the use will experience a page flicker .  (font change from small size to the zoomed size).

**Comment by vedgy** [comment]
Now this is a major issue. You can't hope to select a single font size suitable for everyone. If there is no good workaround for the WebEngine bug, then maybe a GUI option to adjust font size could be added? Or the existing, not working properly, zoom functionality reimplemented in terms of changing the font size?

**Comment by vedgy** [comment]
I just tried to reproduce the zoom issue in my WIP port to Qt WebEngine and couldn't. I search for a new word and the previous zoom factor is used automatically. Both Ctrl+mouse wheel and Ctrl+- work as expected.

**Comment by xiaoyifang** [comment]
> zoom functionality reimplemented in terms of changing the font size?

change font size is a little better , but seems do not work on images(zoomfactor can work on images ).

**Comment by xiaoyifang** [comment]
> I search for a new word and the previous zoom factor is used automatically.

this is great . 

https://bugreports.qt.io/browse/QTBUG-101030 seems qt fixed it in new qt versions.

**Comment by vedgy** [comment]
I am using Qt 5.15.3+kde. Maybe I don't experience the bug because I don't use external websites, and they don't work in my WIP version at all. Zooming works perfectly in local dictionaries and Wikipedia sites.
