### ISSUE TITLE
Arch library incompatibility

### ISSUE THREAD

**Issue by abdulbadii** [goldendict/goldendict#1488]
On latest Arch (actually Artix) it failed to launch:

`goldendict: error while loading shared libraries: libicuuc.so.70: cannot open shared object file: No such file or directory`

this is originated in AUR:  **goldendict-enruen-content**   

How does any experienced one think could solve or mitigate the problem ?

**Comment by vedgy** [comment]
You have to rebuild GoldenDict when *icu* library is updated.

**Comment by nonwill** [comment]
Yes. On latest Arch, icu4c has updated to version 71.

**Comment by steve-chew** [comment]
The way I solved this is that
> rebuild and reinstall qt-webkit
then problem solved!
