### ISSUE TITLE
Provide proper support for Sound Dirs feature in portable version

### ISSUE THREAD

**Issue by Tvangeste** [goldendict/goldendict#150]
Currently, Sound Dirs feature is completely disabled in the portable version.

For a discussion see: http://goldendict.org/forum/viewtopic.php?f=6&t=2054

**Comment by sami-soft** [comment]
> .zips sound packs can be used instead of Sound Dirs.

In the portable version 1.5.0, to use the pronunciation of words, in which path should we copy the zips file?
