### ISSUE TITLE
[feature] zim new namespace from 2021

### ISSUE THREAD

**Issue by xiaoyifang** [goldendict/goldendict#1502]
> Beginning 2021, we change the way we handle namespaces in ZIM file format.
> 
> This is major change in the way we handle entries in libzim and the semantics around but it is not a break in the binary zim format. Old library/readers are compatible with new zim files.
> 
> This page describe the new format. The old format can be found here : [ZIM file format old namespace](https://openzim.org/wiki/ZIM_file_format_old_namespace).

https://openzim.org/wiki/ZIM_file_format

add new support for the new namespace.

PS ,

> these two zim dictionaries:
https://sourceforge.net/projects/telugu-dictionary-zim-file/files/

(from https://github.com/goldendict/goldendict/issues/1472#issuecomment-1086532716)

this zim (old format) seems can not be parsed correctly by goldendict.   after index,there are 40,000+ headwords which most of them can not be opened.   maybe a zim making problem?

**Comment by Abs62** [comment]
>>maybe a zim making problem?

It seems like it. At least pile of resources inside articles namespace is not a sign of good work.
