### ISSUE TITLE
[suggestion] what's the possibility to get rid of Ctrl+C+C

### ISSUE THREAD

**Issue by xiaoyifang** [goldendict/goldendict#1505]
what about to use another approach to achieve the same goal?

eg:
1. set a hotkey , take `F2`(can use other hotkeys) for example, to enable clipboard change tracking (this feature already existed in gd,but can not configured through gui interface).
2.  the normal copy ,translate process. 
users can just use `Ctrl+C` to trigger the popup.(on Linux ,selection can also trigger popup).
3. press F2 to disable clipboard tracking.

pros:
 1. will has little possibility to mess with System's Copy function  ( Ctrl+C )
 2. on most cases,if users have to translate  many times,   save the total   number of keystrokes

**Comment by vedgy** [comment]
There was a related discussion in comments under #998. Particularly relevant:
> A least under Windows scan popup should not be used without key modifiers (in my opinion) because it used some hack metod to determine word under mouse cursor which potentially can conflict with other programs. I don't want to add any options to relieve work without modifiers.

**Comment by xiaoyifang** [comment]
> A least under Windows scan popup should not be used without key modifiers

on Windows ,keystrokes is still used ,the stroke is `Ctrl+C`  . gd just does not need to register `Ctrl+C` as the global hot key

**Comment by vedgy** [comment]
What do you mean by "keystrokes"? "key modifiers" refers to the *Only show popup when all selected keys are kept pressed* checkbox on the Scan Popup tab of GoldenDict's preferences. So the maintainer believes that this checkbox and at least one key modifier checkbox underneath should be checked on most Windows systems.

Well, if the *Ctrl* checkbox is checked, then Ctrl+C would indeed translate the word without any additional modifiers.

**Comment by xiaoyifang** [comment]
I got your idea.

But I'm talking about this
![image](https://user-images.githubusercontent.com/105986/171629189-7d22b562-5436-4022-a11f-b419688b363b.png)

**Comment by vedgy** [comment]
> But I'm talking about this

I understood that from the beginning.

Anyway, the use of `trackClipboardChanges` is discouraged on Windows. IIRC, the option was added back hidden because of user requests, even though developers thought it should not be used. Doesn't mouse-over work for you?

I doubt anyone else is going to implement this feature request. So, if this important to you, scratch your own itch.

**Comment by xiaoyifang** [comment]
The main reason I want to do this  is that the `CTRL+C` occassionally messed with System's own Copy function.

**Comment by vedgy** [comment]
In future, please reference the motivating issue by its number in a related issue description. The "pros" like this are difficult to understand without context:
> will has little possibility to mess with System's Copy function ( Ctrl+C )
