### ISSUE TITLE
Chinese Conversion doesn't work

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [goldendict/goldendict#1512]
I'm using an early access build, **1.5.0-RC2-372-gc3ff15f**, from https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows

I checked the "Chinese Conversion" in Menu Edit -> Dictionaries... -> Sources -> Transliteration, but it doesn't seem to do anything.
Precisely, I have a Chinese dictionary that consists only Simplified Characters, I expect that the "Chinese Conversion" would convert word input from Traditional to Simplified and search for both, means that if I enter 國, GoldenDict would search for both 國 and 国.
The "Japanese Romaji" works fine, so I think this is a bug.

**Comment by wildekat** [comment]
I use Chinese conversion on a daily basis, it works like a charm for me. What this option does under the hood is create a number of tiny pseudo-dictionaries (e.g. "Traditional to simplified" or "Simplified to traditional (Taiwan)"), so make sure those are actually present in the group where your Chinese dictionaries are.
Also, you might want to try a more recent version of GoldenDict: [1.5.0-RC2-522 (exe-only)](https://www.mediafire.com/file/z3yalyatc8hxc5j/goldendict-1.5.0-RC2-522-g10d0d819%2528EXE_only%2529.7z/file)

**Comment by Meigyoku-Thmn** [comment]
> I use Chinese conversion on a daily basis, it works like a charm for me. What this option does under the hood is create a number of tiny pseudo-dictionaries (e.g. "Traditional to simplified" or "Simplified to traditional (Taiwan)"), so make sure those are actually present in the group where your Chinese dictionaries are.

Can you show me where is the source of this exe, to be sure?

**Comment by wildekat** [comment]
The only source I know is the semi-official [GoldenDict forum](http://forum.ru-board.com/topic.cgi?forum=5&topic=49149&glp#lt). That's where the updates are posted by the project maintainer (the link I gave you can be found at the top of the page).

**Comment by wildekat** [comment]
By the way, here's what I get when I look up 國語 or 国语:

![guoyu](https://user-images.githubusercontent.com/1102981/173023552-5a3b1bec-86b0-447f-8d26-d823da482350.png)

**Comment by Meigyoku-Thmn** [comment]
I tried the [Qt 5.12.3](https://sourceforge.net/projects/goldendict/files/early%20access%20builds/Qt5-based/GoldenDict-1.5.0-RC2-372-gc3ff15f_%28QT_5123%29.7z/download) version of 1.5.0-RC2-372-gc3ff15f, still the same issue. I also copied the latest exe from your link to GoldenDict directory and it doesn't change anything. I'm using a Chinese-Vietnamese dictionary that I extracted from a software by myself.

Looking up with 國語 (The font looks somewhat broken with Qt 5 version as well):
![DRvuSZnMoo](https://user-images.githubusercontent.com/16047808/173229399-64867517-2a27-4be1-8b78-bedf18398baa.png)
Looking up with 国语, this works of course:
![V0EevPv09B](https://user-images.githubusercontent.com/16047808/173229429-acb4f3a5-e4d2-435b-b7d8-1c5bbd755780.png)

**Comment by Meigyoku-Thmn** [comment]
Turn out I really misunderstood this feature, it just as [wildekat](https://github.com/wildekat) said, I have to add those "pseudo-dictionaries" into my groups.

**Comment by wildekat** [comment]
Glad it worked for you.
You can easily adjust the font by putting something like this into your qt-style.css:
```
MainWindow #searchPane #translateLine[currentGroup="Lạc Việt"],
MainWindow #searchPane #wordList[currentGroup="Lạc Việt"],
MainWindow #translateLine[currentGroup="Lạc Việt"]
{
    font-family: "Kaiti";
    font-size: 20px;
}
```
