### ISSUE TITLE
help. why lock when read the article?

### ISSUE THREAD

**Issue by xiaoyifang** [goldendict/goldendict#1516]
https://github.com/goldendict/goldendict/blob/10d0d8193b60b8ac5f06973742fdd0fbb1de6a2d/zim.cc#L824

There are also many of such locks in the code.
I can understand that it is necessary to lock it when writing is taking place. But why lock the code when reading?
Is there any chance that the article (to be read) is going to change?

**Comment by Abs62** [comment]
Article can't change. But readArticle() function is not thread-safe because file read position can be changed while calling from other thread.

**Comment by xiaoyifang** [comment]
Thanks .
