### ISSUE TITLE
[Issue] Can't access official site for downloading installer

### ISSUE THREAD

**Issue by Hanjingxue-Boling** [goldendict/goldendict#1535]
In the past few days, I found that I couldn't open the official website of goldendict to download the installation package, and the browser displayed a webpage error.

 more info

https://ibb.co/gWSSGjs

https://tcp.ping.pe/www.goldendict.org:80

**Comment by nonwill** [comment]
If you don't mind the source, you can in fact find several different _**recent & latest**_ releases, which are commercial, private and semi-open or fully open to users, from the following links：
https://github.com/goldendict/goldendict/issues/1424
https://github.com/goldendict/goldendict/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+new
http://forum.ru-board.com/topic.cgi?forum=5&topic=49149&start=3020
And the last one maintained by Abs62 is probably the official build you need.
