### ISSUE TITLE
any plans to port goldendict to mobile such as android ?

### ISSUE THREAD

**Issue by xiaoyifang** [goldendict/goldendict#1539]
as title.

the App version may not have all these features offered by PC version.

**Comment by vedgy** [comment]
The original author has implemented an Android version from the beginning: http://goldendict.mobi/

The original Android version is proprietary and seems to be still more or less supported: https://play.google.com/store/apps/details?id=mobi.goldendict.android&hl=en&gl=US

I don't think anyone has plans to port the free GoldenDict version to Android.

**Comment by loyukfai** [comment]
The existing Android client works but there is a problem now that on some webpages, when you copy from them some text, they attach (by Javascript, I suppose) some copyright or link info to the copied text, so when they're push to GoldenDict, you need to erase those annoying things yourself.

Normally, you can just select, and click share, then choose GoldenDict.

Cheers.
