### ISSUE TITLE
No pronounciation since "the referenced source failed to download"

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [goldendict/goldendict#1544]
Hello, 

I installed goldendict on linux opensuse, from official opensuse repo
I've tried both festival and espeak, making them the default audio program, goldendict can never 'speak', only showing me:
"Warning: the referenced source failed to download" in the bottom. What is this error about?

I just transitioned from stardict to goldendict, and stardict could pronounce fine.

**Comment by vedgy** [comment]
GoldenDict cannot find the audio file for some reason. festival and espeak are not needed at all. And in the case of this warning an audio program hasn't been reached, because the audio resource could not be found. Upload or post a link to your dictionary, perhaps?

**Comment by GreatBigWhiteWorld** [comment]
> GoldenDict cannot find the audio file for some reason. festival and espeak are not needed at all. And in the case of this warning an audio program hasn't been reached, because the audio resource could not be found. Upload or post a link to your dictionary, perhaps?

Must I have audio files in the "Dictionaries -> Sources -> Sound Dirs" to make it work? It's empty now, after I tried to put the path of stardict audio files path there and it couldn't work, which was in the format:

```
/usr/share/stardict/WyabdcRealPeopleTTS/a/abacus.wav
..............
/.................................................................../b/back.wav
..............
```
I put the path as 
`/usr/share/stardict/WyabdcRealPeopleTTS/` in Goldendict's 'Sound Dirs' but it didn't work so I deleted the path in 'Sound Dirs', which is empty now.

As for festival or espeak, I thought it's independent of sound files since they are text-to-speech tools...I remember for stardict, if I didn't install the WyabdcRealPeopleTTS package, stardict would use festival to pronounce the word with a robotic voice.
Say if I don't have audio files, can goldendict still pronounce with robotic voice?
Many thanks for the reply.

**Comment by vedgy** [comment]
It appears that GoldenDict's TTS support is limited to Windows and macOS: https://github.com/goldendict/goldendict/blob/1064880450a648696dfabdf698fdbeec095604e1/articleview.cc#L1475-L1479 https://github.com/goldendict/goldendict/blob/1064880450a648696dfabdf698fdbeec095604e1/goldendict.pro#L517-L518

Sorry, I don't know how to make the audio files work. Search for "sound dirs" in this repository. Here is one relevant discussion: #1413.

**Comment by GreatBigWhiteWorld** [comment]
Hi, thanks for the explanation. What a pity that goldendict TTS doesn't support linux, as an open source project in the first place...
Your link is also helpful. I guess I know what to do now.

**Comment by GreatBigWhiteWorld** [comment]
> > goldendict TTS doesn't support linux
> 
> Seems that flite is available on Manjaro, but it's just need a fully test... ![20220829171235](https://user-images.githubusercontent.com/46510529/187167452-f4464fec-8516-4c9c-93eb-c929fd777b0c.png)

Is that a plugin? I don't have the tab you have. I have 3 tabs on top (you have 4), and I don't have "语音合成“either。

**Comment by nonwill** [comment]
> Is that a plugin? I don't have the tab you have.

Yes, using QTextToSpeech and with flite fully installed, tts is available on Linux too。
The forth tab and extra plugins(osx dictionary\tts\ocr\audio\\...) support are from my private build valued by [GoldenDict++OCR](https://www.autoptr.top/gdocr/GoldenDict-OCR-Changelog/)：
[![](https://z3.ax1x.com/2021/04/25/czQaN9.gif)](https://www.autoptr.top/gdocr/GoldenDict-OCR-Deployment/)

**Comment by vedgy** [comment]
I recommend everyone to stay away from illegal proprietary @nonwill's fork, which may contain spyware/malware. See #1424.

TTS works on GNU/Linux like this: open Dictionaries dialog, switch to Sources tab, inside it - to Programs tab. Add a program with Type=Audio, enable it. Set Command Line to e.g. `espeak "%GDWORD%"`. Then add the newly "created" dictionary to your group(s).

Though I don't see much value in the TTS for learning. The "robotic" pronunciation is often incorrect. Guess could be useful to people with disabilities.

**Comment by GreatBigWhiteWorld** [comment]
> I recommend everyone to stay away from illegal proprietary @nonwill's fork, which may contain spyware/malware. See #1424.
> 
> TTS works on GNU/Linux like this: open Dictionaries dialog, switch to Sources tab, inside it - to Programs tab. Add a program with Type=Audio, enable it. Set Command Line to e.g. `espeak "%GDWORD%"`. Then add the newly "created" dictionary to your group(s).
> 
> Though I don't see much value in the TTS for learning. The "robotic" pronunciation is often incorrect. Guess could be useful to people with disabilities.
Thank you for the heads-up.

**Comment by Immunize2** [comment]
> > > goldendict TTS doesn't support linux
> > 
> > 
> > Seems that flite is available on Manjaro, but it's just need a fully test... ![20220829171235](https://user-images.githubusercontent.com/46510529/187167452-f4464fec-8516-4c9c-93eb-c929fd777b0c.png)
> 
> Is that a plugin? I don't have the tab you have. I have 3 tabs on top (you have 4), and I don't have "语音合成“either。

dirty @nonwill is a malware developer who added tracking + malicious features and also blocks access to certain websites in his illegal fork. 

Today it was discovered a new malicious behaviour:
https://forum.freemdict.com/t/topic/15870

**Comment by darnn** [comment]
That is simply not true, it works fine in GD++ for me:
![gd apple](https://user-images.githubusercontent.com/19672444/193398025-3a019010-2ff7-4749-a54a-5bff6f57d10d.png)

**Comment by rgabiabdo** [comment]
All those answers are **irrelevant**, the answer is **simple**, Goldendict windows and *.lsd files are not good budies, so all you have to do is to unpack them with lsd2dsl and to save space to compress dsl files to dsl.dz with dzip.
look for dzip.exe and put it in system then use cmd prompt to do that in windows.
that's it.
then enjoy audio and don't forget to do istighfar for me and my father if you're a muslim and if that helped you
