### ISSUE TITLE
Change program settings folder

### ISSUE THREAD

**Issue by sami-soft** [goldendict/goldendict#1545]
Hello good time
After scanning dictionaries in both the installed and portable versions, goldendict program saves index file and other settings in the following folder:

C:\Users\ <USER_NAME> \AppData\Roaming\GoldenDict

Is it possible to change the path of this folder? 
It will be great if we can specify this folder in the software settings.
In fact, my goal is to run the portable version without being indexed again in all systems.

**Comment by vedgy** [comment]
The current GoldenDict code clearly saves the index file (and most likely everything else too) within the portable directory. Something must be wrong with your portable version. Where have you downloaded it or what sources have you built it from?

**Comment by sami-soft** [comment]
> The current GoldenDict code clearly saves the index file (and most likely everything else too) within the portable directory. Something must be wrong with your portable version. Where have you downloaded it or what sources have you built it from?

im download portable version "GoldenDict-1.5-RC2-372-gc3ff15f_(QT_5123)" from this link :

https://sourceforge.net/projects/goldendict/files/early%20access%20builds/GoldenDict-1.5.0-RC2-372-gc3ff15f_%28QT_486%29.zip/download

I put the dictionaries file in the content folder  and when running, it saved the settings in the same address as above

**Comment by sami-soft** [comment]
Now I downloaded the 1.0.1 version

https://netix.dl.sourceforge.net/project/goldendict/goldendict/1.0/GoldenDict-1.0.1-Portable.zip

 it saved the settings in its GoldenDict\portable folder and there is no problem. So the problem is from version 1.5

**Comment by vedgy** [comment]
Why do you believe this is a portable version?
Creating a directory named "portable" alongside GoldenDict.exe should make it portable.

**Comment by sami-soft** [comment]
> > https://sourceforge.net/projects/goldendict/files/early%20access%20builds/GoldenDict-1.5.0-RC2-372-gc3ff15f_%28QT_486%29.zip/download
> 
> Why do you believe this is a portable version? Creating a directory named "portable" alongside GoldenDict.exe should make it portable.

Thanks, the problem was solved by creating the "portable" folder manually.

**Comment by vedgy** [comment]
You are welcome.
Please close this issue then.
