### ISSUE TITLE
failed to clone when trying to compile

### ISSUE THREAD

**Issue by noideahowmuch** [goldendict/goldendict#1546]
I tried to build it from the source at a macbookpro M1. Then I followed the instruction here, puting git clone into the terminal bar then I get stucke. A while later I get the timed out message. Can anyone help me with this? Thank you.

192:~ LF$ git clone git://github.com/goldendict/goldendict.git
Cloning into 'goldendict'...
fatal: unable to connect to github.com:
github.com[0: 20.205.243.166]: errno=Operation timed out

**Comment by noideahowmuch** [comment]
> `git clone https://github.com/goldendict/goldendict.git`
> 
> or download the source zip directly ![image](https://user-images.githubusercontent.com/105986/188039048-5515c1a4-cce6-403a-906d-3239d5c88173.png)

thanks

**Comment by vedgy** [comment]
A pull request that updates the clone URL in the README can close this issue.
