### ISSUE TITLE
the popup window not disappearing

### ISSUE THREAD

**Issue by noideahowmuch** [goldendict/goldendict#1547]
I have a problem with the goldenDict interface on Mac.

When I look up words using hot keys the pop-up window appears, but it stays too long even if I move my cursor out of it. It's like it's stuck on my screen not disappearing in time.

<img width="459" alt="image" src="https://user-images.githubusercontent.com/112666380/188404556-5e843c46-26d8-4f94-8c5d-f54333db1f5b.png">

**Comment by xiaoyifang** [comment]
![image](https://user-images.githubusercontent.com/105986/188425800-165bb60c-e263-4dd4-a094-8f855a1b837e.png)
uncheck this button.

**Comment by noideahowmuch** [comment]
thanks
