### ISSUE TITLE
cant use persian tts in goldenDict

### ISSUE THREAD

**Issue by sami-soft** [goldendict/goldendict#1555]
I used the Persian sounds in eSpeak in the Golden program, but unfortunately, the Golden program cannot properly pronounce the Persian text.

"C:\Program Files (x86)\eSpeak\command_line\espeak.exe" -v mb-ir1 %GDWORD%

![2022-09-18_183112](https://user-images.githubusercontent.com/37217976/190911021-1f0ccb7c-cf77-425a-a14f-e6a1220aa39f.jpg)

There is no problem with English words and pronounces them correctly.

**Comment by vedgy** [comment]
Did you try to pronounce the same Persian word from the command line, bypassing GoldenDict?

**Comment by sami-soft** [comment]
> 

Thanks, yes, there is also a problem in the command line, so this problem is from eSpeak

**Comment by vedgy** [comment]
Maybe Persian language data files are missing on your system? You can check with the `espeak --voices` command. If you can't figure it out, log an issue on espeak bug tracker.

In any case, please close this issue.

**Comment by sami-soft** [comment]
> Maybe Persian language data files are missing on your system? You can check with the `espeak --voices` command. If you can't figure it out, log an issue on espeak bug tracker.
> 
> In any case, please close this issue.

The Persian pronunciation file is properly installed and active. Because if it was not active, the following command would not be executed correctly:

espeak.exe -v mb-ir1 =

Now it correctly pronounces the = character in Farsi, but it does not pronounce the Persian word

**Comment by vedgy** [comment]
An encoding issue perhaps? Try changing an encoding in the terminal application you are using.

Take a look at the hint at the bottom of the *Websites* tab in GoldenDict's Dictionaries=>Sources. Perhaps the various encoding placeholders would work in the *Programs* tab as well.

**Comment by vedgy** [comment]
Closing, because if this is a bug, then it is most likely a bug in an external program *espeak*, not GoldenDict.
