### ISSUE TITLE
Unable to add stardict files to goldendict on android

### ISSUE THREAD

**Issue by raviparimi** [goldendict/goldendict#1558]
I'm running Android version 12 on a samsung S7 FE tablet and purchased golden dict. I am trying to get goldendict ingest a few sanskrit dictionaries in stardict format but cannot get it working. The stardict files have been downloaded from https://drive.google.com/file/d/0B2aB-UqlZUk4YkxXYmdYTkZfdm8/view?pli=1&resourcekey=0-pkMARsZFWNrU63MbhA6dWA and this link is obtained from https://arshadrishti.org/golden-dictionary-installation/

The startup screen says "Place your dictionary files on the SD card in the GoldenDict folder". I extracted individual dictionary tarballs and placed them under the GoldenDict folder in my the SD card.
![Screenshot_20220928-101020_My Files](https://user-images.githubusercontent.com/8029143/193194588-0e9cc2bc-f530-4b5f-873f-35acaf6092b3.jpg)

The folder GoldenDict --> Apte has sub-folders as well:

![Screenshot_20220928-102839_My Files](https://user-images.githubusercontent.com/8029143/193194675-0283177a-45fd-4db3-9588-7d6fa1b4feaf.jpg)

![Screenshot_20220928-102847_My Files](https://user-images.githubusercontent.com/8029143/193194710-2468e60d-e089-421e-a8bd-b61527c36ec1.jpg)

Does goldendict recursively search these folders? When I launch the app, I see the same startup message (below) and that tells me that goldendict failed to read files/folders from the SD card's GoldenDict folder.
![startup](https://user-images.githubusercontent.com/8029143/193194883-31c460b6-35ce-481c-a3d5-2a77652a5aa8.jpg)

Prior to this, I placed .tar.gz files each of the stardict dictionaries under SD card's GoldenDict folder but that didn't work either.

Is there a page that describes, in detail, how to install these dictionaries perhaps with screenshots?

**Comment by wildekat** [comment]
This bugtracker is for the desktop version of GoldenDict only; [GoldenDict Mobile](http://goldendict.mobi/) is an entirely different project, so this issue does not belong here (that said, it sounds more like a general issue with permissions on Android 12, I don't even think this is specific to stardict).
Please close this ticket.

**Comment by Immunize2** [comment]
GoldenDict Android is closed-source software (=garbage). It has been abandoned for a long time. Do not expect anything from that app.

Closed-source software is a plague on this world ! Please close this issue.

--------------

Another example of Goldendict-closed source software is the illegal fork GD++ by @nonwill. Garbage !!!

**Comment by Immunize2** [comment]
> I'm running Android version 12 on a samsung S7 FE tablet and purchased golden dict. I am trying to get goldendict ingest a few sanskrit dictionaries in stardict format but cannot get it working. The stardict files have been downloaded from https://drive.google.com/file/d/0B2aB-UqlZUk4YkxXYmdYTkZfdm8/view?pli=1&resourcekey=0-pkMARsZFWNrU63MbhA6dWA and this link is obtained from https://arshadrishti.org/golden-dictionary-installation/
> 
> The startup screen says "Place your dictionary files on the SD card in the GoldenDict folder". I extracted individual dictionary tarballs and placed them under the GoldenDict folder in my the SD card. ![Screenshot_20220928-101020_My Files](https://user-images.githubusercontent.com/8029143/193194588-0e9cc2bc-f530-4b5f-873f-35acaf6092b3.jpg)
> 
> The folder GoldenDict --> Apte has sub-folders as well:
> 
> ![Screenshot_20220928-102839_My Files](https://user-images.githubusercontent.com/8029143/193194675-0283177a-45fd-4db3-9588-7d6fa1b4feaf.jpg)
> 
> ![Screenshot_20220928-102847_My Files](https://user-images.githubusercontent.com/8029143/193194710-2468e60d-e089-421e-a8bd-b61527c36ec1.jpg)
> 
> Does goldendict recursively search these folders? When I launch the app, I see the same startup message (below) and that tells me that goldendict failed to read files/folders from the SD card's GoldenDict folder. ![startup](https://user-images.githubusercontent.com/8029143/193194883-31c460b6-35ce-481c-a3d5-2a77652a5aa8.jpg)
> 
> Prior to this, I placed .tar.gz files each of the stardict dictionaries under SD card's GoldenDict folder but that didn't work either.
> 
> Is there a page that describes, in detail, how to install these dictionaries perhaps with screenshots?

Delete the official app that you paid for. Instead, use the modded GoldenDict app that you can find in the Telegram group>

https://t.me/goldendict_chat

With the app 2.1.40 in the Telegram group, you can solve the problem !

**Comment by nonwill** [comment]
> GoldenDict Android is closed-source software (=garbage). It has been abandoned for a long time. Do not expect anything from that app.
> 
> Closed-source software is a plague on this world ! Please close this issue.
> 
> Another example of Goldendict-closed source software is the illegal fork GD++ by @nonwill. Garbage !!!

https://github.com/goldendict/goldendict/issues/1424#issuecomment-1264279067
