### ISSUE TITLE
What actually git: the scheme of protocol as is not working

### ISSUE THREAD

**Issue by abdulbadii** [goldendict/goldendict#1561]
What actually **git:** the scheme of protocol, it cannot get working (in mine, may be stiil working on else)
but does and  always work is http or https:
`
https://github.com/goldendict/goldendict.git`

if needed update/edit the readme.md written with git: to be replaced with https:

**Comment by vedgy** [comment]
Yes. Here is what I get on my Manjaro GNU/Linux system:
```bash
$ git clone git://github.com/goldendict/goldendict.git
Cloning into 'goldendict'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Connection timed out

128✗
```

A pull request that fixes the README is welcome.
