### ISSUE TITLE
Arch Linux build can't proceed had error of missing file

### ISSUE THREAD

**Issue by abdulbadii** [goldendict/goldendict#1562]
Try to build on Arch Linux but had interruption:

```
In file included from scanpopup.hh:8,
                 from mainwindow.hh:21,
                 from main.cc:7:
articleview.hh:7:10: fatal error: QWebView: No such file or directory
    7 | #include <QWebView>

```

while `qmake-qt4` has succesfully created a makefile

if using qt5:
```

qmake-qt5 && make
build/ui_mainwindow.h:13:10: fatal error: QtGui/QAction: No such file or directory
   13 | #include <QtGui/QAction>

```
Interrupted too wih different error.. , please help solve this out.

**Comment by vedgy** [comment]
1. The *qtwebkit* package is required to build with Qt 4.
2. Something is wrong with your Qt 5 configuration. Do you build against latest official Arch Linux repository packages? Also, if you built over the previous qt4 attempt, run `git clean -xdf` first. WARNING: this `git clean` command removes all untracked files, so if you have anything important in the repository, back it up first.
