### ISSUE TITLE
How: WARNING: Audio player ao_open_live() failed: Cannot

### ISSUE THREAD

**Issue by abdulbadii** [goldendict/goldendict#1564]
Anyone kind enough help me solve
`
WARNING: Audio player ao_open_live() failed: Cannot open the device: alsa channel: 1`

and how to have device option, not constrained to one kind, here alsa
Please help this for golden dictionary the latest, ie. built of git on Arch linux
Thanks before

**Comment by vedgy** [comment]
Use the Qt Multimedia backend or an external player such as `mpv`.

**Comment by vedgy** [comment]
Try the workaround proposed in comments on #412. If the workaround works, please close this issue as a duplicate.

**Comment by abdulbadii** [comment]
OK
