### ISSUE TITLE
gdWarning() and gdDebug() are not thread-safe when logging to file is enabled

### ISSUE THREAD

**Issue by vedgy** [goldendict/goldendict#1587]
[`QTextCodec::setCodecForLocale()`](https://doc.qt.io/qt-5/qtextcodec.html#setCodecForLocale) is not [reentrant](https://doc.qt.io/qt-5/threads-reentrancy.html). Even if it was reentrant, the `gd*` functions would still not be thread-safe. For example, one call to `gd(Warning|Debug)` sets the UTF8 codec; then another call stores the UTF8 codec in the local variable `localeCodec`; then the first call restores the original codec; then the second call "restores" the UTF8 codec.

https://github.com/goldendict/goldendict/blob/3aaaf15e0a8a292a06ffaaeddcf4dd87bef5c93a/gddebug.cc#L15-L31

Should a global mutex be locked if logging to file is enabled?

One more potential issue: `QTextCodec::codecForLocale()` is called in several other places. A replacement UTF8 codec could be obtained in those places unless a wrapper for this function is added, which locks the global mutex if logging to file is enabled.

**Comment by shenlebantongying** [comment]
What's stopping us from replacing gdWarning and gdDebug entirely with QWarning or QDebug?

**Comment by vedgy** [comment]
> What's stopping us from converting all gdWarning and gdDebug entirely with QWarning or QDebug?

Do `qWarning()` and `qDebug()` support logging to file on Windows? Since which Qt version?

**Comment by shenlebantongying** [comment]
I think this is the original commit that added gdDebug()

https://github.com/goldendict/goldendict/commit/444938a330c1693725a8b504afedd624dc57261d

I think a better solution is making a message handler that custom qDebug() so that when logging into a file, the messages are always guaranteed to be utf-8.

https://doc.qt.io/qt-5/qtglobal.html#qInstallMessageHandler

It also solves the previous issue https://github.com/goldendict/goldendict/issues/1575 , since there are 5 types of messages built-in with Qt.

**Comment by vedgy** [comment]
[`qInstallMessageHandler()`](https://doc.qt.io/qt-5/qtglobal.html#qInstallMessageHandler) is already used in *main.cc*. @Abs62 can probably explain why the workaround could not be contained in `gdMessageHandler()`.

There is also the `QString().vsprintf( msg, ap ).toUtf8().data()` part, which runs even if logging to a file is disabled. I wonder if it is useful or only wastes CPU time in that case.

**Comment by vedgy** [comment]
> There is also the QString().vsprintf( msg, ap ).toUtf8().data() part, which runs even if logging to a file is disabled. I wonder if it is useful or only wastes CPU time in that case.

Probably just a waste. Unfortunately, a `va_list` cannot be passed to `qWarning()` and `qDebug()` directly. So getting rid of the waste requires dropping the `gdWarning()` and `gdDebug()` wrappers entirely.
