### ISSUE TITLE
Error `libtiff.so.5: cannot open` on the start of goldendict-git

### ISSUE THREAD

**Issue by kpspu** [goldendict/goldendict#1598]
Having an error on the start of `goldendict-git` (1:1.5.0rc2.r582.g9a5e1e89-1)

```

$ goldendict
goldendict: error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such file or directory

```

**Comment by vedgy** [comment]
Please rebuild GoldenDict against the updated *libtiff* version and close this issue.

**Comment by kpspu** [comment]
Yes, you are right. Rebuilding the GoldenDict solved this issue. Sorry for taking your time.
