### ISSUE TITLE
Request support for the latest XDXF standard revision 34

### ISSUE THREAD

**Issue by ryanlo713** [goldendict/goldendict#1600]
[here](https://github.com/soshial/xdxf_makedict/tree/master/format_standard) for the latest standard

There is no longer a distinction between logical vs. visual since rev. 34 format is semantic-only and cannot store any presentational or visual data

However, GoldenDict cannot render the XDXF dictionary based on the new standard when `xdxf` tag has no `format="logical"` attribute.

![image](https://user-images.githubusercontent.com/12672523/213298215-273f5775-cf0f-4499-9815-0d921feafd46.png)

When with `format="logical"`:

![image](https://user-images.githubusercontent.com/12672523/213299381-3e6dd1e3-3c04-4246-937c-26abece5bcee.png)

When without `format="logical"`:

![image](https://user-images.githubusercontent.com/12672523/213299823-f8223e36-b717-47e6-95c4-a62c8d219612.png)

--------

Another problem is about the language markup. If the `xdxf` tag has no `lang_from="..." lang_to="..." ` attributes, GoldenDict does not recognize the language of the dictionary correctly:

![image](https://user-images.githubusercontent.com/12672523/213301151-25da5326-b4f6-4247-a65c-2a484b9f984f.png)

In the latest XDXF specification, its multi-language markup method can be found in [this example](https://github.com/soshial/xdxf_makedict/blob/master/dict_samples/dictionary_one-to-many_languages_rev34.xml).

**Comment by Abs62** [comment]
Done.
