### ISSUE TITLE
wikipedia redesign makes current parser miss TOC, etc

### ISSUE THREAD

**Issue by 429IhD0** [goldendict/goldendict#1601]
Recently Wikipedia has redesigned its interface:
https://wikimediafoundation.org/wikipedia-desktop/

I believe that, as a result, the current mediawiki.cc parser is missing certain DOM nodes which it previously didn't miss, such as the node containing the table of contents.

Is there an easy way to update the code so wikipedia TOC can appear in GoldenDict again?

**Comment by vedgy** [comment]
Just tried to fix this. But couldn't get a hold of the TOC. Couldn't find relevant API documentation either. The only TOC-related code GoldenDict receives is:
```xml
<meta property="mw:PageProp/toc" />
...
Complications: [vary‐revision‐sha1, show‐toc]
```

Passing the `disabletoc` parameter documented in the [Wikipedia API documentation](https://en.wikipedia.org/w/api.php?action=help&modules=parse) only removes the line `<meta property="mw:PageProp/toc" />`.

**Comment by 429IhD0** [comment]
I wonder if changing this line
`QUrl reqUrl( url + "/api.php?action=parse&prop=text|revid&format=xml&redirects" );`
to
`QUrl reqUrl( url + "/api.php?action=parse&prop=text|revid|sections&format=xml&redirects" );`
would do the trick (I base this on the 1st answer on https://stackoverflow.com/questions/29943369/getting-a-table-of-content-from-wikipedia-via-api).

However it looks like it would return a _structured_ TOC as the value of parse.sections. Which may require some work to embed it into the html ... although, since html anchors are provided, hopefully not too much work ...

Here's an sample toc item object:
```
 {
                "toclevel": 1,
                "level": "2",
                "line": "Gemeinschaftsproduktionen",
                "number": "1",
                "index": "1",
                "fromtitle": "Liste_der_Tatort-Folgen",
                "byteoffset": 176,
                "anchor": "Gemeinschaftsproduktionen",
                "linkAnchor": "Gemeinschaftsproduktionen"
  },
```

**Comment by vedgy** [comment]
That should work. Do you know whether and where the attributes are documented. For example, the values of `anchor` and `linkAnchor` are always equal. What's the difference between them?

**Comment by vedgy** [comment]
Found no documentation. But [this commit message](https://gerrit.wikimedia.org/r/c/mediawiki/core/+/831147/) suggests that `linkAnchor` should be used as the value of the `href` attribute of an `<a>` tag.

**Comment by vedgy** [comment]
`level` appears to always equal `toclevel + 1`. But if that were the case, why send both values? Which of them should GoldenDict use? Is one of them deprecated?

**Comment by 429IhD0** [comment]
On the other hand ... I found this on mediawiki.org but not sure if the explanations it give are relevant/correct...

![image](https://user-images.githubusercontent.com/28206448/216589440-8c6e5378-dcf0-4ad2-a1e0-248f4035dcca.png)

(https://www.mediawiki.org/wiki/Manual:SkinMustache.php)

**Comment by vedgy** [comment]
Thanks for the research. Since `toclevel` also more naturally starts with `1`, I'm going to use it for now. Could easily switch to `level` if some issue crops up.
