### ISSUE TITLE
Free mdict has a killer feature that paid golden doesn't 

### ISSUE THREAD

**Issue by o28o** [goldendict/goldendict#1604]
Hi there. Thank you for the app. I've installed it. Bought paid version and use it ~10 times less then free mdict because of one feature.

Please implement dictionary lookup from the Android context menu (long tap on the word)

As on this example.
![Screenshot_20230212_211529_Chrome Dev.jpg](https://user-images.githubusercontent.com/90468182/218353572-af14de5b-b2f4-4f47-a7c7-e26d63e97c79.jpg)

Same screenshot In dropbox https://www.dropbox.com/s/5p7715qcobonim3/Screenshot_20230212_211529_Chrome%20Dev.jpg?dl=0

**Comment by jhossettstalinn** [comment]
We need some upgrade for paid goldendict on Android! Please

**Comment by srghma** [comment]
Goldendict for pc (open-source ) and goldendict (closed source, if I am not wrong creator used the goldendict for pc code) for android are different projects

**Comment by Memory383** [comment]
The modded version of GoldenDict Android has the feature that you are looking for. It is totally FREE:

https://cloud.freemdict.com/index.php/s/N9EMLkafyjsc5Hy

Dictionaries for GoldenDict are available here:
https://downloads.freemdict.com/

**Comment by o28o** [comment]
> The modded version of GoldenDict Android has the feature that you are looking for. It is totally FREE:
> 
> https://cloud.freemdict.com/index.php/s/N9EMLkafyjsc5Hy
> 
> Dictionaries for GoldenDict are available here:
> https://forum.freemdict.com/t/topic/12050

Thank you @Memory383 that's exactly what is missing on the paid version.
