### ISSUE TITLE
Problem displaying my site's dictionary in goldendict.

### ISSUE THREAD

**Issue by iakesi** [goldendict/goldendict#1607]
What did I do wrong? Does it need to be some specific formatting?
Goldendict has its own will when it comes to showing, sometimes it shows sometimes it doesn't show the dictionaries of the site below.

[http://ultrafile.elementfx.com/?dicionario=priberam&palavra=você](http://ultrafile.elementfx.com/?dicionario=priberam&palavra=você)
[http://ultrafile.elementfx.com/?dicionario=michaelis&palavra=você](http://ultrafile.elementfx.com/?dicionario=michaelis&palavra=você)
[http://ultrafile.elementfx.com/?dicionario=aulete&palavra=você](http://ultrafile.elementfx.com/?dicionario=aulete&palavra=você)

```
http://ultrafile.elementfx.com/index.php?dicionario=priberam&palavra=%GDWORD%/
http://ultrafile.elementfx.com/?dicionario=michaelis&palavra=%GDWORD%/
http://ultrafile.elementfx.com/?dicionario=aulete&palavra=%GDWORD%/
```

**Comment by nonwill** [comment]
It's is a difficult problem to solve which is occasionally encountered in relation to the response time of the site or the scripts used in the article content.
One available mitigation is to manually update the article frame after it has finished loading.
![handict_web_file111](https://user-images.githubusercontent.com/46510529/223714953-71f31335-600c-4367-a938-175b0a507d23.gif)

**Comment by iakesi** [comment]
the problem was that I was putting the article as a link inside the iframe tag, I just had to deactivate the checkboxes highlighted in red and the pages started to load normally.

![2023-03-24_03-28-51](https://user-images.githubusercontent.com/109920933/227445424-7473a921-610a-4626-a98c-fbefc19f8643.png)

![a](https://user-images.githubusercontent.com/109920933/227445337-f87a4b99-5510-472b-a6f1-c2a48faa2eda.gif)
