### ISSUE TITLE
Review comments on  @shenlebantongying's PRs(#1624)

### ISSUE THREAD

**Issue by nonwill** [goldendict/goldendict#1625]
I can't make any comments on #1624, though at the end of content posted on #1624 shenlebantongying emphasizes:
> And it works 🦄 🔥 💯 🥇

but the implementation has obvious problems:
![2023-04-27_225311](https://user-images.githubusercontent.com/46510529/234902337-c88ca1d9-3883-45dd-bdac-c7c74d8c61b1.png)

Word “Http://” exists in wikipedia_en_simple_all_maxi_2021-09.zim, would the processing here cause similar queries to have no results returned?
![2023-04-27_231753](https://user-images.githubusercontent.com/46510529/234908733-1c95ac14-5afe-4cf0-988b-43f3cb7bafb4.png)

But  just said at https://github.com/goldendict/goldendict/pull/1624#issuecomment-1525664868 :
> I cannot build this codebase, but the change is rather simple, the changes should be OK.

@shenlebantongying Are these codes you written there just based on guesswork?

**Comment by vedgy** [comment]
> Word “Http://” exists in wikipedia_en_simple_all_maxi_2021-09.zim

If this rare kind of word cannot be found only via the command line: `goldendict "Http://"`, then I guess it wouldn't be a big problem. Would it? Do you suggest searching for `"dict://"` in the word passed via the command line instead?

**Comment by nonwill** [comment]
> If this rare kind of word cannot be found only via the command line: `goldendict "Http://"`, then I guess it wouldn't be a big problem. 

Also words end with '/' would not be found via the command line.


> Do you suggest searching for `"dict://"` in the word passed via the command line instead?

Personally I don't like doing as that. If just for support of handling custom system schemes, bring an extra parameter to mark the function should be enouth and it would not break the compatibility with the original function.

**Comment by vedgy** [comment]
> bring an extra parameter to mark the function should be enouth

Where precisely to add this extra parameter? The URL still has to be passed via the command line. And I don't think it's possible to insert an extra `--url` argument before the passed URL by fine-tuning the *org.goldendict.GoldenDict.desktop* file.

The least disruptive solution I envision is: check if the received word starts with `dict://` or `goldendict://` (case-sensitive? or are certain letters in these schemes capitalized by some programs?) and remove these prefixes.

**Comment by nonwill** [comment]
> The least disruptive solution I envision is: check if the received word starts with `dict://` or `goldendict://` (case-sensitive? or are certain letters in these schemes capitalized by some programs?) and remove these prefixes.

Yes, this is the easiest and most effective way to deal with it.

And I think it should be better to register a shell script to do it. So the scheme head can be just removed from the word before starting GD, and then nothing will be done with sources of GD. But I just not clear if this is possible in Linux.

**Comment by vedgy** [comment]
> So the scheme head can be just removed from the word before starting GD, and then nothing will be done with sources of GD

What's the advantage of doing so? Letting the `goldendict dict://` command keep translating the word "dict" as it does now? Theoretically there could be a way of using GoldenDict and other apps that leads to a `goldendict dict://word` command invocation that bypasses GoldenDict's desktop file, in which case removing the `dict://` prefix in the goldendict executable would be useful.

**Comment by nonwill** [comment]
> > So the scheme head can be just removed from the word before starting GD, and then nothing will be done with sources of GD
> 
> What's the advantage of doing so? Letting the goldendict dict:// command keep translating the word "dict" as it does now?

Regardless of #1624, just adding an auxiliary script (or program), would make the implementation as simple as possible.

**Comment by vedgy** [comment]
I still don't see a significant advantage for the user in disabling the URL scheme feature. I expect no one, or perhaps less than 10 people, to actually disable it in practice. That's assuming I don't overlook some disadvantages and no unexpected issues arise.

At this point, implementing the feature in the app is more obvious and requires less work. So I'm going to proceed in that direction. Unless you implement a superior alternative script-based solution.

**Comment by nonwill** [comment]
> At this point, implementing the feature in the app is more obvious and requires less work.


> Yes, this is the easiest and most effective way to deal with it.

Yes, doing as this  the convenience is more obvious and if handled properly there are no side effects.

**Comment by vedgy** [comment]
> Couldn't you just sidestep this problem by prefixing the query like this goldendict dict://http://? Other solution might be to add a cli option to accept the query as is.

That's a possibility. But is there any benefit in supporting other schemes than the ones registered in GoldenDict's desktop file? That is, `dict://` and `goldendict://` (case-sensitive?).

**Comment by nonwill** [comment]
![2023-05-02_132150](https://user-images.githubusercontent.com/46510529/235585329-44b1290c-bcae-4cfc-936c-9d7e1a21dd4d.png)
Whoa, it is a big improvement over the original commit, but there are still some issues, no?

**Comment by nonwill** [comment]
Something **_irrelevant_**: _Do anyone need to borrow bugs from goldendict-ng?_
![2023-05-02_133840](https://user-images.githubusercontent.com/46510529/235588040-12d0f2ed-cfe0-4b98-a7e7-b1138501270a.png)

**Comment by vedgy** [comment]
> I tried right now and goldendict doesn't accept any commands at all, and considers everything passed to be a query.

A few command line options exist already. See GoldenDict's built-in Help (F1) => *14 Command line switches*.

> `-h --help` for a help output would be a start, I guess.

Good idea. That would make the command line options more discoverable.

---------------

@ceed0, do you want the URL scheme support merged and plan to use it on GNU/Linux? If yes, could you please answer the following questions I posted above?

Is there any benefit in supporting other schemes than the ones registered in GoldenDict's desktop file? (that is, `dict://` and `goldendict://`). Should GoldenDict accept only lower-case scheme names?

**Comment by vedgy** [comment]
Just closed the pull request reviewed here. Closing this review issue as well. Feel free to post review comments under the replacement pull request #1632.
