### ISSUE TITLE
indent nesting issue

### ISSUE THREAD

**Issue by kevinlawler** [goldendict/goldendict#1634]
pictured is the entry for `d`, which is sampled from a stardict dict, goldendict 1.5.0-RC2-311-g15062f7

it seems that whatever is supposed to start a new subentry is instead being interpreted as an indented subentry of each parent subentry in turn

![golden](https://user-images.githubusercontent.com/376238/236634232-b271e3a8-c3c9-4f27-af42-f9c98a7d6cd2.png)

**Comment by wildekat** [comment]
I assume [this](http://download.huzheng.org/bigdict/stardict-Oxford_English_Dictionary_2nd_Ed._P1-2.4.2.tar.bz2) is the dictionary in question.
Yeah, something seems to be wrong with the way GoldenDict processes those `blockquote` tags.
I'm attaching both the raw article and the HTML dump saved from within GD:

[d-raw.txt](https://github.com/goldendict/goldendict/files/11413404/d-raw.txt)
[d-html.zip](https://github.com/goldendict/goldendict/files/11413411/d-html.zip)

**Comment by nonwill** [comment]
> something seems to be wrong with the way GoldenDict processes those `blockquote` tags.

+1

![2023-05-07_083628](https://user-images.githubusercontent.com/46510529/236651963-02f4ad25-92fc-4f49-90cd-717eff375bb9.png)

**Comment by xiaoyifang** [comment]
@vedgy

**Comment by vedgy** [comment]
@kevinlawler, does the fix (latest commit in master) work for you?

**Comment by kevinlawler** [comment]
i'm not currently in a position to vet. please don't block on me

thanks for all the hard work on this project which I use often

**Comment by vedgy** [comment]
Ok, please reopen if the fix doesn't work for you.
