### ISSUE TITLE
Custom command as TTS backend

### ISSUE THREAD

**Issue by rany2** [goldendict/goldendict#1648]
I think it's a worthwhile feature to allow for a custom command to be executed for TTS. For instance, goldendict would need some kind of "command template" such as `python3 -m edge_tts --text "${text}" --write-media "${mp3_file}" --write-subtitles /dev/null`  and would fill in "text" and "mp3_file". Afterwards, it will playback the audio as usual based on user settings.

Related: https://github.com/rany2/edge-tts/discussions/94

**Comment by vedgy** [comment]
TTS is enabled only on Windows and macOS and I haven't used it: https://github.com/goldendict/goldendict/blob/8c5b26a3924f15fb215e2a8e1e96d87531bf5393/articleview.cc#L1477-L1479

Wouldn't *Dictionaries*=>*Sources*=>*Programs*=>*{Type=Audio}* work just as well as a custom-command TTS backend? See also #1641.

**Comment by rany2** [comment]
I see, I didn't expect it to be in `Dictionaries=>Sources=>Programs=>{Type=Audio}`. Sorry about this issue!
