### ISSUE TITLE
New version multiple problems

### ISSUE THREAD

**Issue by akontsevich** [goldendict/goldendict#1650]
After installing 1.5 release have multiple problems comparing to the previous (Qt 5.15.9 based [revision dd36656ada05731c069ecd5b1878380294fb1f3e], 64 bit):

1. UI: Articles are terrible comparing to previous: all translations in 1 line - no line breaks, colors are terrible, background often becomes white - not yellow. Menus and settings not in KDE style - previously was.

### Current:
![image](https://github.com/goldendict/goldendict/assets/3843657/029a2201-62e9-4903-88ef-82c6db5511bb)

### Previous:
![image](https://github.com/goldendict/goldendict/assets/3843657/40e7aaa0-152e-4287-ae7c-482ff25b8641)

2. Click on tray icon has no effect - previously opened main window.
3. Popup window by Clrt+Alt - does not work. Previous version works fine!

**OS**: openSUSE Tumbleweed.

Downgraded to the previous for now.

**Comment by nonwill** [comment]
Hi, seems that your **_Current_** version is the next generation from @xiaoyifang's fork(#1616), and the **_Previous_** one is the **_true_** Official version here. So there should be no such issues with the official version here.

**Comment by akontsevich** [comment]
> Hi, seems that your **_Current_** version is the next generation from @xiaoyifang's fork(#1616), and the **_Previous_** one is the **_true_** Official version here. So there should be no such issues with the official version here.

No, **Current** is the **Official** one - 1.5.0: Qt 6.5.1 (GCC 13.1.1 20230522 [revision dd36656ada05731c069ecd5b1878380294fb1f3e], 64 bit) (Xapian inside) and it has ALL the problems I mentioned

![image](https://github.com/goldendict/goldendict/assets/3843657/cbcc9255-8f1d-4ea3-a077-a513c23d7e1c)


And **Previous** one (in openSUSE) is 1.5.0~rc2+git.20220215T203220-59.50:

![image](https://github.com/goldendict/goldendict/assets/3843657/64674032-9aab-439d-9de2-60c8c837681c)

Downgraded to the previous one.

**Comment by nonwill** [comment]
> No, **Current** is the **Official** one - 1.5.0: Qt 6.5.1 (GCC 13.1.1 20230522 [revision dd36656ada05731c069ecd5b1878380294fb1f3e], 64 bit) (Xapian inside) and it has ALL the problems I mentioned

It is the fork that real attempts to replace the official one here and seems that it has succeeded -- Have to say that aside from the shoddy implementation it does succeed.

> Compare GoldenDict master, @xiaoyifang's fork and @vedgy's Qt WebEngine PR #1542 #1616

**Comment by vedgy** [comment]
@akontsevich, the icons in your "**Current**" version clearly define it as goldendict-ng. GoldenDict's icons haven't changed. Also the window caption says "Добро пожаловать! - GoldenDict-ng". Make sure you install GoldenDict 1.5, not GoldenDict-ng before reporting an issue.

**Comment by akontsevich** [comment]
> @akontsevich, the icons in your "**Current**" version clearly define it as goldendict-ng. GoldenDict's icons haven't changed. Also the window caption says "Добро пожаловать! - GoldenDict-ng". Make sure you install GoldenDict 1.5, not GoldenDict-ng before reporting an issue.

Yes, openSUSE has GoldenDict-ng - what is it?!

**Comment by akontsevich** [comment]
I see: https://github.com/xiaoyifang/goldendict-ng, @xiaoyifang above is FYI as well - Your fork is terrible!

**Comment by xiaoyifang** [comment]
> I see: https://github.com/xiaoyifang/goldendict-ng, @xiaoyifang above is FYI as well - Your fork is terrible!

I guess you are using xdxf dictionaries.  The reason is that Qt has changed the implementation of QDomDocument in Qt6 . 
 https://github.com/xiaoyifang/goldendict-ng/issues/811

**Comment by akontsevich** [comment]
@vedgy for some reason [openSUSE can't use original goldendict](https://bugzilla.suse.com/show_bug.cgi?id=1211986) in the distro because of `QtWebkit`: so is it possible to upgrade `goldendict` to Qt6 so they can include it again?

**Comment by xiaoyifang** [comment]
> > @akontsevich If you want to make it better, you can also provide your dictionary
> > for further analyze & testing in my fork
> 
> Lingvo dictionaries.

can you provide one for troubeshooting the issue.

**Comment by akontsevich** [comment]
> openSUSE can introduce a GoldenDict package based on #1542, similar to [my AUR package](https://aur.archlinux.org/packages/goldendict-webengine-pr-git). #1542 hasn't ported some nonessential for many users features to Qt WebEngine yet (see the pull request's description). Still, some of those missing features are absent or work poorly in GoldenDict-ng too, which hasn't prevented openSUSE from packaging it.

I've noticed them, however [they do not wan't to use the PR](https://bugzilla.suse.com/show_bug.cgi?id=1211986#c9) - need to merge it first.

**Comment by akontsevich** [comment]
> No telling when that happens. In the meantime, you can create your own GoldenDict+PR package. Or build the sources and install without a package.

They promised to fix regressions in `goldendict-ng` in few days.

**Comment by vedgy** [comment]
If you don't mind frequent regressions, then maybe goldendict-ng is the right choice for you.
