### ISSUE TITLE
Build fails with fatal error: QWebSecurityOrigin

### ISSUE THREAD

**Issue by fdservices** [goldendict/goldendict#1656]
Building with `"CONFIG+=use_qtwebengine"` to use QtWebEngine in place of QtWebkit, I still get the error:
<code>
In file included from mainwindow.hh:17,
                from main.cc:7:
article_netmgr.hh:10:10: fatal error: QWebSecurityOrigin: No such file or directory
   10 | #include \<QWebSecurityOrigin\>
</code>

QWebSecurityOption was included in QtWebKit, do I need to install something else?

**Comment by vedgy** [comment]
Have you merged #1542 into master locally before building? Report Qt WebEngine integration issues at [vedgy/goldendict](https://github.com/vedgy/goldendict), not here.
