### ISSUE TITLE
dlopen() ffmpeg please

### ISSUE THREAD

**Issue by birdie-github** [goldendict/goldendict#1659]
Linking to ffmpeg directly is excessive considering the sheer amount of dependencies it brings.

Please consider `dlopen()`ing ffmpeg libraries.

Thank you!

**Comment by vedgy** [comment]
I don't expect any GoldenDict maintainer to rework the FFmpeg+libao backend integration any time soon. Someone would have to contribute such an improvement. Should be merged if clearly better and without significant downsides.

If you compile GoldenDict yourself (and not use a binary GoldenDict package), you can build it with `qmake "CONFIG+=no_ffmpeg_player"` (see the README). Then use the Qt Multimedia internal player backend or an external audio player such as `mpv`.

**Comment by xvitaly** [comment]
dlopening is the worst choice, because ffmpeg has multiple soversions and the app will need to handle them separately and will break on every ffmpeg major release.

**Comment by birdie-github** [comment]
How does GoldenDict use ffmpeg anyways? To play audio files? Why not simply call mpv/mplayer/ffplayer instead? Why all the trouble of linking?

**Comment by xvitaly** [comment]
> Why not simply call mpv/mplayer/ffplayer instead?

![image](https://github.com/goldendict/goldendict/assets/966711/79b609cc-e861-4255-bd7f-b82a87e850a9)

> Why all the trouble of linking?

I don't see any problem here. Everything works as expected. Package maintainers can build goldendict with QtMultimedia, ffmpeg or both.

Most GNU/Linux distributions build goldendict with both backends enabled and end users can choose between implementations in program settings.

**Comment by birdie-github** [comment]
Thanks!

**Comment by vedgy** [comment]
GoldenDict pronounces words using a configurable backend, one of which is FFmpeg+libao, or an external player. Internal player backends are better integrated and work more efficiently. This could be important if the user enables one or both *Auto-pronounce* options, which pronounces words/phrases during each lookup.

**Comment by birdie-github** [comment]
> are better integrated and work more efficiently

Could you please elaborate on that?

We live in 2023, not in 1996 when Pentium 133 struggled to play MP3 files in real time. The `ffplay` binary vs. linked ffmpeg could result maybe in the whole 1% CPU difference when playing audio files.

**Comment by vedgy** [comment]
External program is launched in a separate process. This is inefficient, sometimes causes issues (e.g. zombie processes). Plus GoldenDict cannot always stop/kill the external processes quickly and reliably. Stopping/canceling playback is important when several pronunciations start one after another in quick succession or when a long pronunciation starts (such as an audio version of a Wikipedia article).

**Comment by birdie-github** [comment]
Got it thanks. 

`killall -9 whatever_player` is spawned should deal with the issue perfectly.

```c++
    pid_t process = std::stoi(argv[1]);
    if (kill(process, 9)) {
        std::cerr << strerror(errno) << '\n';
        return EXIT_FAILURE;
    }
```

**Comment by vedgy** [comment]
GoldenDict resorts to killing the process when it cannot be stopped nicely. This is done via the much-higher-level cross-platform [`QProcess`](https://doc.qt.io/qt-5/qprocess.html) API.

`ffmpeg` is used not by itself, but in combination with `libao`. Before the Ffmpeg+libao backend, GoldenDict used several backends on different platforms, e.g. Phonon. Apparently the older backends didn't work as well as the new unified one.
