### ISSUE TITLE
updated linux, but error. So # ln .. solved, but

### ISSUE THREAD

**Issue by leftside2** [goldendict/goldendict#1660]
<<libtiff.so.x>> was the error before, so solved by # ln ...
But today after update, u_charDirection_72 became an error such as "undefined symbol".

how to solve this error?

**Comment by vedgy** [comment]
Please provide a more comprehensible description of what you are trying to do on which system and the exact error message. Did you try a clean GoldenDict build?

**Comment by leftside2** [comment]
solved by re-installing by # yay goldendict # in arch linux.
though it took hours.
I don't know why # pacman -Syu # doesn't update goldendict, but gives wrong files pointing or wrong variables using.
Thank u that u gave me a hint to re-install.

**Comment by vedgy** [comment]
> I don't know why # pacman -Syu # doesn't update goldendict, but gives wrong files pointing or wrong variables using.

That's because `goldendict` is not in official Arch repositories, but in AUR.
