### ISSUE TITLE
After indexing no dictionaries appear in the list of dictionaries

### ISSUE THREAD

**Issue by AmetistoFF** [goldendict/goldendict#1670]
I use 1.0.1 windows version of GoldenDict. I installed CEDICT (65.5 mb one) dictionary from freemdict and [Chinese Encyclopedia "Cihai"] from dadako. When I try to rescan, a window with indexing pop up and after it's done no dictionaries appear on the list. When recursive option is disabled, the window appears and disappears immediately. With recursive option enabled, it stays for around 5-6 sec and then closes all the same.

I tried searching for issues with the same problem in the closed and found none. If this problem is solved and I simply missed the thread, then I'm sorry.

**Comment by vedgy** [comment]
The version 1.0.1 is ancient. Please try [the latest version 1.5](https://github.com/goldendict/goldendict/releases).

**Comment by AmetistoFF** [comment]
Yes, that worked
