### ISSUE TITLE
Please update goldendict/blob/master/mdictparser.cc#L622

### ISSUE THREAD

**Issue by VimWei** [goldendict/goldendict#1672]
GoldenDict would break with these PNG images（keyword：OPEU4_0002）:  **[test.zip](https://github.com/goldendict/goldendict/files/12767768/test.zip)**

More discuss： https://forum.freemdict.com/t/topic/23713

Advise：

From：[goldendict/goldendict/blob/master/mdictparser.cc#L622](https://github.com/goldendict/goldendict/blob/master/mdictparser.cc#L622)

to：[xiaoyifang/goldendict-ng/blob/staged/src/dict/mdictparser.cc#L559](https://github.com/xiaoyifang/goldendict-ng/blob/staged/src/dict/mdictparser.cc#L559)

**Comment by vedgy** [comment]
> More discuss： https://forum.freemdict.com/t/topic/23713

How about a short version of the discussion's conclusions in English?

**Comment by VimWei** [comment]
Summary of the discussion:

Experimentation was conducted to determine the cause of the program crashing. Different symptoms were observed when the number of images in the case was increased or decreased, indicating that there is a problem.

There are two non-professional speculations that have a certain probability of solving the problem: (1) There might be an issue with image processing. All images should be processed using a more professional software like Photoshop, rather than other ones. (2) There might be a problem with the image file names. If a file name contains an underscore, the first half before the underscore should not contain numbers.

Reply from experts: Programmers discussed this issue two to three years ago. The above-mentioned speculations and solutions are mere luck, and the real problem lies in the encoding of GoldenDict. The "endPos" in goldendict/goldendict/blob/master/mdictparser.cc#L622 should be changed to "shadowEndPos".
