### ISSUE TITLE
Question: how can I see all compile options?

### ISSUE THREAD

**Issue by AngryPhantom** [goldendict/goldendict#1675]
This is not a bug. I will close this issue as soon as this question gets answered.

How can I see all compile options? Like:

```
	'CONFIG+=no_extra_tiff_handler' \
	'CONFIG+=no_qtmultimedia_player' \
	'CONFIG+=no_epwing_support' \
	'CONFIG+=no_ffmpeg_player' \
        'DISABLE_INTERNAL_PLAYER=1' \
```

etc. etc. etc...

I wanna make a PKGBUILD for my Arch Linux and slim down goldendict as mush as possible, stripping all chinese, ffmpeg and qt-stuff support (just don't need all these).

The problem is that it requires some packages to be installed in order to run ./configure --help and I don't want to track all them and then uninstall, don't want to pollute the system.

Can anyone please post the list off all possible ./ configure options?

Thank you in advance!

**Comment by vedgy** [comment]
Most or all options are listed in [the README](https://github.com/goldendict/goldendict/blob/master/README.md). Most or all options are also handled in [goldendict.pro](https://github.com/goldendict/goldendict/blob/master/goldendict.pro). I am not aware of a more complete list.

**Comment by AngryPhantom** [comment]
@vedgy I thought there would be more options. Well, then I'm fine. Thank you!
