### ISSUE TITLE
Can't import offline dict files

### ISSUE THREAD

**Issue by FattyMattier** [goldendict/goldendict#1676]
Have added a folder of offline dict files, however, after clicked rescan, nothing happened.  Tried both Chinese or English folder name, the same.  Also built portable folder and .gdindex accordingly, not work.  Most of my offline dict files are mdd/mdx, they are workable in previous version of Goldendict++.  

![image](https://github.com/goldendict/goldendict/assets/108229524/611dd784-fdb0-4885-b896-31d21962e25c)
![image](https://github.com/goldendict/goldendict/assets/108229524/4383a9ee-13b3-4f7e-89e3-04270d6f1745)
![image](https://github.com/goldendict/goldendict/assets/108229524/5fd75678-b4dc-4793-824b-e8aa9e146ab7)

**Comment by nonwill** [comment]
> they are workable in previous version of Goldendict++
```
GoldenDict++OCR-*-Qt-5.9.9-p3-msvc-*:    
	Support All formats except MDict / 支持除 mdict 外的所有词典格式
GoldenDict++OCR-*-Qt-5.9.9-p3-mingw-*: 
	Support All formats except Apple's OSX / 支持除 Apple‘s OSX 外的所有词典格式
Others / 其它版本: 
	Support All formats / 支持所有词典格式
```

Except [Qt-5.9.9-p3-msvc](https://sourceforge.net/projects/goldendict-pro/files/), all others support mdict format.

**Comment by nonwill** [comment]
BTW, it is not a problem with the official GoldenDict, which is released by default to support all dictionary formats.

**Comment by vedgy** [comment]
Report GoldenDict++ issues elsewhere. Also check out #1424 and reconsider using the proprietary fork.
