### ISSUE TITLE
Run Python script as `Programs` dictionary return about `UnicodeEncodeError`.

### ISSUE THREAD

**Issue by scillidan** [goldendict/goldendict#1678]
OS: Windows 10
Version: GoldenDict 1.5.0 (Protable)

I add [ety-python](https://github.com/jmsv/ety-python) into `Programs` of GoldenDict as dictionary. It's data come from `.tsv` of http://etym.org/.

The command line is `ety -r -t "%GDWORD%"`, it return some errors when I search some word liked `apple`, `aerodynamically`:

```
Query error: The program has returned exit code 1. Traceback (most recent call last): File "\\?\C:\Users\scillidan\scoop\persist\python39\Scripts\ety-script.py", line 33, in <module> sys.exit(load_entry_point('ety==1.4.0', 'console_scripts', 'ety')()) File "C:\Users\scillidan\scoop\apps\python39\current\lib\site-packages\ety-1.4.0-py3.9.egg\ety\cli.py", line 42, in cli print(output.strip()) UnicodeEncodeError: 'gbk' codec can't encode character '\u1f00' in position 112: illegal multibyte sequence

```

I try it in `cmd.exe`, `ety -r -t aerodynamically` return:

```sh
aerodynamically (English)
├── -ally (English)
└── aerodynamic (English)
    ├── aero- (English)
    │   └── ἀήρ (Ancient Greek (to 1453))
    └── dynamic (English)
        └── dynamique (French)
            └── δυναμικός (Ancient Greek (to 1453))
                └── δύναμις (Ancient Greek (to 1453))
                    └── δύναμαι (Ancient Greek (to 1453))
```

I have similar problems when I used other python cli liked [etym-cli](https://github.com/agmmnn/etym-cli) in GoldenDict🤔. And node cli [thes](https://github.com/grantshandy/thes) work well.

**Comment by wildekat** [comment]
Your version of Python seems to be set up to automatically convert things to `GBK` on output:
```
$ PYTHONIOENCODING=GBK python3 -c "print('ἀ')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeEncodeError: 'gbk' codec can't encode character '\u1f00' in position 0: illegal multibyte sequence
```
However, I don't see how that could be GoldenDict's fault - there's just no way GD would ever set `PYTHONIOENCODING` or any of its equivalents.
When in `cmd.exe`, does `ety` still work when redirected to a file: `ety -r -t aerodynamically >test_redir` ??

**Comment by scillidan** [comment]
I got the same output in `cmd.exe` with `python39` and `python310`.

```sh
D:\home>ety.exe -r -t aerodynamically >test_redir
Traceback (most recent call last):
  File "\\?\C:\Users\scillidan\scoop\persist\python39\Scripts\ety-script.py", line 33, in <module>
    sys.exit(load_entry_point('ety', 'console_scripts', 'ety')())
  File "d:\cacher\goldendict_ety-python\ety\cli.py", line 42, in cli
    print(output.strip())
UnicodeEncodeError: 'gbk' codec can't encode character '\u1f00' in position 112: illegal multibyte sequence
```

I checked my environment, and I didn't seem to set any environment values except for where `python.exe` and `Scripts/` are.

I should test it on `wsl2` later, but I uninstalled it before and need to reinstall it.

**Comment by scillidan** [comment]
I test it on `wsl2` and `termux`. It works well on them.

![image](https://github.com/goldendict/goldendict/assets/19889610/52cfbaad-4af5-425b-8255-1a926f50aaf6)

And get same errors on newly installed `Windows10` in VirtualBox:

![image](https://github.com/goldendict/goldendict/assets/19889610/3f4eb69e-a8e0-4ba3-82c6-d7c0324470f5)
