### ISSUE TITLE
The theme doesn't show some things clearly

### ISSUE THREAD

**Issue by emanuelps2708** [goldendict/goldendict#1681]
Hi, thanks for your software it's amazing and it has a lot of features, I just have a question/issue with the theme, the thing is that some things when I hover or in some menus it appears a white background but it doesn't appear text about the setting/feature it happen in both the dark and light theme. I tried to change the theme and set a custom one but even though I change it, it doesn't change.

![image](https://github.com/goldendict/goldendict/assets/147004033/959b7930-ed9c-447f-9ba8-86d5ebc36172)

Goldendict version: 23.12.07.b0086d5
OS: Linux mint 21.2 Cinnamon

**Comment by vedgy** [comment]
The screenshot does not show GoldenDict (but likely GoldenDict-ng). Either use GoldenDict proper or report the issue elsewhere.
