### ISSUE TITLE
what is this???? search panel is not normal

### ISSUE THREAD

**Issue by zzfhadr** [goldendict/goldendict#1696]
search panel stoping me to see the whole search result... i don't know how to setting it please help!
![image](https://github.com/goldendict/goldendict/assets/57316428/01595cae-706c-400a-9ffc-f113738881c0)

**Comment by vedgy** [comment]
You have accidentally detached the search pane. Drag it by the caption to whichever side (left, right, top, bottom) of the main GoldenDict window you prefer, then drop and it should fall into place and become attached again.
