### ISSUE TITLE
Use local ollama llms as translater source not work. (goldendict not support stream output?)

### ISSUE THREAD

**Issue by zw963** [goldendict/goldendict#1703]
I running a local LLM for translate server, and get the translater result from the command line.

like following screenshot:

![image](https://github.com/user-attachments/assets/bed8f813-4461-40d5-bafb-4f00139ba191)

It works, basically, it just run ollama like following:

```sh
$: ollama run llama3.1 "Translate following Chinese content into English: Hello world!"
```

But, when i add this command as programs into goldendict, it not work. (Please check following screenshot)

![image](https://github.com/user-attachments/assets/2fcb6738-30dd-42e9-90b0-1add4b1a0f8e)

I even can saw the process is running after i input the content into goldendict, but never result is output.(please check following screenshot)

![image](https://github.com/user-attachments/assets/735e1f53-51f0-49b6-afe8-8123da2ec3fe)

My others programs which not use stream output work well, so, i guess this is a stream issue? (not well understand this, sorry) because ollama output the result use stream,  but goldendict return quickly before the ollama running and stream the output?

Thanks.

**Comment by wildekat** [comment]
> It works, basically, it just run ollama like following:

It's a shell script wrapper, so it needs a working `$PATH`.
What if you run it like this:
```
/path/to/bash_or_zsh --login /path/to/translator %GDWORD%
```

**Comment by zw963** [comment]
Sorry, both not work. following is my script, named: `llama_goldendict_translater`

```sh
        content="$1"

        if echo "$content" |grep -P '[\p{Han}]' >/dev/null; then
            printf '\xEF\xBB\xBF'
            ollama run llama3.1 "Translate Simplified Chinese into English: $content"
        else
            printf '\xEF\xBB\xBF'
            ollama run llama3.1 "Translate English into Simplified Chinese: $content"
        fi
```

I can run it successful on my terminal.

```
 ╰─ $ /usr/bin/bash --login /home/zw963/Dropbox/linux/utils/llms/bin/llama_goldendict_translater 'hello world!'
Hello, translated into Simplified Chinese is:

嗨！世界！
```

But, after i add it as plain text type program into goldendict, like following, still not work.

/usr/bin/bash --login /home/zw963/Dropbox/linux/utils/llms/bin/llama_goldendict_translater %GDWORD%

**Comment by zw963** [comment]
Oops, it works after i change my script into following: (read content from PIPE)

```sh
        content=$(cat /proc/$$/fd/0);

        if echo "$content" |grep -P '[\p{Han}]' >/dev/null; then
            printf '\xEF\xBB\xBF'
            ollama run llama3.1 "Translate Simplified Chinese into English: $content"
        else
            printf '\xEF\xBB\xBF'
            ollama run llama3.1 "Translate English into Simplified Chinese: $content"
        fi
```

And add plain text type program as following (remove the %GDWORD% part)

It works now.

I don't know why, i remember my previous command line tools `translater`(as you can see on my issue second screenshot) not work with %GDWORD% too, i have to add PIPE support to that command too.

I consider this is a issue?

```
/home/zw963/Dropbox/linux/utils/llms/bin/llama_goldendict_translater
```

**Comment by zw963** [comment]
I create a  new issue #1704 for this, will close this now.
