### ISSUE TITLE
Ctrl+A and Ctrl+Shift+A also selects the dictionary name

### ISSUE THREAD

**Issue by vjjustin** [goldendict/goldendict#171]
The new Currently Ctrl+A and Ctrl+Shift+A both selects the dictionary name. Ideally only the article content would be enough for all practical purposes.

Specially with Ctrl+Shift+A, it will be better if it selects only the content, not the dictionary name, since we are selecting the article from only one dictionary.

**Comment by stepaniuk** [comment]
Maybe it would be better to have such option in Preferences?
