### ISSUE TITLE
Multitran bug

### ISSUE THREAD

**Issue by mcmimik** [goldendict/goldendict#189]
Если подключено несколько веб-сайтов (википедия и др.) и в том числе Multitran (http://www.multitran.ru/c/m.exe?s=%GDWORD%), то при поиске слова загружается только Multitran, а справа в колонке «Найдено в словарях:» не отображается список словарей.

![ 2013-01-23 23 19 10](https://f.cloud.github.com/assets/3358193/91129/d8d19d00-6591-11e2-9cc8-1f76f243cc72.png)

GoldenDict 1.0.1-501-g0040469
Mac OS X 10.7.5

**Comment by regs01** [comment]
There could be a solution of a different way. An option to load online dictionaries manually. So each online service would add a button on toolbar or a line in some list of online services with assignable keyboard shortcut for every online service. By default only offline dictionaries would load on search. But, if needed, user would click a button, or would click a line in list of online services, or  would use keyboard shortcut to load specific online service.
