### ISSUE TITLE
Too many realated words in a lookup process

### ISSUE THREAD

**Issue by AshkanV** [goldendict/goldendict#198]
Hello
Thank you for this excellent dictionary software.

The program usually does not have any problem when it uses small glossaries, whether in number or size. Recently I added about 20 large Babylon glossary (*.bgl) like Oxford, Webster, Cambridge, offline Wikipedia, ... . Some of them are more than 200MB.

The problem is when i select to show some of these glossaries with some other special ones, GoldenDict shows too many related word to the one i entered and it takes a very long time to show all the results (sometimes more than 5 min, on a core-i7 cpu).

For example:
when i search "Look" in GD, with only "Webster's New Third International Unabridged Dictionary" glossary enabled, i get only the meaning of "look" as a noun and as a verb. But when I add "Oxford Learner's Thesaurus" to the group, in addition to the word "look", GD also shows the result for "appearance, consideration, expression, fashion, search, seem" in both glossaries, and any of these extra results enteries add many outputs to the result window.

Till now I have found these glossaries, as problematic ones, the words in front of each one are the extra result shows in "Babylon En-En" which is the original glossary of babylon:

TestGroup = Babylon En-En + one the following glossaries:

Word = Look
Oxford Learner's Thesaurus => appearance, consideration, expression, fashion, search, seem
Oxford Collocations Dictionary => look after, look at, look down, look for, look in, look into, ...
Chambers Dictionary 11th Edition => askance, face, Hippocratic, rise, rose, rose, rose (rise), ...
Persian Computer Encyclopaedia => look alike, look up
Picture Dictionary => observe
American Idioms => feel small, look a gift horse in the mouth, look after, look at, look down on, ...

Word = Flower
English (GB) Morphology => flow

Word = Up
Merriam-Webster Collegiate® Dictionary => ups and downs
Macmillan English Thesaurus => close, closed

Word = a
Concise Oxford English Dictionary => A.D. (anno domini), ad, ampere
General Chemistry Glossary => activity

Now imagine when there are 10 large glossaries in a group and 5 of them make GD to lookup lots of related word to the one entered. The result are a very huge output!

As putting download link to copy-right protected items, is forbidden in the forum, I didn't add any. But if there is a need, i can add a direct download link for any of mentioned glossaries. And I know that some of theme are freely available at the Babylon website.

I used the git version from 28th of January and build it on fedora 18 using qmake-qt4 + make.

So I asked if this is a feature of GD, please make an option for disabling it, and if it is bug please fix it.

Thank you.

**Comment by Ansa211** [comment]
I think I reported the same problem as https://github.com/goldendict/goldendict/issues/534

**Comment by Abs62** [comment]
Such option is implemented in last builds.
