### ISSUE TITLE
Make GD source to be ready for Qt5

### ISSUE THREAD

**Issue by Tvangeste** [goldendict/goldendict#212]
Now that Qt 5.0.1 with proper mingw support on Windows is officially available, it would be nice to be able to compile GD against Qt5.

I made a quick and dirty first attempt, and it seems that there is a number of compilation problems that need to be fixed.
- [x] <del>Problem 1. to/fromAscii() is deprecated. Should be replaced by to/fromLatin1(). Will do.</del>
- [x] Problem 2. AtomicInt cannot be cast to int anymore, we should use something like load() or loadAcquire().
- [x] <del>Problem 3. Breaking changes in QSingleApplication.</del>
- [x] Problem 4. Missing includes here and there.
- [x] Problem 5. Hunspell-related issues, compilation problem.
- [x] Problem 6. Model's reset() is deprecated/removed, we should use beginResetModel() and then endResetModel().
- [x] Problem 7. QUrl's add/removeQueryItem is deprecated/removed, we should use QUrlQuery to work with url's query.
- [x] <del>Problem 8. Phonon is missing, sigh.</del> (Not a problem anymore, we don't use Phonon, got rid of it).
- [x] Problem 9: Q_WS_\* macros have been removed in Qt5. At least Q_WS_WIN for sure. We should use Q_OS_WIN instead.

After quick and dirty fixes, I was able to build GD with Qt5/mingw4.7.2, but it works quite unstable and significantly slower compared to Qt4, so I'm rather disappointed. Even the basic scrolling is jerky and not very smooth.

**Comment by Yukariin** [comment]
Any progress?

**Comment by Abs62** [comment]
Look "qt4x5" branch.
