### ISSUE TITLE
Ctrl-Tab is invalid

### ISSUE THREAD

**Issue by xell** [goldendict/goldendict#22]
Hi all.  I noticed that I can use Tab to navigate, but Ctrl-Tab didn't work as expected (i.e. reverse navigation).  Please add this function, especially with the new feature "Dictionaries Pane", in that case I'd like to use Ctrl-Tab to quickly access the pane without running through all the hotspots in the dic text.  Thanks very much.

**Comment by JonahWong** [comment]
On MacOS, Ctrl-Tab is not to switch tabs forwards. It basically does nothing. Is this a platform problem or is it intended this way?
