### ISSUE TITLE
Ability to change User-Agent header

### ISSUE THREAD

**Issue by Tvangeste** [goldendict/goldendict#259]
Some _evil_ sites block GoldenDict specifically, based on the User-Agent string and it is desired to be able to change GoldenDict's User-Agent header to avoid such cases.

The fix is simple: https://gist.github.com/VVSiz/5335292

But I'm hesitant to make it a global change for all sites since some of the sites would find it useful to know from which agent users visit them.

Maybe, an option? A checkbox in Advanced settings seems simple enough, by default no changes in headers.

**Comment by ubless607** [comment]
any update?
