### ISSUE TITLE
Provide support for Epwing format

### ISSUE THREAD

**Issue by chulai** [goldendict/goldendict#298]
Epwing seems to be a popular dictionary format in Japan and a continuos request for support in GoldenDict forum. There are multiple free viewers that support this format: 

http://maximilk.web.fc2.com/viewers.htm

There is almost no documentation available in English about the format but there is a free and open source dictionary application, Fantasdic, here: http://projects.gnome.org/fantasdic/

More info:
http://goldendict.org/forum/viewtopic.php?f=8&t=69&p=557#p500
http://goldendict.org/forum/viewtopic.php?f=4&t=1410
http://goldendict.org/forum/viewtopic.php?f=4&t=1430
http://goldendict.org/forum/viewtopic.php?f=4&p=7436#p7436
http://goldendict.org/forum/viewtopic.php?f=4&t=1211#p5446
http://goldendict.org/forum/viewtopic.php?f=4&t=1701
http://goldendict.org/forum/viewtopic.php?f=4&t=2096#p9030
http://goldendict.org/forum/viewtopic.php?f=4&t=2191

**Comment by the-cla5h** [comment]
Is it going to be added to the Linux version anytime soon?

**Comment by NinKenDo64** [comment]
Any news on whether the Linux version can support EPWING? I can't find any solid information on this, but when I try to add EPWING dictionaries, it doesn't seem to work.

**Comment by the-cla5h** [comment]
> Any news on whether the Linux version can support EPWING? I can't find any solid information on this, but when I try to add EPWING dictionaries, it doesn't seem to work.

I'm on Ubuntu and the version in the repository can handle Epwing format. It seems like it is more up-to-date than the early access one that's [here](https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Linux-Portable) on github. Now I hope the Android version will be updated with this feature.
