### ISSUE TITLE
 Goldendict 1.5.0-RC-358-g6cb186a  used too much CPU resource.

### ISSUE THREAD

**Issue by Hassenky** [goldendict/goldendict#484]
My laptop is running Windows 8.1.
![goldendict](https://cloud.githubusercontent.com/assets/7237164/2955263/034d88e8-da7e-11e3-83ce-e8fac5da0f4f.jpg)

**Comment by elFua** [comment]
fyi, in case you don't need it then full-text indexing can be disabled in **Preferences** > **Full-text search**.
