### ISSUE TITLE
Improve: assign group with tab.

### ISSUE THREAD

**Issue by bkt92** [goldendict/goldendict#511]
Hi. I suppose to add this feature to goldendict.

![untitled](https://cloud.githubusercontent.com/assets/3808392/3642261/59be9024-10bf-11e4-98c3-93fe917a9d68.png)
- And I think it's better if we add some item like "lookup in group -> ( Group A, Group B ... [list all group in goldendict])" in context menu when we select a text.
- And I also think we shoud use clear-type font for chinese, japansese dictionary to display better.
  Thanks.

**Comment by Ansa211** [comment]
This is a duplicate of https://github.com/goldendict/goldendict/issues/84

**Comment by Abs62** [comment]
Closed as duplicate.
