### ISSUE TITLE
"Export/import preferences and dictionary settings" option needed... 

### ISSUE THREAD

**Issue by sanon** [goldendict/goldendict#514]
Hi,

While upgrading to a newer version or for installing the program on another computer an option to export (/import) the current preferences and more importantly the dictionary settings would be great. Recreating the various dictionary groups, reentering the addresses of the web-dictionaries, remanaging the sources and stuff can be a pain...  
(Or is this doable by saving the whole content of the configuration folder and by copying it into the new one after a new installation?)

Thank you very much for the great work btw. I enjoy the program so much...

**Comment by Konfekt** [comment]
Hello, does this also apply to porting to the Android version? The configuration files of the Desktop and Mobile version look incompatible.
