### ISSUE TITLE
Option for switching off synonym search

### ISSUE THREAD

**Issue by Ansa211** [goldendict/goldendict#534]
By default, if one dictionary list synonyms/equivalents of a word, other dictionaries look up all those synonyms, too. (This is true for off-line dictionaries and wiki-style dictionaries. It is not true for online dictionaries.) This feature is useful for searching for "cat" when the user inputs "cats" (the equivalent will be supplied by a morhological dictionary). However, if one of the searched dictionaries is a thesaurus, all of the listed synonyms will be searched for. This clutters the output with information that may not be wanted.

I think a tickbox for switching this off is intended to be shown in the options dialog, look at line 20 in https://github.com/goldendict/goldendict/blob/2f8b4975a3371b70b6045e9b1c076bc3993203c5/options.ui - but I can't find it. I think the best solution would be to have either a separate tickbox for morphological dictionaries (those listed in the "Morphology" section of the "Dictionaries" dialog) and for other dictionaries (i.e. synonyms supplied by the "normal" dictionaries).

**Comment by Ansa211** [comment]
I think this is actually a duplicate of https://github.com/goldendict/goldendict/issues/198

**Comment by Abs62** [comment]
Such option is implemented in last builds.
