### ISSUE TITLE
Find function in mobile version 

### ISSUE THREAD

**Issue by atlaseinewelt** [goldendict/goldendict#538]
Hi, 
I give you an example:
I'm reading a definition (let's say, the definition of "surround"). I go to the menu, then "Find on page". I type a word whatever (for example: "place") and use the arrows. Now I tap a word within the definition (usually a derivative of the first word: let's say "surroundings").  A window pops up ("Look up") and I tap on the word I want Goldendict to search. Now I'm reading the definition of "surroundings", the "Find on page" bar is still open (which is good, because I want to keep finding the word "place") but it doesn't  work properly: it won't show the word "place" in the definition of "surroundings". I have to close the bar, open it again, and type "place" again to find it in the definition of "surroundings". 
I'm using version 1.6.2 in a MotoG 
Regards

**Comment by Abs62** [comment]
Mobile version is not discussed here.
