### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by moceap** [goldendict/goldendict#553]
goldendict takes 25-50% CPU 

https://admin.fedoraproject.org/updates/FEDORA-2014-17070/goldendict-1.5-0.6.RC2.fc21

**Comment by blueyi** [comment]
I also have this problem , I need this version,but when i open the url you give,it prompt File Not Found.
Can you give me again ? Thanks, best regards!

**Comment by alirezaimi** [comment]
same problem , problem solved with disabling full text search , 
1.5.0~git20150923-1
debian.
