### ISSUE TITLE
Simple Feature Request: Favorite Word List 

### ISSUE THREAD

**Issue by lgmazure** [goldendict/goldendict#556]
The history feature is already implemented. Similarly to implement "add to favorite word list" function will be helpful. The favorite word list could take the similar form of the history list, and can be imported and exported. Also a hot-key can be designated for the "add" action.

**Comment by vvch** [comment]
Yes, very useful feature. It may even be implemented not as a separate list, but as ability to flag history items (and current word) with star (like Bookmarks in browser) and an option to export only flagged words in History export procedure.

Similar functionality I've seen in ColorDict.
Android version of GoldenDict also needs bookmarks.

**Comment by blueyi** [comment]
Me too, the bookmark words function is too important, I expect some one can implement it.

**Comment by wenqiangwang** [comment]
+1 for the bookmark feature.

**Comment by hoteru** [comment]
"add to favorite word list" function and export/inport that list feature could be very helpful for master of vocabulary.

**Comment by Abs62** [comment]
Implemented in last builds.

**Comment by vvch** [comment]
Thanks! Would be great to have this functionality in Android version also. Is there official wishlist for the Android version?
