### ISSUE TITLE
XML parse error on Russian Wikipedia and Wiktionary

### ISSUE THREAD

**Issue by zsdedan** [goldendict/goldendict#576]
С недавних пор стала появляться ошибка:
<i>Ошибка поиска: XML parse error: unexpected end of file at 1,1</i>
под выдачей Russian Wikipedia и Wiktionary. Скриншот прилагаю.

---

Not so long ago began to appear this error
<i>Ошибка поиска: XML parse error: unexpected end of file at 1,1</i>
under the search results of Russian Wikipedia and Wiktionary. Screenshot attached.

![gd](https://cloud.githubusercontent.com/assets/3087460/6264109/75523452-b831-11e4-8eca-f474e15dbb19.png)

**Comment by Abs62** [comment]
Change "http://" to "https://" in Wikipedia url in preferences (OpenSSL required).

**Comment by zsdedan** [comment]
Now it works. Thanks.

**Comment by dbzix** [comment]
Thanks, changing 'http' to 'https' did the trick!
