### ISSUE TITLE
Slob: Images are not displayed

### ISSUE THREAD

**Issue by tovaremeterio** [goldendict/goldendict#578]
There is an issue with the images of slob dictionaries. Namely, the images from wikipedia / wiktionary are not displayed at all.

I tried with the slob wikipedia/wiktionary in the following languages: japanese, english and spanish.

**Comment by Abs62** [comment]
It seems wki's in Slob format don't contain pictures at all. Look for example english Wikipedia in Zim - 12G without pictures and 41G with ones. Slob english wiki have size 11G only.
