### ISSUE TITLE
Non-Breaking Hyphen on Win 7

### ISSUE THREAD

**Issue by quendimax** [goldendict/goldendict#585]
On windows 7 GoldenDict can't display a non-breaking hyphen. Changing of font doesn't help.
![2015-04-07 13-46-15 - goldendict](https://cloud.githubusercontent.com/assets/415512/7021984/cba38504-dd2f-11e4-9f63-687152328285.png)

GoldenDict 1.5.0-RC-468-gb19df25, Win 7, 64-bit.

I don't have this issue on Ubuntu 14.04, 64-bit.

**Comment by Abs62** [comment]
Can you give a link to dictionary example with such issue?

**Comment by quendimax** [comment]
[The dictionary](https://yadi.sk/d/VFr6xQJ3fqKCE)

**Comment by Abs62** [comment]
However it is font problem. Try to set "Arial Unicode MS" for articles via article-style.css.

**Comment by quendimax** [comment]
I'm not sure. This hyphen is showed normally in other programs with the same font (Tahoma for example).
But thanks for help.

**Comment by Abs62** [comment]
Depends on. You can try to use Qt5-based build. QWebKit in Qt5 more correctly handle unicode symbols, it uses standard ICU library instead of own text codecs in Qt4.
