### ISSUE TITLE
Conversion between Traditional and Simplified Chinese. 

### ISSUE THREAD

**Issue by zeroarst** [goldendict/goldendict#591]
Hi first of all thank you for the contribution for this great dict. 
In our Chinese community we have many users and many of them have built many useful dictionaries.
However, there is a problem that in Chinese we have two types of characters:  Traditional and Simplified Chinese. 
So it will be great that we can have this function to convert between them.
I don't know C++ so I can't really help for this, but I found a open lib is already there:
https://github.com/BYVoid/OpenCC
Is it possible to integrate to goldendict?

**Comment by Abs62** [comment]
GD only show dictionaries, it don't make any changes in ones. To create/edit/convert dictionaries a other programs should be used.

**Comment by tianliang0123** [comment]
For linux version we can use cconv to convert traditional Chinese to simplified Chinese as command below: cconv -f utf8-tw -t utf8-CN SOURCE_Traditional.txt -o TAR-GET_Simplified.txt
