### ISSUE TITLE
HELP: Setup QT Environment

### ISSUE THREAD

**Issue by guibirow** [goldendict/goldendict#592]
Hello guys, I'm trying for a few weeks to configure the QT environment to develop some functions to goldendict but all tries was failed.

I'm a C# Visual Studio Developer, I have C++ knowledge as well, but I never worked with QT.
After so many tries to setup VS or QT environment, I still couldn't run the project.
Does anyone have or knows a step-by-step to setup the environment, may be on VS or QT.

I followed the instructions on MD file on project root, but when I build the project shows a lot of erros, everytime I fix one error a new one appears.

I tried with QT 4.8.6 and 5.4
VS 2010 and 2012
Mostly of errors, seems to occur because of 
# include <inttypes.h>

The build can't find this header and I couldn't find it on the project, so I assume it's from QT framework, it's right?
Any way, I changed the framework on build configuration of project, executed the make and build again and the error still happens.
I don't know anywhere else I should configure to run the project.

I'll be glad for any TIP.

Thank you guys.

**Comment by Abs62** [comment]
https://code.google.com/archive/p/msinttypes/downloads
