### ISSUE TITLE
uiGridConstants.filter.SELECT does not have any effect

### ISSUE THREAD

**Issue by salarmehr** [goldendict/goldendict#593]
Is adding the following to a column definition enough to have a category filter:

                    filter: {
                        type: uiGridConstants.filter.SELECT,
                        selectOptions: [
                            {value: 'f', label: 'Female'},
                            {value: 'm', label: 'Male'}
                        ]
                    }

I have added it and it has no effect. Also there is not error. What's wrong with it?

**Comment by Daiverspb** [comment]
May be blabla.$inject = ['uiGridConstants'];

**Comment by salarmehr** [comment]
I wonder how this issues appear here instead of ui-grid repository.
