### ISSUE TITLE
English Wikipedia 2015 [Index file]

### ISSUE THREAD

**Issue by tovaremeterio** [goldendict/goldendict#594]
Hello. There is an offline version of the English Wikipedia for GoldenDict. The 48gb file is in .zim format. Available at:
http://www.kiwix.org/wiki/Content_in_all_languages

"wikipedia 	en	 48G	   2015-04	 all"
Torrent file: https://yadi.sk/d/LPnotE6LgXdzH

The only problem is that the file weights 48Gb and the index is extremely large. Indeed, it is necessary at least 8gb of RAM for creating the index. It is impossible to create the index for the English Wikipedia with an old pc with less than 8GB of RAM.

Problem solved> Index file available at 
http://www.pdawiki.com/forum/forum.php?mod=viewthread&tid=13672&page=1&extra=#pid200110

**Comment by jjzz** [comment]
I just created a few index files http://104.236.5.216/work/wiki.index/ for the the kiwix zim from http://download.kiwix.org/zim/
Note, these index files are for the latest wikipedia/wikisource (May 2015).

btw, I recommend vps if you really need to do something temporarily that's beyond your own physical hardware capacity. I made these index files in 3 hours, and it only cost less than half dollar.
