### ISSUE TITLE
cannot build the qt4x5 branch on ubuntu 15.04

### ISSUE THREAD

**Issue by yilksd** [goldendict/goldendict#595]
In the file hotkeywrapper.hh,line4:#include <QtGui>;
line 10 :#include <X11/Xlib.h>.
Because Xlib.h has a line :" #define Bool int " ,it conflict with qvariant.h in QtGui ,which has a "QMetaType::Bool".
Forgive my pool English.

**Comment by alium** [comment]
I have another problem:
keyboardstate.cc:10:20: fatal error: QX11Info: No such file or directory

I have installed:
qt5-base 5.4.2 qt5-declarative 5.4.2 qt5-graphicaleffects 5.4.2 qt5-imageformats 5.4.2  qt5-location 5.4.2  qt5-multimedia 5.4.2 qt5-quickcontrols 5.4.2 qt5-script 5.4.2 qt5-sensors 5.4.2 qt5-svg 5.4.2 qt5-tools 5.4.2 qt5-translations 5.4.2 qt5-webchannel 5.4.2 qt5-webkit 5.4.2 qt5-x11extras 5.4.2 qt5-xmlpatterns 5.4.2

**Comment by alium** [comment]
@Abs62  
Thanks, for me fixed, i can compiled again  :+1:
