### ISSUE TITLE
No GUI after "Close To Tray" (Ctrl+F4)

### ISSUE THREAD

**Issue by galexrry** [goldendict/goldendict#596]
Summary:

After "Close To Tray" (Ctrl+F4), an attempt to launch a second instance of /usr/bin/goldendict caused the GUI of the already running GoldenDict instance to appear. This was convenient. However, it is no longer the case after recent yum-upgrade in Fedora 21: instead there is an undefined symbol error and there seems no way to bring up the GUI again - you need to kill GoldenDict first and launch it again.

I guess some changes in Qt libraries/files may have caused this issue.

Here is how the error looks like by an attempt to launch the second instance of GoldenDict after the first one was closed to tray:

$ goldendict
goldendict: symbol lookup error: goldendict: undefined symbol: _ZN19QtSingleApplication11sendMessageEPKci

Here is what got updated (an excerpt from the yum.log):

May 23 10:07:36 Updated: qtlockedfile-2.4-16.fc21.x86_64
May 23 10:07:36 Updated: qtsingleapplication-2.6.1-17.fc21.x86_64

Here is /usr/share/doc/qtsingleapplication/README.TXT:

Qt Solutions Component: Single Application

The QtSingleApplication component provides support for
applications that can be only started once per user.

Version history:

2.0: - Version 1.3 ported to Qt 4.

2.1: - Fix compilation problem on Mac.

2.2: - Really fix the Mac compilation problem.
     - Mac: fix crash due to wrong object releasing.
     - Mac: Fix memory leak.

2.3: - Windows: Force creation of internal widget to make it work
     with Qt 4.2.

2.4: - Fix the system for automatic window raising on message
     reception. NOTE: minor API change.

2.5: - Mac: Fix isRunning() to work and report correctly.

2.6: - - initialize() is now obsolete, no longer necessary to call
     it
     - - Fixed race condition where multiple instances migth be started
     - - QtSingleCoreApplication variant provided for non-GUI (console)
     usage
     - Complete reimplementation. Visible changes:
     - LGPL release.

Basic info about the system:

$ lsb_release -d
Description: Fedora release 21 (Twenty One)
$ uname -a
Linux node.name 3.19.7-200.fc21.x86_64 #1 SMP Thu May 7 22:00:21 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by galexrry** [comment]
Basic info about the system:
$ lsb_release -d
Description:	Fedora release 21 (Twenty One)
$ uname -a
Linux prhost1.pragdomain 3.19.7-200.fc21.x86_64 #1 SMP Thu May 7 22:00:21 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Abs62** [comment]
I think it needs to recompile GoldenDict with new QtSingleApplication/

**Comment by galexrry** [comment]
Apparently, you are right. Looks like a particular distro-related issue. Therefore I am closing it.

**Comment by galexrry** [comment]
The issue no longer appears in Fedora 22 with binary goldendict RPM.
