### ISSUE TITLE
How to enable voice button on android version of GoldenDict?

### ISSUE THREAD

**Issue by salarmehr** [goldendict/goldendict#601]
Android version of Goldendict has a 'say' button that should play the pronunciation of the current word. However it's disable for me. How should I enable it? I guess I should copy sound files to a specific folder. What is its path? There is not documentation regarding this issue.

**Comment by salarmehr** [comment]
Isn't here anybody to help?

**Comment by yilksd** [comment]
I think this place is for discussing the desktop version.

**Comment by salarmehr** [comment]
@yilksd Where to you think is better to ask about the issue?

**Comment by rtfmpls** [comment]
Any updates for this?

**Comment by Abs62** [comment]
Android version is not discussed here.

**Comment by elswerky** [comment]
Ok as you say Android version not discussed here

From where to download sound files for desktop version??
