### ISSUE TITLE
no image in an offline dictionary with <img src=""> Tag.

### ISSUE THREAD

**Issue by kleinstein** [goldendict/goldendict#603]
hi~
- environment info:
  version 1.5.0-RC-468-gb19df25
  Windows 8.1 pro.
- how to reproduce:
  a simple dictionary text file(for example: mydic.txt) and a image file(image.jpg) in the same folder.
  the content of mydic.txt might looks like this:

``` html
     Any_Word<hier a tab character><p>The Meaning of this Word and a image<img src="image.jpg"></p>
```

and i have converted this mydic.txt file with star-dict editor for creating dict, idx and ifo files.
and ifo file has the attribute "sametypesequence=h" for proper reading html format contents.
- the problem: 
  if i put these converted files in GoldenDict Dictionary folder, then i can not see the image. i can only see the text.
- what i tried: edit mydic.txt file with other html tag.

``` html
     <img src="file:///my_absolute_path/image.jpg"> 
     <img src="./image.jpg"> 
..
```

etc.
But it did not help.

How can i show the image in GoldenDict?

**Comment by Abs62** [comment]
Place your images into "res" folder. Or pack ones into "res.zip" file and place it beside your .ifo file.

**Comment by ilius** [comment]
I still can't get this to work.
What should the path look like?

For example if the original html is `<img src="a/b.png">`
Which one should be in StarDict glossary (assuming we place `a` folder in `res`)
- `<img src="a/b.png">`
- `<img src="res/a/b.png">`
- `<img src="file://a/b.png">`
- `<img src="file://res/a/b.png">`
