### ISSUE TITLE
Wiktionary parsing error

### ISSUE THREAD

**Issue by Xodetaetl** [goldendict/goldendict#607]
It's been a few days that Goldendict is broken for me. It seems the XML for the Wiktionary has changed:
`Request error: XML parse error: unexpected end of file at 1,1`

Using v1.5.0

**Comment by themqy** [comment]
In main window go to "Edit">"Dictionares"... and than to "Wikipedia" change in address field from http to https.

**Comment by Xodetaetl** [comment]
That was it, thanks themqy.

**Comment by notargets** [comment]
With 1.5.0-RC-489-gb4bb1e9, when I change the address to https and try to look up the word "meticulous", I get the following error:
`Query error: Error downloading https://en.wiktionary.org/wiki/w/api.php?action=parse&prop=text%7Crevid&format=xml&redirects&page=meticulous - server replied: Not Found`

When it's http, I get the same error as @Xodetaetl.

**Comment by ntung** [comment]
If I use GD in Ubuntu, your suggestions work well.
But the issues have existed with GD 1.5.0 in Windows 7.

Do you have any solutions?

**Comment by Abs62** [comment]
Take last EA build.

**Comment by ntung** [comment]
@Abs62 I've download the latest version, but the error has not resolved.

**Comment by ntung** [comment]
Thanks @Abs62. I have run the latest build. It resolves this issue.
