### ISSUE TITLE
Wiktionary - Query error: Error creating SSL context ()

### ISSUE THREAD

**Issue by navidada** [goldendict/goldendict#608]
I encountered the problem of "XML parse error: unexpected end of file at 1,1" in Wiktionary dictionaries, so I changed the HTTP to HTTPS like people advised here. 
But now I get the message:
Query error: Error creating SSL context ()
What can I do in order to fix it?

I'm using goldendict v1.0.1 on windows 7, as it is the latest version on goldendict.org

**Comment by Abs62** [comment]
Take last GD version from [sourceforge.net](https://sourceforge.net/projects/goldendict/files/early%20access%20builds/).

**Comment by trigo3go** [comment]
Did it work? I am having the same issues here...

**Comment by navidada** [comment]
Sorry for the late response.
It did work and the new version looks great!
Thanks Abs62

**Comment by Rx3210** [comment]
I have windows 10 and downloaded the latest version of Goldendict from the link you have posted on Github and changed the http to https but still I am having this error Query error: Error creating SSL context ()

I am typing the wikipedia address as follows: https://en.wikipedia.org/w

Thank you for answering

**Comment by cyberbaker** [comment]
Thanks a ton.

**Comment by mikeweilgart** [comment]
@Rx3210 same situation here.  Brand new Windows 10, latest GoldenDict (1.0.1), got [XML parser error](https://superuser.com/q/927740/504387) out of the box and "Error creating SSL context ()" now that I've set https.

**Comment by WangYihang** [comment]
I got the same problem...
OS: Windows 10
Version of GoldenDict: 1.0.1

![image](https://user-images.githubusercontent.com/16917636/35710914-08c014d2-07f5-11e8-813c-f4e489bf4bd4.png)

The error page looks like that:
![image](https://user-images.githubusercontent.com/16917636/35710928-16f13eaa-07f5-11e8-8844-c667eb475ff6.png)

My setting for wikipedia:
![image](https://user-images.githubusercontent.com/16917636/35710940-2942b49e-07f5-11e8-9bd5-80990722e1ac.png)

Could you help me to solve this problem, thank you so much

@Abs62 @navidada

**Comment by cyberbaker** [comment]
Update your version. 
[sourceforge.com](https://nchc.dl.sourceforge.net/project/goldendict/early%20access%20builds/GoldenDict-1.5.0-RC2-209-gfe9312e-Install.exe) offers the current latest version if you don't want to compile the source on your own.

**Comment by WangYihang** [comment]
Okay, got it, thank you so much.

Cyber Baker <notifications@github.com> 于 2018年2月2日 周五 13:25写道：
