### ISSUE TITLE
Some links in Witkionary aren't working others are being opened in the browser

### ISSUE THREAD

**Issue by navidada** [goldendict/goldendict#615]
[I'm using 1.5.0-RC-482, but I think this problem was also in version 1.0.]

Sometimes, when I use Wiktionary and try to click the links inside the article in order to inspect different words, nothing happens.

I figured out which links work and which don't - links that end with #Name-of-Language don't work.
For example, take the word "hub"
- If you try and click the linked words in the definition (the ones linking to other words in Wiktionary) - it works - for example the word "central" under the the first "Noun" definition.
- But, when you try going a bit down to the "Translations" section, if you try clicking on the dutch translation: naaf, then nothing happens. Because the link in the English Wiktionary is: https://en.wiktionary.org/wiki/naaf#Dutch
- Also if you try clicking the link to "Buh" in the "Anagrams" section, nothing works, the link points to: https://en.wiktionary.org/wiki/Buh#English
- What's also interesting is that in the first section ("Pronunciation"), clicking on "-ʌb" also leads nowhere, maybe it's because the link points to https://en.wiktionary.org/wiki/Rhymes:English/-ʌb and the ":" or "ʌ" characters are causing the problem (the "ʌ" character is translated to "%CA%8C", so maybe the problem is characters such as: # % $ etc.)

Also, some links are being opened in the browser and not in goldendict, although they're part of Wiktionary. 
For example, type "central", under "Pronunciation", the link to "IPA" and "(key)" are being opened in the browser and there's no option to open them in another goldendict tab, although they're part of Wiktionary.

Does anyone have any idea what's causing this or how to fix it?

**Comment by Abs62** [comment]
Try: [goldendict-1.5.0-RC-488-ga8df5c9(EXE only).7z](http://www.mediafire.com/download/yzx1xtvxpv7i7kw/goldendict-1.5.0-RC-488-ga8df5c9%28EXE_only%29.7z)

**Comment by navidada** [comment]
Abs62, you're amazing! That fixed it! Thank again for solving my issue.

Maybe you can add another minor fixes, both of them relate to focus after clicking a link: 

When clicking on a link that points to definition#Name-of-Language, it links to the head of the page and not to the language's paragraph. 
For example, in English Wiktionary: "world", under "Translations", the French translation links to: https://en.wiktionary.org/wiki/monde#French
But when clicking on it, the Focus shifts to the top of the English Wiktionary article of "monde" (i.e. https://en.wiktionary.org/wiki/monde) and not to the paragraph of 'French' in the English Wiktionary article of "monde" (i.e. ..../monde#French)

Links from Wiktionary to Wikipedia - For example "world" again on English Wiktionary, under "Pronunciation", there's a link pointing to "General American" in Wikipedia, but when pressing it, the search is being done in all dictionaries (as it's supposed to), but the focus is in Wiktionary and not in Wikipedia, where the link pointed. I don't know if it's intentional or not (Because some people might use Wiktionary but not Wikipedia). If it's meant to be that way, then disregard this comment.
