### ISSUE TITLE
Save hiding settings

### ISSUE THREAD

**Issue by Oreolek** [goldendict/goldendict#617]
I want to be able to save hiding settings, to hide the journal and the dictionary panel. They should stay hidden on the next program startup.

**Comment by Abs62** [comment]
GoldenDict store hiding settings. What version do you use?

**Comment by Oreolek** [comment]
ubuntu package: 1.5.0+git

**Comment by vedgy** [comment]
I suppose this issue is obsolete now. Can it be closed?
