### ISSUE TITLE
Search function in Mobile version not working properly

### ISSUE THREAD

**Issue by atlaseinewelt** [goldendict/goldendict#619]
Search function in Mobile version does not work, if translation popup is full screen and if the mobile phone is in horizontal position. It does not search at all. No problem in vertical position or if is a floating window (I use ebookdroid).
But If I open the app independently, I mean, without using it with a reader, it is the same it works vertical and does not search in horizontal position

I have a Moto G Android 4.4.4
A friend of mine confirmed the bug in a Samsung

**Comment by Abs62** [comment]
Only desktop version is discussed here. GoldenDict for Android is not open-source program, ask author about one.
