### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by drgibbon** [goldendict/goldendict#620]
Any plans for a new release? Looks like there's been a lot of development since 1.5.0-RC in 2013.

**Comment by virtualtam** [comment]
+1 for a more regular release scheme, it'd be a relief for packagers ;-)

**Comment by v-fox** [comment]
Yeah, it's a goddamn shame when devs of essential and/or unique applications go full-hipster with the idea of "hey, with fancy CVS like git all my changes are neatly kept together and I can promptly fix issues which I encounter while using my bleeding edge and/or bring features in without code-proofing or stabilizing changes but other users can suck it and just guess which revision is less broken" ! It's entire trend here on github >_<

It also weird that some kind of linguistic institution doesn't back it up, devote a full team on it and push it as state's standard. You would think a lot of people would like a FOSS replacement for Lingvo and such.

**Comment by drgibbon** [comment]
Good news, 1.5.0-RC2 is out (since April 2016).

**Comment by Symbian9** [comment]
> Good news, 1.5.0-RC2 is out (since April 2016)

Where is Trusty 14.04  binary of RC2?
* https://launchpad.net/ubuntu/+source/goldendict

**Comment by drgibbon** [comment]
@Symbian9 I meant released here on [Github](https://github.com/goldendict/goldendict/releases). I don't know anything about Ubuntu, sorry.

**Comment by drgibbon** [comment]
So, July 2020, any love for a 1.5.0 release? :dancers:

**Comment by drgibbon** [comment]
Oh sorry, I see that lots of people have been asking for this, closing.
