### ISSUE TITLE
Remove duplicated headwords in Wordnet dictionaries.

### ISSUE THREAD

**Issue by cpicanco** [goldendict/goldendict#622]
Running on Debian, version 1.5.0+git.

![goldendict screenshot - 08162015 - 10 55 09 am](https://cloud.githubusercontent.com/assets/6511849/9293559/f0ec2b08-4405-11e5-9c41-6caf69801e84.png)

**Comment by Abs62** [comment]
As I see, you have two same dictionaries in active group. GD show articles for all presented dictionaries.

**Comment by cpicanco** [comment]
Well, is it possible to deactivate one of them? It seems that I have just one dictionary at the source path:
![goldendict screenshot - 08162015 - 01 21 43 pm](https://cloud.githubusercontent.com/assets/6511849/9294125/fbd6fc46-4419-11e5-92f4-b639cbd0e41f.png)
![goldendict screenshot - 08162015 - 01 22 48 pm](https://cloud.githubusercontent.com/assets/6511849/9294126/fbdd01cc-4419-11e5-9a7c-a3d0a916ec0e.png)

It really seems to be duplicated dictionaries somehow.
![goldendict screenshot - 08162015 - 01 25 36 pm](https://cloud.githubusercontent.com/assets/6511849/9294134/6a180e66-441a-11e5-825a-9e7fd71656f5.png)

**Comment by cpicanco** [comment]
And the groups: 
![groups screenshot - 08162015 - 01 29 02 pm](https://cloud.githubusercontent.com/assets/6511849/9294143/d241f826-441a-11e5-8285-daf1d0ccdc45.png)

Even removing all the groups, duplicates persists.

**Comment by Light2Yellow** [comment]
Did you try just to disable one of the copies?

**Comment by cpicanco** [comment]
Yes, they are linked together. Disable one of them by clicking in the icon in the main windows disable both instances.

**Comment by cpicanco** [comment]
Should I delete one of these two files?

Files comprising this dictionary:
/usr/share/goldendict-wordnet/goldendict-wordnet.dsl.dz
/usr/share/goldendict-wordnet/goldendict-wordnet_abrv.dsl

**Comment by Light2Yellow** [comment]
Why not? I definitely can.
No, you should't. `*dsl.dz` is a `.dsl` dictionary zipped with `dictzip` (see `man 1 dictzip`) and `*_abrv.dsl` is a file where abbreviations rely.
I'll try to add this dictionary to my installation.

**Comment by Abs62** [comment]
Try to remove path for Wordnet dictionary in settings, then restart GD and add it again.

**Comment by cpicanco** [comment]
Removed and Restarted. Duplicates persists. With or without recursive. Maybe it is an WordNet issue. They are defined as En-En dictionary. I'm guessing they should be En dictionary, or it does not make any sense??

**Comment by cpicanco** [comment]
Drag and drop one of the instances to the Inactive dictionaries solved the problem. Thanks guys. Please, reopen if necessary.

**Comment by cpicanco** [comment]
![solved screenshot - 08162015 - 02 31 41 pm](https://cloud.githubusercontent.com/assets/6511849/9294428/9a5bef44-4423-11e5-929d-81bb68a4d47e.png)
![solved screenshot - 08162015 - 02 32 05 pm](https://cloud.githubusercontent.com/assets/6511849/9294427/9a5ac34e-4423-11e5-9384-65114b400987.png)
