### ISSUE TITLE
Poor font rendering under Linux

### ISSUE THREAD

**Issue by Light2Yellow** [goldendict/goldendict#623]
I'm using *Infinality* patch and font rendering is very good by default. Further, for those apps which ignore global font settings I have `~.Xresources` with `fontconfig` settings:
```
Xft.autohint: 0
Xft.lcdfilter:  lcddefault
Xft.hintstyle:  hintfull
Xft.hinting: 1
Xft.antialias: 1
Xft.rgba: rgb
```
So, where could the problem rely?
Is it possible to substitude default fonts, if they are present?
![actual_rendering](https://cloud.githubusercontent.com/assets/10786469/9294132/4f624f08-4444-11e5-9a71-4ec7b89a656a.png)
![goldendict](https://cloud.githubusercontent.com/assets/10786469/9294133/5187b3c2-4444-11e5-955b-9b05b756998a.png)

**Comment by Abs62** [comment]
You can change articles font via user style file "article-style.css" placed in GD configuration folder. Read GD help, chapter "User styles".

**Comment by Light2Yellow** [comment]
Substituted fonts for Liberation Sans in style file from github in this manner (have never actually worked with css):
````
font-family: Liberation, "Liberation Sans", sans;
```
A bit better, but still bad. How does goldendict render text?
![goldendict1](https://cloud.githubusercontent.com/assets/10786469/9294494/0e57b736-444f-11e5-81b0-0d537631fb82.png)

**Comment by Abs62** [comment]
GD just make html content and transfer it to QT Webkit module to render.

**Comment by Light2Yellow** [comment]
Is it possible that this issue occurs because of I'm using qt4 version of GD on Plasma, which currently uses qt5.5? The thing is, I didn't manage to compile qt5 version (a lot of errors).

**Comment by Abs62** [comment]
To compile Qt5-based version use "qt4x5" branch from git, not "master".

**Comment by Light2Yellow** [comment]
It took me a while to figure out how to compile files from remote branch but it was worth it. Now rendering is as it should be. Thank you, Abs62.
![goldendict](https://cloud.githubusercontent.com/assets/10786469/9302098/297d4ae6-44d4-11e5-9afe-1cec57964dff.png)

![goldendict2](https://cloud.githubusercontent.com/assets/10786469/9302083/04fb1d60-44d4-11e5-9759-48b2e54266ec.png)
