### ISSUE TITLE
goldendict stop working when searching for "emotion"

### ISSUE THREAD

**Issue by nhamlh** [goldendict/goldendict#624]
When I type "emotion" in searchbox, then goldendict close accidentally.

**Comment by xiaoyifang** [comment]
I think this issue may not be occured any more. and the issue is to old to verify.
can be closed.

**Comment by vedgy** [comment]
Cannot reproduce. @nhamlh, please reopen and provide more details, such as your OS, if you can reproduce the crash in the latest GoldenDict build.
