### ISSUE TITLE
Hotkey to show main window not working on Windows 10

### ISSUE THREAD

**Issue by amosbird** [goldendict/goldendict#635]
![w3lc0v d7sb63d fc8c 6](https://cloud.githubusercontent.com/assets/5085485/10429301/19f3b9ca-712a-11e5-9b58-e94ffd19a0e2.png)

This customized hotkey is not working. I've tried different comb keys, no good.

**Comment by Abs62** [comment]
Try to use letter/number/functional keys for global hotkeys.

**Comment by amosbird** [comment]
Thanks, it works with `Ctrl + 0`. But why does this become a limitation?
