### ISSUE TITLE
%GDWORD% only catches first word of the phrase

### ISSUE THREAD

**Issue by trotamundos** [goldendict/goldendict#637]
Hi there. 
I'd like to get full phrase , entered in goldendict search window instead of only first word, as it's currently done. Is there a way to do it?

**Comment by Abs62** [comment]
GD replace %GDWORD% by all content of search line when web dictionary called. Check you url template.

**Comment by rileyrg** [comment]
Can you please explain this. What is GD? %GD% doesnt work.
