### ISSUE TITLE
GoldenDict always fully occupies 1 CPU core

### ISSUE THREAD

**Issue by d0vgan** [goldendict/goldendict#640]
Checked with:
- GoldenDict 1.5.0.496 and 1.5.0.482;
- Windows 7 32-bit and Windows 8.1 64-bit.

Steps to reproduce:
- create a new (empty) folder.
- extract "GoldenDict-1.5.0-RC-496-g8ac7edd_(QT_486)(Abs62).7z" into that folder.
- place several dictionaries into the "content" subfolder. Just for reference, I have:
  ...\content\en-en\
  En-En-Longman_DOCE5.ann
  En-En-Longman_DOCE5.bmp
  En-En-Longman_DOCE5.dsl.dz
  OxfordDictionaryEnEn.ann
  OxfordDictionaryEnEn.bmp
  OxfordDictionaryEnEn.dsl.dz
- start GoldenDict.exe.

It is expected that it fully occupies 1 CPU core while creating its dictionary index.
What is unexpected that it fully occupies 1 CPU core even after the dictionary index has been created, and even after GoldenDict.exe is restarted!

In the same time, when GoldenDict's settings window is shown, the process occupies less than 1% of the 1 CPU core. But once GoldenDict's main window is shown again, it occupies 100% of the 1 CPU core! (Thus, in 2-core CPU you get 50% total CPU usage, and in 4-core CPU you get 25% total CPU usage.) This happens without any user actions, when GoldenDict is expected to wait for user input.

**Comment by d0vgan** [comment]
When looking at GoldenDict.exe in ProcessHacker, also high I/O Total Rate is reported: it's 50 MB/s on my PC and 20 MB/s on my notebook, and this value is constant.
Have no idea what GoldenDict.exe reads or writes while it should not do anything.

**Comment by Abs62** [comment]
Have you read GD help about full-text search? It is FTS indexing process. Indexing statistic you can see in full-text search dialog.

**Comment by d0vgan** [comment]
OMG, that must be it!
Hmm, could GoldenDict somehow indicate this to let user know that the full-text indexing is in progress?
Because having a program that does not seem to do anything - at least it does tell anything about it - and occupies 100% of 1 CPU core is, well, frustrating.
Such indicating could be either a some coloured/blinking/moving text at the bottom of the GoldenDict's window (e.g. in statusbar or something like that) - or a direct dialog shown when GoldenDict is started (e.g. "Full-text search indexing is performed in background, %d dictionaries from %d indexed.")

**Comment by bam80** [comment]
Can we cache results of the FTS indexing process to not start it again every time program runs?

**Comment by gavenkoa** [comment]
> Can we cache results of the FTS indexing process to not start it again every time program runs?

It should be one time process.  If the process was interrupted, it will continue, just give it a time ))

You can disable Full Text Search in the Preferences (F4).

**Comment by nonwill** [comment]
> > Can we cache results of the FTS indexing process to not start it again every time program runs?
> 
> It should be one time process. If the process was interrupted, it will continue, just give it time ))
> 
> You can disable Full Text Search in the Preferences (F4).

![macos_dict_wl](https://user-images.githubusercontent.com/46510529/194773290-641f0b40-52d4-417f-b794-4bdd79b222a1.gif)

**Comment by nonwill** [comment]
> > Can we cache results of the FTS indexing process to not start it again every time program runs?
> 
> It should be one time process. If the process was interrupted, it will continue, just give it time ))
> 
> You can disable Full Text Search in the Preferences (F4).

![macos_dict_wl](https://user-images.githubusercontent.com/46510529/194774023-b552b1db-a96b-41de-9209-1b91e295c603.gif)
