### ISSUE TITLE
Wikipedias/Wiktionaries are not available after hibernation on Linux

### ISSUE THREAD

**Issue by vedgy** [goldendict/goldendict#642]
This is a regression (less than a year old, I think). After hibernation, instead of the word translation, the following text is displayed in all wiki dictionaries "Query error: Network access is disabled.". The Wiki dictionaries do not become available until I manually restart goldendict.

**Comment by vedgy** [comment]
I'm probably mistaken and this is not actually a regression. I switched from master to qt4x5 branch recently, and noticed this issue. I checked the Qt4 version of goldendict - and wikis work after hibernation. So, I suppose that this is Qt5-only issue.

**Comment by Abs62** [comment]
May be it's because [QTBUG-46323](https://bugreports.qt.io/browse/QTBUG-46323)?

**Comment by vedgy** [comment]
Yes, this is probably the same issue. I'm currently using Qt 5.5.1, and the fix (https://codereview.qt-project.org/#/c/121724/14//ALL,unified) is not yet there (http://code.qt.io/cgit/qt/qtbase.git/tree/src/network/access/qnetworkaccessmanager.cpp?h=v5.5.1). Hopefully, the fix will be included into Qt 5.5.2, and then I'll be able to close this issue.

**Comment by xmyth** [comment]
It works for me by changing wikipedia url from http to https .  #607

**Comment by vedgy** [comment]
This issue is still present with Qt 5.6.0 even though [QTBUG-46323](https://bugreports.qt.io/browse/QTBUG-46323) was fixed in 5.6.0 RC and the code from the fix is present here: https://code.qt.io/cgit/qt/qtbase.git/tree/src/network/access/qnetworkaccessmanager.cpp?h=v5.6.0.
So I think that this issue is caused by something else. Not sure whether this is Qt or goldendict fault.

**Comment by vedgy** [comment]
This issue became much less frequent with Qt 5.6.
It manifests itself about once every 5-10 hibernations.

**Comment by vedgy** [comment]
Haven't encountered this issue with Qt 5.10/5.11 and fresh goldendict versions for months. I assume it has been fixed somehow.
