### ISSUE TITLE
Article don't correspond to title in slob dict

### ISSUE THREAD

**Issue by ccaid** [goldendict/goldendict#648]
GD 1.5.0-RC-496-g8ac7edd x86
Windows 7 x84 / Windows 8.1 x86
dictionary: ruwiki-20151002.lzma2.slob (see header of topic http://4pda.ru/forum/index.php?showtopic=357315)
title: Шкала Кинси
GD shows article: 1806 год в литературе
at aard2 android application there is no such problem.

**Comment by Abs62** [comment]
In this file the both reference entries "Шкала Кинси" and "1806 год в литературе" points to the same article. In the file "ruwiki-20150319.slob" for example I don't see such issues.

**Comment by ccaid** [comment]
at aard2 app "Шкала Кинси" points to "Шкала Кинси" article, and "1806 год в литературе" points to "1806 год в литературе" article. no problem at all.
did you use some kind of "unpack" tool for slob to make your conclusion? or it based on some internal data structures of GD?
if second then maybe there is some bug in GD?
if first then may be there is some misunderstanding of slob structure?

**Comment by Abs62** [comment]
Sorry, I just found one dumb error in GD parsing. Will be fixed.

**Comment by ccaid** [comment]
solved
