### ISSUE TITLE
Incomplete support of Tex in slob

### ISSUE THREAD

**Issue by ccaid** [goldendict/goldendict#649]
not all commands of Tex are rendered in math formulas
f.e. in  ruwiki-20151002.lzma2.slob (see header of topic http://4pda.ru/forum/index.php?showtopic=357315) articles:
Бином Ньютона
Биномиальный коэффициент
Ряд Тейлора
unrendered commands:
\leqslant, \geqslant, \tbinom, \iff, \infin

**Comment by Abs62** [comment]
Will be fixed in the next EA build.

**Comment by ccaid** [comment]
solved
but not sure about other articles and commands
