### ISSUE TITLE
Can any one add touch swipe gesture to goldendict with one finger.

### ISSUE THREAD

**Issue by bkt92** [goldendict/goldendict#651]
I use windows tablet so it inconvenient to scroll up and down with scroll bar in goldendict.
I also realize that touch gesture can use in goldendict but with two finger and it`s inconvenient too.
I want to fix but i now know c++ and qttouch. So anyone can fix this ?
I think that not only me need this feature :) 

Thank you ! !

**Comment by guai** [comment]
bump
