### ISSUE TITLE
scan popup don`t work when i copy text !

### ISSUE THREAD

**Issue by mega4area** [goldendict/goldendict#653]
in version 1.0.1 when i copy any text using the right click in Mouse the scan popup work and translate the copied text
but in newer versions of this software the scan popup don`t work when i copy text using the right click in Mouse  !?
btw i use Windows 7

**Comment by Abs62** [comment]
Read help, "Preferences" -> "Options adjustable via config file" (parameter "trackClipboardChanges").

**Comment by mega4area** [comment]
it`s work , Thank you Abs62
