### ISSUE TITLE
Wikipedia/Wikidictionary: Query error: XML parse error: unexpected end of file at 1,1

### ISSUE THREAD

**Issue by embar-** [goldendict/goldendict#654]
After you enable Wikipedia or/and Wikidictionary as GoldenDict dictionaryies via GoldenDIct menu, you still can not use them, because it fails to obtain query from wikipedia. It shows only warning:

Query error: XML parse error: unexpected end of file at 1,1

![goldendict_wiki](https://cloud.githubusercontent.com/assets/1218781/12075678/c1f2bb6a-b155-11e5-884b-65ef5f92cd36.png)

I use latest GoldenDict GIT version 20151231T154233-617.1 from https://software.opensuse.org/download.html?package=goldendict&project=office:goldendict in openSUSE.

P.S. This is different Wikipedia in GoldenDict bug from https://github.com/goldendict/goldendict/issues/642 as it is not about "SSL handshake failed".

**Comment by imd** [comment]
I have the same bug in Ubuntu 15.10. The version is called 1.5.0~git20131003-1build4.

**Comment by Abs62** [comment]
Change "http" to "https" in wikipedia urls .

**Comment by imd** [comment]
Yeah, that works. If the URLs have been updated on GitHub then it seems this should be closed as fixed.
