### ISSUE TITLE
TeX bug

### ISSUE THREAD

**Issue by ccaid** [goldendict/goldendict#657]
dictionary: ruwiki-20151002.lzma2.slob (see header of topic http://4pda.ru/forum/index.php?showtopic=357315)
article Sinc
there is mistaken string "*35l$" in first two formulas — the string should not be.

**Comment by Abs62** [comment]
[goldendict-1.5.0-RC2-158-g4b0df85(EXE only).7z](http://www.mediafire.com/file/120snw8lwbn58op/goldendict-1.5.0-RC2-158-g4b0df85%28EXE+only%29.7z)
