### ISSUE TITLE
Scan Popup Always on top

### ISSUE THREAD

**Issue by kzelda** [goldendict/goldendict#659]
Hi ; Please , When i pin the popup window , i want to show it Always on top.

**Comment by Abs62** [comment]
[goldendict-1.5.0-RC2-161-g58abc3b(EXE only).7z](http://www.mediafire.com/file/swli17z3spaa6ni/goldendict-1.5.0-RC2-161-g58abc3b%28EXE+only%29.7z)

**Comment by kzelda** [comment]
thank you very much
