### ISSUE TITLE
[Feature request] History limit removed, or at least increased to 100 000

### ISSUE THREAD

**Issue by GemzDigg** [goldendict/goldendict#667]
Hello,

That's a need for me, and i guess for anyone with a big collection of words.
I would like to see ALL my "rare" and interesting words, expressions, locutions, proverbs (in french) in the history panel.

Currently, i have 50 000 + entries, i have to split my history into groups of 10 000 words, and import / export whenever.

Thanks of the good work.

**Comment by aksr** [comment]
@GemzDigg: I agree,  I allready requested it: #569

**Comment by aksr** [comment]
@GemzDigg: This issue should be closed - the upper limit is already increased.

**Comment by GemzDigg** [comment]
With the last build (1.5.0-RC-517-g38adb08), the upper limit is still 9999, and when i add words, the first are removed.

**Comment by Abs62** [comment]
Fixed in [last early access builds](https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows).
