### ISSUE TITLE
Bug using the clipboard toward goldendict when searched entry starting or ending with character (-) or ending with (!) (?) (...) etc.

### ISSUE THREAD

**Issue by GemzDigg** [goldendict/goldendict#671]
Hello,

When i copy/search the expression : "hurry up !", it will search "hurry up"
When i copy/search prefix or suffix : "céphalo-" or "-thérapie", it will search "céphalo" or "thérapie"

I have to always edit my search, because search results is not digging right in advanced or specialized dictionaries, which includes those special characters.

Excuse my english.
Thanks for the good work.

**Comment by Abs62** [comment]
It is not bug, it is feature. GD truncate spaces and punctuation along the edges of word/expression to avoid it accidental capture while selection.
