### ISSUE TITLE
goldendict make error

### ISSUE THREAD

**Issue by WilliamXIII** [goldendict/goldendict#678]
build/chinese.o: In function `Chinese::CharacterConversionDictionary::CharacterConversionDictionary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, QIcon, QString const&)':
chinese.cc:(.text+0xda): undefined reference to`opencc::SimpleConverter::SimpleConverter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
build/chinese.o: In function `Chinese::CharacterConversionDictionary::~CharacterConversionDictionary()':
chinese.cc:(.text+0x2ee): undefined reference to`opencc::SimpleConverter::~SimpleConverter()'
build/chinese.o: In function `Chinese::CharacterConversionDictionary::getAlternateWritings(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)':
chinese.cc:(.text+0x17ce): undefined reference to`opencc::SimpleConverter::Convert(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'

Why is the error?

**Comment by Abs62** [comment]
Rebuild OpenCC library with same compiler as you build GD.
