### ISSUE TITLE
GD does not remember folded dictionary - 1.5.0~git20131003-1build1

### ISSUE THREAD

**Issue by johann-ka** [goldendict/goldendict#685]
A minor bug: goldendict does not remember the folded dictionary/dictionaries in the main and in the pop-up window. 

OS: Ubuntu 14.04, 64-bit - with latest updates installed
GDversion: 1.5.0~git20131003-1build1
QT: 4.8.6 (GCC 4.8.2, 64-bit)

goldendict is an awesome piece of software - thank you to the main developer and those who helped out!

**Comment by Abs62** [comment]
Very old version. Many bugs has been fixed at last two and half years. Try to build GD from git sources.
