### ISSUE TITLE
MDICT: CSS with Data URI scheme url not working

### ISSUE THREAD

**Issue by challenging75** [goldendict/goldendict#687]
Hi,

In latest goldendict build(I am using GoldenDict-1.5.0-RC-616-g5731349_(QT_560)(64bit)), if css contians url like: url(data:image/png;base64,xxx), the image is embedded in xxx, then the image is not disaplayed correctly. However there is no problem in last build(GoldenDict-1.5.0-RC-604-gb99a02f_(QT_560)(64bit)). I suspect the issue is caused by Commits on Apr 2, 2016(MDict: Handle local url's in loaded .css). I found bres:// is added to url: url(bres://id/data:image/png;base64,xxx). For the image embedded, this url doesn't work. Please review this.

Thank to the developer and those who work on this.

**Comment by Abs62** [comment]
Try this version - [goldendict-1.5.0-RC-536-ga6d7e20(EXE only).7z](http://www.mediafire.com/download/cpckbyfj3ea2skz/goldendict-1.5.0-RC-536-ga6d7e20%28EXE+only%29.7z). Archive contains .exe files for all my builds.

**Comment by challenging75** [comment]
It works! Thanks.
