### ISSUE TITLE
From portable to regular version

### ISSUE THREAD

**Issue by sanon** [goldendict/goldendict#688]
Hi,

I want to turn my portable Goldendict into a standard, non-portable version. Can I do that just by deleting the portable folder and without messing up all my settings and groups and installed dictionaries?

Thanks in advance...

PS: I am on Win7...

**Comment by Sasoona** [comment]
well if you deleted the folder all your settings will be gone .. 

what you should do is to close goldendict and to go to ... "C:\Users\{your user name}\AppData\Roaming" .. and create a folder and rename to "GoldenDict" .. and then move all the files inside the portable folder into this new folder .. and delete the empty portable folder afterwards ;) .. now reopen Goldendict .. and voila :)
