### ISSUE TITLE
playing sound in online dictionaries like ( Linguee & Dict.cc & Arabdict.com & Reverso ) from within GoldenDict

### ISSUE THREAD

**Issue by Sasoona** [goldendict/goldendict#690]
I'm facing a problem with playing sounds on these websites inside goldendict .. I'm able to get the translations but the pronunciation fails to load.. and after inspecting the play sound elements I get the Error: (Failed to load resource: Content Blocked).. and I've tried with reverso.com and also faced the same problem but I get this error msg .. "your browser doesn't support HTML5 Audio or mp3 codec is missing" .. so i tried to install a lot of codecs like .. Lame encoder & Klite mega codec .. I've also installed .. silverlight, shockwave player and flash player .. but with no luck .. 

and  of course I've enabled the option to use external plugins.

I believe the problem lies in the Url path that Goldendict request when I try to play the sounds or with HTML5 support in the GD browser .. If any body can help me .. I'd be most grateful :)

thanks in advance

**Comment by Abs62** [comment]
Try last QT5-based version.

**Comment by Sasoona** [comment]
That actually worked .. I haven't tried the QT builds before .. thank you very very very very very much :+1:
