### ISSUE TITLE
Do not set Profile path to users\[username]\Application Data on Windows XP+

### ISSUE THREAD

**Issue by lychichem** [goldendict/goldendict#691]
For Windows XP+ it's a system path that do not let users to access or modify. Please change it to users\[username]\AppData\Roaming instead.

**Comment by Sasoona** [comment]
you can make golden dict portable ... by creating a folder next to Goldendict.exe and rename it to "portable".. and the profile will be created within this folder.. ;) .. but with a little bit of limitation .. your dictionary files must be inside the content folder .. and you can't add audio files like mp3 or wav files for pronounciation..

**Comment by lychichem** [comment]
I see... But please change the default value for Windows installer version. If you do not want to add OS target code just give two link for users using different system.

**Comment by Abs62** [comment]
GoldenDict take application data folder from "APPDATA" environment variable. Windows XP don'use "AppData" folder at all. Windows Vista+ contains "Application Data" as symlink to "AppData\Roaming" folder.

**Comment by lychichem** [comment]
Yes, it is actually a system link. But why there is no such folder AppData\Roaming\Goldendict?

**Comment by Abs62** [comment]
>> and you can't add audio files like mp3 or wav files for pronounciation..  
You can't use "Sound dirs" feature in portable version but you can use Zips sound dictionaries - ones are just sound files packed in zip archive.

>> But why there is no such folder AppData\Roaming\Goldendict?
Where? GD create this folder at start if not see "portable" folder beside DoldenDict.exe.
