### ISSUE TITLE
If portable mode is enabled the default install path should be given enough right

### ISSUE THREAD

**Issue by lychichem** [goldendict/goldendict#692]
As Windows Vista+ do not give C:\Program Files (or C:\Program Files (x86)) writing authority by default, if portable mode is enabled on Windows Vista+, Goldendict can't write its config file and will be forced to exit. See #691 for more information.

**Comment by Abs62** [comment]
Don't install GoldenDict to "Program Files" if you want to use it in portable mode.

**Comment by lychichem** [comment]
Then would you mind adding an instruction to it in your program?

**Comment by Abs62** [comment]
It is common rule for all portable applications.
