### ISSUE TITLE
Building fail for OS X target with chinese conversion support

### ISSUE THREAD

**Issue by PurlingNayuki** [goldendict/goldendict#694]
I cloned OpenCC source code and run
`cmake .`
 `make install`
And OpenCC is working. Then I copied libopencc.dylib to maclibs/lib and export files to maclibs/include, and add -lopencc to LIBS and it compiles well. However when linking it keeps telling that
`Undefined symbols for architecture x86_64:`
`  "opencc::SimpleConverter::SimpleConverter(std::string const&)", referenced from:
      Chinese::CharacterConversionDictionary::CharacterConversionDictionary(std::string const&, std::string const&, QIcon, QString const&) in chinese.o
  "opencc::SimpleConverter::Convert(std::string const&) const", referenced from:
      Chinese::CharacterConversionDictionary::getAlternateWritings(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&) in chinese.o`
`ld: symbol(s) not found for architecture x86_64`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`make: *** [GoldenDict.app/Contents/MacOS/GoldenDict] Error 1`
My environment is OS X 10.11.4, QT 5.5.1_2 from HomeBrew, lastest XCode and lastest source code under qt4x5 branch. Thank you!

**Comment by Abs62** [comment]
Try today git source.

**Comment by PurlingNayuki** [comment]
It compiles and runs but not works properly as expected. Traditional Chinese can't be converted into simplfied Chinese after checking conversions in settings and add it into dictionary list. Would this be an other issue or continue belonging to this one?

**Comment by Abs62** [comment]
Check GoldenDict log (in console or via --log-to-file command line option). Most likely OpenCC library can't find needed data. It data (.ocd) and config (.json) files should be accessible via PATH system variable or placed in "opencc" directory beside GoldenDict executable (in GoldenDict.app/Contents/MacOS directory). Look [GoldenDict-1.5.0-RC-632-g436edad.dmg](http://www.mediafire.com/download/g9coehy5mkmjnok/GoldenDict-1.5.0-RC-632-g436edad.dmg) structure for example.

**Comment by PurlingNayuki** [comment]
Added opencc data into the package and it's working. Thank you!
Still need to find a way to pack the data automatically.

**Comment by PurlingNayuki** [comment]
Using the master branch of the lastest source and compile OS X target will fail starting up. Delete the `opencc` folder in the App bundle will fix it so it seems that there's something wrong with opencc data.
I believed that it's something wrong in commit 777d07e09 but still got failure when replace them with 32-bit data.

**Comment by Abs62** [comment]
Can't reproduce. Do you have other version of OpenCC library somewhere? Try to check version path to libopencc.dylib in GD executable (via "otool -L").

**Comment by PurlingNayuki** [comment]
Don't sure I do the right thing but:
```
$ otool -L ./libopencc.2.dylib
./libopencc.2.dylib:
	@executable_path/../Frameworks/libopencc.2.dylib (compatibility version 2.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```
At that time I'm in `GoldenDict.app/Content/Frameworks`. Have compiled opencc and install from source code but I have now a working GoldenDict. I compiled 436edad just now and it works like a charm, while 6f04427 refused to start up.

**Comment by Abs62** [comment]
No, I mean "otool -L ./GoldenDict" in "GoldenDict.app/Contents/MacOS".

**Comment by PurlingNayuki** [comment]
Here it is:
```
$ otool -L ./GoldenDict | grep 'opencc'
	@executable_path/../Frameworks/libopencc.2.dylib (compatibility version 2.0.0, current version 1.0.0)
```

**Comment by Abs62** [comment]
Test [this bundle](http://www.mediafire.com/download/iank3alb44o5a2c/gd-1.5.0-RC2.dmg), compiled from git sources as is and handled by macdeployqt. It works on my VM with OSX 10.9.

**Comment by PurlingNayuki** [comment]
This works perfectly. I noticed that it's built using QT 5.6.0 but when I use QT 5.6.0, I received
```
Project ERROR: Unknown module(s) in QT: webkitwidgets
```
And I've tried to compile using the latest source codes and still got failure.

**Comment by Abs62** [comment]
Since Qt 5.6.0  Qt WebKit [was excluded](https://wiki.qt.io/New_Features_in_Qt_5.6) from Qt release. You should build it from sources to compile GD.

**Comment by PurlingNayuki** [comment]
So is there any possibility that the problem could be caused by QT 5.5.1?

**Comment by Abs62** [comment]
For me GD compiled with Qt 5.5.1 also works. Try to uninstall other OpenCC libraries before compiling.

**Comment by PurlingNayuki** [comment]
Pull-request #700 works for me.

**Comment by Abs62** [comment]
Do you not use QtCreator? It add values for compile specifications and architecture like "-spec macx-clang CONFIG+=x86_64" automatically. Otherwise you should tune qmake command line manually, I think.

**Comment by PurlingNayuki** [comment]
You mean something like `qmake CONFIG+="x86_64"`? OS X is 64-bit only since years ago and x64 should be built as default. We should correct it even it's the qmake's problem.
P.S. `CONFIG+="x86_64` does work for me too.
