### ISSUE TITLE
Error with image in MDict Dictionary

### ISSUE THREAD

**Issue by htrung** [goldendict/goldendict#695]
The Golden Dict 1.5.0-RC-533-g5ff9838 has issues in bullet pics (can't show the bullet) with my old dict.
The 1.5.0-RC-517-g38adb08 (Qt 5.5.1-based) version don't have this problem.
The dict here:
https://onedrive.live.com/?authkey=!AJNFfEapY5E7xxg&id=C4BBB0BD147AFCA2!107&cid=C4BBB0BD147AFCA2

Thanks

**Comment by Abs62** [comment]
Try [goldendict-1.5.0-RC-536-ga6d7e20](http://www.mediafire.com/download/cpckbyfj3ea2skz/goldendict-1.5.0-RC-536-ga6d7e20%28EXE+only%29.7z) over last EA build.

**Comment by htrung** [comment]
It worked like a charm !
Thank you  very much!
