### ISSUE TITLE
Goldendict exhausts too much CPU on windows 10. 

### ISSUE THREAD

**Issue by codetrainee** [goldendict/goldendict#699]
Version: GoldenDict-1.5.0-RC-616-g5731349_(QT_560)(64bit)
Platform: Windows 10 64-bit(up to date)

After adding one or more dictionaries, GoldenDict uses up too much CPU, whether it is running in the front or background. It is always taking about 30% of CPU. However, if all dictionaries are removed, the  CPU's percentage used by GoldenDict can't be ignored. 
![dictionaries added](https://cloud.githubusercontent.com/assets/8357863/14853891/bb302c1e-0cd0-11e6-91c4-1d23c99d7b34.png)
![without dictionaries](https://cloud.githubusercontent.com/assets/8357863/14853888/ba4487dc-0cd0-11e6-923b-47c713185773.png)

**Comment by Abs62** [comment]
Most likely it is dictionaries indexation for full-text search. Look status line.

**Comment by codetrainee** [comment]
Thanks. Disabling full-text search really resolves the problem. It seems that it is not only on windows 10 but also on windows 7. And the resolution works as well.
