### ISSUE TITLE
epwing_book.hh:25:19: fatal error: eb/eb.h: No such file or directory

### ISSUE THREAD

**Issue by svetlemodry** [goldendict/goldendict#705]
Hi all!
Building the latest RC2 with Qt5 in a clean chroot on an up to date Arch Linux system ends with the below error message:

...
g++ -c -pipe -rdynamic -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -W -D_REENTRANT -fPIC -DHAVE_X11 -DPROGRAM_DATA_DIR=\"/usr/share/goldendict/\" -DPROGRAM_VERSION=\"1.5.0-RC2+git\" -DMAKE_EXTRA_TIFF_HANDLER -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WEBKITWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_HELP_LIB -DQT_WIDGETS_LIB -DQT_WEBKIT_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -I. -Iqtsingleapplication/src -isystem /usr/include/hunspell -isystem /usr/include/qt -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWebKitWidgets -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtHelp -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtWebKit -isystem /usr/include/qt/QtX11Extras -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtXml -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtCore -Ibuild -Ibuild -I/usr/lib/qt/mkspecs/linux-g++ -o build/epwing_book.o epwing_book.cc
g++ -c -pipe -rdynamic -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -W -D_REENTRANT -fPIC -DHAVE_X11 -DPROGRAM_DATA_DIR=\"/usr/share/goldendict/\" -DPROGRAM_VERSION=\"1.5.0-RC2+git\" -DMAKE_EXTRA_TIFF_HANDLER -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WEBKITWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_HELP_LIB -DQT_WIDGETS_LIB -DQT_WEBKIT_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -I. -Iqtsingleapplication/src -isystem /usr/include/hunspell -isystem /usr/include/qt -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWebKitWidgets -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtHelp -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtWebKit -isystem /usr/include/qt/QtX11Extras -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtXml -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtCore -Ibuild -Ibuild -I/usr/lib/qt/mkspecs/linux-g++ -o build/epwing_charmap.o epwing_charmap.cc
In file included from epwing.cc:4:0:
epwing_book.hh:25:19: fatal error: eb/eb.h: No such file or directory
 #include <eb/eb.h>
                   ^
compilation terminated.
Makefile:3624: recipe for target 'build/epwing.o' failed
make: *** [build/epwing.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from epwing_book.cc:4:0:
epwing_book.hh:25:19: fatal error: eb/eb.h: No such file or directory
 #include <eb/eb.h>
                   ^
compilation terminated.
Makefile:3641: recipe for target 'build/epwing_book.o' failed
make: *** [build/epwing_book.o] Error 1

**Comment by Abs62** [comment]
Have you read Readme.md? Install libeb16-dev package or use "CONFIG+=no_epwing_support" key for qmake to build GD without Epwing support.

**Comment by svetlemodry** [comment]
Thanks for the quick pointer!
