### ISSUE TITLE
MDict format: audio script added automatically by GoldenDict is wrongly displayed

### ISSUE THREAD

**Issue by PurlingNayuki** [goldendict/goldendict#709]
In some MDict dictionaries, the script added by GoldenDict automatically to sound icon with a hyperlink `sound://xxxxx` could be wrongly displayed:
![2016-05-27 10 06 34](https://cloud.githubusercontent.com/assets/536792/15595693/dbc4d3be-23f3-11e6-9573-d31b8e58feda.png)
![2016-05-27 10 06 47](https://cloud.githubusercontent.com/assets/536792/15595694/dc035756-23f3-11e6-8272-7740f7c826b6.png)
The exactly same dictionary files used in MDict:
<img width="866" alt="mdict" src="https://cloud.githubusercontent.com/assets/536792/15595695/dc32eb6a-23f3-11e6-9b60-4f5f7a118122.png">

Most of the entries can be well displayed but some of them will make mistakes as above.
Here is a  sample containing 3 entries:
[osd sample.zip](https://github.com/goldendict/goldendict/files/285652/osd.sample.zip)

Thank you!

**Comment by Abs62** [comment]
Change ".ifs-g *" selector in "osd.css" to ".ifs-g *:not(script)".

**Comment by PurlingNayuki** [comment]
It works, thank you. But is it a bug, or what else?

**Comment by Abs62** [comment]
When you turn on visibility for "script" element browser will show it. It is normal behavior.

**Comment by PurlingNayuki** [comment]
What makes it strange is that only scripts in some entries are not displaying well. Most of the entries are displayed as expected.
Anyway the issue is gone, and thank you again.
