### ISSUE TITLE
Cannot play sound archlinux

### ISSUE THREAD

**Issue by ifooyoyo** [goldendict/goldendict#710]
WARNNING: FFmpeg audio Player ao_open_live() failed: can not open the device pluse channel 1, rate 22050, bit 16，I changed the file /etc/libao.conf alsa to pulse and it still not work.

**Comment by ifooyoyo** [comment]
at first,it doesnot work,then I reboot,and finally it works!,here is my solution:
changed the file /etc/libao.conf,
 default_driver=alsa 
……
after change:
default_driver=pulse
then restart

**Comment by 1345472228** [comment]
Thanks
