### ISSUE TITLE
fails to build on Big Endian 64 bit machines

### ISSUE THREAD

**Issue by LocutusOfBorg** [goldendict/goldendict#714]
Hi, as said, seems that 
```  
uint64_t finalcount = qFromLittleEndian( count << 3 );
```
on ripemd.cc is not available on 64 bit BE machines
```
build/ripemd.o: In function `unsigned long qFromLittleEndian<unsigned 
long>(unsigned long)':
/usr/include/qt4/QtCore/qendian.h:344: undefined reference to `unsigned long 
qbswap<unsigned long>(unsigned long)'
collect2: error: ld returned 1 exit status
Makefile:424: recipe for target 'goldendict' failed
```

can you please help? Note: this is preventing Debian and Ubuntu from having in stable the latest release/snapshot

**Comment by Abs62** [comment]
Try to buid now.

**Comment by LocutusOfBorg** [comment]
Hi, how can your solution work?
```diff
 -  uint64_t finalcount = qFromLittleEndian( count << 3 );
+  quint64 finalcount = qFromLittleEndian( count << 3 ); 
```
the problem is that qFromLittleEndian doesn't take a 64byte parameter.
Do you want me to test your commit?

**Comment by Abs62** [comment]
>>the problem is that qFromLittleEndian doesn't take a 64byte parameter

qendian.h have qbswap template for quint64 (defined as "unsigned long long" in qglobal.h) parameter but haven't it for uint64_t (defined as "unsigned long" on UNIX-like systems).

>>Do you want me to test your commit?

Yes.

**Comment by LocutusOfBorg** [comment]
working flawlessly!
the build has finished a few seconds ago. thanks!
