### ISSUE TITLE
May shortcut be used to set focus rather than closing window.

### ISSUE THREAD

**Issue by regs01** [goldendict/goldendict#717]
Especially when using option ESC to hide. So if window is hidden, bring window and set focus to search field. If window is open, set focus to search field by a shortcut rather than hiding the window.

**Comment by Abs62** [comment]
To set focus to search line you can use "Ctrl+L" or "Alt+D" shortcuts.

**Comment by regs01** [comment]
yeah, but a single shortcut greatly increases usability.

**Comment by regs01** [comment]
> Is this feature request a duplicate of #630?
Looks like forgot about that one.

> Do you know that just starting to type a word automatically gives focus to the translate line?
No, i didn't. It is indeed helps a lot.

**Comment by vedgy** [comment]
Please close the duplicate issue, and perhaps even this one if you no longer need this feature.
