### ISSUE TITLE
Can't play online audio file(no sound)

### ISSUE THREAD

**Issue by OZv** [goldendict/goldendict#721]
ver: 1.5.0-RC2-21-gdb6f369_(QT_561)
OS: WinXP sp3

No sound when playing online pronunciation audio file.
Start GoldenDict with debug-mode, found the following message in the log file:
Warning: defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
=======
I compared "mediaservice/dsengine.dll" file with the old version, there is difference as below:
version 5.5.1.0: Size 223KB
version 5.6.1.0: Size 284KB
And if I replace the new 5.6.1.0 DLL file with the old 5.5.1.0 one, it works fine.
I guess there may be some APIs changed in Qt5.6.1, please have a check.

**Comment by Abs62** [comment]
It is not APIs changes. Just dsengine plugin since 5.6.0 by default use EVR  which use MF and DXVA2 which don't work on XP.  
Try - [dsengine_5.6.1_for_XP.7z](http://www.mediafire.com/download/6obcsw3xkkt2zyu/dsengine_5.6.1_for_XP.7z)

**Comment by OZv** [comment]
It works. Thanks a lot.
