### ISSUE TITLE
Please add file Changelog

### ISSUE THREAD

**Issue by nemysis** [goldendict/goldendict#723]
I not find Changelog for Releases from 1.0.1 to 1.5.0-RC2

Here not write this

http://goldendict.org/changelog.php

Please add on GitHub file ChangeLog for all Releases.
Thanks.

**Comment by Abs62** [comment]
Read about early access builds in [GD wiki](https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows).

**Comment by nemysis** [comment]
Thanks many.
