### ISSUE TITLE
64-bit version failed to load the dictionaries

### ISSUE THREAD

**Issue by w13508** [goldendict/goldendict#725]
When 64-bit SW is installed and opened, there is popup saying -
EB library report error EB "eb_bind" function error: EB_ERR_FAIL_OPEN_CAT (failed to open a catalog file). Then click Ok button of the popup, there is no any dictionary loaded.
32-bit version is also installed in same computer, no this problem.

OS - Windows 8.1 Enterprise
GoldenDict - 1.5.0-RC2-21-gdb6f369

**Comment by Abs62** [comment]
Try to replace libeb-16.dll in 64-bit version by [this one](http://www.mediafire.com/download/500yqhl3pq37we9/libeb-16.dll.7z).

**Comment by w13508** [comment]
Hello,
Yes, now it's working.

Date: Thu, 30 Jun 2016 03:35:30 -0700
