### ISSUE TITLE
Making scan popup window larger

### ISSUE THREAD

**Issue by light2yellow** [goldendict/goldendict#726]
Is there a way to resize this window? Or set a default geometry? I know that I can affect the text in it, but on 4k display this is not enough. Only 10-15 words fit into it.

**Comment by Abs62** [comment]
Just pin down popup window by button in upper right corner and resize it by mouse as any other window.

**Comment by light2yellow** [comment]
Thanks a lot! I knew I've done this before, but have forgotten.
