### ISSUE TITLE
Equations are too small

### ISSUE THREAD

**Issue by klonuo** [goldendict/goldendict#731]
This is latest git pre-release. Zoom is normal, 100%:

![untitled](https://cloud.githubusercontent.com/assets/361447/16714724/65d680ca-46cc-11e6-9f18-818dbba87232.png)

**Comment by Abs62** [comment]
You can use [Mimetex](http://www.forkosh.com/mimetex.html) for rendering of TeX equations. Just place mimetex.cgi beside GD executable.

**Comment by klonuo** [comment]
Thanks, but `mimetex.cgi` is already in GD folder. I checked and it is included in GD pre-release.

Now I removed `mimetex.cgi`, but its just the same.

**Comment by klonuo** [comment]
Further I'm generating articles implemented as program dictionaries. Some use mathjax to render equations. For example, when I select article, equations are shown fine while mathjax is still rendering:

![untitled](https://cloud.githubusercontent.com/assets/361447/16715683/6ae2a254-46e7-11e6-949d-f52d261773d1.png)

Then after 2-3sec, when rendering finishes, equations are reduced for some reason, finally yielding in unreadable content:

![untitled2](https://cloud.githubusercontent.com/assets/361447/16715687/9e7cf452-46e7-11e6-9dbd-0e51cf932369.png)

I tried with and without `mimetex.cgi`, to see same result.

**Comment by Abs62** [comment]
[goldendict-1.5.0-RC2-158-g4b0df85(EXE only).7z](http://www.mediafire.com/file/120snw8lwbn58op/goldendict-1.5.0-RC2-158-g4b0df85%28EXE+only%29.7z)
