### ISSUE TITLE
Web results for french : unicode issue?

### ISSUE THREAD

**Issue by Yomgui33** [goldendict/goldendict#733]
Hi, 

I’m trying to figure out how to get proper french results from Linguee inside GoldenDict, using this URL:

http://www.linguee.fr/francais-anglais/search?source=anglais&query=%GDWORD%

My problem is that all accented letters are displayed as �. Is there any way to display the results correctly?

(I tried searching the previous issues but didn’t find anything, sorry if this was asked before)

Thanks.

**Comment by Abs62** [comment]
Turn on "As link" option for this dictionary.

**Comment by Yomgui33** [comment]
Thanks a lot! 

Easy fix. I feel dumb to have missed that.
