### ISSUE TITLE
no "Copy" option in context menu

### ISSUE THREAD

**Issue by userko** [goldendict/goldendict#737]
When click on word in the dictionary entry, there are the following options: "Select Current Article," "Select All," [the list of dictionaries where the word was found], and "Inspect". But there is no "Copy" option. It is available and very much appreciated in the 1.0.1 of the GoldenDict. Please add it in the next compilation. Thank you!

**Comment by Abs62** [comment]
No selection - no "copy" in context menu. It is standard behaviour.
