### ISSUE TITLE
no interaction while browsing through the results in the search box

### ISSUE THREAD

**Issue by userko** [goldendict/goldendict#738]
Another very useful function available in Goldendict 1.0.1 is an instant switching to the dictionary entry when browsing (by pressing the "Up" or "Down" arrows) through the results in the search box. In 1.5.0-RC2-21-gdb6f369, when browsing through such 'context menu' one has to hit "Enter" every time, which is far less productive, than if the entries showed automatically. Please add this functionality in the next release. Thank you!

**Comment by Abs62** [comment]
You can just to turn on old interface instead of new browser-like one (View -> Search pane).

**Comment by userko** [comment]
So easy and it works ! Thanks a lot !
