### ISSUE TITLE
doubleclick translates the word clicked

### ISSUE THREAD

**Issue by Golddouble** [goldendict/goldendict#744]
**System:**
Windows 7 32bit
GoldenDict Version: 1.5.0-RC2

**I have made the following settings:**
![goldendict](https://cloud.githubusercontent.com/assets/13977359/17642036/bae3a798-6137-11e6-842d-1da5f9ae05df.PNG)

**What I have expected:**
I can now in each application doubleclick a word and this word should be translated through GoldenDict. For example in Firefox, notepad, Microsoft Word.

**What happend:**
I can doubleclick a word in Firefox, notepad or Microsoft Word but nothing happens.
Only if I doubleklick a word within GoldenDict himself, then this works.

**Would be great if this would work in each application in Windows 7 32bit.** Works this with Linux?

**Comment by Abs62** [comment]
This settings is for GD articles only and don't touch other applications.

**Comment by Golddouble** [comment]
Thank you.
In this case it is a feature request to implement the possibility to use this behaviour also in other applications. 
This is for example implemented in Lingoes.

**Comment by MinJunGitHub** [comment]
doubleclick translates the word clicked

**Comment by MinJunGitHub** [comment]
I wanna this feature!
