### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by lipanXJ** [goldendict/goldendict#750]
I am using V1.5-rc2  in openSUSE now,when i open goldendict,goldendict's cpu usage become high,and fan run fast,is something i am doing wrong?(i use five *mdx dictionaries)

**Comment by xtalazen** [comment]
Yes, I can confirm. The same behavior of the program in Ubuntu 16.04.1 Unity. If the program is active and focused window processor loaded for some time by 35% and then stops. If the program is minimized to the system tray program starts shipping the processor to 35% of the time.

**Comment by Abs62** [comment]
Read GD help about full-text search.

**Comment by xtalazen** [comment]
@Abs62  Yes to disconnect search the full text of the problem went away. Thanks for the tip! What influences included the full text search? I did not notice the difference. It accelerates the search speed?

**Comment by Abs62** [comment]
Full-text search allow to search words inside dictionary articles instead of search in headwords.

**Comment by xtalazen** [comment]
@Abs62 And I seem to have understood. It allows you to find the word in its description or synonyms?

**Comment by Abs62** [comment]
It allows to search articles by words/phrases in its content, not by headword.

**Comment by xtalazen** [comment]
@Abs62 about how much time it may take this process on a modern computer with a dual-core processor under the condition that Wikipedia is disabled and active seven dictionaries?

**Comment by Abs62** [comment]
It depends on size and complexity of dictionary. From seconds for simple and small dictionary to several hours for big one.
