### ISSUE TITLE
using "https://de.wiktionary.org/w" offline possible?

### ISSUE THREAD

**Issue by Golddouble** [goldendict/goldendict#753]
In the menu "dictionaries" there is a tab "wikipedia". I made a hook by "https://de.wiktionary.org/w".
So I am able to use this wordbook.

**Question:** Is there a way to use "https://de.wiktionary.org/w" offline together with **GoldenDict**?

**Comment by Abs62** [comment]
No, of course. But you can use converted offline dictionaries in Slob/Zim/Aard format. For examply look [here](https://github.com/itkach/slob/wiki/Dictionaries).

**Comment by Golddouble** [comment]
Thank you. This is what I was looking for.

**Comment by 07151129** [comment]
It actually is possible, if you host a dump of Wiktionary locally.

**Comment by Golddouble** [comment]
@07151129 
Thank you for mention that.
But I am not able to get any benefit of your contribution.
Can you make a step by step guidance?

**Comment by 07151129** [comment]
See [this](https://de.wiktionary.org/wiki/Wiktionary:Download) page. It describes what is needed to host Wiktionary locally. Note that it is probably easier to use converted dictionaries, as @Abs62 suggested.
