### ISSUE TITLE
Empty spaces (no text) in some dictionaries (no fonts or smth. else)

### ISSUE THREAD

**Issue by barmaley321** [goldendict/goldendict#754]
Hello everyone. I'm using the same dictionaries in Windows and Linux (the same "content" folder) but in Linux (Arch, Awesome WM) I can see empty spaces in some dictionaries.
Please, look at the screenshots. Normal one:
![image](https://cloud.githubusercontent.com/assets/18070140/18511183/2fa9d09a-7aa4-11e6-8684-f185e59753be.png)

Something wrong here with Longman Dict (only "play sound" icons):
![image](https://cloud.githubusercontent.com/assets/18070140/18511602/69a943be-7aa6-11e6-8746-524e700b16ec.png)

WordNet (only dashes):
![image](https://cloud.githubusercontent.com/assets/18070140/18511639/a41ba280-7aa6-11e6-8add-69fa429a3698.png)
and with selection: 
![image](https://cloud.githubusercontent.com/assets/18070140/18511685/f67744d0-7aa6-11e6-85a8-4c9bddab8f9c.png)
(it looks like no text here at all)

**Comment by Abs62** [comment]
Read GD help about Preferences/Advanved/Articles parameters.

**Comment by barmaley321** [comment]
Thank you for you advice! I solved this issue
