### ISSUE TITLE
[FEATURE REQUEST]dict groups drop-down menu

### ISSUE THREAD

**Issue by cronel** [goldendict/goldendict#758]
# **please stretch dict groups drop-down menu to fit entire goldendict's  height .**

<img width="960" alt="capture" src="https://cloud.githubusercontent.com/assets/11556026/18622590/b0d9ad20-7e46-11e6-854f-2cd90823b516.PNG">

**Comment by Abs62** [comment]
[goldendict-1.5.0-RC2-164-ga0c60d0(EXE only).7z](http://www.mediafire.com/file/s62ajcbnsjsk39s/goldendict-1.5.0-RC2-164-ga0c60d0%28EXE+only%29.7z)
