### ISSUE TITLE
mdict: be firing/shooting blanks (bug)

### ISSUE THREAD

**Issue by amazon200code** [goldendict/goldendict#771]
source: `<a href="entry://be firing/shooting blanks">be firing/shooting blanks</a>`
convert: 
`<a href="gdlookup://localhost/be firing?gdanchor=g5f5d9f31575ca51a8d06b427d9f8b16b_7fd2833641f0_shooting blanks">be firing/shooting blanks</a>`

`gdlookup://localhost/be firing?gdanchor***`

It should be: 
`gdlookup://localhost/be firing%2fshooting blanks?gdanchor***`
or
`gdlookup://localhost/be firing/shooting blanks?gdanchor***`

??

**Comment by Abs62** [comment]
Can you give a link to such dictionary example?

**Comment by amazon200code** [comment]
http://www.pdawiki.com/forum/forum.php?mod=viewthread&tid=18880&extra=page%3D1
download:
url:http://pan.baidu.com/s/1i44GnZZ
password:hasl

>entry:blank(noun)
>>phrases
>>>be firing/shooting blanks

**Comment by Abs62** [comment]
Try: [goldendict-1.5.0-RC2-37-gf0256b2(EXE only).7z](http://www.mediafire.com/file/5fg8km0onvyxkdz/goldendict-1.5.0-RC2-37-gf0256b2%28EXE+only%29.7z)

**Comment by amazon200code** [comment]
It works! Thanks a lot.
