### ISSUE TITLE
dictinary  content  missing(bug)

### ISSUE THREAD

**Issue by zongou** [goldendict/goldendict#772]
I'm using goldendict both on my cellphone and computer, i found there is a very serious problem in goldendict with displaying on computer when i compare to the cellphone
check these screenshots out:
![pc](https://cloud.githubusercontent.com/assets/23202896/19913279/1d480d78-a0dc-11e6-8806-6a9606dfcaea.PNG)
and check the displaying on my andriod cellphone
![screenshot_2016-11-02-08-50-34 1](https://cloud.githubusercontent.com/assets/23202896/19913310/692cab9a-a0dc-11e6-9a65-2af1527744e1.png)
it's same dictionary
it has no problem displaying on my cellphone, but as you can see lots of information missing on pc.
that dictionary was downloaded from goldendict's  site, you can find it here:http://downloads.sourceforge.net/goldendict/WordNet3.0_1.0.zip
the goldendict i downloaded from here:https://sourceforge.net/projects/goldendict/files/early%20access%20builds/GoldenDict-1.5.0-RC2-36-gc689487-Install.exe/download

**Comment by Abs62** [comment]
Read GD help about Preferences/Advanced/Articles options.

**Comment by zongou** [comment]
thanks, problem solved
