### ISSUE TITLE
 How to remove the dictionary name in the text 

### ISSUE THREAD

**Issue by piiiiq** [goldendict/goldendict#773]
![capture1](https://cloud.githubusercontent.com/assets/20429161/19926022/6117662e-a12d-11e6-8b88-c04853dbd2f6.PNG)

**Comment by Abs62** [comment]
Via artycle-style.css file (read GD help about user styles).

    .gddicttitle,.gddicticon
    {
    display:none;
    }

**Comment by xiaoyifang** [comment]
can be closed and all other fixed issues.
