### ISSUE TITLE
Looking up with double-click doesn't work on Welcome(start) page

### ISSUE THREAD

**Issue by GeneralFailer** [goldendict/goldendict#782]
"No translation for *word* was found in group help." message is displayed.

GoldenDict 1.5.0RC2
Arch Linux w/ Xfce

**Comment by Abs62** [comment]
GD search word selected by double click on tab in group corresponded this tab (with which one was opened). "Welcome" page corresponds some special group without dictionaries.

**Comment by GeneralFailer** [comment]
OK, though seems kinda unintuitive.
