### ISSUE TITLE
Doesn't launch on Linux with Hunspell 1.5

### ISSUE THREAD

**Issue by homocomputeris** [goldendict/goldendict#784]
Hi! GD produces this error:
`goldendict: error while loading shared libraries: libhunspell-1.4.so.0: cannot open shared object file: No such file or directory`
Maybe GD should at least launch, and only then notify that morphology dics are unavailable? 

GoldenDict 1.5.0.RC2.24.gb236612-1
Hunspell 1.5.3-1

**Comment by light2yellow** [comment]
I experience this problem as well.

    $ hunspell -v
    @(#) International Ispell Version 3.2.06 (but really Hunspell 1.5.3)

```
$ pacman -Ql hunspell
hunspell /usr/
hunspell /usr/bin/
hunspell /usr/bin/affixcompress
hunspell /usr/bin/analyze
hunspell /usr/bin/chmorph
hunspell /usr/bin/hunspell
hunspell /usr/bin/hunzip
hunspell /usr/bin/hzip
hunspell /usr/bin/ispellaff2myspell
hunspell /usr/bin/makealias
hunspell /usr/bin/munch
hunspell /usr/bin/unmunch
hunspell /usr/bin/wordforms
hunspell /usr/bin/wordlist2hunspell
hunspell /usr/include/
hunspell /usr/include/hunspell/
hunspell /usr/include/hunspell/atypes.hxx
hunspell /usr/include/hunspell/csutil.hxx
hunspell /usr/include/hunspell/htypes.hxx
hunspell /usr/include/hunspell/hunspell.h
hunspell /usr/include/hunspell/hunspell.hxx
hunspell /usr/include/hunspell/hunvisapi.h
hunspell /usr/include/hunspell/w_char.hxx
hunspell /usr/lib/
hunspell /usr/lib/libhunspell-1.5.so
hunspell /usr/lib/libhunspell-1.5.so.0
hunspell /usr/lib/libhunspell-1.5.so.0.0.0
hunspell /usr/lib/libhunspell.so
hunspell /usr/lib/pkgconfig/
hunspell /usr/lib/pkgconfig/hunspell.pc
hunspell /usr/share/
hunspell /usr/share/locale/
hunspell /usr/share/locale/es/
hunspell /usr/share/locale/es/LC_MESSAGES/
hunspell /usr/share/locale/hu/
hunspell /usr/share/locale/hu/LC_MESSAGES/
hunspell /usr/share/locale/it/
hunspell /usr/share/locale/it/LC_MESSAGES/
hunspell /usr/share/man/
hunspell /usr/share/man/hu/
hunspell /usr/share/man/hu/man1/
hunspell /usr/share/man/hu/man1/hunspell.1.gz
hunspell /usr/share/man/man1/
hunspell /usr/share/man/man1/hunspell.1.gz
hunspell /usr/share/man/man1/hunzip.1.gz
hunspell /usr/share/man/man1/hzip.1.gz
hunspell /usr/share/man/man3/
hunspell /usr/share/man/man3/hunspell.3.gz
hunspell /usr/share/man/man5/
hunspell /usr/share/man/man5/hunspell.5.gz
```

@virtualtam please keep an eye on this to update accordingly when the fix will be ready.

**Comment by ShevoPramide** [comment]
yes this happened to me too and i dont what should i do as this updated package is needed by other apps.

**Comment by homocomputeris** [comment]
A workaround is disabling the morphology setting.

**Comment by Abs62** [comment]
Just build GD with appropriate hunspell library. Or with static library instead of shared one.

**Comment by homocomputeris** [comment]
Mb, just fix it in the upstream, so that GD would search for 1.6 shared library instead of 1.4? As it was noted, FF also depends on the new version, which is 1.6 already, BTW.

**Comment by Abs62** [comment]
GD builded with Hunspell 1.4 will search 1.4 shared library. GD builded with Hunspell 1.6 will search 1.6 shared library. GD builded with static Hunspell library will not search shared library at all. It is not depended from GD source code.

**Comment by homocomputeris** [comment]
@Abs62 that's a much clearer explanation, thanks.

**Comment by ShevoPramide** [comment]
so if i rebuild GD, it will work again ?!

**Comment by Abs62** [comment]
Yes, if you build it with actual Hunspell version.
