### ISSUE TITLE
Scan Pop-up in Mozilla Firefox on Windows 8.1 not working.

### ISSUE THREAD

**Issue by fxt3** [goldendict/goldendict#788]
Hello. Scan pop-up in Mozilla Firefox and Tor Browser on Windows 8.1 x64 edition not working. All Options in GoldenDict (Preferences->Advanced) for scan pop-up enabled, but in Internet Explorer and other applications like Notepadd+ scan works fine, but i don't use Internet Explorer. I use Mozilla Firefox 64-bit Edition, but Tor Browser Bundle based on Mozilla Firefox 32-bits. In all versions (32 and 64 bits) scan pop-up not working.

**Comment by Abs62** [comment]
Douplicate of issue #29
