### ISSUE TITLE
Build for Qt 5.6/5.7

### ISSUE THREAD

**Issue by samerafach** [goldendict/goldendict#798]
Is there a build for Windows with Qt 5.6 or 5.7? I tried to build it myself, and it's not as simple as it sounds. Previous versions of Qt have a problem with QHD and 4K displays that the scaling is not automatically. If that's not possible, a build with version 5.5 is OK, since it supports manual scaling using QT_DEVICE_PIXEL_RATIO environment variable.

I never dealt with Webkit, and this took 6 hours and I still couldn't do it. Every time there's something wrong or some dependency missing.

Please provide such builds for download. Honestly, I don't believe all these commits and comments about version 5.6 are there, and yet there's not a single built version available for download. Could someone please provide that? I'm happy to host this on my website and/or my server if that's the problem.

Thanks!

**Comment by darnn** [comment]
Did you try here? https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows

**Comment by samerafach** [comment]
Oh! Thanks a lot! Please put that link in the main repository's readme. Have a nice day!

**Comment by darnn** [comment]
I would, but I'm not part of the project...
