### ISSUE TITLE
Search Hotkey to main window

### ISSUE THREAD

**Issue by MichailBachtin** [goldendict/goldendict#802]
There should be an option to open the main window with a hot-key search.
The main window has the "found in dictionaries" list on the right, which makes it easier to choose quickly a specific source after the search.

Alternatively, is there an option to include the "Found in Dictionaries" sidebar to the popup window?

One or the other would be a great option!

**Comment by Abs62** [comment]
You can use "Send translated word to main window" option to use main window instead of popup one. The popup window is designed for quick search in limited dictionaries number.

**Comment by MichailBachtin** [comment]
Thanks, Abs62, for pointing out this option. What a pleasure! This is why I believe Goldendict is the best thing out there for dictionaries: you can customize it to suit your own preferences!

Thanks again.
