### ISSUE TITLE
Hotkey to close the scan pop-up and options for not scanning in other applications

### ISSUE THREAD

**Issue by ghost** [goldendict/goldendict#81]
It's really inconvenient to get into the interface of GD or right-click the icon to close the function... Also it would be helpful in my opinion to add an option for not scanning in other applications for it's very annoying and it doesn't serve a lot in most cases.

Best regards!

**Comment by yilksd** [comment]
Is there any hotkey or command line options to turn on/off scan popup now?

**Comment by vedgy** [comment]
I have implemented the requested feature in a way. The implementation was merged into master today as 782cede2175f37922362015adb79da16e582602a. As the updated GoldenDict help puts it:
> Assigning a global keyboard shortcut to the `goldendict --toggle-scan-popup` command in system preferences emulates a scanning mode-toggling global hotkey.
