### ISSUE TITLE
The latest cannot run at MACOS Sierra 10.12.4

### ISSUE THREAD

**Issue by lobstergy** [goldendict/goldendict#829]
Today, I freshly download it from https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Mac-OS-X, the latest version: GoldenDict-1.5.0-RC2-85-g473cb2b(Qt_562).dmg

But it cannot be opened on my MacBook Pro 15" 2016. Any idea? Are there have any compatible issues? Plz, help, thanks.

<img width="1524" alt="screenshot 2017-04-14 13 00 25" src="https://cloud.githubusercontent.com/assets/15153547/25033753/4e77f414-2113-11e7-9f05-faeb8afde67c.png">

**Comment by lobstergy** [comment]
Click open, nothing but this pop up:
<img width="617" alt="screenshot 2017-04-14 13 09 57" src="https://cloud.githubusercontent.com/assets/15153547/25033812/c74a93e2-2113-11e7-8a6f-d96ab5c1dc97.png">

**Comment by Abs62** [comment]
Try [Qt 5.8.0-based version](https://sourceforge.net/projects/goldendict/files/early%20access%20builds/MacOS/GoldenDict-1.5.0-RC2-85-g473cb2b%28Qt_580%29.dmg/download).

**Comment by lobstergy** [comment]
@Abs62 It works, charmingly! Thanks, Bro. you're a life saver!
