### ISSUE TITLE
A Problem in the Built-in CSS

### ISSUE THREAD

**Issue by BLKSerene** [goldendict/goldendict#832]
i'm not very sure whether this problem is caused by the built-in CSS
The style applied to the class _gdarticle_ which is the containers for different dictionaries
is marigin-top: -9px and margin-bottom: 8px which in the case of multiple dictionaries being
loaded at the same time will casue the last row of pixels to be overlapped by the dictionary following it

It doesn't matter most of the time, but if a set a bottom border of 1px for the first dictionary, the border
will disappear (be overlapped by the next dictionary).
Then I had to add the line of JavaScript (actually jQuery):
$('.gdarticle').css('margin-top', '-8px') then the problem is solved (plus the top margin by 1)

**Comment by Abs62** [comment]
Fixed in last EA build.

**Comment by and-thus-are-no-longer-available-to-eat** [comment]
> i'm not very sure whether this problem is caused by the built-in CSS
> The style applied to the class _gdarticle_ which is the containers for different dictionaries
> is marigin-top: -9px and margin-bottom: 8px which in the case of multiple dictionaries being
> loaded at the same time will casue the last row of pixels to be overlapped by the dictionary following it
> 
> It doesn't matter most of the time, but if a set a bottom border of 1px for the first dictionary, the border
> will disappear (be overlapped by the next dictionary).
> Then I had to add the line of JavaScript (actually jQuery):
> $('.gdarticle').css('margin-top', '-8px') then the problem is solved (plus the top margin by 1)

If you don't mind me asking, how did you add your user javascript to goldendict? I would very much like to be able to do so
