### ISSUE TITLE
Wish List: A little Bookmark Button in the toolbar

### ISSUE THREAD

**Issue by skywind3000** [goldendict/goldendict#835]
Having been using GD for almost 3 years, I really love it. I know a lot of translators profit from GD every day. 
Thanks for your work.

I lookup nearly 100 words every day in GD. All I want is to mark some of them as "important words" which can be reviewed or studied later. These important words  can also be imported to Anki to get memorized.

A bookmark button is required because a lot of words in the history list is not so important.

Therefor, can we have this bookmark list in GD ? Just like the history list (add/delete/import/export).
In the toolbar, a STAR icon beside the magnifier button can be used to add current word into the bookmark list or remove it from list if it has been previously added.

We can press CTRL-D to bookmark a word or un-bookmark it.
We can browse marked words in the bookmark list window which is hidden by default but could show itself in the "View" menu option, and also it could attach to the window border just like the history window.

Studying / Working will be more productive if we have this "bookmark feature" in GD.

GD is similar to a web browser. A good web browser has bookmark list, a good desktop dictionary should have a bookmark list too.

**Comment by itkind** [comment]
I would love to have this funktion. PLEASE! I will donate 50€

**Comment by skywind3000** [comment]
To some one who can implement this feature, I will also pay him 500€ for appreciation.

**Comment by itkind** [comment]
I saw in the Russian forum, that Abs is already working on this since last week. I think we will have it soon.

**Comment by skywind3000** [comment]
@itkind Do you remember the URL about the topic in the Russian forum ?

**Comment by itkind** [comment]
Sure, but you have to register first:
http://forum.ru-board.com/topic.cgi?forum=5&topic=49149&start=320

**Comment by skywind3000** [comment]
thanks, do you know what does Abs's latest reply mean about the 1.5.0 final release:

```text
Релиз делать некому, вот и весь критерий.
```

Google translation interpreted it as: "Release there is nobody to do, that's the whole criterion."

Do you know what does it mean ?

**Comment by darnn** [comment]
Pretty much what Google Translate says: "There's nobody to make the release, there's your whole criterion."

**Comment by itkind** [comment]
@skywind3000 
If you are already registered, check out the huge dictionary archive:
http://forum.ru-board.com/topic.cgi?forum=93&topic=2618#1

You can also find my dictionaries there.

**Comment by skywind3000** [comment]
What a great treasure it is. 
I also found your dictionaries about judaica, thanks a lot.

**Comment by Abs62** [comment]
Try - [goldendict-1.5.0-RC2-105-g61295ce(EXE only).7z](http://www.mediafire.com/file/b7avwd4jy8b77b8/goldendict-1.5.0-RC2-105-g61295ce%28EXE+only%29.7z) (EXE for [early access builds](https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows) 1.5.0-RC-85).

**Comment by skywind3000** [comment]
Thanks very much, here is some feedback:

It crashed when I am trying to delete two or more items together (folders or words).

![gd1](https://cloud.githubusercontent.com/assets/3035071/26026763/481369e0-3834-11e7-9d97-23d03a14c3a5.png)

And why there is an empty column before the words in the favorite pane, what is it used for ?

At last, can I have a hot key to add current word into favorite list ?

**Comment by Eosphorus** [comment]
First off, great work, Abs62!

'Favorites' is a really useful new feature to an already great program. And funny thing is: I didn't know that I missed it until just now.

Ok, it needs some refinement though. I can confirm those crashes, see below. But it doesn't give out every time I delete some words; it seems rather erratic.

Where is that bug?!

![screenshot - 13 05 2017 18_25_15](https://cloud.githubusercontent.com/assets/8929191/26027330/8c9a36ca-380c-11e7-8d90-a1fecd3894c3.png)

**Comment by Abs62** [comment]
>> It crashed when I was trying to delete two or more items together (folders or words).  

Fixed - [goldendict-1.5.0-RC2-107-g2bf4c51(EXE only).7z](http://www.mediafire.com/file/159kaqrjqg3l9oz/goldendict-1.5.0-RC2-107-g2bf4c51%28EXE+only%29.7z).

>> And why there is an empty column before the words in the favorite pane, what is it used for ?

For tree structure as in any TreeView.

>> At last, can I have a hot key to add current word into favorite list ?

Will be "Ctrl+E".

**Comment by itkind** [comment]
@Abs62
Give me your PayPal address, so I can send you the promised 50€.

**Comment by skywind3000** [comment]
@Abs62 
Thank you for the favorite pane, I am ready to make the payment now.

**Comment by skywind3000** [comment]
Having invited almost 10 people to test and got some feedback:

1. Never crash while deleting items.

2. The preview window (you know, the Ctrl-C-C Window) also needs a favorite button and CTRL-E hotkey:

![favorite](https://cloud.githubusercontent.com/assets/3035071/26045335/496664c0-397c-11e7-8d61-b52f3e6c71c9.png)

When they were reading fictions they preferred to use preview window rather than the main GD window.
And most of them wanted a "star button" (also CTRL-E) in the preview window.

**Comment by Abs62** [comment]
OK - [goldendict-1.5.0-RC2-111-gb86f680(EXE only).7z](http://www.mediafire.com/file/bxuxagedhfu3cga/goldendict-1.5.0-RC2-111-gb86f680%28EXE+only%29.7z).

**Comment by Abs62** [comment]
New help files you can take [from GD sources](https://github.com/goldendict/goldendict/tree/master/help).

**Comment by Eosphorus** [comment]
Since I usually (well... sometimes) know what I am doing, how can I suppress the inquiry when deleting an item on the list?
"All selected items will be deleted. Continue?"

For now, I commented these code lines in file "favoritespanewidget.cc" out:

/*
  QMessageBox mb( QMessageBox::Warning, "GoldenDict",
                  tr( "All selected items will be deleted. Continue?" ),
                  QMessageBox::Yes | QMessageBox::No );
  mb.exec();
  if( mb.result() != QMessageBox::Yes )
    return;
*/

But for convenienc's sake, an option in 'Preferences' would be nice here.

**Comment by Abs62** [comment]
OK - [goldendict-1.5.0-RC2-113-g182449f(EXE only).7z](http://www.mediafire.com/file/1xz4y7g59gk4i3q/goldendict-1.5.0-RC2-113-g182449f%28EXE+only%29.7z).

**Comment by skywind3000** [comment]
After 20 days, I believe the favorite pane is stable enough.
Only this picture can express our gratitude:

![panda](https://cloud.githubusercontent.com/assets/3035071/26821794/41ad556c-4ada-11e7-85ed-a7d60a21b29b.gif)

Expecting next release on https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows ??

Has it been planned ?

**Comment by Abs62** [comment]
Planned. At the right time or some later.
