### ISSUE TITLE
Some links in Stardict dictionaries no longer work

### ISSUE THREAD

**Issue by embar-** [goldendict/goldendict#846]
Somewhere between 1.5.0rc2.git.20161226T19173 and 1.5.0rc2+git.20170314T174738 GoldenDict stopped to follow some links, if I press link in article. 

If I press F12 to inspect source, I see for working links:

`<a href="bword:my_link">my_link</a>` 
or
`<a title="my_link" href="my_link">my_link</a>`

For **no longer working** links I see:
 `<a href="bword://my_link">my_link</a>` 
or
 `<a title="my_link" href="bword://my_link">my_link</a>`

I attach simple sample dictionary for testing with its source code.

[test.zip](https://github.com/goldendict/goldendict/files/1045744/test.zip)

**Comment by Abs62** [comment]
Should be fixed now.

**Comment by embar-** [comment]
I recompiled GoldenDict and tested. Thank you - it works!

**Comment by Abs62** [comment]
OK.
