### ISSUE TITLE
flag for scan popup

### ISSUE THREAD

**Issue by embar-** [goldendict/goldendict#848]
Xiaoguang Wang created nice patch to show flying icon, that will open scan-popup window, see:
https://build.opensuse.org/package/view_file/home:xiaoguang_wang:branches:my_goldendict/goldendict-master/add-scan-flag.patch?expand=1

Your can test it by installing RPM package from Xiaoguang Wang repository: http://download.opensuse.org/repositories/home:/xiaoguang_wang:/branches:/my_goldendict/

Patch:
[add-scan-flag-patch.txt](https://github.com/goldendict/goldendict/files/1045806/add-scan-flag-patch.txt)

See also
[example.zip](https://github.com/goldendict/goldendict/files/1045833/example.zip)

**Comment by sunwxg** [comment]
I created pull request https://github.com/goldendict/goldendict/pull/822 for this function.
Thanks for the video.

**Comment by llity** [comment]
Thanks, I used AHK can get word in Chrome, adobe acrobat.

**Comment by embar-** [comment]
I see newest version of patches live here:
https://github.com/goldendict/goldendict/pull/849

**Comment by Abs62** [comment]
Done.
