### ISSUE TITLE
GD Mobile crashes on LineageOS 14.1

### ISSUE THREAD

**Issue by quicktrick** [goldendict/goldendict#850]
Hi!

Samsung Galaxy S4 with external SD card. On CM13 everything was alright. After installing LineageOS 14.1 recently, I got persistent GD crashes when choosing `Additional directory` item in `Preferences`. Apart from that GD is working fine and it finds Lingvo's dictionaries easily. Every other app works perfectly (except maybe QuickPic, that sometimes crashes too). External SD Card is writable, the apps can write to it and I have my GD dictionaries there (that config is inherited from my CM13 times).

**Comment by Abs62** [comment]
Only desktop GD version is discussed here. not mobile. About mobile version ask GD author.

**Comment by quicktrick** [comment]
Ну что уж так сразу закрывать-то. :)  Прошу прощения, конечно, что написал сюда.  Сам понимал, что не по адресу, но боялся, что на форуме GoldenDict мое сообщение долго никто не увидит.  Написал сейчас автору.  Извините, Abs62.  ;)

**Comment by Abs62** [comment]
Так всё равно же без толку - код мобильной версии есть только у автора. Думаю, на письмо он быстрее ответит, потому как сюда уже лет пять как ничего не коммитил.
