### ISSUE TITLE
Do drag-select in Chrome, popup window is weird.

### ISSUE THREAD

**Issue by sunwxg** [goldendict/goldendict#854]
On Linux system, open `scan popup` function, after selecting a word, popup window appears every time.

In Chrome, double click one word, word is selected automatically, and popup window appears well. 
But when you do drag-select in Chrome, popup window appears weirdly. 

After tracing, I find when do drag-select in Chrome, there will be many clipboard-changed events, that means goldendict  has to draw popup window many times in a short time. This let popup window appear weirdly.

In Firefox or pdf-viewer application, if you do drag-select option, goldendict only get one clipboard-changed event, popup window appears well.

Can we find a good way to handle many clipboard-changed events in a short time?

**Comment by sunwxg** [comment]
I try to add a delay timer to solve this.
https://github.com/goldendict/goldendict/pull/855

**Comment by Abs62** [comment]
Why don't you want to use key modifiers?

**Comment by sunwxg** [comment]
Yes, using key modifiers can avoid this problem.

I don't like to show popup window with keyboard cooperation. I just want to use mouse.
So I really want to find a way to solve it.

**Comment by Abs62** [comment]
You can try last git version with scan flag instead of popup window.

**Comment by sunwxg** [comment]
I have tried. scan flag function has same problem. 
Scan flag window will also be weird if drawing many time in a short time.

**Comment by sunwxg** [comment]
I have another idea to solve this problem. When clipboard-changed event happens, we check the mouse button state, if button state is pressed, do nothing. But I don't find a proper API in Qt to check mouse button state.
