### ISSUE TITLE
Display Error on the Dictionary border with the latest version (135-g58e41fe)

### ISSUE THREAD

**Issue by skywind3000** [goldendict/goldendict#859]
**System**: Windows 7 64 bits
**Version**: GoldenDict-1.5.0-RC2-135-g58e41fe_(QT_486)
**Expected Behavior**: Dictionary border will be displayed (just like 85-g473cb2b)
**Actuall Behavior**: Dictionary border disappeared.

Screen capture of version 85-g473cb2b, which display correctly:

![golden1](https://user-images.githubusercontent.com/3035071/27385762-48e27fa4-56c6-11e7-864d-faa8756426b6.png)

Screen capture of version 135-g58e41fe, which display incorrectly (no border):

![golden2](https://user-images.githubusercontent.com/3035071/27385770-4f941f56-56c6-11e7-8c06-50cfb3301f4d.png)

**Comment by Abs62** [comment]
Try - [goldendict-1.5.0-RC2-137-g022682a(EXE only).7z](http://www.mediafire.com/file/fde7radk2netlqe/goldendict-1.5.0-RC2-137-g022682a%28EXE+only%29.7z).

**Comment by skywind3000** [comment]
137-g022682a works fine !

**Comment by dolevu** [comment]
Hello @skywind3000 

How do you get the border like in the picture?
Do you use custom css file? Can you please post it?

Thanks.

**Comment by skywind3000** [comment]
Edit -> Preferences -> Display Style -> Modern

**Comment by xiaoyifang** [comment]
can be closed as fixed
