### ISSUE TITLE
Cannot display examples in Longman dictionary

### ISSUE THREAD

**Issue by Hassenky** [goldendict/goldendict#863]
Hello developers,

I am using the latest version of Goldendict on Windows 7 and Windows 10. Everything is perfect except for one issue. Goldendict on two of three laptops (one windows 7 and one windows 10)  cannot display examples in Longman dictionary as the below image. Can you help me to solve this inconvenience? Thank you in advance .

![error](https://user-images.githubusercontent.com/7237164/27957073-e10fad62-631c-11e7-89a9-ee1dce0bdd28.PNG)

VS 

![error2](https://user-images.githubusercontent.com/7237164/27957085-ec1bc506-631c-11e7-881f-74886c4a1c60.PNG)

Hassenky

**Comment by Abs62** [comment]
Just press "+" icon beside headword. Or Edit -> Preferences -> Advanced -> Expand optional parts.

**Comment by Hassenky** [comment]
Wow, it works perfectly. Thank you so much @Abs62 .
