### ISSUE TITLE
Feature Idea 'Word of the Day'

### ISSUE THREAD

**Issue by Eosphorus** [goldendict/goldendict#868]
Wouldn't it be nice if when you start up GoldenDict a random word/phrase were displayed? Just as on those websites that offer you a new 'word of the day.'

Or, alternatively, you are given the word that you looked up in your last session with GoldenDict. The one at the top of the 'History' list so you can continue where you left off the last time.

Or, for those who already have to deal with enough words around them, you simply get a blank page or the welcome screen as it is now.

And of course there would be a switch in the 'Preferences' window to choose between these options.

Wouldn't this be something?

## **Update:**
Just saw that somebody else beat me to it. So, it's not just me who wants to see this implemented. Quite a relief!

 [Feature Request] Word of the Day #666
Open
perpi opened this Issue on Jan 31, 2016 · 0 comments

Anyway I found these code lines as a starting point ("mainwindow.cc") and changed one thing:

**// Show the initial welcome text
  {
    ArticleView *view = getCurrentArticleView();
...
    view->showDefinition( tr( "success" ), Instances::Group::AllGroupId );
...
  }**

Now, instead of showing the 'Welcome!' message the app shows the dictionary entries for the word 'success' at startup. Well, that's a start.

**Comment by diskotechjam** [comment]
Is it possible to implement this via the article-style.css or qt-style.css files?

**Comment by Eosphorus** [comment]
The long and short of it is no. I've directly modified the C++ source code and recompiled the whole enchilada. And btw, with style sheet files you can only change HOW something is displayed, not WHAT is shown - the content. To implement this feature as described further code needs to be written.
