### ISSUE TITLE
No [ref][/ref] display in the latest 170 build

### ISSUE THREAD

**Issue by konandrom** [goldendict/goldendict#870]
After reindexing, the latest RC2-170 build (QT 4.8.6) doesn't display [ref][/ref] or <<>> coded items properly as it used to do. (Windows 7/10 64).

**Comment by Abs62** [comment]
What exactly is wrong?

**Comment by konandrom** [comment]
I'm so sorry, excuse me, my fault! What was wrong with my formattingt, was [ref] insted of [sup]! It must have been all this hot weather!
