### ISSUE TITLE
Weird tray icon

### ISSUE THREAD

**Issue by brunces** [goldendict/goldendict#873]
Hey, guys. What's up?

I've been a GoldenDict user for a long, long time and I really appreciate the work you have put on this amazing program.

Have you ever considered using a static tray icon instead of a temporary hard coded one? I'm asking this because, first of all, it could be easier, for example, to use monochromed icons on panels, which is a very common approach for most of programs that have tray icons, or indicators, etc. Second, depending on the panel, sometimes the icon gets totally messed up. Check out this screenshot of my desktop, for instance. I use Linux Mint 18.2 with a vertical panel on the left side of the screen. Take a look at how the GoldenDict icon sits weirdly on the panel. It just won't get centered. This is really annoying.

![image](https://user-images.githubusercontent.com/7181488/28998173-0d3c93c4-79fb-11e7-9975-a42b37c0df5e.png)

Well, I hope you consider some kind of fix for this.

Congratulations for the great piece of software you have. I really love it. Cheers. :)

brunces

**Comment by dbogdanov** [comment]
Same issue and feature request here.
