### ISSUE TITLE
goldendict will show file is corrupted if overwritten by different file in same name

### ISSUE THREAD

**Issue by WanderMax** [goldendict/goldendict#881]
After GoldenDict loading one dict file, then exit GoldenDict and overwrite this dict file with different one( same filename). Then open GoldenDict, but it can't reload this dict anymore even do ctrl+F5.
When querying words then GoldenDict shows "Failed loading article from *.mdx, reason: Dictionary file was tampered or corrupted"
Though I do reload all dict file via the menu (ctrl+F5), it still shows this error.
Thanks.

**Comment by 61t** [comment]
You need rebuild index. I am not sure windows. 
For mac, remove dict root path, then add it back. After click rescan now, it will auto rebuild index for all dicts.
