### ISSUE TITLE
I dont konw why i can't see example sentence 

### ISSUE THREAD

**Issue by BOOLMANOR** [goldendict/goldendict#884]
<img width="457" alt="2017-08-29 9 53 04" src="https://user-images.githubusercontent.com/15701805/29824616-94690b40-8d04-11e7-9265-a30cd617d9dc.png">
look like that
i google and find that the windows some version also have this problem but i change two version of dict but it do not change

**Comment by Abs62** [comment]
Read GD help: Preferences -> Advanced -> Articles -> 
Expand optional parts.
