### ISSUE TITLE
Wildcard search doesn't work after v1.5.0-RC2-152

### ISSUE THREAD

**Issue by kyleskimo** [goldendict/goldendict#885]
Not sure if it is known issue.
When using .mdx dictionary, wildcard "*" or "?" in search box doesn't work on v1.5.0-RC2-152, 170 and 175.

For example:
It can use "*olden" or "?olden" to search "golden" in .mdx dictionary before v1.5.0-RC2-135.
But it doesn't work after v1.5.0-RC2-152.

**Comment by Abs62** [comment]
Fixed - [goldendict-1.5.0-RC2-176-g31688d4(EXE only).7z](http://www.mediafire.com/file/lpnpjvozaojpt5m/goldendict-1.5.0-RC2-176-g31688d4%28EXE+only%29.7z).

**Comment by kyleskimo** [comment]
Fixed on v1.5.0-RC2-176.
Thanks.
