### ISSUE TITLE
x-frame-options thing

### ISSUE THREAD

**Issue by icq8680** [goldendict/goldendict#889]
hello! I'm not into a web development and this stuff, but my online entries in goldendict seem to be broken now. when I untick "as link" at the dictionary, everything seems to work fine with one disturbing exception: GoldenDict opens every link from online-entry in default browser (which is just unacceptable)
![image](https://user-images.githubusercontent.com/6546397/30180955-d162af68-943b-11e7-8f0e-47a36ecb2aa3.png)
But when I put a tick back (so it becomes the same it was half a year ago, when everything worked fine), GoldenDict refuses to show an online entry. When I click "Inspect", the console shows me this:
![image](https://user-images.githubusercontent.com/6546397/30181255-d9acfd44-943c-11e7-9408-27355cc7d4c9.png)
I wonder if it is server-sided and whether it is fixable from GoldenDict or not. Should I contact bkrs.info owners to know this? I'm asking, because it _works_ in non-link mode. Thank you

**Comment by Abs62** [comment]
>> I wonder if it is server-sided

[X-Frame-Options](https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/X-Frame-Options)

>> and whether it is fixable from GoldenDict or not

Try last Qt5-based GD version.

**Comment by icq8680** [comment]
> Try last Qt5-based GD version.
![image](https://user-images.githubusercontent.com/6546397/30183514-e2e171e4-9444-11e7-9eec-5dc271b03618.png)
it worked, thanks
