### ISSUE TITLE
Can't load some StarDict Dictionaries from TheFictionary.net

### ISSUE THREAD

**Issue by vmlemon** [goldendict/goldendict#890]
Using GoldenDict revision a4a4012255e65fadc62dcca6985f7e1f25d852cf, on Ubuntu 17.04, built against Hunspell 1.6.2, with ZIM support, and Chinese Conversion enabled, I am unable to load the dictionaries downloaded from http://thefictionary.net/nathan-croft/, and http://thefictionary.net/j-r-r-tolkien/.

Although GoldenDict will attempt to index/parse them, to the point where their titles appear in the loading dialogue, at launch time, I receive the following output; and the dictionaries do not appear in the list of actively installed dictionaries:

<pre>
tyson@tyson-HP-EliteBook-6930p-GB985ET:~$ goldendict 
No favorities file found
Stardict: Building the index for dictionary: Polish-Irish

bookname = Polish-Irish
wordcount = 274
Stardict dictionary initializing failed: /home/tyson/.goldendict/dicts/stardict-freedict2-pol-gle-2.4.2/dictd_freedict2_pol-gle.ifo, error: Can't decode the given string from Utf8: �aciński

Stardict: Building the index for dictionary: Tolkien_Fictionary_1

bookname = Tolkien_Fictionary_1
wordcount = 7102
Stardict dictionary initializing failed: /home/tyson/.goldendict/dicts/Tolkien/Tolkien_v1.ifo, error: Can't decode the given string from Utf8: ( h ) l�k�

Stardict: Building the index for dictionary: Homunculus_and_the_Cat_Fictionary_1

bookname = Homunculus_and_the_Cat_Fictionary_1
wordcount = 166
Stardict dictionary initializing failed: /home/tyson/.goldendict/dicts/Homunculus_and_the_Cat_v1.ifo, error: Can't decode the given string from Utf8: Ankh�Si-Amunet

Load done
Loading 30 abbrv
Loading 11 abbrv
Loading 36 abbrv
Loading 3 abbrv
Loading 171 abbrv
getResource: gdlookup://localhost?blank=1
scheme: gdlookup
host: localhost
getResource: gdlookup://localhost?blank=1
scheme: gdlookup
host: localhost
getResource: gdlookup://localhost?word=Welcome!&group=4294967295
scheme: gdlookup
host: localhost
In-place finish.
====reading 16384 bytes
====reading 43650 bytes

</pre>

**Comment by Abs62** [comment]
Check .ifo files encoding, it must be UTF-8.

**Comment by vmlemon** [comment]
Thanks - it looks like "file" reports: 

<pre>Homunculus_and_the_Cat_v1.ifo: HTML document, Non-ISO extended-ASCII text</pre>, and looking at the file itself, it seems that some characters aren't correctly encoded (e.g. <code>'</code>, is rendered as <code></code>).

GEdit says that the file is of encoding "Western (ISO-8859-15)", and if I fix the offending characters, and resave the file as UTF-8, I still receive:

<pre>
Stardict: Building the index for dictionary: Homunculus_and_the_Cat_Fictionary_1

bookname = Homunculus_and_the_Cat_Fictionary_1
wordcount = 166
Stardict dictionary initializing failed: /home/tyson/.goldendict/dicts/Homunculus_and_the_Cat_v1.ifo, error: Can't decode the given string from Utf8: Ankh�Si-Amunet
</pre>

Even though the string <code>Ankh�Si-Amunet</code> doesn't appear in that IFO file, at all:

<pre>
StarDict's dict ifo file
version=2.4.2
wordcount=166
idxfilesize=2851
bookname=Homunculus_and_the_Cat_Fictionary_1
sametypesequence=h
description= Homunculus and the Cat Fictionary and Reference for Nathan Croft's Books.<p>Copyright © 2015 by Nathan Croft. All Rights Reserved. The right to distribute exclusively granted to Fictionaries, LLC on <a href="http://theFictionary.net/" target="_blank">theFictionary.net</a>  <br>
author=Nathan Croft
</pre>

I suspect that something is upsetting the parser, in another file (maybe the "dictd_freedict2_pol-gle.ifo", which "file" reports as just "ASCII text"?), but there's no malformed content in it:
<pre>
StarDict's dict ifo file
version=2.4.2
wordcount=274
idxfilesize=6678
bookname=Polish-Irish
sametypesequence=m
</pre>

FWIW, the "Tokien" file is supposedly of type "HTML document, Non-ISO extended-ASCII text, with very long lines, with LF, NEL line terminators", even though there's no HTML content inside.

**Comment by lbschenkel** [comment]
Hi @vmlemon. I encountered the same thing with the Dune fictionary. The problem is not with GoldenDict, but with the dictionaries themselves. Not even `pyglossary` can handle them.

The problem is that the files should be encoded in UTF-8, but they're using Windows-1252 instead:
- `.ifo` must be converted to UTF-8, I used `iconv -f Windows-1252 > new.ifo` and then overwrote the old file with `new.ifo`
- `.idx` must also be converted, however because this is a binary file you can't use `iconv` without destroying it. I solved it by opening in a text editor with "Windows-1252" encoding, finding all the chars that were beyond the ASCII range (in my case it was the "smart" apostrophe) and re-saved the file (although it's still with the wrong encoding, by limiting the chars to ASCII the file is also valid UTF-8)

After doing this the files now worked in every tool I tried.

So this should be closed, it's not a bug in GoldenDict.

**Comment by vmlemon** [comment]
Thanks for looking into this, @lbschenkel.

I completely forgot about this bug report (so much has changed, in the last few years, that I don't even have the laptop that I posted this from, anymore!), but if I ever need to use those dictionaries, again, I'll be sure to try your suggestion.
