### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by GD-fix** [goldendict/goldendict#896]
On all Linux_x86-64 (since GD version from 20.07.17):
`    hunspell.cc: В функции-члене «void HunspellMorpho::{anonymous}::HunspellArticleRequest::run()»:
    hunspell.cc:273:38: ошибка: нет подходящей функции для вызова «Hunspell::spell(std::string&)»
         if ( hunspell.spell( encodedWord ) )
                                          ^
    hunspell.cc:273:38: замечание: candidate is:
    In file included from hunspell.cc:22:0:
    /usr/include/hunspell/hunspell.hxx:56:7: замечание: int Hunspell::spell(const char*, int*, char**)
       int spell(const char * word, int * info = NULL, char ** root = NULL);
           ^
    /usr/include/hunspell/hunspell.hxx:56:7: замечание:   no known conversion for argument 1 from «std::string {aka std::basic_string<char>}» to «const char*»
    hunspell.cc:285:49: ошибка: нет подходящей функции для вызова «Hunspell::suggest(std::string&)»
         suggestions = hunspell.suggest( encodedWord );
                                                     ^
    hunspell.cc:285:49: замечание: candidate is:
    In file included from hunspell.cc:22:0:
    /usr/include/hunspell/hunspell.hxx:66:7: замечание: int Hunspell::suggest(char***, const char*)
       int suggest(char*** slst, const char * word);
           ^
    /usr/include/hunspell/hunspell.hxx:66:7: замечание:   candidate expects 2 arguments, 1 provided
    hunspell.cc: В функции «QVector<std::basic_string<wchar_t> > HunspellMorpho::{anonymous}::suggest(std::wstring&, Mutex&, Hunspell&)»:
    hunspell.cc:507:49: ошибка: нет подходящей функции для вызова «Hunspell::analyze(std::string&)»
         suggestions = hunspell.analyze( encodedWord );
                                                     ^
    hunspell.cc:507:49: замечание: candidate is:
    In file included from hunspell.cc:22:0:
    /usr/include/hunspell/hunspell.hxx:78:7: замечание: int Hunspell::analyze(char***, const char*)
       int analyze(char*** slst, const char * word);
           ^
    /usr/include/hunspell/hunspell.hxx:78:7: замечание:   candidate expects 2 arguments, 1 provided
    hunspell.cc: В функции-члене «void HunspellMorpho::{anonymous}::HunspellPrefixMatchRequest::run()»:
    hunspell.cc:662:38: ошибка: нет подходящей функции для вызова «Hunspell::spell(std::string&)»
         if ( hunspell.spell( encodedWord ) )
                                          ^
    hunspell.cc:662:38: замечание: candidate is:
    In file included from hunspell.cc:22:0:
    /usr/include/hunspell/hunspell.hxx:56:7: замечание: int Hunspell::spell(const char*, int*, char**)
       int spell(const char * word, int * info = NULL, char ** root = NULL);
           ^
    /usr/include/hunspell/hunspell.hxx:56:7: замечание:   no known conversion for argument 1 from «std::string {aka std::basic_string<char>}» to «const char*»
    Makefile:2408: ошибка выполнения рецепта для цели «build/hunspell.o»
    make: *** [build/hunspell.o] Ошибка 1
`

**Comment by Abs62** [comment]
Read "readme.md" -  "To compile with libhunspell older than 1.5 pass "CONFIG+=old_hunspell" to qmake".

**Comment by GD-fix** [comment]
Thanks! It works.
But there is a bug with dictionaries names in Modern style:
![bug_new](https://user-images.githubusercontent.com/21008593/31044610-96a84e78-a5e3-11e7-85cb-a77caf7a392b.png)
Is it necessary to close this issue and open new one for this bug?

**Comment by Abs62** [comment]
For "Modern" style element "Из словаря" should be hidden by CSS rule for "gdfromprefix" elements. Check rules in the GD inspector.

**Comment by GD-fix** [comment]
In version from 04.10.17 it's OK.

Thanks!
