### ISSUE TITLE
Query error: Error creating SSL context ()

### ISSUE THREAD

**Issue by iccm** [goldendict/goldendict#901]
Dear friends,

I'm trying to use Goldendict with Wikipedia and I've changed the http to https in the Wikipedia address.

I receive "Query error: Error creating SSL context ()"

What can I do?

Thank you,

Ilan.

**Comment by Abs62** [comment]
What GD version do you use?

**Comment by iccm** [comment]
1.01

**Comment by Abs62** [comment]
Very old version. Try [last one](https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows).

**Comment by iccm** [comment]
It works.
When I looked for Goldendict, I could only find ver 1.01.
I will save this link.
Thank you.
