### ISSUE TITLE
new button in scan window that opens the scanned term in the main window

### ISSUE THREAD

**Issue by mhtamala** [goldendict/goldendict#904]
many times I noticed that I must copy-paste the term from the scan widow to the main window for more control. It would be nice if there is a button in the scan window that lets the scanned term get opened in the main window.

Thank you

**Comment by Abs62** [comment]
![send_word](https://user-images.githubusercontent.com/837578/31460984-ae6bb810-aed0-11e7-82b4-05ade01e2bdb.png)

**Comment by mhtamala** [comment]
Thank you! I didn't notice that!
