### ISSUE TITLE
different dictionary / group / settings for each tab

### ISSUE THREAD

**Issue by mihaaly** [goldendict/goldendict#906]
Thi is a feature request :)

Would be nice to have multiple tabs open for different language groups / dictionaries, so as when you switch tabs and search you could look up different languages / dictionaries. For instance:

Tab 1 - being on this tab would search in an English-Italian dictionary
Tab 2 - switching to this tab would search say in a German-Russian dictionary
etc.

**Comment by SDPMrem71** [comment]
YES. +1 +100
It is extremely useful, sometimes for fast search i don't want to load up Wikipedia or other online site.
but when i switch tab i can use others while maintaining my group setting and search result.
@vedgy @Abs62 

![image](https://user-images.githubusercontent.com/54465233/207800506-a6ba15f3-2380-4bd4-883e-53e26c022b8c.png)

**Comment by vedgy** [comment]
@mihaaly, please close this issue as a duplicate of #84.

**Comment by nonwill** [comment]
@SDPMrem71 Just as this?
![handict_web_file111](https://user-images.githubusercontent.com/46510529/207817439-ac25350f-9cab-4c98-9598-8465224707f0.gif)

**Comment by mihaaly** [comment]
duplicate issue: https://github.com/goldendict/goldendict/issues/84
