### ISSUE TITLE
Mate 1.8 System Tray Malfunction

### ISSUE THREAD

**Issue by Kixmi** [goldendict/goldendict#907]
I'm a ArchLinux user and my favourite desktop is Mate. I'm also a Goldendict user for several years, and with the Mate 1.8 actualization, right clicking the system tray icon stop working. It show a black rectangle, and is impossible choose anything, making very difficult the work of enable and disable the emerging window.
On others desktops, for example XFCE or KDE, it works properly.
Thanks for your support.

**Comment by Kixmi** [comment]
Sorry, the Mate DE version is 1.18, not 1.8.

**Comment by tehkonst** [comment]
I have the same issue with Ubuntu Mate (1.20). If remove tray icon and return it back, the dropdown menu works fine. Or just run "mate-panel --reset" after launching goldendict. But it's very inconvenient.

The same bug is on Ubuntu 18.04.1 LTS (Gnome 3). Here's someone's report - https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-appindicator/+bug/1760447

**Comment by Vladimyr0** [comment]
The same bug is on Ubuntu 18.04.1 LTS (Unity)
