### ISSUE TITLE
En-En-Longman_DOCE5 dictionary doesn't be parsed correctly in Mac OX

### ISSUE THREAD

**Issue by limxtop1989** [goldendict/goldendict#908]
Hi, after I add the dictionaries into GoldenDict, the audios work properly but the illustrative sentences after which can't shown as figure below. I am not sure whether the root case is software itself.  

Addition, the dictionary files works properly in Windows and Linux system. Here is my system information: macOS Sierra version 10.12.6.

<img width="520" alt="qq20171011-234240 2x" src="https://user-images.githubusercontent.com/10472057/31572652-81e9c31c-b070-11e7-86fa-6139cbef8a3c.png">

**Comment by Abs62** [comment]
Read GD help, "Preferences/Advanced" section about "Expand optional parts" parameter.

**Comment by limxtop1989** [comment]
The Expand optional parts parameter is unchecked by default, that the expand button doesn't been shown as figure above make me confused since the help document said "if it is unset, areas marked as optional will be hide and beside article header will be shown expand button". 

But whatever, the example banks can be shown properly once I check the parameter. 

Thanks so much.

**Comment by limxtop1989** [comment]
Sorry, I have found the expand button now which resides right side of article header in the first line of search result.
