### ISSUE TITLE
Indexing wikipedia zim - once and for all

### ISSUE THREAD

**Issue by 7877ad41b8a7948** [goldendict/goldendict#914]
Previously discussed: #546 #680 #763

I'd like to see wikipedia zim files work out of the box with goldendict and I'm willing to do the work.
I've looked into the b-tree code to find out what's blowing up and here's what I've found:

- `wikipedia_en_all_nopic_2017-01.zim` has 13M+ articles.
- The total memory footprint of keeping all the titles strings is about 300MB (just the strings).
- The index gen code splits every title into words and stores a full copy of the title for each word.
With 13M articles whose titles usually contain multiple words, the total memory requirement multiples
several times.
- In order to simplify (and speed-up?) the generation of the b-tree, gd depends on an ordered traversal of keys for insertion. The indexing code achieves this by building a complete list of keys and then iterating through it in order. The entire list has to fit in memory for this to work.
- The standard C++ `map<>` is used to store the strings and iterate through them in order, but that data structure itself adds lots of memory overhead to the already large memory requirement.

The solution (1) I have now is to:
- disable FTS for zim files above ? GB
- Modify the `addWord()` logic to index only the full (folded) title and not to generate additional entries on word boundaries - if the article count is large enough.

I'm perfectly happy with the result. Indexing takes just a few minutes (for the full english no-pic 2017 wikipedia) and <4GB of memory, so it's practical on reasonably modern machines. 
The index file generated is about 400MB and I the result is perfectly usable: I've had no problem finding articles (despite the more limited indexing), and I've noticed no UI lag. As an extra bonus, it's a fairly trivial code change.

There's a way to build the full b-tree using bounded memory, but it'll be trickier to get working. 

Or, it may also be simpler to just switch the index format into a sqlite3 database and have it deal with the btree acrobatics. That way goldendict can just INSERT strings one by one, or in comfortably-sized transactions to speed things up. It'd also make it easier to write external programs to populate the index with keys, for exotic cases like this. Performance may be terrific or awful, dunno.

Or, just stick with the simplest thing that works, i.e. (1).

how about it, @Abs62 ? I can send a PR for (1) soon if you're interested.

**Comment by darnn** [comment]
If you do move forward on this, please consider adding the option to create a Wikipedia-based dictionary from dumps, i.e. something that would enable you to input, say, "The Terminator" and have GD output "Терминатор (фильм)" (if you've selected English->Russian).

**Comment by Abs62** [comment]
wikipedia_en_all_nopic_2017-08.zim, 64-bit Qt5-based GD - 8 minutes for indexing, 720 MB index file. Up to 7 GB memory consumption while indexing.

What criterion do you suggest for reduce headwords handling?

**Comment by data-man** [comment]
IMO, the best solution would be to use the [libzim](https://github.com/openzim/libzim) library, which has built-in support for the [Xapian](https://github.com/xapian/xapian) library with advanced full-text search capabilities.

**Comment by 7877ad41b8a7948** [comment]
> wikipedia_en_all_nopic_2017-08.zim, 64-bit Qt5-based GD - 8 minutes for indexing, 720 MB index 
> file. Up to 7 GB memory consumption while indexing.

sounds right. I consider >4GB ambitious. Note that the linked issues suggest 80GB memory needed. Perhaps that describes FTS indexing.

> What criterion do you suggest for reduce headwords handling?

I suggest eliminating it altogether for files that exceed a size threshold. Say, 4M entries (before headwording). Same for disabling FTS. Optionally, make these into settings in preferences.

As I see it, as long as the indexing process uses unbounded amounts of memory, a circuit-breaker is required. Either that, or level-up the index generation machinery (Several possibilities, all more complicated).

**Comment by Abs62** [comment]
I have add parameter to config file.

**Comment by 7877ad41b8a7948** [comment]
Thanks. The problem is still there because:
- FTS indexing is on by default for zim -> OOM
- no default value set for maxHeadwordsToExpand -> OOM (I suggest 4M)

**Comment by Abs62** [comment]
>> FTS indexing is on by default for zim -> OOM for fresh users (FTS should have size limit too? some smaller zim files could benefit from FTS)

![fts_limit](https://user-images.githubusercontent.com/837578/32014354-849e537a-b9c6-11e7-9ffb-bd305b2d4dad.png)

>> default value set for maxHeadwordsToExpand is 0, so headword expansion it now turned off for ALL dicts (IIUC). default should probably be large enough to only apply to wikipedia-scale files.

No. Limit should be turned on only if GD can't index dictionary wthout one. 64-bit GD and 8+ GB RAM is not rare configuration nowadays.

**Comment by 7877ad41b8a7948** [comment]
Fair enough. Thanks for fixing! :+1:

**Comment by jjzz** [comment]
@darnn 
I just put wikipair online https://github.com/jjzz/wikipair
I guess that's exactly what you want.

**Comment by darnn** [comment]
That is, in fact, exactly what I want! I'm clueless when it comes to Linux, but I managed to run it as far as getting the txt and the dsl file, after which it gave an error on the dos2unix command. I copied over the files and changed the linebreak style to Windows, and turned on BOM, and Windows Goldendict now reads it! So, thank you so much!

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/commit/7a2ec4fd8a1b0aa1bd052fad1275d76c8af08439
