### ISSUE TITLE
Not Rendering HTML anchor tag <a> for some dictionaries

### ISSUE THREAD

**Issue by lRadha** [goldendict/goldendict#918]
![golden_dict_issue](https://user-images.githubusercontent.com/17251444/32232720-b0205f9a-be7e-11e7-8c53-ce9edd98590c.jpg)
Hey, Thanks for providing such a brilliant app in a intelligent way.

I'm facing an issue in it; it makes me an HTML parser to read some dictionary content [You have looked upon the image, I think. Look below for more clarity]. Anchor tag 
![golden_dict_anchor_tag_issue](https://user-images.githubusercontent.com/17251444/32233753-20f09cba-be81-11e7-8208-4d8e412f5276.jpg)
is working in it, can you plz provide some help [either in the form of new update or some type hack that can be implied using F12 :-)]

BTW, I don't remember where from I got that excellent dictionary, but uploaded only for you [Don't show it to your colleagues]
[quick_foldoc.zip](https://github.com/goldendict/goldendict/files/1431281/quick_foldoc.zip)

**Comment by Abs62** [comment]
"sametypesequence=m" in the quick_foldoc.ifo means plain text format, not html.

**Comment by lRadha** [comment]
Is there any way that can help in rendering it as HTML so that tags will show properly or can I convert it to something that can help.

**Comment by Abs62** [comment]
Try to change "sametypesequence=m" to "sametypesequence=h" in the quick_foldoc.ifo.

**Comment by lRadha** [comment]
Thanks, it really worked. :+1:

**Comment by lRadha** [comment]
Although I'm happy with that (because I'm not a HTML parser anymore), [I don't want to create another issue, you know.] thanks for your precious time, but I want that you should maintain a list of various dictionaries that all the user's have (obviously by their contribution)

Here I got an image from an issue which shows many dictionaries in it. In short, I want them all, plz do something fast. Many thanks

https://camo.githubusercontent.com/a153da97757d50ffc72dfe2c4f5a1ceb7e8ba9f7/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3436323638302f38393737312f37336630363066302d363535312d313165322d393335632d3863666361663163303936322e706e67
