### ISSUE TITLE
Can it parse some tex?

### ISSUE THREAD

**Issue by lRadha** [goldendict/goldendict#919]
![golden_dict_tex_parsing_functionality](https://user-images.githubusercontent.com/17251444/32279802-b634efce-bf3f-11e7-9a00-165ac01a89e3.jpg)

The issue is clear as the image and the title of the issue makes it, yes, I'm telling the same, to parse some Latex code in Dictionary; is that possible using some hack or you have to write some code to do this?

If some new code has to be written then I will not force you guys to do it immediately (as others usually do, like they are your boss or client or paying for it, they should remember that its FREE :-)), don't be stressed, take your full time.

BTW I think, this can be done using on-line CDNs or just using some script.

I'm going to close this issue asap you guys make it clear that what can be done in this case (coding or some hack.)

Thanks

**Comment by Abs62** [comment]
Just take this dictionary in the Slob or Zim format. Zim dictionaries contains equations as pictures, Slob ones contains MathJax-based scripts to handle equations in Latex format.

**Comment by lRadha** [comment]
Thanks for your suggestion will try it tomorrow from [here](https://github.com/itkach/slob/wiki/Dictionaries)

**Comment by lRadha** [comment]
Hey up there! plz help
![golden_dict_pls_help](https://user-images.githubusercontent.com/17251444/32308704-4200ffee-bfad-11e7-9ada-818cd6fbcaab.jpg)

Now I have downloaded English Wikipedia in slob format but there is some issue to be looked upon.

**Comment by Abs62** [comment]
Try to remove (or rename) mimetex.cgi file in the GD folder.

**Comment by lRadha** [comment]
I just renamed it. But (Don't Worry) it is working properly. Many thanks. Great Work. :+1:
