### ISSUE TITLE
Some symbols appear in input box after Linux start/restart

### ISSUE THREAD

**Issue by Michael20545** [goldendict/goldendict#920]
After starting Linux, symbols (hex and "_") appear in input edit box, there is also an attempt to translate them. See attached file.
Goldendict git version, Kubuntu 16.04.
![screenshot_20171102_135557](https://user-images.githubusercontent.com/33310647/32314226-5e1e3a9e-bfd9-11e7-8e01-001e03d0a30f.png)

**Comment by Abs62** [comment]
Check GD command line.
