### ISSUE TITLE
Please add this new attached Italian translation 

### ISSUE THREAD

**Issue by orecchionebruno** [goldendict/goldendict#922]
Hi to everyone

I translated all Italian version of Golden Dict and I simply update it the translation.

Please replace existing translation with the attached.

Thanks
Daniele

[it_IT.zip](https://github.com/goldendict/goldendict/files/1464964/it_IT.zip)

**Comment by sikmir** [comment]
It would be better to create Pull Request instead of Issue. Here there is no way to review the diff.

**Comment by orecchionebruno** [comment]
Hi Sikmir, 

sorry I've forgotten a crucial file: **it_IT.ts** 

The new attachment includes TS and QM file.

Yesterday, I've simply downloaded the last **_Code_** version available here (pushing the 'Clone or Download' button) and I've translated.

I think this is enough, can someone please replace code and compiled file?

Thanks
Daniele
[it.zip](https://github.com/goldendict/goldendict/files/1466157/it.zip)

**Comment by Abs62** [comment]
Thanks, translation updated.
