### ISSUE TITLE
[Feature Request] Support for Dictionaries built by Mdxbuilder 4.0 (.mdx)

### ISSUE THREAD

**Issue by BLKSerene** [goldendict/goldendict#933]
http://www.mdict.cn/wp/?page_id=5325&lang=en

Dictionary Tools
MDXBuilder 4.0 Beta Test：
*Dictionary made by v4.0 can only be opened by MDict PC/Android version 2.0
MDXBuilder 4.0 RC2:

**Comment by nikita-moor** [comment]
I suspect that support of the MDict format in most of the dictionary shells is based on the work of [Wang Xiaoqiang](https://bitbucket.org/xwang/mdict-analysis/src/default/), but he analyzed 2nd version of the format, so structure of the 4th version is not known.

**Comment by michaelbeijer** [comment]
I noticed that this Feature Request has been closed. I too would love to be able to use MDXBuilder 4.0 RC2 to generate files GoldenDict could use. Any news on this?

**Comment by michaelbeijer** [comment]
see also: http://beijer.wiki/software/mdxbuilder-manual_eng.txt
