### ISSUE TITLE
“goldendict” terminated by signal SIGSEGV (Address boundary error) and segfaults

### ISSUE THREAD

**Issue by munzirtaha** [goldendict/goldendict#935]
Goldendict doesn't work in wayland. I tried to launch it in Arch Linux with latest updates and I got error:
fish: “goldendict” terminated by signal SIGSEGV (Address boundary error)
or
Segmentation fault (core dumped)

**Comment by scpkyy** [comment]
May 2019 using Fedora 30 with KDE Plasma Wayland - Goldendict crashes immediately.  This is a real pity as I use this program more than any other.

**Comment by lulitao1997** [comment]
goldendict has many x11-specific codes.
set QT_QTA_PLATFORM=xcb forces qt to run in X11 mode would solve this issue.

**Comment by egor-glukhov** [comment]
> set QT_QTA_PLATFORM=xcb forces qt to run in X11 mode would solve this issue.

typo? QT_Q**P**A_PLATFORM=xcb worked for me, albeit without X11-specific features like hotkeys.

**Comment by doctorcolossus** [comment]
For me it still segfaults in Wayland even with `QT_QTA_PLATFORM=xcb`.

**Comment by doctorcolossus** [comment]
The above occurred [with the official package in the community repository](https://archlinux.org/packages/community/x86_64/goldendict/).

However, after building from git using the `PKGBUILD` script [in the user repository](https://aur.archlinux.org/packages/goldendict-git/), goldendict ran fine even without `QT_QTA_PLATFORM=xcb`. Help → About shows version "1.5.0-RC2-490-gbaff02a1-dirty".
