### ISSUE TITLE
The main window has not focus when close to tray and active again using hotkey

### ISSUE THREAD

**Issue by wxwok** [goldendict/goldendict#95]
I'm running the GoldenDict on the Ubuntu 11.10 with unity desktop.  I enabled the option "preference->interface->Enable System tray icon->Close to system tray".
How to reproduce:
    After it close to tray, active it using the hotkey again.
Expected:
    The dict window should be focused so that we can input word directly.
Actual:
    The main window is not focused, I have to set focus on it by clicking the main window.

It is not convenient on user experience. It is better paste the current selected word into the word input box.

**Comment by vramazani** [comment]
I still have this problem on Kubuntu 16.04
