### ISSUE TITLE
Please, make a release

### ISSUE THREAD

**Issue by vitlav** [goldendict/goldendict#953]
Please, make a next release.

**Comment by AdKiller** [comment]
seriously, it's been about 5 years? since the last release, is this the longest release candidate in history?!

**Comment by nikita-moor** [comment]
Duplicates: #910, #839

**Comment by tungmilan** [comment]
Would it be possible to have v1.6.0 released around New Year? I think we have v1.5.0 long enough already. Thanks!

**Comment by Ray-Eldath** [comment]
Yet is 2020, and still no new release...
Seems are still actively developing. Hopes could release soon.

**Comment by GitHunter0** [comment]
> 
> 
> seriously, it's been about 5 years? since the last release, is this the longest release candidate in history?!

The last official release was in 2010, I just cannot understand what the owners of this project have in mind.

 It is a monumental pity that the best dictionary software in the world is in this situation...

**Comment by AdKiller** [comment]
> 
> 
> > seriously, it's been about 5 years? since the last release, is this the longest release candidate in history?!
> 
> The last official binary release for Windows was in 2010, I just cannot understand what the owners of this project have in mind.
> 
> It is a monumental pity that the best dictionary software in the world is in this situation...

yeah it's sad that the development is abandoned. luckily Windows 10 still hasn't broken the last version of GoldenDict which is good enough.

**Comment by sikmir** [comment]
What about forking the project and continuing development (with releases!) under the new name? As an example with the same reason - [gogs](https://gogs.io/) was forked by community into [gitea](https://gitea.io/en-us/).

**Comment by GitHunter0** [comment]
> > > seriously, it's been about 5 years? since the last release, is this the longest release candidate in history?!
> > 
> > 
> > The last official binary release for Windows was in 2010, I just cannot understand what the owners of this project have in mind.
> > It is a monumental pity that the best dictionary software in the world is in this situation...
> 
> yeah it's sad that the development is abandoned. luckily Windows 10 still hasn't broken the last version of GoldenDict which is good enough.

@AdKiller , extremely sad, man. It is almost a crime...

**Comment by GitHunter0** [comment]
> What about forking the project and continuing development (with releases!) under the new name? As an example with the same reason - [gogs](https://gogs.io/) was forked by community into [gitea](https://gitea.io/en-us/).

@sikmir , it is a great idea! I don't have the expertise to create this side project but I would love to see that.

**Comment by nikita-moor** [comment]
It's not abandoned. [New commits](https://github.com/goldendict/goldendict/commits/master) are made regularly. The [main developer](https://github.com/goldendict/goldendict/graphs/contributors) @Abs62 is still here, and he helped me to solve several problems very fast. Yes, development is not active, there aren't new features, it's more in supporting phase but is definitely not abandoned.

Linux users have access to recent releases, the only problem is Windows and macOS. If you can compile binaries for Win/Mac and [release them on Wiki](https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows) then it will be very helpful.

**Comment by vitlav** [comment]
> **It's not abandoned.** [New commits](https://github.com/goldendict/goldendict/commits/master) are made regularly. The [main developer](https://github.com/goldendict/goldendict/graphs/contributors) @Abs62 is still here, and he helped me to solve several problems very fast. Yes, development is not active, there aren't new features, it's more in supporting phase but is definitely not abandoned.
> 
> Linux users have access to recent releases, the only problem is Windows and macOS. If you can compile binaries for Win/Mac and [release them on Wiki](https://github.com/goldendict/goldendict/wiki/Early-Access-Builds-for-Windows) then it will be very helpful.
Good news. But you don't make releases. Please, increment version and set tag to the release commit.

**Comment by tungmilan** [comment]
For Windows users, you can get the latest executable from this thread
https://forum.ru-board.com/topic.cgi?forum=5&topic=49149#1

**Comment by GitHunter0** [comment]
> For Windows users, you can get the latest executable from this thread
> https://forum.ru-board.com/topic.cgi?forum=5&topic=49149#1

@tungmilan , I cannot understand a word in Russian but I managed to download, thank you

**Comment by powerman** [comment]
It is going to be [removed from Gentoo Linux](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=c30a6df296ff8c6f61d949c98d658925c15d0893) if won't be released anytime soon with modern dependencies. :cry:

**Comment by loyukfai** [comment]
> For Windows users, you can get the latest executable from this thread
> https://forum.ru-board.com/topic.cgi?forum=5&topic=49149#1

502 Bad Gateway as of writing?

**Comment by nikita-moor** [comment]
@loyukfai 
There are some technical problems in their hosting datacenter. Information about current status is published here:

- https://ruboard.livejournal.com/
- https://vk.com/club537048

**Comment by loyukfai** [comment]
NET::ERR_CERT_DATE_INVALID right now...

**Comment by loyukfai** [comment]
Hi anyone? 😊

**Comment by loyukfai** [comment]
> @loyukfai A new version of GoldenDict is [being made by @xiaoyifang](https://github.com/xiaoyifang/goldendict/releases). It's ready for everyday use, but some features need to be polished before the final release.

I tried the Windows build the other day but it failed to launch... will try again later

**Comment by nonwill** [comment]
[New releases](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/) for macOS/Linux/Windows [are now available](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/).

**Comment by GitHunter0** [comment]
> [New releases](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/) for macOS/Linux/Windows [are now available](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/).

I can't read chinese, is there an english version?

**Comment by nonwill** [comment]
> > [New releases](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/) for macOS/Linux/Windows [are now available](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/).
> 
> I can't read chinese, is there an english version?

Yes, translations can be changed on the Preference dialog. By default, the ui's language is same as your system local setting.

**Comment by loyukfai** [comment]
> > [New releases](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/) for macOS/Linux/Windows [are now available](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/).
> 
> I can't read chinese, is there an english version?

You may like to check this out before committing to that version: https://github.com/goldendict/goldendict/issues/1424

Personally I know neither of them, but there seems to be some serious issues (depending how you value GPL)... so for the time being I think the builds by @xiaoyifang as mentioned by @nikita-moor seem safer.

Cheers.

**Comment by nonwill** [comment]
> You may like to check this out before committing to that version: #1424

Welcome to add bricks and tiles to make the scammers🐷 happy.

**Comment by nonwill** [comment]
> I think the builds by @xiaoyifang as mentioned by @nikita-moor seem safer.

I only see black holes from it and It is recommended that anyone with this idea to use the official version.

**Comment by Immunize2** [comment]
> [New releases](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/) for macOS/Linux/Windows [are now available](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/).

dirty @nonwill do not post links to your malware on this site ! You dirty code stealer....

**Comment by nonwill** [comment]
> > [New releases](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/) for macOS/Linux/Windows [are now available](https://nonwill.github.io/gdocr/GoldenDict-OCR-Deployment/).
> 
> dirty @nonwill do not post links to your malware on this site ! You dirty code stealer....

dirty @Immunize2 do not pull out your intestines on this site ! You dirty souls' grave....

**Comment by vedgy** [comment]
Created the [GitHub release 1.5.0](https://github.com/goldendict/goldendict/releases/tag/1.5.0).

**Comment by loyukfai** [comment]
WOW, thank you @vedgy !!
