### ISSUE TITLE
Failed building on macOS

### ISSUE THREAD

**Issue by 1900forever** [goldendict/goldendict#956]
I have installed Qt 5.10.1 with webkitwidgets plugin. While I tried configuring via Qt Creator, the errors poped up:

> 
Could not find qmake spec 'default'.
Error while parsing file /Users/yan/src/goldendict/goldendict.pro. Giving up.
Project ERROR: Unknown module(s) in QT: webkitwidgets
Cannot read /Users/yan/src/goldendict/qtsingleapplication/config.pri: No such file or directory

**Comment by Abs62** [comment]
Qt 5.6 and later don't include QtWebKit module. You should add it by oneself.

**Comment by 1900forever** [comment]
Thanks, problem solved!
