### ISSUE TITLE
Full text search results: double clicking a word is limited to the few dictionaries

### ISSUE THREAD

**Issue by vedgy** [goldendict/goldendict#964]
_Steps to reproduce:_
1. Make a full text search query and select a result with only a few dictionaries (as opposed to all active dictionaries in the current group).
2. Double click a common word in one of the search result articles.

_Actual result:_ the double-clicked word is translated only in the same dictionaries that displayed the full text search results.
_Expected result:_ the double-clicked word is translated in all active dictionaries in the current group.

I'm using the latest goldendict master on Manjaro GNU/Linux, Qt 5.10.1, GCC 7.3.0, 64 bit.

**Comment by Abs62** [comment]
It is not bug, it is feature. If you want to see same word in other dictionaries just click it in the History pane after.

**Comment by vedgy** [comment]
This is an unexpected feature, but not much of a problem for me.
I guess it can be useful for someone...
