### ISSUE TITLE
Wikipedia audio link detection regression with Qt5

### ISSUE THREAD

**Issue by vedgy** [goldendict/goldendict#967]
* Get the latest version of goldendict master branch and build it on GNU/Linux with Qt5 and Qt4.
* Search for "United States" in English Wikipedia and examine the Anthem and March audio links near the top of the article summary.
* Compare the audio links in goldendict built with Qt5 and Qt4: the links seem to be undetected with Qt5.
* Run "git checkout 109bd56f39fd570f9e006a21d067dc3b284e950d -- mediawiki.cc" and notice that the results with Qt5 are now the same as with Qt4.
* The same issue happens with most other Wikipedia audio links.

**Comment by Abs62** [comment]
Should be fixed now.

**Comment by vedgy** [comment]
Thanks for this and other MediaWiki fixes!

By the way, I found the ".*" pattern in several `QRegularExpression`s: in *gls.cc*, *mdx.cc*, *stardict.cc*. These might also cause regressions without `QRegularExpression::DotMatchesEverythingOption`...

**Comment by Abs62** [comment]
Gls use single-line articles (format request), mdx converter use not ".*" but "\.*" pattern. Stardict I overlooked, thanks.
