### ISSUE TITLE
It doesn't display WordReference results

### ISSUE THREAD

**Issue by Fibroblasto** [goldendict/goldendict#97]
Goldendict doesn't display WordReference online dictionary results. It looks I am not the only one with this problem, as can be seen in this Goldendict forum thread: http://goldendict.org/forum/viewtopic.php?f=5&t=1617

Invoking the program from the cvonsole with a WordReference dictionary as the only one and doing a search, Igot nothing on Goldendict program and this output in the console:

Load done
getResource: gdlookup://localhost?blank=1
scheme: gdlookup
host: localhost
getResource: gdlookup://localhost?blank=1
scheme: gdlookup
host: localhost
getResource: gdlookup://localhost?word=¡Bienvenido!&group=4294967295
scheme: gdlookup
host: localhost
In-place finish.
Loading 30 abbrv
====reading 16384 bytes
====reading 38055 bytes
getResource: gdlookup://localhost?word=ventana&group=2&muted=ed5e34e65bafce44782724fcf7f381c6,9a7cc7e377d18a832daf156c599f49ca,1ebe9a5c7517ca465e873354826ba847,cc6ce8141b1fa0cbabc9f945dc2aa1f9,74209671007efe9fc26f2e989e4a9e2f,9f32ff707665952505497640721ee8d4,d377f29a139b29d44ee686c02de30fc5,5b0b904cf559ecf05839749be2dcb265
scheme: gdlookup
host: localhost
alts finished
some body finished
one finished.
erasing..
erase done..
In-place finish.
====reading 16384 bytes
====reading 37267 bytes
getResource: http://www.wordreference.com/es/en/translation.asp?spen=ventana
scheme: http
host: www.wordreference.com
getResource: http://www.wordreference.com/2008/scripts/WRredesign.css?v=10
scheme: http
host: www.wordreference.com
getResource: http://www.wordreference.com/2008/scripts/newaudiomin.js?v=3
scheme: http
host: www.wordreference.com
getResource: http://www.wordreference.com/2008/scripts/WRhistorymin.js?v=3
scheme: http
host: www.wordreference.com
getResource: http://cdn.amgdgt.com/base/js/v1/amgdgt.js
scheme: http
host: cdn.amgdgt.com
Blocking element http://cdn.amgdgt.com/base/js/v1/amgdgt.js
getResource: http://yui.yahooapis.com/combo?2.8.0r4/build/yahoo-dom-event/yahoo-dom-event.js&2.8.0r4/build/datasource/datasource-min.js&2.8.0r4/build/autocomplete/autocomplete-min.js&2.8.0r4/build/connection/connection_core-min.js
scheme: http
host: yui.yahooapis.com
Blocking element http://yui.yahooapis.com/combo?2.8.0r4/build/yahoo-dom-event/yahoo-dom-event.js&2.8.0r4/build/datasource/datasource-min.js&2.8.0r4/build/autocomplete/autocomplete-min.js&2.8.0r4/build/connection/connection_core-min.js
getResource: http://www.wordreference.com/2008/scripts/2010kmin.js?v=5
scheme: http
host: www.wordreference.com
getResource: https://apis.google.com/js/plusone.js
scheme: https
host: apis.google.com
Blocking element https://apis.google.com/js/plusone.js
getResource: http://www.google-analytics.com/ga.js
scheme: http
host: www.google-analytics.com
Blocking element http://www.google-analytics.com/ga.js
getResource: http://www.wordreference.com/2008/publ/topIframe.aspx?cc=ES&dict=esen&r=5&no=0
scheme: http
host: www.wordreference.com
getResource: http://www.wordreference.com/images/magnifying_glass_dark_flipped.png
scheme: http
host: www.wordreference.com
getResource: http://www.wordreference.com/images/speaker.png
scheme: http
host: www.wordreference.com
getResource: http://www.wordreference.com/images/android.png
scheme: http
host: www.wordreference.com
getResource: http://www.wordreference.com/images/appstore.png
scheme: http
host: www.wordreference.com
getResource: http://www.wordreference.com/audio/es/es/ogg/es038922-11.ogg
scheme: http
host: www.wordreference.com
getResource: http://www2.wordreference.com/2008/publ/recordadsall.aspx?per=1&id=189
scheme: http
host: www2.wordreference.com
getResource: http://www.facebook.com/plugins/likebox.php?href=http://www.facebook.com/pages/WordReferencecom/277856304509&width=215&height=62&colorscheme=light&show_faces=false&border_color&stream=false&header=false
scheme: http
host: www.facebook.com
Blocking element http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fpages%2FWordReferencecom%2F277856304509&width=215&height=62&colorscheme=light&show_faces=false&border_color&stream=false&header=false
getResource: http://www2.wordreference.com/2008/publ/recordadsall.aspx?per=1&id=190
scheme: http
host: www2.wordreference.com
getResource: http://www2.wordreference.com/2008/publ/recordadsall.aspx?per=1&id=187
scheme: http
host: www2.wordreference.com
getResource: http://www.wordreference.com/audio/es/es/ogg/es038922-11.ogg
scheme: http
host: www.wordreference.com
getResource: http://www.wordreference.com/audio/es/es/ogg/es038922-11.ogg
scheme: http
host: www.wordreference.com

**Comment by timofonic** [comment]
I fixed it!

http://mini.wordreference.com/mini/index.aspx?dict=enes&w=%GDWORD%

URL found here...
http://readtheworld.seeyoosoon.com/dictionaries.shtml

**Comment by timofonic** [comment]
I fixed it!

http://mini.wordreference.com/mini/index.aspx?dict=enes&w=%GDWORD%

URL found here...
http://readtheworld.seeyoosoon.com/dictionaries.shtml
