### ISSUE TITLE
Audio files in MDX dictionaries are played one after another automatically

### ISSUE THREAD

**Issue by BLKSerene** [goldendict/goldendict#971]
There might be a problem while unpacking MDD files. For example, I look up "government" in the dictionary and click the audio icon, after the pronunciation of the "government", it goes on with "governmental", "governor", etc....(the pronunciation of serveral other words following the one I'm looking up). There no problem with other dictionary software, so it might be a problem when GoldenDict unpacks MDD files.

**Comment by Abs62** [comment]
Can you upload such dictionary sample?

**Comment by BLKSerene** [comment]
https://pan.baidu.com/s/1nw4UK0D#list/path=%2F
Password: ycdx

**Comment by Abs62** [comment]
Can't reproduce issue. What GD version do you use?

**Comment by BLKSerene** [comment]
1.5.0-RC2-209-gfe9312e x86-64
Date: 10 December 2017
Windows10 Enterprise x86-64
Not all audio files have this problem, try look up "hire".

**Comment by Abs62** [comment]
Try [this version](http://www.mediafire.com/file/aef993h4n897qhr/goldendict-1.5.0-RC2-273-g2b3a8d1%28EXE+only%29.7z).

**Comment by BLKSerene** [comment]
It works. Thanks a lot.

**Comment by mohsenkhanpour** [comment]
Hi dear @BLKSerene , I am a member of pdawiki, knowing you are an admin there made me post to you.
My usergroup has expired, but I can not delete it. It says "user group not found".
I have lost access to anywhere else on the forum.
Will you please send me an e-mail on mohsenkhanpour@gmail.com.
My pdawiki username is :mhsnkhnpr
